### ISSUE TITLE
Not able to get secret into AKSCluster

### ISSUE THREAD

**Issue by KannanAadhav** [Azure/secrets-store-csi-driver-provider-azure#1001]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/) Yes
- [ ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Trying to configure TLS for NGINX ingress controller, as part of it trying to get a secret into an AKS cluster using UserAssignedIdentity but the pod isn't able to pull the secret.

**What did you expect to happen:**
Expecting the pod to pull the secret and the secret to be available in Kubernetes cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
kubectl get csidriver
NAME                       ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS                REQUIRESREPUBLISH   MODES                  AGE
disk.csi.azure.com         true             false            false             <unset>                      false               Persistent             37d
file.csi.azure.com         false            true             false             <unset>                      false               Persistent,Ephemeral   37d
secrets-store.csi.k8s.io   false            true             false             api://AzureADTokenExchange   false               Ephemeral              5h14m

Below are the steps i have performed .. FYI i have replaced vault name and Userassignedclient ID according to the values in the actual environment

1) export CERT_NAME=aks-ingress-cert
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -out aks-ingress-tls.crt \
    -keyout aks-ingress-tls.key \
    -subj "/CN=demo.azure.com/O=aks-ingress-tls"

2) az keyvault certificate import --vault-name $AKV_NAME -n $CERT_NAME -f $CERT_NAME.pfx

3) export NAMESPACE=ingress-basic
4) kubectl create namespace $NAMESPACE

5) # set policy to access keys in your key vault
az keyvault set-policy -n <keyvault-name> --key-permissions get --spn <identity-client-id>
# set policy to access secrets in your key vault
az keyvault set-policy -n <keyvault-name> --secret-permissions get --spn <identity-client-id>
# set policy to access certs in your key vault
az keyvault set-policy -n <keyvault-name> --certificate-permissions get --spn <identity-client-id>

6)  apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: $CERT_NAME
      key: tls.key
    - objectName: $CERT_NAME
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <client id>
    keyvaultName: $AKV_NAME                 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: $CERT_NAME
          objectType: secret
    tenantId: $TENANT_ID                    # the tenant ID of the AKV instance

7) kubectl apply -f secretProviderClass.yaml -n $NAMESPACE

8) helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

9) helm install ingress-nginx/ingress-nginx --generate-name \
    --namespace $NAMESPACE \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
    -f - <<EOF
controller:
  extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-tls"
  extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
EOF

POD is unable to start and the secret is not created at kubernetes cluster, below is the error being received

MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod ingress-basic/ingress-nginx-1666358579-controller-c8d865df4-pldqc, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:aks-ingress-cert, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<AKV>.vault.azure.net/secrets/aks-ingress-cert/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://<IP>/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=<ServicePrinicipalClientID>&resource=https%!!(MISSING)A(MISSING)%!!(MISSING)F(MISSING)%!!(MISSING)F(MISSING)vault.azure.net

**Comment by aramase** [comment]
> StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}

@KannanAadhav That error means the identity with the clientID you provided in the `SecretProviderClass` doesn't exist on the underlying VM/VMSS. Did you assign the identity by following the step 2 in the [doc](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/user-assigned-msi-mode/)?

**Comment by KannanAadhav** [comment]
Yeah, i missed that part. Thank you for directing
