### ISSUE TITLE
k8s secret is not updated on roll-out , even with sync enabled and updated SecretProvider class

### ISSUE THREAD

**Issue by esune** [Azure/secrets-store-csi-driver-provider-azure#1007]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
I'm running an AKS cluster and installed the the secret store csi driver provider using Helm. I am using k8s secrets to mount values as environment variables, and the settings to sync the secret and poll interval have been set when installing the Helm chart: `helm upgrade --install --set secrets-store-csi-driver.enableSecretRotation=true --set secrets-store-csi-driver.rotationPollInterval=2 csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --namespace kube-system`

When a new secret is added to Azure KeyVault, a custom Helm chart proceeds to update the custom `SecretproviderClass` with the new mappings, before new deployments are rolled-out. When this happens, the k8s secrets should refresh with the newly specified key/value pairs, however this does not seem to happen (the secret is not updated at all).

Deleting the secret and rolling out a new deployment causes it to be re-created with the correct (new) values.

**What did you expect to happen:**
The k8s secret is refreshed with the new values when a new deployment is rolled out.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:** User Assigned managed identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.2.3
- Azure Key Vault provider version: (use the image tag): v1.3.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
  Client Version: v1.25.3
  Kustomize Version: v4.5.7
  Server Version: v1.22.6
  Nodes: v1.22.6
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): Helm

**Comment by esune** [comment]
Likely related to #746 and #821

**Comment by sintetico82** [comment]
Yes me too. I don't understand how to force to synch

**Comment by joywaves** [comment]
also just ran into the same issue. had to drop the existing secret in order to update it.

- AKS v1.24.6 client & server, sync/update doing over the helm. 
- Secrets Store CSI Driver version: (use the image tag): v1.2.3
- Azure Key Vault provider version: (use the image tag): v1.3.0

I don't recall it being an issue in the previous version though(regarding limits)

**Comment by aramase** [comment]
> I don't recall it being an issue in the previous version though(regarding limits)

Hello 👋🏻  this limitation always existed: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated. If you have secret auto rotation feature enabled, it'll update the Kubernetes secret after the rotation poll interval but if you're new pod is relying on a new value from Kubernetes secret, then you will need to delete the Kubernetes secret so it gets recreated with updated `SecretProviderClass` values. 


> But any impruvement on the roadmap for this?

We currently use a custom controller for rotation which is why we don't update the Kuberenetes secret adhoc every time `SecretProviderClass` is updated. We are planning to switch to https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/585 for rotation which can enhance this behavior. That feature is in our backlog and will be planned for implementation soon.

**Comment by esune** [comment]
> 
> Hello 👋🏻 this limitation always existed: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated. If you have secret auto rotation feature enabled, it'll update the Kubernetes secret after the rotation poll interval but if you're new pod is relying on a new value from Kubernetes secret, then you will need to delete the Kubernetes secret so it gets recreated with updated `SecretProviderClass` values.

The issue is that the k8s secret is not being updated even when auto rotation is enabled.

**Comment by aramase** [comment]
> The issue is that the k8s secret is not being updated even when auto rotation is enabled.

With auto rotation enabled, the driver will only update after the next rotation poll interval. If the next poll interval is t + 2m and the `SecretProviderClass` is updated at t + 1, then k8s secret will only be updated at t + 2. For on-demand update of k8s secret, recommendation is to delete the k8s secret and let it be recreated. 

If k8s secret never gets updated even after multiple poll intervals, then the logs will contain an error message.

**Comment by esune** [comment]
@aramase I'll do some more digging, i am pretty sure it was just sitting unchanged without any specific error and blocking the deployments that depend on the new keys from being completed successfully.

In the meantime: any suggestions on how to programmatically delete the secret when the chart updating the `SecretProvider` class runs? Having the secret component block other service rollouts because its keys and/or values won't be updated right away even if the provider class definition changes seems like a dependency that I would rather not have - that is why I always run the secret provider class chart before the services that depend on it.

**Comment by esune** [comment]
@aramase I just run the scenario again: see first post for details on my setup. I added a new secret in KeyVault and updated my SecretProvider class to include it so that the driver would update the k8s secret after the polling interval has expired.

This was now 17m ago, the k8s secret is not yet up-to-date.

I am following [these](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/#isolate-errors-from-logs) instructions to gather more information:
* `kubectl get pods -l app=csi-secrets-store-provider-azure -o wide`: shows all pods are running without issues
* `kubectl get pods -l app=secrets-store-csi-driver -o wide`: I see two sets of pods, one that appears to be managed by AKS and is running (have label `kubernetes.azure.com/managedby=aks`) and one that seems managed by helm (with annotation `app.kubernetes.io/managed-by=Helm`) that is in `CrashLoopBackOff`.

I am not too sure how there are two sets of pods for the service, my guess is whoever initially set-up the environment had it managed by AKS and then tried adding the Helm chart? Not sure. 

I believe the Helm revision is what I want to keep: is there a procedure to remove the other instance (what objects should I be pruning exactly)?

Either way, when I execute the command to fetch the logs from the containers nothing is returned and describing the resource only shows the pod is being restarted, not an error message (for both running and crashing instances).

**Comment by aliaksei-babuk** [comment]
I have the same problem. Interesting that after deleting secret start taking the Disabled values from KV. https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1087

**Comment by aramase** [comment]
> @aramase I have the same problem. Interesting that after deleting secret start taking the Disabled values from KV. [kubernetes-sigs/secrets-store-csi-driver#1087](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1087)

@aliaksei-babuk Please open a new issue and provide the `SecretProviderClass` yaml file as part of it. Also, include the relevant logs. Here is our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/

**Comment by aramase** [comment]
> kubectl get pods -l app=secrets-store-csi-driver -o wide: I see two sets of pods, one that appears to be managed by AKS and is running (have label kubernetes.azure.com/managedby=aks) and one that seems managed by helm (with annotation app.kubernetes.io/managed-by=Helm) that is in CrashLoopBackOff.


@esune It's possible the AKS add-on driver pods don't have auto-rotation enabled which is why it isn't working. I would recommend uninstalling everything (helm and add-on) and then doing a clean-install either with helm or the AKS add-on. If you're on AKS, the recommendation is to use the AKS add-on as that's officially supported. If you install it with helm, support is only via GitHub and you'll need to manage upgrading when there are newer releases.

Here is more detail on the AKS add-on: https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

> Either way, when I execute the command to fetch the logs from the containers nothing is returned and describing the resource only shows the pod is being restarted, not an error message (for both running and crashing instances).

You might have conflicting features enabled with helm and the AKS add-on pods which is the issue. Recommend to do a clean-install.

**Comment by esune** [comment]
@aramase I tried following the uninstall procedure and I get an error stating the AKS plugin may not be installed, which is confusing. I'll do some more digging and follow-up.

**Comment by esune** [comment]
I asked the person who is maintaining the environment to proceed with uninstalling and reinstalling the Secret Provider, but don't have a time estimate on when I will be able to report back, unfortunately.

**Comment by esune** [comment]
Bumping to keep open while we run further testing/troubleshooting.
