### ISSUE TITLE
failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by travis-sobeck** [Azure/secrets-store-csi-driver-provider-azure#101]
Followed directions from https://github.com/Azure/secrets-store-csi-driver-provider-azure#usage
Installed fresh today on a new cluster (v1.17.5 via Rancher) with:
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name
(also tried:
helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver
kubectl apply -f https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml
Identical results)
All the pods deploy fine
I created Service Principle and installed as secret as directed  
Deployed provider class https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml
(updated appropriate values)
The applied the example https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/nginx-deployment-synck8s-azure.yaml
(nginx as container)
nginx pod stuck on ContainerCreating, reporting 
Warning  FailedMount  7s (x7 over 39s)  kubelet, temp2-2   MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

**What did you expect to happen:**
Create pod and sync secrets as described by docs

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**
Add defaults as of 5/14/2020
- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
@travis-sobeck Can you list the csidrivers running on the cluster?

```
kubectl get csidrivers
kubectl describe csidriver secrets-store.csi.k8s.io
```

**Comment by travis-sobeck** [comment]
PS C:\Users\travis\Documents\GitHub> kubectl get CSIDriver 

NAME                       CREATED AT
secrets-store.csi.k8s.io   2020-05-14T18:24:16Z
PS C:\Users\travis\Documents\GitHub> kubectl describe csidriver secrets-store.csi.k8s.io

Name:         secrets-store.csi.k8s.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1beta1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2020-05-14T18:24:16Z
  Resource Version:    473851
  Self Link:           /apis/storage.k8s.io/v1beta1/csidrivers/secrets-store.csi.k8s.io
  UID:                 49d8dedd-3502-4830-8aa0-4f591c298fc2
Spec:
  Attach Required:    false
  Pod Info On Mount:  true
  Volume Lifecycle Modes:
    Ephemeral
Events:  <none>

I'll clean out environment and re-run the helm

**Comment by travis-sobeck** [comment]
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: C:\Users\travis\AppData\Local\Temp\helm\repository\csi-secrets-store-provider-azure-0.0.6.tgz

client.go:87: [debug] creating 7 resource(s)
NAME: csi-secrets-store-provider-azure-1589487363
LAST DEPLOYED: Thu May 14 15:16:04 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image:
  pullPolicy: IfNotPresent
  repository: mcr.microsoft.com/k8s/csi/secrets-store/provider-azure
  tag: 0.0.5
linux:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi
secrets-store-csi-driver:
  global: {}
  install: true
  linux:
    enabled: true
    image:
      pullPolicy: Always
      repository: docker.io/deislabs/secrets-store-csi
      tag: v0.0.10
  livenessProbe:
    port: 9808
  logLevel:
    debug: true
  rbac:
    install: true
  windows:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: mcr.microsoft.com/k8s/csi/secrets-store/driver
      tag: v0.0.10
windows:
  enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

HOOKS:
MANIFEST:
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: default
  labels:
    heritage: "Helm"
    release: "csi-secrets-store-provider-azure-1589487363"
    revision: "1"
    chart: "secrets-store-csi-driver"
    chartVersion: "0.0.10"
    app: secrets-store-csi-driver
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: secretproviderclasses.secrets-store.csi.x-k8s.io
spec:
  group: secrets-store.csi.x-k8s.io
  names:
    kind: SecretProviderClass
    listKind: SecretProviderClassList
    plural: secretproviderclasses
    singular: secretproviderclass
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: SecretProviderClass is the Schema for the secretproviderclasses
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SecretProviderClassSpec defines the desired state of SecretProviderClass
          properties:
            parameters:
              additionalProperties:
                type: string
              description: Configuration for specific provider
              type: object
            provider:
              description: Configuration for provider name
              type: string
            secretObjects:
              items:
                description: SecretObject defines the desired state of synced K8s
                  secret objects
                properties:
                  data:
                    items:
                      description: SecretObjectData defines the desired state of synced
                        K8s secret object data
                      properties:
                        key:
                          description: data field to populate
                          type: string
                        objectName:
                          description: name of the object to sync
                          type: string
                      type: object
                    type: array
                  secretName:
                    description: name of the K8s secret object
                    type: string
                  type:
                    description: type of K8s secret object
                    type: string
                type: object
              type: array
          type: object
        status:
          description: SecretProviderClassStatus defines the observed state of SecretProviderClass
          properties:
            byPod:
              items:
                description: ByPodStatus defines the state of SecretProviderClass
                  as seen by an individual controller
                properties:
                  id:
                    description: id of the pod that wrote the status
                    type: string
                  namespace:
                    description: namespace of the pod that wrote the status
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretproviderclasses-role
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - update
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretproviderclasses-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretproviderclasses-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: default
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-secrets-store-provider-azure-1589487363-secrets-store-csi-d
  namespace: default
  labels:
    heritage: "Helm"
    release: "csi-secrets-store-provider-azure-1589487363"
    revision: "1"
    chart: "secrets-store-csi-driver"
    chartVersion: "0.0.10"
    app: secrets-store-csi-driver
spec:
  selector:
    matchLabels:
      app: secrets-store-csi-driver
  template:
    metadata:
      labels:
        heritage: "Helm"
        release: "csi-secrets-store-provider-azure-1589487363"
        revision: "1"
        chart: "secrets-store-csi-driver"
        chartVersion: "0.0.10"
        app: secrets-store-csi-driver
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: secrets-store-csi-driver
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-secrets-store/csi.sock
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "rm -rf /registration/secrets-store.csi.k8s.io-reg.sock",
                  ]
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: secrets-store
          image: "docker.io/deislabs/secrets-store-csi:v0.0.10"
          args:
            - "--debug=true"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--provider-volume=/etc/kubernetes/secrets-store-csi-providers"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /healthz
                port: healthz
              initialDelaySeconds: 30
              timeoutSeconds: 10
              periodSeconds: 15
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: providers-dir
              mountPath: /etc/kubernetes/secrets-store-csi-providers
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          imagePullPolicy: Always
          args:
          - --csi-address=/csi/csi.sock
          - --probe-timeout=3s
          - --health-port=9808
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
      volumes:
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-secrets-store/
            type: DirectoryOrCreate
        - name: providers-dir
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
            type: DirectoryOrCreate
---
# Source: csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-secrets-store-provider-azure-1589487363
  namespace: default
  labels:
    heritage: "Helm"
    release: "csi-secrets-store-provider-azure-1589487363"
    revision: "1"
    chart: "csi-secrets-store-provider-azure"
    chartVersion: "0.0.6"
    app: csi-secrets-store-provider-azure
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
  template:
    metadata:
      labels:
        heritage: "Helm"
        release: "csi-secrets-store-provider-azure-1589487363"
        revision: "1"
        chart: "csi-secrets-store-provider-azure"
        chartVersion: "0.0.6"
        app: csi-secrets-store-provider-azure
    spec:
      containers:
        - name: provider-azure-installer
          image: "mcr.microsoft.com/k8s/csi/secrets-store/provider-azure:0.0.5"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: TARGET_DIR
              value: "/etc/kubernetes/secrets-store-csi-providers"
          volumeMounts:
            - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
              name: providervol
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
      nodeSelector:
        beta.kubernetes.io/os: linux
---
# Source: csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/csidriver.yaml
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: secrets-store.csi.k8s.io
spec:
  podInfoOnMount: true
  attachRequired: false
  # Added in Kubernetes 1.16 with default mode of Persistent. Secrets store csi driver needs Ephermeral to be set.
  volumeLifecycleModes:
  - Ephemeral

**Comment by travis-sobeck** [comment]
I have not configured an storageclasses for this cluster yet if that matters

**Comment by aramase** [comment]
@travis-sobeck Could you check the csi-driver logs?

You can get the driver pods by running -
```
kubectl get pods -l app=secrets-store-csi-driver
```

Then view the logs for the pod 
```
kubectl logs <pod name> node-driver-registrar
kubectl logs <pod name> secrets-store
```

**Comment by travis-sobeck** [comment]
PS C:\Users\travis\Documents\GitHub> kubectl get pods -l app=secrets-store-csi-driver

NAME                                                              READY   STATUS    RESTARTS   AGE
csi-secrets-store-provider-azure-1589487363-secrets-store-jfc5g   3/3     Running   0          20m
csi-secrets-store-provider-azure-1589487363-secrets-store-sxvjm   3/3     Running   0          20m
csi-secrets-store-provider-azure-1589487363-secrets-store-zps45   3/3     Running   0          20m

I0514 20:16:08.320163       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0514 20:16:08.320373       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0514 20:16:08.320488       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0514 20:16:13.580978       1 main.go:127] Calling CSI driver to discover driver name
I0514 20:16:13.580998       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0514 20:16:13.581004       1 connection.go:181] GRPC request: {}
I0514 20:16:13.587538       1 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.10"}
I0514 20:16:13.588102       1 connection.go:184] GRPC error: <nil>
I0514 20:16:13.588122       1 main.go:137] CSI driver name: "secrets-store.csi.k8s.io"
I0514 20:16:13.588200       1 node_register.go:58] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0514 20:16:13.603986       1 node_register.go:67] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
{the other 2 look the same]

PS C:\Users\travis\Documents\GitHub> kubectl logs csi-secrets-store-provider-azure-1589487363-secrets-store-zps45 secrets-store        

time="2020-05-14T20:16:08Z" level=info msg="Driver: secrets-store.csi.k8s.io "
time="2020-05-14T20:16:08Z" level=info msg="Version: v0.0.10"
time="2020-05-14T20:16:08Z" level=info msg="Provider Volume Path: /etc/kubernetes/secrets-store-csi-providers"
time="2020-05-14T20:16:08Z" level=info msg="Minimum provider versions: "
time="2020-05-14T20:16:08Z" level=info msg="Enabling controller service capability: CREATE_DELETE_VOLUME"
time="2020-05-14T20:16:08Z" level=info msg="Enabling volume access mode: SINGLE_NODE_READER_ONLY"
time="2020-05-14T20:16:08Z" level=info msg="Enabling volume access mode: MULTI_NODE_READER_ONLY"
time="2020-05-14T20:16:08Z" level=info msg="minimum compatible provider versions not specified with --min-provider-version"
time="2020-05-14T20:16:08Z" level=info msg="Listening for connections on address: //csi/csi.sock"
time="2020-05-14T20:16:08Z" level=debug msg="GRPC call: /csi.v1.Identity/GetPluginInfo"
time="2020-05-14T20:16:08Z" level=debug msg="GRPC request: "
time="2020-05-14T20:16:08Z" level=debug msg="Using default GetPluginInfo"
time="2020-05-14T20:16:08Z" level=debug msg="GRPC response: name:\"secrets-store.csi.k8s.io\" vendor_version:\"v0.0.10\" "
time="2020-05-14T20:16:09Z" level=debug msg="GRPC call: /csi.v1.Identity/GetPluginInfo"
time="2020-05-14T20:16:09Z" level=debug msg="GRPC request: "
time="2020-05-14T20:16:09Z" level=debug msg="Using default GetPluginInfo"
time="2020-05-14T20:16:09Z" level=debug msg="GRPC response: name:\"secrets-store.csi.k8s.io\" vendor_version:\"v0.0.10\" "
time="2020-05-14T20:16:43Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-05-14T20:16:43Z" level=debug msg="GRPC request: "
time="2020-05-14T20:16:43Z" level=debug msg="GRPC response: ready:<value:true > "
time="2020-05-14T20:16:58Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-05-14T20:16:58Z" level=debug msg="GRPC request: "
.... [repeats for a while]

**Comment by aramase** [comment]
@travis-sobeck From the logs you posted for `node-driver-registrar`, looks like kubelet never finds /registration/secrets-store.csi.k8s.io-reg.sock. 

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/23eaef9b463bdbe0433549cd65d8dde55ac35776/deploy/secrets-store-csi-driver.yaml#L99-L102

Does your kubelet use the same path?

**Comment by travis-sobeck** [comment]
When I fist tried to get this going I ran into the error "MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory"
and the csi driver pods wouldn't start, then I found this https://github.com/rancher/rke/issues/1151
and added the following to the k8s config file
`kubelet:
      extra_binds:
        - "/var/lib/kubelet/plugins_registry:/var/lib/kubelet/plugins_registry"`
After that the csi driver pods spun up

**Comment by travis-sobeck** [comment]
does that answer your question?  I'm not a k8s expert quite yet :)

**Comment by aramase** [comment]
@travis-sobeck can you try this workaround - https://github.com/rancher/rke/issues/1151#issuecomment-466113635

You'll probably need this one too -
```
        - "/var/lib/kubelet/plugins:/var/lib/kubelet/plugins"
```

**Comment by travis-sobeck** [comment]
I'll give it a go

**Comment by travis-sobeck** [comment]
I made the change, clear everything out and re-applied. same error
`MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers`

logs the same too
PS C:\Users\travis\Documents\GitHub> kubectl logs $pns[2] node-driver-registrar
I0514 21:20:13.495206       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0514 21:20:13.496827       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0514 21:20:13.496924       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0514 21:20:14.498178       1 main.go:127] Calling CSI driver to discover driver name
I0514 21:20:14.498470       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0514 21:20:14.498569       1 connection.go:181] GRPC request: {}
I0514 21:20:14.501180       1 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.10"}
I0514 21:20:14.501889       1 connection.go:184] GRPC error: <nil>
I0514 21:20:14.501974       1 main.go:137] CSI driver name: "secrets-store.csi.k8s.io"
I0514 21:20:14.502082       1 node_register.go:58] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0514 21:20:14.502322       1 node_register.go:67] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock

**Comment by travis-sobeck** [comment]
it gets a response when it asks for plugin info `GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.10"}`
so it knows it exits?
After GRPC error:
it seems to complete `Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock`  is it a timing issue?

**Comment by aramase** [comment]
@travis-sobeck It never gets a response back because kubelet doesn't recognize the `/var/lib/kubelet/plugins` or `/registration/secrets-store.csi.k8s.io-reg.sock`

A successful log looks like this -
```
I0514 20:30:11.784808       1 node_register.go:67] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0514 20:30:12.728625       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0514 20:30:13.724772       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0514 20:30:13.745770       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

From the logs you posted, the request just hangs because kubelet is probably looking for the socket in a different path.

**Comment by travis-sobeck** [comment]
I know this isn't super amazing to look at, but maybe it has some useful info
![image](https://user-images.githubusercontent.com/20098093/81990217-564ace00-9604-11ea-8cae-c6ce580d630f.png)

**Comment by aramase** [comment]
@travis-sobeck What is the root-dir that kubelet is using for this cluster? You should be able to hop on any node and run `ps aux | grep kubelet`.The `--root-dir` might be configured to a different path.

I believe RKE starts kubelet with a different root dir -
```
--root-dir=/opt/rke/var/lib/kubelet
```

**Comment by travis-sobeck** [comment]
--root-dir=/opt/rke/var/lib/kubelet
I saw something about that in another issue with rke but can't find it now

**Comment by travis-sobeck** [comment]
https://github.com/rancher/rke/issues/1585 but not sure if its %100 related

**Comment by aramase** [comment]
@travis-sobeck Can you edit the daemonset to change all references of `/var/lib/kubelet` to `/opt/rke/var/lib/kubelet` in the driver?

**Comment by travis-sobeck** [comment]
sure, I can give that a go

**Comment by aramase** [comment]
@travis-sobeck Also, please note, changing the will enable mount to work, but the secret creation will still fail. The driver currently only understands `/var/lib/kubelet`. I've opened an issue to track this change - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/206

**Comment by travis-sobeck** [comment]
That worked! Thanks.  Would it be worth adding that as a path option in values.yaml ??
it created the secret just fine, i was able to decode it, got what I expected

**Comment by aramase** [comment]
@travis-sobeck Yeah, I've opened the [issue](kubernetes-sigs/secrets-store-csi-driver#206) to track that change. I'll get that added.

**Comment by travis-sobeck** [comment]
Thanks.  Will updating the path negate the need to add those extra binds to the k8s config?
I guess I can roll back and test it.

**Comment by aramase** [comment]
@travis-sobeck The driver updates the status of `SecretProviderClass` after successfully creating the secret. It gets the podUID from the mount target path and adds that to the status field. In RKE cluster, as the path starts with `/opt/rke/*`, it'll update the status with wrong data. I'll get that fixed with PR to allow kubelet path to be configurable.

**Comment by ritazh** [comment]
Just FYI, create secret works because podUID in `NodePublishVolume` comes from the volume's attribute. Delete secret during unmount will fail as `getPodUIDFromTargetPath` assumes the root dir.

**Comment by travis-sobeck** [comment]
@ritazh thanks.
For reference to anyone else that finds this, in the end I didn't need to add the extra_binds
I just had to Update the secrets-store-csi-driver.yaml file to replace any reverence to `/var/lib/kubelet` to `/opt/rke/var/lib/kubelet`
Then after running 
 - `helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name`
 - `kubectl delete daemonset -l app=secrets-store-csi-driver`
 - `kubectl apply -f <path_to_updated_secrets-store-csi-driver.yaml>

The issue aramase submitted above should simplify things.  Not sure about the fix for deleting secret.

**Comment by travis-sobeck** [comment]
@aramase I see your change got added to the "upstream" helm [Change](https://github.com/kubernetes-sigs/secrets-store-csi-driver/commit/03f6387c075c5f3ed002aeba1c4f799d3b125f36)
 but I don't see the change reflected in the csi-secrets-store-provider-azure helm chart?
Thanks

**Comment by aramase** [comment]
@travis-sobeck The changes have been merged, but we have not yet cut a release with for the helm charts and driver with the changes included. We'll cut a new release this week and then you should be able to try it out with the official helm charts.

**Comment by travis-sobeck** [comment]
@aramase Sounds good, thanks

**Comment by aramase** [comment]
@anujgeek The custom kubelet dir is not applicable in your scenario. @travis-sobeck is using a rancher cluster and the kubelet root dir is `/opt/rke/var/lib/kubelet` for that cluster. For AKS, the kubelet root dir is the default `/var/lib/kubelet`.

**Comment by SwatantraYadav** [comment]
> @ritazh thanks.
> For reference to anyone else that finds this, in the end I didn't need to add the extra_binds
> I just had to Update the secrets-store-csi-driver.yaml file to replace any reverence to `/var/lib/kubelet` to `/opt/rke/var/lib/kubelet`
> Then after running
> 
> * `helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name`
> * `kubectl delete daemonset -l app=secrets-store-csi-driver`
> * `kubectl apply -f <path_to_updated_secrets-store-csi-driver.yaml>
> 
> The issue aramase submitted above should simplify things. Not sure about the fix for deleting secret.

@travis-sobeck Where is the file secrets-store-csi-driver.yaml located. I ssh into the vm and dont see this file.
