### ISSUE TITLE
Mount failed with an error -  failed to get keyvault client: failed to get authorizer for keyvault client: nmi response failed with status code: 404

### ISSUE THREAD

**Issue by nuru5** [Azure/secrets-store-csi-driver-provider-azure#1016]
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    19m                   default-scheduler  Successfully assigned aks-keyvault/nginx-deployment-6748746f8f-xdxgg to aks-linuxpool-12988371-vmss000001
  Warning  FailedMount  4m15s (x7 over 17m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-mount], unattached volumes=[secrets-mount kube-api-access-l6t7n]: timed out waiting for the condition
  Warning  FailedMount  2m23s (x10 over 18m)  kubelet            MountVolume.SetUp failed for volume "secrets-mount" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get authorizer for keyvault client: nmi response failed with status code: 404, response body: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
  Warning  FailedMount  117s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-mount], unattached volumes=[kube-api-access-l6t7n secrets-mount]: timed out waiting for the condition
  
======================================================================  
mic pod logs:
I1108 12:09:29.201552       1 main.go:114] starting mic process. Version: v1.8.13. Build date: 2022-10-12-22:23
W1108 12:09:29.201620       1 main.go:119] --kubeconfig not passed will use InClusterConfig
I1108 12:09:29.201625       1 main.go:136] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I1108 12:09:29.201757       1 main.go:144] running MIC in namespaced mode: false
I1108 12:09:29.201773       1 main.go:148] client QPS set to: 5. Burst to: 5
I1108 12:09:29.202096       1 mic.go:138] starting to create the pod identity client. Version: v1.8.13. Build date: 2022-10-12-22:23
I1108 12:09:29.230785       1 mic.go:144] Kubernetes server version: v1.24.6
I1108 12:09:29.232464       1 cloudprovider.go:117] MIC using user assigned identity: 1e10##### REDACTED #####8e8d for authentication.
I1108 12:09:29.235437       1 probes.go:41] initialized health probe on port 8080
I1108 12:09:29.235457       1 probes.go:44] started health probe
I1108 12:09:29.236993       1 metrics.go:341] registered views for metric
I1108 12:09:29.237294       1 prometheus_exporter.go:21] starting Prometheus exporter
I1108 12:09:29.237311       1 metrics.go:347] registered and exported metrics on port 8888
I1108 12:09:29.237321       1 mic.go:242] initiating MIC Leader election
I1108 12:09:29.237342       1 leaderelection.go:248] attempting to acquire leader lease default/aad-pod-identity-mic...

=========================
I1108 12:09:29.070091       1 main.go:114] starting mic process. Version: v1.8.13. Build date: 2022-10-12-22:23
W1108 12:09:29.070179       1 main.go:119] --kubeconfig not passed will use InClusterConfig
I1108 12:09:29.070185       1 main.go:136] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I1108 12:09:29.070282       1 main.go:144] running MIC in namespaced mode: false
I1108 12:09:29.070299       1 main.go:148] client QPS set to: 5. Burst to: 5
I1108 12:09:29.070325       1 mic.go:138] starting to create the pod identity client. Version: v1.8.13. Build date: 2022-10-12-22:23
I1108 12:09:29.097760       1 mic.go:144] Kubernetes server version: v1.24.6
I1108 12:09:29.098073       1 cloudprovider.go:117] MIC using user assigned identity: 1e10##### REDACTED #####8e8d for authentication.
I1108 12:09:29.101017       1 probes.go:41] initialized health probe on port 8080
I1108 12:09:29.101031       1 probes.go:44] started health probe
I1108 12:09:29.101104       1 metrics.go:341] registered views for metric
I1108 12:09:29.101168       1 prometheus_exporter.go:21] starting Prometheus exporter
I1108 12:09:29.101175       1 metrics.go:347] registered and exported metrics on port 8888
I1108 12:09:29.101180       1 mic.go:242] initiating MIC Leader election
I1108 12:09:29.101194       1 leaderelection.go:248] attempting to acquire leader lease default/aad-pod-identity-mic...
I1108 12:09:50.348169       1 leaderelection.go:258] successfully acquired lease default/aad-pod-identity-mic
I1108 12:09:50.352833       1 mic.go:330] type upgrade status configmap found from version: v1.8.13. Skipping type upgrade!
I1108 12:09:50.454209       1 crd.go:457] CRD informers started
I1108 12:09:51.054063       1 pod.go:72] pod cache synchronized. Took 700.880706ms
I1108 12:09:51.054084       1 pod.go:79] pod watcher started !!
I1108 12:09:51.054098       1 mic.go:400] sync thread started.

=======================================
nmi logs:
E1108 12:18:14.695930       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:18:14.695968       1 server.go:239] status (404) took 80015517486 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
E1108 12:19:50.778757       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:19:50.778794       1 server.go:239] status (404) took 80026399344 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
E1108 12:21:42.850062       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:21:42.850098       1 server.go:239] status (404) took 80029780417 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
E1108 12:24:06.942650       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:24:06.942688       1 server.go:239] status (404) took 80033792124 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
E1108 12:27:29.005866       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:27:29.005917       1 server.go:239] status (404) took 80007873543 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
I1108 12:30:29.492542       1 server.go:413] exception pod kube-system/ama-logs-756p9 token handling
I1108 12:30:29.492563       1 server.go:356] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1108 12:30:29.536166       1 server.go:239] status (200) took 43661496 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.86.92.115
E1108 12:30:51.083465       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:30:51.083512       1 server.go:239] status (404) took 80027364832 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
I1108 12:31:40.532784       1 server.go:413] exception pod kube-system/ama-logs-rs-6f7456fcbb-fpc88 token handling
I1108 12:31:40.532801       1 server.go:356] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1108 12:31:40.539660       1 server.go:239] status (200) took 6914186 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.86.92.102
E1108 12:34:13.133201       1 server.go:281] failed to get identities, error: getting assigned identities for pod aks-keyvault/nginx-deployment-6748746f8f-xdxgg in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I1108 12:34:13.133234       1 server.go:239] status (404) took 80009718833 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1

**Comment by nilekhc** [comment]
@nuru5 Have you checked the troubleshooting guide?

https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/#failed-to-get-key-vault-token-nmi-response-failed-with-status-code-404

**Comment by nuru5** [comment]
nuruddin [ ~ ]$ az login --identity --allow-no-subscriptions --debug
cli.knack.cli: Command arguments: ['login', '--identity', '--allow-no-subscriptions', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fbc4c050160>, <function OutputProducer.on_global_arguments at 0x7fbc4bf114c0>, <function CLIQuery.on_global_arguments at 0x7fbc4bf16a60>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.002         2         9
cli.azure.cli.core: Total (1)                 0.002         2         9
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.146         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.146         1         1  
cli.azure.cli.core: Loaded 3 groups, 10 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fbc4b189e50>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/nuruddin/.azure/commands/2022-11-09.05-35-26.login.639.log'.
az_command_data_logger: command args: login --identity --allow-no-subscriptions --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fbc4b133a60>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fbc4b100280>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fbc4b1003a0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fbc4bf11550>, <function CLIQuery.handle_query_parameter at 0x7fbc4bf16af0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fbc4b100310>]
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2404
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core._profile: MSI: token was retrieved. Now trying to initialize local accounts...
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2404
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1667973914' -> 1667973914
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '50808d26-5ff0-11ed-abea-929ae4407e6d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--identity --allow-no-subscriptions --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.42.0 (RPM) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.9.14 (Linux-5.4.0-1094-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions?api-version=2019-11-01 HTTP/1.1" 200 476
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '1d1e1140-bb27-46c1-a475-16d4eb50b0fb'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '1d1e1140-bb27-46c1-a475-16d4eb50b0fb'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTINDIA:20221109T053527Z:1d1e1140-bb27-46c1-a475-16d4eb50b0fb'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 09 Nov 2022 05:35:27 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '476'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"id":"/subscriptions/b4fb9e24-4084-465c-932b-7cdf625f6ef8","authorizationSource":"RoleBased","managedByTenants":[{"tenantId":"2f4a9838-26b7-47ee-be60-ccc1fdec5953"}],"subscriptionId":"b4fb9e24-4084-465c-932b-7cdf625f6ef8","tenantId":"04c72f56-1848-46a2-8167-8e5d36510cbc","displayName":"********","state":"Enabled","subscriptionPolicies":{"locationPlacementId":"PublicAndIndia_2015-09-01","quotaId":"EnterpriseAgreement_2014-09-01","spendingLimit":"Off"}}],"count":{"type":"Total","value":1}}
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7fbc4b152dc0>, <function _x509_from_base64_to_hex_transform at 0x7fbc4b152e50>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
[
  {
    "environmentName": "AzureCloud",
    "homeTenantId": "04c72f56-1848-46a2-8167-8e5d36510cbc",
    "id": "b4fb9e24-4084-465c-932b-7cdf625f6ef8",
    "isDefault": true,
    "managedByTenants": [
      {
        "tenantId": "2f4a9838-26b7-47ee-be60-ccc1fdec5953"
      }
    ],
    "name": "**********",
    "state": "Enabled",
    "tenantId": "04c72f56-1848-46a2-8167-8e5d36510cbc",
    "user": {
      "cloudShellID": true,
      "name": "nuruddin.shaikh*******",
      "type": "user"
    }
  }
]
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fbc4b18a0d0>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 0.933 seconds (init: 0.117, invoke: 0.816)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3262 in cache
telemetry.check: Negative: The /home/nuruddin/.azure/telemetry.txt was modified at 2022-11-09 05:28:52.769716, which in less than 600.000000 s

**Comment by nilekhc** [comment]
@nuru5 Are you able to resolve this?
