### ISSUE TITLE
What is the best option to access KV: Pod Identity or VMSS

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/secrets-store-csi-driver-provider-azure#102]
Between the four modes for accessing a Key Vault instance, what is the best option ?
When to use what ?

> The Azure Key Vault Provider offers four modes for accessing a Key Vault instance:
> 1. Service Principal
> 2. Pod Identity
> 3. VMSS User Assigned Managed Identity
> 4. VMSS System Assigned Managed Identity

The first option for SPN seems to be clearly not recommended.
Pod Identity will give access to Key Vault to only the Pod, not to all the VMs/Nodes in VMSS, right ?
Until today, AKS supports only System Managed Identity, does that mean I cannot use option number 3 ?

**Comment by aramase** [comment]
@HoussemDellai 

> Pod Identity will give access to Key Vault to only the Pod, not to all the VMs/Nodes in VMSS, right ?
That's right.

aad-pod-identity will assign/un-assign the identity on the underlying VM/VMSS based on where the pod lands. The identity is present on the entire VMSS, but the aad-pod-identity component will ensure only pods that have access configured for the identity can fetch a token using the identity. 

> Until today, AKS supports only System Managed Identity, does that mean I cannot use option number 3 ?

You can still use `VMSS User Assigned Managed Identity`. You can create a User Assigned Managed Identity and manually assign to the node pool as documented. 

All the 4 options should work today on an AKS or AKS-Engine cluster.

**Comment by HoussemDellai** [comment]
Thank you a lot @aramase :)
