### ISSUE TITLE
The Kubernetes secrets are not getting synced as part of the CSI syncenabled feature to get secrets into Environment Variables..

### ISSUE THREAD

**Issue by anu1508k** [Azure/secrets-store-csi-driver-provider-azure#1026]
I have installed helm csi driver with sync.secret enabled set to true. The SecretProviderClass has secretObjectName and pods have mounts .
SecretProviderClass:
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
      name: xyz-job-spc
      namespace: ${ENV_NAME}
spec:
  provider: gcp
  parameters:
    ClusterRole: secretprovidersyncing-role
    secrets: |
      - resourceName: "projects/xyz/secrets/xyz_key_txt_${ENV_NAME}/versions/latest"
        fileName: "key.txt"
  secretObjects:
    - data: 
      - key: xyz-key
        objectName: key.txt   
      secretName: xyz-secret
      type: Opaque

Pod Spec:

         env:
           -  name: PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: xyz-secret
                   key: xyz-key
          volumeMounts:
            - name: xyz-secret
              mountPath: /etc/xyz/xyz-secret/key.txt
              readOnly: true
      serviceAccountName: csi
      restartPolicy: Never
      volumes:
        - name: xyz-secret
          csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: xyz-job-spc

**Comment by anu1508k** [comment]
@aramase : can you pls help here?

**Comment by nilekhc** [comment]
@anu1508k Looks like you are using the `GCP` provider. Perhaps you want to open an issue here? https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues

**Comment by aramase** [comment]
As this issue is with `gcp` provider, please open an issue there as Nilekh mentioned.
