### ISSUE TITLE
certificate chain in the wrong order (nginx failed to start)

### ISSUE THREAD

**Issue by ibattat** [Azure/secrets-store-csi-driver-provider-azure#103]
**What steps did you take and what happened:**
Integrate k8s with AzureKeyVault, when fetching a PEM format certificate from the Vault the certificate chain is in the wrong order.
It seems that the server certificate is the last one in the list.
nginx is failed to start with the following msg:
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/nginx/intezer.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**What did you expect to happen:**
the server certificate is the first one and in the right order.

**Anything else you would like to add:**
in the Nginx [documentation](http://nginx.org/en/docs/http/configuring_https_servers.html#chains) you can see it's the same error. when changing the certificates order it seems to solve the issue.

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity

**Comment by ritazh** [comment]
@ibattat can you pls provide your `SecretProviderClass` yaml and how nginx is referencing it?

**Comment by aramase** [comment]
@ibattat Checking into see if you're still having issues. If you are, could you share the `SecretProviderClass` yaml that @ritazh requested?

**Comment by ibattat** [comment]
I checked it again and it seems to work
