### ISSUE TITLE
Still connecting to unix:///csi/csi.sock

### ISSUE THREAD

**Issue by nicklev** [Azure/secrets-store-csi-driver-provider-azure#1030]
**What steps did you take and what happened:**
I used the  `az aks enable-addons -a azure-keyvault-secrets-provider` command to add AKV secrets provider. The deployment used to work fine until there was an outage to my cluster and I had to Stop & Start AKS.
After restarting the AKS pods started deploying in the nodes. Then I saw that 3 out of 4 `aks-secrets-store-csi-driver` pods failed.
In the logs of the failed containers (node-driver-registrar) I see these messages:
`I1201 13:45:08.626379       1 main.go:166] Version: v2.5.1-0-ga31bf169
I1201 13:45:08.626433       1 main.go:167] Running node-driver-registrar in mode=registration
I1201 13:45:08.626987       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1201 13:45:08.627032       1 connection.go:154] Connecting to unix:///csi/csi.sock
W1201 13:45:18.627662       1 connection.go:173] Still connecting to unix:///csi/csi.sock`

**What did you expect to happen:**
I expected the `aks-secrets-store-csi-driver` to be properly deployed without any issues.

**Anything else you would like to add:**
-

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity - installed with `helm install aad-pod-identity aad-pod-identity/aad-pod-identity`

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 
mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.1
mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.2.2.3
mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.7.0
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.2.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.25.2
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): AKS managed add-on

**Comment by aramase** [comment]
@nicklev Thanks for reporting the issue. For the AKS managed add-on, could you open an issue in the [AKS](https://github.com/Azure/AKS/issues) instead? Also, while getting the logs, post the logs from `secrets-store` container from the driver.

cc @zeromagic to assist with the issue when opened in AKS repo
