### ISSUE TITLE
An error when constructing chain for a self signed certificate

### ISSUE THREAD

**Issue by annaFarbo** [Azure/secrets-store-csi-driver-provider-azure#1051]
**What steps did you take and what happened:**
Uploaded a pfx that contains:
* Private key
* Certificate 
* Intermediate Certificate 
* Root certificate(self signed)

The object type we configured for this pfx in the SecretProviderClass yaml is "secret"
The azure key vault provider fails to get this file and results in a "constructing chain resulted in cycle" error

**What did you expect to happen:**
We expected to get a pem format containing the private key and all the chain

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): v1.2.2.4
- Azure Key Vault provider version: (use the image tag):v1.2.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
   Client Version: v1.25.2
   Kustomize Version: v4.5.7
   Server Version: v1.24.6
  Nodes:  v1.24.6 
- Cluster type:AKS
- Installation method: AKS add-on

**Comment by aramase** [comment]
@annaFarbo thanks for opening the issue. The chain is constructed based on the authority key id and subject key id (when they match, the cert with subject key id was used to sign the cert with matching authority key id)

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/f2654600c01e2a37fc4122b3ef379f63d8aa23fa/pkg/provider/provider.go#L832-L834

can you confirm if all the certs have the correct ids? If not, that'll cause the loop.

**Comment by annaFarbo** [comment]
Hi @aramase ,
Thanks! You are right.
Even though the issuer and subject on the certificates are as expected and openssl verify succeeded for them the authority key identifier was not correct on the user certificate .
For certificates with correct ids the construction of the chain works as expected.
