### ISSUE TITLE
Volume mount fails on windows node

### ISSUE THREAD

**Issue by ayuzzz** [Azure/secrets-store-csi-driver-provider-azure#1056]
Hi team, we are facing an issue w.r.t secret-store csi driver on a windows node which is behind a proxy server. We want to know if there is some firewall configuration (or some other configuration) that is needed specifically for such machines.

We are getting the following error message for the application which uses the driver :

```
MountVolume.SetUp failed for volume "secrets-store02-inline" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  3m1s (x475 over 23h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store02-inline], unattached volumes=[secrets-store02-inline kube-api-access-whlvf]: timed out waiting for the condition
```

We also see the following error on secret-store pod logs for container "secret-store" :

```
{"ts":1671613958670.3242,"caller":"secrets-store/nodeserver.go:242","msg":"failed to mount secrets store object content","pod":{"name":"win-secretmanagement-6f947656d6-v9k62","namespace":"testapp"},"err":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"ts":1671613958670.3242,"caller":"secrets-store/nodeserver.go:88","msg":"unmounting target path as node publish volume failed","v":0,"targetPath":"c:\\var\\lib\\kubelet\\pods\\0bf9ba4d-5362-44c3-9f00-a9ff51d5a859\\volumes\\kubernetes.io~csi\\secrets-store02-inline\\mount","pod":{"name":"win-secretmanagement-6f947656d6-v9k62","namespace":"testapp"}}
{"ts":1671614080702.347,"caller":"secrets-store/nodeserver.go:359","msg":"Using gRPC client","v":0,"provider":"azure","pod":"win-secretmanagement-6f947656d6-v9k62"}
```

These are some details regarding our setup :

Kubernetes distribution : RKE2
We are using azure arc and the azuresecretprovider extension
We are using the following application (the placeholders get properly replaced by our kustomization file) :
[secretprovider.zip](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/10371017/secretprovider.zip)
The following solution works on a host machine which is not behind a proxy
Windows node is 2019 data server

**Comment by aramase** [comment]
cc @nilekhc is looking into this for the arc extension

**Comment by nilekhc** [comment]
Hi @ayuzzz RKE is not a supported distro yet. https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-akv-secrets-provider#prerequisites

cc @salaxander

**Comment by salaxander** [comment]
@aramase @nilekhc, just so my understanding is correct - this isn't actually an issue with the Azure provider or Arc right? Sounds like there needs to be a change in the driver to handle the kubelet path in RKE?

**Comment by nilekhc** [comment]
> @aramase @nilekhc, just so my understanding is correct - this isn't actually an issue with the Azure provider or Arc right? Sounds like there needs to be a change in the driver to handle the kubelet path in RKE?

It is an Arc issue. The driver already exposes an option to override kubelet path. Arc needs to handle updating the kubelet path while installation when the distro is RKE.

**Comment by ayuzzz** [comment]
Hi @aramase and @nilekhc, we have actually got informed by the Microsoft team that this extension (AkvSecretProvider) is supported on RKE. Please check the following link for details : https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/validation-program#validated-distributions
