### ISSUE TITLE
Volumes mounted error in certain scenario 

### ISSUE THREAD

**Issue by Lu1234** [Azure/secrets-store-csi-driver-provider-azure#1058]
Hi

Our team is using private cluster on Azure and install secret-store-csi-driver to retrieve TLS certification.
Everything works fine until we added NSG outbound rules on our cluster subnet to restrict any access to Internet.It is necessary due to our network policy and internal network strategy.
Here's the event logs from the pod

`Warning  FailedMount  9m22s (x3 over 16m)  kubelet                   Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[webhook-cert secrets-s
tore-inline kube-api-access-c87ph]: timed out waiting for the condition
  Warning  FailedMount  8m6s (x5 over 16m)   kubelet                   MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = DeadlineExceeded desc = context deadline
 exceeded`

My question is that if there's any ip list which shows what will be used by nginx ingress controller to mount certification using secret-store-csi-driver  during pod creation.And so we can allow those ip access in NSG.

Environment:

Secrets Store CSI Driver version: (use the image tag):
Azure Key Vault provider version: (use the image tag):
Kubernetes version: (use kubectl version):
Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
> My question is that if there's any ip list which shows what will be used by nginx ingress controller to mount certification using secret-store-csi-driver during pod creation.And so we can allow those ip access in NSG.

@Lu1234 It's mentioned here: https://learn.microsoft.com/en-us/azure/aks/limit-egress-traffic#csi-secret-store and https://learn.microsoft.com/en-us/azure/aks/limit-egress-traffic#azure-global-required-fqdn--application-rules. You need to allow access to keyvault and AAD.

**Comment by Lu1234** [comment]
@aramase 
Hi there,it seems that multiple FQDN are required by AKS to keep it working.Deny all internet access in NSG seems to be a bad strategy.I will keep looking for proper network policy to fit in my scenario,thank you for your time.

**Comment by aramase** [comment]
Closing this issue  with https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1058#issuecomment-1379671882. Please feel free to reopen if you have any questions.
