### ISSUE TITLE
Getting error on deployment with mounted secret on pod

### ISSUE THREAD

**Issue by williamohara** [Azure/secrets-store-csi-driver-provider-azure#1092]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

I am using Azure CSI secrets provider. I am deploying it correctly I feel. I am running a job that runs software I made with golang that does the following in this order.

1. Creates a new Azure user managed identity (az go sdk)
2. Gives the new user managed identity read access to secrets in my AZ vault (az go sdk)
3. Creates a new Namespace using the go-client (client-go sdk)
4. Creates a new service account in the namespace (client-go sdk)
5. Creates a role binding to said service account (client-go sdk)
6. Creates a federation between the managed identity and the service account (az go sdk)
7. Creates a CSI secrets provider for Azure Vault (client-go sdk)
8. Creates a deployment that pulls a container (another one I made) from ACR and uses the CSI driver to mount secrets from Azure Vault (client-go sdk)

Everything works as I want it to, but - I get a few of these errors when my deployment is kicked off..

```
Warning  FailedMount  12m   kubelet            MountVolume.SetUp failed for volume "my-mount-name" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod my-new-namespace/my-new-pod-from-my-deployment, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get authorizer for keyvault client: failed to acquire token: FromAssertion(): http call(https://login.microsoftonline.com/<my-az-tenant-id>/oauth2/v2.0/token)(POST) error: reply status code was 400:
{"error":"invalid_request","error_description":"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: '<my-AKS-cluster-oidc-issue-url>'. Assertion Subject: 'system:serviceaccount:my-new-namespace:my-new-service-account'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace ID: bac9ec79-1d93-491d-9098-e03d4ce08700\r\nCorrelation ID: 1db5358b-c445-4e60-93d3-48a07ef2bce3\r\nTimestamp: 2023-03-10 22:50:42Z","error_codes":[70021],"timestamp":"2023-03-10 22:50:42Z","trace_id":"bac9ec79-1d93-491d-9098-e03d4ce08700","correlation_id":"1db5358b-c445-4e60-93d3-48a07ef2bce3","error_uri":"https://login.microsoftonline.com/error?code=70021"}
```

basically, indicating that it cannot find a federation for the service account I created and the managed identity I am using in the CSI definition. it throws the error from zero to numerous times while starting the pod. It almost always resolves itself after several tries.

I do a check in my logic to make sure that azure resources are deployed fully before moving forward (the managed identity, the federation, etc.) so I am certain that Azure has completed setting up the federation. 

Why am I getting this error? It has something to do with Azure and not Kubernetes for sure, but I am not sure how I can set up my logic to mitigate this. 

Here is my CSI provider yaml definiton.

   ```apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: "2023-03-10T22:50:38Z"
  generation: 1
  name: my-csi-name
  namespace: first-main-auth-fe
  resourceVersion: "920653"
  uid: c2af1ab3-6c13-4f04-8786-f883f6b8204b
spec:
  parameters:
    clientID: <the client id of the managed identity>
    cloudName: ""
    keyvaultName: my-vault-name
    objects: |
      array:
        - |
          objectName: aSecretName
          objectType: secret
    resourceGroup: my-vault-rg
    subscriptionID: <my-subscription-id>
    tenantId: <my-tenant-id>
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
  provider: azure
  secretObjects:
  - data:
    - key: tls.key
      objectName: vaultSecretNameForTls
    - key: tls.crt
      objectName: vaultSecretNameForTls
    secretName: mySecretName
    type: kubernetes.io/tls
status: {}
```

**What did you expect to happen:**

I expect there to be no errors at all. The federation exists.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
i have a workload managed identity ( a managed identity specific to the workload and it is federated)

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 
   The most recent I assume (I checked the box to use secret store provider on cluster deployment)
- Azure Key Vault provider version: (use the image tag):
  The most recent I assume (I checked the box to use secret store provider on cluster deployment)
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
NAME                                  STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-subagntpool-28215076-vmss00000b   Ready    agent   58m   v1.25.5   172.16.6.4    <none>        Ubuntu 22.04.1 LTS   5.15.0-1033-azure   containerd://1.6.17+azure-1
```
- Cluster type: (e.g. AKS, aks-engine, etc):
  AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): Installed with cluster I used terraform to deploy cluster

**Comment by Yiyito11** [comment]
Having exactly the same issue, any news? where yo able to solve it @williamohara ?

**Comment by Yiyito11** [comment]
you should probably double check first that the URL of the cluster issuer inside the  federated credentials, matches with the one you are getting the error for. 
If you go to managed identity in azure then look for federated credentials and check that URL is the same.

**Comment by williamohara** [comment]
> you should probably double check first that the URL of the cluster issuer inside the federated credentials, matches with the one you are getting the error for. If you go to managed identity in azure then look for federated credentials and check that URL "issuer" is the same.

- indeed they are the same - I only have one AKS cluster on my tenant right now.

**Comment by nilekhc** [comment]
@williamohara Are you using the managed add-on in your AKS cluster? If not then we recommend using it. Also, we recently announced the [GA](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/general-availability-for-azure-active-directory-ad-workload/ba-p/3798292) of Workload Identity and highly recommend using that going forward.
