### ISSUE TITLE
Unable to provide multiple objectnames in secret 

### ISSUE THREAD

**Issue by rameshthangaraj** [Azure/secrets-store-csi-driver-provider-azure#110]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In flexvolume we are able to provide multiple secret names as objectnames as a semicolon seperated where as in csi driver we are not able to provide multiple secrets. 

Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadParameter\" Message=\"The request URI contains an invalid name:

**What did you expect to happen:**
Able to load multiple secrets in a comma or semicolon seperated 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by ritazh** [comment]
@rameshthangaraj Unlike the flexvolume solution, for Secrets store csi driver, please provide each object and its properties as an item in an array, refer to this example: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/v1alpha1_secretproviderclass.yaml
