### ISSUE TITLE
Pod is invalid when executing the updated YAML file

### ISSUE THREAD

**Issue by taytran0** [Azure/secrets-store-csi-driver-provider-azure#112]
I followed the guide up until the "Deploy you Kubernetes Resources" section. I downloaded the deployment yaml file and made sure that the secretProviderClass was correct, "azure-kvname" as it has been when the SecretProviderClass was made. Below is what I was trying to run:

![updateDeployment](https://user-images.githubusercontent.com/22763512/83191112-82387a00-a101-11ea-9341-9b1c032fa1f1.PNG)

When I ran the "kubextl apply -f updateDeployment.yaml": I got these errors below: 

![issues](https://user-images.githubusercontent.com/22763512/83191547-2fab8d80-a102-11ea-9599-5411d3909f88.PNG)

I expected the application to be deployed so I can then see what the mounted secret is. 

I'm confused as to why the Pod is invalid. Also, I'm using a Service Principal. 

**Environment:**

- Secrets Store CSI Driver version: latest:
- Azure Key Vault provider version: latest:
- Kubernetes version: 
    - Client Version: v1.18.0
    - Server Version: v1.1510
- Cluster type: AKS

**Comment by ritazh** [comment]
Can you please validate the driver is running as expected, run the following command:
```bash
kubectl get pods -l app=csi-secrets-store
```

**Comment by ritazh** [comment]
oh just noticed you are on k8s v1.15.10. As mentioned in the readme:

```
Recommended Kubernetes version:

For Linux - v1.16.0+
For Windows - v1.18.0+
```

**Comment by aramase** [comment]
@taytran0 Looks like you are using kubernetes version 1.15.10. The recommended kubernetes version is 1.16+ for this solution(https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider). 

The `CSIInlineVolume` feature gate is not enabled by default for 1.15 cluster and currently there is no way in AKS to enable feature gates.

So please try it out with 1.16+ kubernetes cluster.

**Comment by taytran0** [comment]
Hello, thank you so much for pointing that out. How do I get the latest version for the server side. I have the client one for v1.18 but no matter what I do to update. The server version stays at v1.15. Please advise.

**Comment by taytran0** [comment]
Disregard the last statement. I went into the Azure Portal to change it myself. I couldn't find a way to change it from CLI. I'm going to go through the whole set-up again to make sure this issue is closed for good. Thank you again!

**Comment by taytran0** [comment]
Yes! The issue is now closed. Also, I didn't know this before but even though you may have updated your kubernetes cluster to 1.16+, the node pool will still be on the version you created it with so you have to go in and manually change that as well.
