### ISSUE TITLE
AAD identity doesn't work

### ISSUE THREAD

**Issue by rosanch** [Azure/secrets-store-csi-driver-provider-azure#114]
followed the steps in https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md and couldn't create the Nginx store app to test.

describe in Nginx pod
Events:
  Type     Reason       Age                From                                        Message
  ----     ------       ----               ----                                        -------
  Normal   Scheduled              default-scheduler                           Successfully assigned default/nginx-secrets-store-inline-podid to aks-agentpool-42776086-vmss000002
  Warning  FailedMount  10s (x6 over 26s)  kubelet, aks-agentpool-42776086-vmss000002  MountVolume.SetUp failed for volume "secrets-store01-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Unauthorized

kubectl get pods -l app=csi-secrets-store
NAME                      READY   STATUS    RESTARTS   AGE
csi-secrets-store-6jbz4   2/2     Running   0          141m
csi-secrets-store-c4k5j   2/2     Running   0          141m
csi-secrets-store-nrz2p   2/2     Running   0          141m

**Comment by rosanch** [comment]
Secret provider class
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretproviderclasses-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretproviderclasses-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretproviderclasses-role
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
`


NMI POD Logs

> I0528 14:59:34.220505       1 main.go:61] Starting nmi process. Version: 1.6.1. Build date: 2020-05-22-17:50.
I0528 14:59:34.321607       1 crd.go:447] CRD lite informers started
I0528 14:59:34.321629       1 main.go:85] Running NMI in namespaced mode: false
I0528 14:59:34.321640       1 nmi.go:52] Initializing in standard mode
I0528 14:59:34.321646       1 probes.go:42] Initialized health probe on port 8080
I0528 14:59:34.321658       1 probes.go:45] Started health probe
I0528 14:59:34.321715       1 metrics.go:329] Registered views for metric
I0528 14:59:34.321767       1 prometheus_exporter.go:22] Starting Prometheus exporter
I0528 14:59:34.321779       1 metrics.go:336] Registered and exported metrics on port 9090
I0528 14:59:34.321788       1 server.go:97] Listening on port 2579
W0528 14:59:34.413622       1 iptables.go:104] Flushing iptables to add aad-metadata custom chains
W0602 05:43:17.118623       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.AzureAssignedIdentity ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Status\" is registered for version \"v1\" in scheme \"pkg/runtime/scheme.go:101\"") has prevented the request from succeeding

**Comment by aramase** [comment]
Had an offline conversation with @rosanch. The error indicated the required role assignments were not granted in `aad-pod-identity`. Closing this issue now. Please feel free to reopen if you still have issues.
