### ISSUE TITLE
Update secret values

### ISSUE THREAD

**Issue by rosanch** [Azure/secrets-store-csi-driver-provider-azure#115]
**Describe the solution you'd like**
Can the CSI update a secret stored instead of mounting the value in the pod?

**Anything else you would like to add:**
The main reason is to reload the Nginx tls cert and key

**Comment by aramase** [comment]
@rosanch We recently added a feature to sync the values as Kubernetes secrets. Check out this doc for more info about the feature - https://github.com/Azure/secrets-store-csi-driver-provider-azure#optional-sync-with-kubernetes-secrets

Also, check out this sample doc on how to use the Secrets Store CSI Driver and Azure Keyvault Provider with ingress controller -https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls

**Comment by rosanch** [comment]
Thank you @aramase 
Also, I see it does support to sign into different clouds, but I'm wondering if it will work in airgap clouds as well.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/153. Will be included in release `0.0.8`
