### ISSUE TITLE
Tolerations are not being included in the DeamonSet secrets-store-csi-driver

### ISSUE THREAD

**Issue by marinisaac1** [Azure/secrets-store-csi-driver-provider-azure#1190]
When executing the helm chart with a values file such as:
```csi-vaults.yaml
linux:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
```
By using the following command to install the driver:
`helm install csi-vault-secrets csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --namespace kube-system --values csi-vaults.yaml`

The `csi-vault-secrets-csi-secrets-store-provider-azure` DeamonSet includes the described toleration in the YAML file, but the `secrets-store-csi-driver` DeamonSet does not includes the toleration.

It is expected that the toleration is applied to both DeamonSets.

**Comment by aramase** [comment]
> It is expected that the toleration is applied to both DeamonSets.

The driver chart is packaged as a dependency in the provider charts:

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/dad67ff93e76554a489f72f2d4b0bef9afe2d417/charts/csi-secrets-store-provider-azure/Chart.yaml#L13-L17

You'll need to set the tolerations for the driver too under `secrets-store-csi-driver` section in the values.yaml

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/dad67ff93e76554a489f72f2d4b0bef9afe2d417/charts/csi-secrets-store-provider-azure/values.yaml#L108-L111
