### ISSUE TITLE
Volume mount failed on node with taints

### ISSUE THREAD

**Issue by tanzencoder** [Azure/secrets-store-csi-driver-provider-azure#120]
**What steps did you take and what happened:**
I am moving my pods to specific nodes with taints and the volume mount failed with the following errer. 

FailedMount: MountVolume.SetUp failed for volume "secrets-store" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

**What did you expect to happen:**

**Anything else you would like to add:**
This worked before I tried to move the pod to a node with a taint. We want to get all of our custom applications on to separate nodes so we can control scaling better for our applications separate from system level applications such as this.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity] Service Principal

**Environment:**

- Secrets Store CSI Driver version: v0.0.10:
- Azure Key Vault provider version: (use the image tag): 0.0.5
- Kubernetes version: 1.16.9:
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@tanzencoder Can you confirm if there is a driver pod running on the node with taint?

**Comment by tanzencoder** [comment]
@aramase No, the driver pod never got deployed. I have since dropped the used of taints and switched to node affinity to accomplish what I wanted and that worked. So it feels like it's related to taints.

**Comment by aramase** [comment]
@tanzencoder For nodes that are tainted, the driver needs to be modified to tolerate the taint. I've opened an issue in the driver to allow user to set tolerations they need for driver using helm charts - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/227. In the meantime could you try adding the toleration to check if that fixes your issue?

**Comment by tanzencoder** [comment]
@aramase I will try it over the weekend, I won't be able to today.
