### ISSUE TITLE
Dynamically add secrets to pod without restart

### ISSUE THREAD

**Issue by RamIoTMalhotra** [Azure/secrets-store-csi-driver-provider-azure#1204]
**Describe the solution you'd like**

When a CRD is updated with a new secret definition, we would like the secret to be available in the pod without requiring a pod restart. 

**Anything else you would like to add:**

Background:
Currently there is no way for us to get secrets inside a KeyVault into a cluster after a pod starts. We have a customer scenario in an upcoming product launch wherein we deploy an initial bunch of secrets into a cluster using the AKV provider, but the customer is able to add new connections post deployment that will require new secrets inside the cluster. We would like to be able to pull in new secrets into the pods ideally without either updating the CRD or restarting the pods. 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.3.4
- Azure Key Vault provider version: (use the image tag): 1.4.1
- Kubernetes version: (use `kubectl version`): 1.25.9
- Cluster type: (e.g. AKS, aks-engine, etc): minikube and k3s

**Comment by ms-sambell** [comment]
+1 This would be amazing for a lot of customers.

**Comment by RamIoTMalhotra** [comment]
This works! We are able to deploy new secrets without having to restart the pod :) @ms-sambell  fyi!
