### ISSUE TITLE
Verbosity not configurable of the PODS

### ISSUE THREAD

**Issue by MartinKosicky** [Azure/secrets-store-csi-driver-provider-azure#124]
When I watch trace logs of the pods generated by this helm chart, they are too verbose. This can cause high pricing in AKS when using LogAnalytics. Debug verbosity is not required once we figure out problems

**Comment by aramase** [comment]
@MartinKosicky I've opened a PR to inherit the `logLevel.debug` option from the driver dep - #125. After this is merged and a new helm chart release is created, you should be able to enabled debug verbosity only if required.

**Comment by MartinKosicky** [comment]
seems ok
