### ISSUE TITLE
Provider identifies the "offline mode" and informs the driver

### ISSUE THREAD

**Issue by mandreap** [Azure/secrets-store-csi-driver-provider-azure#1240]
**Describe the solution you'd like**
The provider should identify that it can't retrieve secrets from the vault and inform the driver. The driver should mount secrets from the Cached CRDs in this case.
- [ ] Provider identifies the offline mode and informs the driver
- [ ] Driver uses the cache to mount secrets as volumes

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
reopening this as it's relevant issue for provider

**Comment by aramase** [comment]
As there is no plan to implement an offline mode in the CSI driver, this issue is not relevant.

Closing it!
