### ISSUE TITLE
Cluster's using service principal 

### ISSUE THREAD

**Issue by cwash05** [Azure/secrets-store-csi-driver-provider-azure#1254]
I discovered that the KV secrets provider doesn't work on clusters that use a SP.  there's no mention in the docs that the cluster needs to use and MSI, so is this a bug or do the docs need to be updated?

If you do enable it, no azurekeyvaultsecretsprovider MI will be created. 

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc):
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):

**Comment by aramase** [comment]
> I discovered that the KV secrets provider doesn't work on clusters that use a SP. there's no mention in the docs that the cluster needs to use and MSI, so is this a bug or do the docs need to be updated?

AKV provider for Secrets Store CSI Driver doesn't use cluster identity unless configured explicitly. You need to configure the driver-provider with the identity access mode to use for accessing kv and it doesn't have any relation with the underlying cluster using SP/MSI. Supported identity access modes are documented here: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/
