### ISSUE TITLE
"no leaf found" error when mounting a cert

### ISSUE THREAD

**Issue by dgkanatsios** [Azure/secrets-store-csi-driver-provider-azure#1257]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

Tried to use Secrets Store CSI driver for AKS to mount a KeyVault pfx Certificate as secret and it failed.
Logs from the aks-secrets-store-provider-azure Pod:

```
pod="default/fog-59dbb997d5-jv5js"
I0807 09:47:04.588409       1 provider.go:202] "unmarshaled objects yaml array" objectsArray=<
        [ ... other PFX certs that work fine ...
         objectName: "name"
        objectAlias: "alias"
        objectType: secret
]
 > pod="default/fog-59dbb997d5-jv5js"
I0807 09:47:04.588679       1 provider.go:231] "vault url" vaultName="vaultName" vaultURL="https://vaultName.vault.azure.net/" pod="default/fog-59dbb997d5-jv5js"
E0807 09:47:05.093533       1 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:certName, objectVersion:: no leaf found"
```

**What did you expect to happen:**

The cert to be mounted and .crt/.key files to be created. Other PFX certs in the same configuration are loading fine so we assume that this is something in the cert itself. FWIW, pulling the cert via `objectType: cert` works great. However, we need the private key as well.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

User Assigned MSI.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.3.4
- Azure Key Vault provider version: (use the image tag): 1.4.1
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.25.5
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): AKS Managed add-on

**Comment by aramase** [comment]
@dgkanatsios there was a similar issue before: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1051. Maybe this is helpful.

**Comment by dgkanatsios** [comment]
thanks @aramase for the response! Unfortunately, this doesn't seem to be the case, just did a `certutil -v` dump on the cert and I discovered that:

```
certificate 0

authority
subject: A


certificate 1

authority: A
subject: B


certificate 2

authority: B
subject: C


certificate 3

authority: C
```

which seems legitimate.

**Comment by dgkanatsios** [comment]
So, after some digging, we discovered that the pfx certificate contained "bag attributes". Converting it to PEM, manually removing the bag attributes and re-uploading to KeyVault made it work. @aramase have you heard of  this? Do you think it would be doable to update the Go code to ignore these attributes?
