### ISSUE TITLE
nodePublishSecretRef & namespace

### ISSUE THREAD

**Issue by Mimetis** [Azure/secrets-store-csi-driver-provider-azure#127]
**What steps did you take and what happened:**

I have a deployment in namespace `api-dev` using the CSI driver to get some secrets.   

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api-dev
spec:
   ...
```
The K8S secret containing my clientid / clientserver are stored in the `default` namespace.

``` bash
k get secret -n default
NAME                                                                TYPE                                  DATA   AGE
secrets-store-creds                                                 Opaque                                2      108m
secrets-store-csi-driver-token-sc6cs                                kubernetes.io/service-account-token   3      81m
```
My deployment (one pod / one service) are both deployed in the `api-dev` namespace:

``` bash
$ k get po -n api-dev
NAME                   READY   STATUS              RESTARTS   AGE
test-5856748977-x6gfr   0/1     ContainerCreating   0          7m19s
```

My deployment yaml volume mount is declared like this:

``` yaml
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname" 
            nodePublishSecretRef:
              name: secrets-store-creds 
              namespace: default

```

As you can see "I try" to get the secret from the `default` namespace, but when applying I have this issue:

``` bash
k apply -f test.yaml
error: error validating "test.yaml": error validating data: ValidationError(Deployment.spec.template.spec.volumes[0].csi.nodePublishSecretRef): 
unknown field "namespace" in io.k8s.api.core.v1.LocalObjectReference; 
if you choose to ignore these errors, turn validation off with --validate=false
```
Once removed (removing `namespace: default` from the deployment yaml file), everything is deployed correctly, but the pod failed to attach the mount volume

``` bash
k describe po test-5856748977-x6gfr -n api-dev

Events:
  Type     Reason       Age               From                                      Message
  ----     ------       ----              ----                                      -------
  Normal   Scheduled    <unknown>         default-scheduler                         Successfully assigned api-dev/poi-5856748977-x6gfr to aks-default-35064155-vmss000000
  Warning  FailedMount  4s (x7 over 36s)  kubelet, aks-default-35064155-vmss000000  MountVolume.
SetUp failed for volume "secrets-store-inline" : fetching NodePublishSecretRef api-dev/secrets-store-creds failed: kubernetes.io/csi: 
failed to find the secret secrets-store-creds in the namespace api-dev with error: secrets "secrets-store-creds" not found
```

**What did you expect to happen:**

Being able to use a the kubernetes secret used by CSI (`secrets-store-creds`) stored in one namespace from any other namespace

By the way, you have a sample using the `namespace` property inside the  `NodePublishSecretRef` property:

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/b8fe3e20993ee831b65718e8ec2927a64a8fe831/examples/pv-secrets-store-csi.yaml#L35

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Using helm to install the last version, I guess

``` bash
helm list
NAME                                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART
                        APP VERSION
csi-secrets-store-provider-azure-1592311739     default         1               2020-06-16 14:49:11.1647625 +0200 CEST  deployed        csi-secrets-store-provider-azure-0.0.7       0.0.6
```

- Kubernetes version: (use `kubectl version`): 1.18.2
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@Mimetis This is a limitation imposed by kubernetes. In case of CSI Volumes, the `nodePublishSecretRef` is a [LocalObjectReference](https://pkg.go.dev/k8s.io/api/core/v1?tab=doc#LocalObjectReference) which only accepts the name of the secret. The namespace is always defaulted to the pod namepace for the secret - [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L167-L170). However in case of `PersistentVolume` the `nodePublishSecretRef` is a [secretRef](https://pkg.go.dev/k8s.io/api/core/v1?tab=doc#SecretReference) which accepts both name and namespace. 

You would need the secret to be in the same namespace as the application pod which in this case is `api-dev`.

**Comment by Mimetis** [comment]
@aramase Thanks for your quick answer.

Indeed it's working correctly if the secret is stored in the right namespace.

Thanks for all

**Comment by MarekLani** [comment]
@aramase @Mimetis sorry for opening the closed issue and asking bit unrelated question, but what does actually nodePublishSecretRef do? I can't find any piece of documentation on it and this issue comes up as number one results of web search.

**Comment by jobinjosem** [comment]
@MarekLani Had the same question. Found the answer here.
https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/service-principal-mode/
It is the name of the Kubernetes secret that contains the service principal credentials to access keyvault. Only required when using service principal mode.
