### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by DrEight** [Azure/secrets-store-csi-driver-provider-azure#1287]
I'm trying to install the CSI driver following this doc: https://learn.microsoft.com/en-us/azure/aks/hybrid/secrets-store-csi-driver
When I run the helm command reported in the doc I get this error, but I can't understand what is the problem:

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "secretproviderclasses-admin-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "csi": current value is "csi-secrets-store"

Any ideas ?

**Comment by aramase** [comment]
The error means you have already have a helm installation of the driver in the cluster. You can check that with `helm ls -A` command. 

Only single instance of driver is required in the cluster. So either delete the existing helm installation and install again or if the old installation is sufficient, you can use that.

**Comment by DrEight** [comment]
Thank you, you right. I tried to execute the helm command many times because the Key vault provider seems not successfully installed and I thought the helm script failed.
If I run the command: kubectl get pods -l app=csi-secrets-store-provider-azure -n kube-system
I get the message: No resources found in kube-system namespace.

And I don't really know what to do. Any suggestions ?
