### ISSUE TITLE
Update secrets without deleting/creating pods

### ISSUE THREAD

**Issue by stan-solovyov** [Azure/secrets-store-csi-driver-provider-azure#129]
Hi,

Is it possible to keep the values from Azure Key Vault in sync with the mounted ones without the need of deleting/recreating pods.
Haven't found any info on the current behavior.
I assume that after updating/adding secrets for example into the Key Vault, the changes are not seen in the pods.
In order to see them we need to update SecretProviderClass  and delete/recreate the pods.

Is that correct?

**Comment by aramase** [comment]
@stan-solovyov That's correct. Currently there is no support for automatically reloading the secrets/keys based on updates in Key Vault. This is the issue that's being used to track that enhancement - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/125

**Comment by stan-solovyov** [comment]
Got it. Thanks for clarification!
