### ISSUE TITLE
Unable to mount volumes for pod - timeout expired waiting for volumes to attach or mount

### ISSUE THREAD

**Issue by adamcarter81** [Azure/secrets-store-csi-driver-provider-azure#130]
**What steps did you take and what happened:**
Pod fails to mount volume, stuck in Init phase.
Event from describing the pod:
Events:
  Type     Reason       Age                  From                                    Message
  ----     ------       ----                 ----                                    -------
  Warning  FailedMount  38s (x76 over 170m)  kubelet, aks-linux-35064155-vmss000000  Unable to mount volumes for pod "<pod name>": timeout expired waiting for volumes to attach or mount for pod . list of unmounted volumes=[secrets-store-inline]. list of unattached volumes=[secrets-store-inline default-token-bbsn4 istio-envoy istio-data istio-podinfo istio-token istiod-ca-cert]

**What did you expect to happen:**
The volume would mount and the pod would start successfully

**Anything else you would like to add:**
I installed the CSI driver via helm from the instructions here: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md

I followed the instructions here: https://github.com/kubernetes-sigs/secrets-store-csi-driver#usage

I am deploying the nginx sample application to a new namespace.
The CSI driver is installed in the default namespace
 
I am a bit stuck as to what to look for next for troubleshooting. The NMI & MIC logs don't show anything untoward.  What is happening during the timeout?

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: 1.6.2 
- Azure Key Vault provider version: 0.0.6:
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster type: AKS

**Comment by aramase** [comment]
@adamcarter81 

1. Can you share the `SecretProviderClass` file you're using for the pod?
2. The logs from the driver pod on the same node should provide error logs as to why the mount is unsuccessful. 
3. Can you also provide the output for `kubectl get nodes -o wide`

**Comment by adamcarter81** [comment]
1 - SecretProviderClass:
`apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "true"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: ""  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "kv-aks-lab"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DB-PW
          objectAlias: dbpw_1     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: "rg-aks-lab"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "xxx"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "xxx"                 # the tenant ID of the KeyVault`

2 - logs from driver pod on the same node:
`PS C:\repos\aks-lab-001> kubectl logs csi-secrets-store-provider-azure-1592501512-secrets-store-jjzsv node-driver-registrar
I0618 17:31:59.378854       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0618 17:31:59.378897       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0618 17:31:59.378907       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0618 17:32:02.597810       1 main.go:127] Calling CSI driver to discover driver name
I0618 17:32:02.597840       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0618 17:32:02.597846       1 connection.go:181] GRPC request: {}
I0618 17:32:02.599298       1 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"0.0.11"}
I0618 17:32:02.600128       1 connection.go:184] GRPC error: <nil>
I0618 17:32:02.600135       1 main.go:137] CSI driver name: "secrets-store.csi.k8s.io"
I0618 17:32:02.600184       1 node_register.go:58] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0618 17:32:02.600275       1 node_register.go:67] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0618 17:32:02.643491       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0618 17:32:02.691159       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}`

3
`PS C:\repos\aks-lab-001> kubectl get nodes -o wide
NAME                            STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-linux-35064155-vmss000000   Ready    agent   113d   v1.14.8   15.0.0.4      <none>        Ubuntu 16.04.6 LTS   4.15.0-1066-azure   docker://3.0.8
aks-linux-35064155-vmss000001   Ready    agent   113d   v1.14.8   15.0.0.35     <none>        Ubuntu 16.04.6 LTS   4.15.0-1077-azure   docker://3.0.8`

**Comment by aramase** [comment]
@adamcarter81 This solution is only supported for v1.16.0+ (https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider)

```
Recommended Kubernetes version:

For Linux - v1.16.0+
For Windows - v1.18.0+
```

The agent nodes are running K8s version `v1.14.8`. Please try it out with a 1.16+ K8s cluster.

**Comment by adamcarter81** [comment]
Ahh well spotted - the nodes need to be upgraded too - I'll get that done and report back
Thanks

**Comment by adamcarter81** [comment]
Updated the nodes - all working now
