### ISSUE TITLE
kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by dariuszbz** [Azure/secrets-store-csi-driver-provider-azure#139]
**What steps did you take and what happened:**

**the following steps:**
kubectl config set-context --current --namespace=dev2
helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver

kubectl apply -f https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer-windows.yaml --namespace dev2

kubectl apply -f .\1-CustomResourceForDriver.yaml --namespace dev2
kubectl apply -f .\2-podInlineSecretesVolume.yaml --namespace dev2

**Yaml files content:
\1-CustomResourceForDriver.yaml**
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: username                           # data field to populate
      objectName: secret1Name                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: foosecret                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: "97d652e8-9dfa-452c-9201-187ff6010349"  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "xxxxxxx"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: secret1Name
          objectAlias: ""    # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectAlias: ""
          objectType: secret
          objectVersion: ""
    resourceGroup: "xxxxxxx"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "xxxxxxx"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "xxxxxxx"                 # the tenant ID of the KeyVault

**\2-podInlineSecretesVolume.yaml**
kind: Pod
apiVersion: v1
metadata:
  name: windows-secrets-store-inline-pod
  labels:
    aadpodidbinding: "demo"
spec:
  containers:
    - name: iis
      image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: foosecret
              key: username
      volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"

**Now:
Pod wont start:**

**kubectl describe pod**

  Normal   Scheduled    8m56s                 default-scheduler      Successfully assigned dev2/windows-secrets-store-inline-pod to akswin000000
  Warning  FailedMount  42s (x12 over 8m56s)  kubelet, akswin000000  MountVolume.SetUp failed for volume "secrets-store01-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
  Warning  FailedMount  9s (x4 over 6m53s)    kubelet, akswin000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store01-inline], unattached volumes=[secrets-store01-inline default-token-dcj24]: timed out waiting for the condition

 **kubectl get csidrivers**

NAME                       CREATED AT
secrets-store.csi.k8s.io   2020-06-29T13:49:22Z

**What did you expect to happen:**
I able to assign the keyvault secret to K8s secret value and expose to the pod environment variable

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): using latest published on today.
- Azure Key Vault provider version: (use the image tag): using latest published on today.
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):

**kubectl version**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**kubectl get nodes -o wide**

NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-25525932-vmss000000   Ready    agent   70m   v1.16.9   10.240.0.4    <none>        Ubuntu 16.04.6 LTS               4.15.0-1089-azure   docker://3.0.10+azure
aks-agentpool-25525932-vmss000001   Ready    agent   70m   v1.16.9   10.240.0.35   <none>        Ubuntu 16.04.6 LTS               4.15.0-1089-azure   docker://3.0.10+azure
akswin000000                        Ready    agent   66m   v1.16.9   10.240.0.66   <none>        Windows Server 2019 Datacenter   10.0.17763.1217     docker://19.3.5

- Cluster type: (e.g. AKS, aks-engine, etc):

AKS,  1.16.9

**Comment by aramase** [comment]
@dariuszbz The Secrets Store CSI Driver and Azure Key Vault Provider is supported on windows 1.18+ (https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider) -

```
For Linux - v1.16.0+
For Windows - v1.18.0+
```

Please try it out with the 1.18+ for windows and let us know if you run into any issues.

**Comment by dariuszbz** [comment]
sorrrry :)
