### ISSUE TITLE
Question: How does it exactly work with Pod identity

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/secrets-store-csi-driver-provider-azure#140]
I was wondering, if deploy the Azure Key Vault Provider for Secrets Store CSI Driver in combination with Pod Identity, Igive the MI the correct role assignments and permissions on the KeyVault then I use the MI id in the AzureIdentity Resource and in the SecretProviderClass. 
What if someone fetches the MI id and knows the keyvault name etc, can they not abuse this by using this id on their own cluster with their own AzureIdentity resource and SecretProviderClass to fetch secrets from that specific KeyVault?

**Comment by aramase** [comment]
Closing this issue as the conversation is on slack - https://kubernetes.slack.com/archives/C013PUP2WRK/p1593532429075900. Please feel free to reopen if you have any more questions.
