### ISSUE TITLE
[Question] Understanding how many calls are made to KeyVault?

### ISSUE THREAD

**Issue by kchilka-msft** [Azure/secrets-store-csi-driver-provider-azure#1416]
Hello! I am trying to understand how often calls are made to KeyVault (sorry for opening a separate issue, couldn't re-open the last one I created)

If we take the [load test example](https://secrets-store-csi-driver.sigs.k8s.io/load-tests.html), there are 10000 pods with 2 secrets and as per the comment in https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/722#issuecomment-977058462, the check is made linearly:

> We create SecretProviderClassPodStatuses (SPCPS) resource per Pod. This has information of all secrets being used in the Pod. During rotation, we list all SPCPS and linearly checks for newer version of secret.

And since the Rotation Poll Interval was set to 2m in load test example, does that mean the number of calls made to KeyVault will be:
10000 pods with 2 secrets = 10000 * 2 = 20000?

Can you please help explain how this works? 🙂

Thanks in advance.

**Comment by kchilka-msft** [comment]
hey @aramase - wanted to follow up re the above question.

**Comment by aramase** [comment]
@kchilka-msft It's a `GET` call to Key vault per secret per pod. So, in the load test scenario, it is 20k calls to KV as it's the same 2 secret per pod and there are 10k pods. 

In case of rotation, the list of all existing pods is generated and the contents in the mount are rotated linearly. A workqueue is created in the driver, all 10k pods added to queue and then the queue is processed. The AKV rate limit is 4000 GET/10s (xref: https://learn.microsoft.com/en-us/azure/key-vault/general/service-limits#secrets-managed-storage-account-keys-and-vault-transactions). As we're not making all 20k calls at once, the rate limit is not hit with the load tests. Having said this , if there is a burst of pods all requesting the secrets at the same time, the rate limit with be hit.

**Comment by kchilka-msft** [comment]
@aramase thanks for the explanation! 

So in every rotation, the number of calls to AKV will be (_number of pods * number of secrets_)? But in a linear fashion so AKV throttling limit isnt breached? 

Also, is there any explicit check you have that ensures calls to AKV are 4000 GET/10s?

**Comment by aramase** [comment]
> So in every rotation, the number of calls to AKV will be (number of pods * number of secrets)? But in a linear fashion so AKV throttling limit isnt breached?

Yes!

> Also, is there any explicit check you have that ensures calls to AKV are 4000 GET/10s?

There is no explicit check. The retries are in the SDK and in case of 429 error, the sdk returns error without retry.
