### ISSUE TITLE
Allow defining a custom azure environment

### ISSUE THREAD

**Issue by pwiens** [Azure/secrets-store-csi-driver-provider-azure#144]
**Describe the solution you'd like**
We need the ability to specify custom azure environment settings. There are certain scenarios such as Azure Stack that use custom endpoints. This should be possible to add via parameters. The azure go sdk provides a setEnvironment function that we can use.

**Environment:**

- Kubernetes version: 1.16
- Cluster type: AKS

**Comment by DavidParks8** [comment]
This should already be supported, though undocumented. Try using `AzureStackCloud` as the environment name. Doing so should cause it to pick up the AzureStackCloud.json file that is available on kubernetes in a custom cloud.

**Comment by pwiens** [comment]
@DavidParks8 I know this functionality exists in the azure go sdk but I'm not sure how it would work with this this csi driver. Where would it look for the file? On the host? If so where?

**Comment by aramase** [comment]
@pwiens This would require a new field in the parameters

```yaml
  parameters:
    cloudName: "AzureStackCloud"
    cloudEnvPath: "/etc/kubernetes/<path to custom env json>
```

If `cloudEnvPath` is defined, then provider can set the [AZURE_ENVIRONMENT_FILEPATH](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L28) env var. The sdk should then be able to [read](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L224-L226) from the file which is already on host.
