### ISSUE TITLE
Add support for object level RBAC 

### ISSUE THREAD

**Issue by ritazh** [Azure/secrets-store-csi-driver-provider-azure#145]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently the key vault RBAC can be set for all secrets, all certs, or all keys. Would be great to add support to restrict access at each object level.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by adn-K987** [comment]
Are there any updates on this?

We have a central key vault managing multiple certificates of different applications, some applications share certain certificates while others not. From security point of view it is concerning that all umis have vault level access.

**Comment by aramase** [comment]
> Are there any updates on this?
> 
> We have a central key vault managing multiple certificates of different applications, some applications share certain certificates while others not. From security point of view it is concerning that all umis have vault level access.

@adn-K987 There are no changes required in this provider to support this. You can refer to https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli to learn how to grant the identity access to key vault. The only permission the identity configured in `SecretProviderClass` requires is `GET` on the objects defined.

**Comment by adn-K987** [comment]
@aramase I was seeking for an option to define azure rbac on individual objects (eg. secret-1234, certificate-XYZ, ...) in the key vault. It seems that I might misunderstand the term "object" in the title of the issue.
