### ISSUE TITLE
Azure CSI Provider disturbs autoscaler associated with KEDA

### ISSUE THREAD

**Issue by NileshGule** [Azure/secrets-store-csi-driver-provider-azure#149]
**What steps did you take and what happened:**
I have an application which uses Kubernetes-based Event Driven Autoscaling KEDA to autoscale pods. This autoscaler works with RabbitMQ cluster as event provider. When I am not using the Azure Provider for secret store CSI driver, the autoscaler is able to scale down RabbitMQ consumer pods to zero. If I pump in more messages onto the queue, the autoscaler starts to scale up the consumer pods again.

The image below shows the pods getting terminated when there are no messages to be processed.
<img width="1917" alt="KEDA terminated pods" src="https://user-images.githubusercontent.com/1298374/86613296-f78e4900-bfe3-11ea-9684-8ea8099bf547.PNG">

In the below screenshot we see the scale up happening due to adding of new messages onto RabbitMQ
<img width="1916" alt="KEDA autoscaling" src="https://user-images.githubusercontent.com/1298374/86613288-f3622b80-bfe3-11ea-8d8f-94ed1b73cfc8.PNG">

However, when using the Azure provider for Secret Store CSI driver, the auto scaler does not work after the number of consumers have scaled down to zero. The scale up does not happen when new messages are added to the RabbitMQ queue. You can refer to the YouTube video where I faced this issue on multiple occasions https://youtu.be/MHm4IVGVO1w

**What did you expect to happen:**
KEDA autoscaler should work when the secrets are pulled from AKV using Azure provider for Secret Store CSI driver. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): installed using helm chart with defualt options
- Azure Key Vault provider version: (use the image tag): installed using helm chart with defualt options
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.18.5
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@NileshGule I'm not sure how the CSI driver here interferes with the autoscaler functionality. The driver is invoked by kubelet only after the pod is scheduled on the node and the volume needs to be mounted. The `consumer` pod here is using the volume with CSI driver, but as long as the pod has not been created/scheduled the CSI driver doesn't really play a role yet.

**Comment by NileshGule** [comment]
@aramase The only change I have between the working code and the one with error is the AKV Provider for Secrets Store CSI driver.

**Comment by aramase** [comment]
@NileshGule Do you see any error in the autoscaler logs trying to scale up the pod? The CSI driver is only invoked after pod is scheduled, so if there is any error in autoscaler or the replica set failing to scale because of CSI volume mount, then it'll be a good starting point.

**Comment by NileshGule** [comment]
@aramase I didn't see any error. The KEDA autoscaler is using TriggerAuthentication kind of object. This is also created as a secret in the Kubernetes cluster. I am not sure why the first time auto scalar works but when scaled down to zero due to no workload, it does not scale back up when the load is added again.

**Comment by aramase** [comment]
@NileshGule Are you by any chance using the same secret used by KEDA for syncing as K8s secret with the Secrets Store CSI Driver? The K8s secret that the CSI driver creates is deleted when all pods referring the `SecretProviderClass` are deleted.

**Comment by NileshGule** [comment]
@aramase The secret names are different for the KEDA and the CSI driver.

**Comment by aramase** [comment]
Thanks for confirming @NileshGule! Are you able to confirm after removing the csi provider, KEDA is scaling fine again in the same cluster? 

Are you able to consistently reproduce this?

**Comment by NileshGule** [comment]
hi @aramase 
Yes I can confirm that the same code works perfectly fine without the CSI provider.

You can see from the images below that is is able to auto scale down when there are not enough messages to process and after the workload is added, scales back up without troubles.
<img width="1902" alt="04 -auto scale after second workload" src="https://user-images.githubusercontent.com/1298374/88460478-070bfe00-cecf-11ea-98c3-99ac93d61256.PNG">



<img width="1920" alt="01 - before first workload" src="https://user-images.githubusercontent.com/1298374/88460468-02474a00-cecf-11ea-89ea-10e3f43f12fb.PNG">
<img width="1876" alt="02 - auto scaling after first workload" src="https://user-images.githubusercontent.com/1298374/88460472-04110d80-cecf-11ea-88d0-290b83514b28.PNG">
<img width="1884" alt="03 - auto scaled down after first workload" src="https://user-images.githubusercontent.com/1298374/88460476-05423a80-cecf-11ea-813b-b3f113ef1443.PNG">

**Comment by helayoty** [comment]
Hi @NileshGule, I was able to reproduce the issue. 

This happens as when we start applying autoscale, all consumer pods got deleted and therefore all secrets related to these pods including `akvsecrets`. 

The expected scenario for secret-store-sci is the pod will be created first and then check for secrets but in KEDA, they check first to resolve all [DeploymentEnv](https://github.com/kedacore/keda/blob/414b302bc59c5954b0957eeb2074c1871b42d241/pkg/handler/scale_handler.go#L210) before go ahead and create the pod. This creates a deadlock situation.

**Comment by NileshGule** [comment]
hi @helayoty 
Kubernetes secrets are shared across pods. It looks like a bad design decision to me to delete the secrets which are not created as part of the secret-store-csi. 
If for security reasons, you are deleting the `akvsecrets`, I suggest to delete only the secret which is linked to secret-store-csi driver and not all other secrets.

**Comment by aramase** [comment]
@NileshGule The CSI driver doesn't delete Kubernetes secrets that were not created by the driver itself. When the secret is created based on `secretObjects` in `SecretProviderClass` by the CSI driver, the pods that the secret were created for are added as owners to the secret. When all pods that use the secret get deleted, the secret is garbage collected. If `akvsecrets` is created by the CSI driver, then the lifetime of the secret is based on the lifetime of the pods using it. Also, the secret is first created when at least *a* pod referencing the `SecretProviderClass` is created. This is done because the primary function of the driver is to mount the contents to the pod and sync K8s secret is an add-on feature which uses the mounted content and replicates as Kubernetes secrets. Hope that clarifies it?

**Comment by NileshGule** [comment]
Thanks for the clarification @aramase.

**Comment by aramase** [comment]
Closing this issue based on the comments above. Please feel free to reopen if you have any other issues or concerns.

**Comment by Hipster74** [comment]
Ok, many hours troubleshooting later I found this issue. 

It seems to still be true that if you like to use KEDA and scale down to zero in AKS you can't use the KeyVault CSI Provider.

Just like @NileshGule I have found out that the pods simply won't start because mounting the secrets from KeyVault to filesystem fails during boot.

Would it be possible to add functionality for this to work in future releases, quit annoying to be forced to have a pod running 99% idle just to keep the KeyVault CSI Provider working?

Maybe something to add to the documentation/troubleshooting guide in the meantime?

Other than that, this is a really useful tool that works great for me so far.

**Comment by aramase** [comment]
Thank you for the feedback! We'll add this to our troubleshooting guide. 

Tying the lifetime of the kubernetes secret created to the lifetime of the pods using it keeps it secure and prevents secrets from existing in the cluster longer than they're required. The actual data in kubernetes secret is a mirror of the mounted content and in the absence of any pod using the secret there is no data to mirror.
