### ISSUE TITLE
Create a secret containing CA certificate along with the Server Certificate

### ISSUE THREAD

**Issue by lavanyamylsamy** [Azure/secrets-store-csi-driver-provider-azure#159]
How to create a secret containing CA certificate along with the Server Certificate, that can be used for both TLS and Client Authentication. I tried the below configuration, but it doesn't work

  secretObjects:
  - secretName: tls-cert # for k8s
    type: kubernetes.io/tls
    data:
    - objectName: importcert 
      key: tls.key
    - objectName: importcert
      key: tls.crt
    - objectName: sample
      key: ca.crt

Any ideas on how to get this working?

**Comment by aramase** [comment]
`kubernetes.io/tls` supports only `tls.crt` and `tls.key` - https://github.com/kubernetes/api/blob/v0.18.6/core/v1/types.go#L5580-L5588

Setting the `objectType: secret` for `importcert` as mentioned [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md) will fetch the entire chain of certs and the private key. The chain typically contains the root, intermediate and server certificates.

Here is a link to the doc on how to use the driver and Key Vault provider with ingress controller - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls

**Comment by aramase** [comment]
Closing this issue. Please feel free to reopen if you're having issues after trying out the steps in the docs.
