### ISSUE TITLE
Issue with auto recreation of new pod after if deployment is not updated and has only 1 replica : ContainerConfigError

### ISSUE THREAD

**Issue by krshbt** [Azure/secrets-store-csi-driver-provider-azure#160]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- I have a AKS cluster and I was trying to get the secrets with Azure Key vault.
- My Deployment has 1 replica and I am mounting the csi driver volume. 
- I am using the approach to Sync Key vault with the Kubernetes Secret and then using that secret to pass on to the environment variable of the pod.
- If I delete the pod or run kubectl rollout restart deployment command the existing container gets deleted and the new one doesn't get created and throws a ContainerConfigError
- If I check the logs, it says the secret [which gets created by SecretProviderClass] not found.
- If I delete and recreate or make changes to deployment and apply it again the pod gets created fine.
- But again If I delete the pod the existing container gets deleted and the new one doesn't get created and throws a ContainerConfigError
- The above behavior doesn't seem to happen if I have more than 1 replicas in my deployment.

**What did you expect to happen:**
The Key vault and secret sync should also happen for 1 replica or the single Pod in the deployment.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): Not sure installed using helm
- Azure Key Vault provider version: (use the image tag): 0.0.7
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.16.10
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
Thank you for opening the issue 👍 

I was able to reproduce this after some fuzzy tests of deleting and recreating the pods. We have changed the way secrets are created and reconciled with this https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/224. We plan to cut a release tomorrow. I'll post here when the release is available and then you can try out the same tests with the new driver.

**Comment by aramase** [comment]
Closing this issue with [v0.0.12](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.12) for driver which uses a separate controller for reconciling/creation of secrets. Please feel free to re-open if you're still seeing issues after trying out the new release.
