### ISSUE TITLE
Clarification needed around "objectType"

### ISSUE THREAD

**Issue by manojampalam** [Azure/secrets-store-csi-driver-provider-azure#161]
[README](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/README.md) says
``` 
objectType: secret        # object types: secret, key or cert
```
What does it mean to have a "key" objectType. Azure Key Vault does not let importing private keys. So, is it just the public key that would be retrieved and mounted as a secret?

**Comment by aramase** [comment]
`objectType: secret` fetches the private key along with chain of certs. 

`objectType: key` fetches only the public key

Ref doc: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md
