### ISSUE TITLE
Clarify that syncing from a vault to a Kubernetes secret only works with secrets created by the SecretProviderClass instance

### ISSUE THREAD

**Issue by ejschoen** [Azure/secrets-store-csi-driver-provider-azure#1620]
If secretObjects.secretName refers to a pre-existing secret, a pod configuration error is flagged because the secret is missing the key requested in the pod's env.<<secret>>.valueFrom.secretRef.key field.  If the secret exists and the requested key exists, there is no error, but the vault value is not synced to the secret value.  

It might help if the documentation for syncing to Kubernetes secrets explicitly states that the SPC must create the secret.

**Comment by MostefaKamalLala** [comment]
I think this is an interesting feature request, To avoid having multiple secrets, it woul be interesting to update an existing k8s secret object by appending a non existant key.
