### ISSUE TITLE
Getting v1beta1.metrics.k8s.io False (MissingEndpoints) after installing secrets-store-csi-driver-provider-azure

### ISSUE THREAD

**Issue by BenyErnest** [Azure/secrets-store-csi-driver-provider-azure#167]
**What steps did you take and what happened:**
After installing secrets-store-csi-driver-provider-azure, https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md, I get v1beta1.metrics.k8s.io kube-system/metrics-server False (MissingEndpoints) using kubectl get apiservices

**What did you expect to happen:**
Not to get v1beta1.metrics.k8s.io in False (MissingEndpoints) availability state

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@BenyErnest I don't believe that's an issue with the `secret-store-csi-driver-provider-azure`. Please take a look at similar issue in the metrics server repo - https://github.com/kubernetes-sigs/metrics-server/issues/525.

**Comment by BenyErnest** [comment]
@aramase It seems to have been a problem with resources, I only had one node in the cluster with only 4GB memory and 2 vCPU. Thanks.

**Comment by aramase** [comment]
Thanks for the confirmation. Closing this issue now. Please feel free to re-open if you have any questions.
