### ISSUE TITLE
Application Helm Charts that uses csi-secrets-store-provider-azure are broken after PR #164

### ISSUE THREAD

**Issue by prabdeb** [Azure/secrets-store-csi-driver-provider-azure#169]
**What steps did you take and what happened:**
Application Helm Charts that uses `csi-secrets-store-provider-azure` are broken after PR #164 . We are getting the following errors -

1. Error event from applications -
```bash
Events:
  Type     Reason       Age                  From                                           Message
  ----     ------       ----                 ----                                           -------
  Normal   Scheduled    2m35s                default-scheduler                              Successfully assigned default/application-pod-56xxxx8b-6dxxx to xxxxx
  Warning  FailedMount  32s                  kubelet, xxx  Unable to attach or mount volumes: unmounted volumes=[azure-key-vault], unattached volumes=[azure-key-vault default-token-xxxxx]: timed out waiting for the condition
  Warning  FailedMount  26s (x9 over 2m34s)  kubelet ,xxx  MountVolume.SetUp failed for volume "azure-key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = secretProviderClass is not set
```

2. Error logs from `csi-secrets-store-provider-azure-xxxxx-secrets-store-xxxx` container `secrets-store` -
```bash
time="2020-07-23T05:52:16Z" level=debug msg="GRPC call: /csi.v1.Node/NodePublishVolume"
time="2020-07-23T05:52:16Z" level=debug msg="GRPC request: {VolumeId:csi-xxxx PublishContext:map[] StagingTargetPath: TargetPath:/var/lib/kubelet/pods/xxxxx/volumes/kubernetes.io~csi/azure-key-vault/mount VolumeCapability:mount:<> access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:true Secrets:map[clientid:[REDACTED] clientsecret:[REDACTED]] VolumeContext:map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:application-pod-xxxxx-xxxx csi.storage.k8s.io/pod.namespace:xxxx csi.storage.k8s.io/pod.uid:xxxxx csi.storage.k8s.io/serviceAccount.name:default keyvaultName:xxxxx objects:array:\n  - |\n    objectName: secret-file-1\n    objectType: secret\n  - |\n    objectName: secret-file-2\n    objectType: secret\n providerName:azure tenantId:xxxxx usePodIdentity:false] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}"
time="2020-07-23T05:52:16Z" level=debug msg="target /var/lib/kubelet/pods/xxxxx/volumes/kubernetes.io~csi/azure-key-vault/mount, volumeId csi-xxxxxx, attributes map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:application-pod-xxxxx-xxx csi.storage.k8s.io/pod.namespace:xxxx csi.storage.k8s.io/pod.uid:xxxx csi.storage.k8s.io/serviceAccount.name:xxxx keyvaultName:xxxx objects:array:\n  - |\n    objectName: secret3\n    objectType: secret\n  - |\n    objectName: secret4\n    objectType: secret\n providerName:azure tenantId:xxxx usePodIdentity:false], mountflags []"
time="2020-07-23T05:52:16Z" level=error msg="GRPC error: secretProviderClass is not set"
```

**What did you expect to happen:**
Application Helm Charts were working fine before the PR #164 and it's broken after that. However currently the `csi-secrets-store-provider-azure` Helm Chart version [0.0.8](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure-0.0.8.tgz) is working fine.

Expectoration is that Application Helm Charts should work fine with `csi-secrets-store-provider-azure` Helm Chart version 0.0.9 as well.

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: latest
- Azure Key Vault provider version: latest
- Kubernetes version: 1.16+
- Cluster type: AKS

**Comment by prabdeb** [comment]
CC: @anandchugh

**Comment by ritazh** [comment]
@prabdeb Thanks for reporting the issue! 
From this error `secretProviderClass is not set`, I wonder if you are impacted by 
> Defining driver configuration and provider-specific parameters to the CSI driver in pod.Spec[].Volumes has been deprecated. It is now mandatory to use SecretProviderClass custom resource.

From the latest secrets store csi driver [v0.0.12 release](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.12)

Can you see if this is the issue? If so, PTAL https://github.com/Azure/secrets-store-csi-driver-provider-azure#create-your-own-secretproviderclass-object to create a `SecretProviderClass` custom resource.

**Comment by prabdeb** [comment]
Thanks @ritazh for your quick reply.

That means all our Application Helm Charts will be broken and it's mandatory to create an extra K8's resource `secretProviderClass` for all of our application Helm Charts!

I am checking if there is any backward compatibility for the application Helm Charts that does not uses extra K8's resource `secretProviderClass` (it was not mandatory). Since this deprecation happens all of a sudden and as a consequences there is a huge impact for us to migrate all of our application Helm Charts to create this additional K8's resource.

**Comment by ritazh** [comment]
@prabdeb Thanks for the feedback and we will definitely make deprecation messages more obvious in the future. did you get a chance to test the updates?

**Comment by prabdeb** [comment]
@ritazh We have decided not to upgrade to 0.0.9 right now, as we have to invest a lot for modifying/testing all the Helm Charts. We have hard-coded the version 0.0.8.

**Comment by aramase** [comment]
Thanks for the feedback @prabdeb. We'll make sure to add the deprecated notice and warning logs a few releases before the actual deprecation. 

Closing this issue now. Please feel free to reopen if you have any issues while trying out the latest releases.
