### ISSUE TITLE
PR #164 metrics addr is already in use, breaks secrets-store container.

### ISSUE THREAD

**Issue by maperr** [Azure/secrets-store-csi-driver-provider-azure#171]
**What steps did you take and what happened:**
The metrics addr port is already in use and causes the secrets-store pod to fail.

$ kubectl logs csi-secrets-store-provider-azure-secrets-store-csi-driver-rvrmw secrets-store
time="2020-07-23T20:25:15Z" level=fatal msg="failed to start manager, error: error listening on :8080: listen tcp :8080: bind: address already in use"

**Comment by aramase** [comment]
@maperr Looks like the `metrics-addr` port `8080` is in use by another process on the host. You can configure the `metrics-addr` using the flag when installing with helm. 

```
helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set secrets-store-csi-driver.linux.metricsAddr=:8081
```

Doc for Configuration settings - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration

**Comment by maperr** [comment]
Thanks
