### ISSUE TITLE
Sync with K8s secret requires SecretProviderClass in the same namespace as the pod

### ISSUE THREAD

**Issue by kenans** [Azure/secrets-store-csi-driver-provider-azure#177]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Hi, I tried to follow [the ingress tls secret setup doc](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls) to test sync the CSI object from KV with k8s secret. 

However, I found the k8s `secret` can be created only when the `SecretProviderClass` is in the same `namespace` as the `pod` that consumes the CSI object. If the `SecretProviderClass` is in a different `namespace` from the `pod`, checking the `secrets-store` logs, it says, 
```
time="2020-07-29T10:41:55Z" level=error 
msg="failed to get spc kv-csi-provider-class, err: SecretProviderClass.secrets-store.csi.x-k8s.io \"kv-csi-provider-class\" not found" node=aks-agentpool-34916382-vmss000000 secretproviderclasspodstatus=default/nginx-test-684fb86555-tbswb-default-kv-csi-provider-class
```

When I saw the secret sync failure, all the CSI driver and AAD identity related resources (including the `SecretProviderClass`) were under one namespace "security" but the pod that referenced the CSI object was under the "default" namespace. Once I put the `SecretProviderClass` under `default` but kept the rest resources the way they were, the secret sync was successul and the error message disappeared. 

Note I could see the secret wss mounted successfully on to the pod regardless if the `SecretProviderClass` was in the same namespace as the pod. Only sync with k8s secret doesn't work. 

**What did you expect to happen:**
From the Nginx doc, I saw the `SecretProviderClass` and the deployments were under different namespaces (`SecretProviderClass` under default but all the rest under `nginx-test`), so I assumed my senario would also work. Searching the docs, I don't see any restrictions regarding the k8s namespace. If mounting to pod works across namespaces, sync with k8s secret should also work.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
I used user assigned MSI for asscessing KV.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.12
- Azure Key Vault provider version: (use the image tag): 0.0.7
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.16.10
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
Thank you for reporting the issue 👍 

The `SecretProviderClass` is a namespaced resource and needs to be in the same namespace as the pod referencing it. This follows the same RBAC best practice as other namespaced resources - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/60#issuecomment-656312749. The mount should also fail if the `SecretProviderClass` is not in the same namespace as the pod. I'll open a bug to fix the issue. The requirement is added in the release notes - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.12, we'll also make sure to add this to the readme as part of the next release.

**Comment by kenans** [comment]
@aramase Thank you for the quick response!

**Comment by aramase** [comment]
Closing this with https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/264. This will be included in the next release of the driver.
