### ISSUE TITLE
Keep k8s secret around after the referencing pod is deleted

### ISSUE THREAD

**Issue by kenans** [Azure/secrets-store-csi-driver-provider-azure#178]
**Describe the solution you'd like**
Currently when the pod that references the KV object is deleted, the synced k8s secret is also removed. It would be nice if we can provide an option to keep the secret around when the referencing pod is deleted.

**Anything else you would like to add:**
Our working scenario is to use a cronjob to sync all the KV objects with k8s secrets. Other pods then purely depend on the k8s secrets. But I find once the pod of the cronjob is removed, the k8s secret is also deleted.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.12
- Azure Key Vault provider version: (use the image tag): 0.0.7
- Kubernetes version: (use `kubectl version`): v1.16.10
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by ritazh** [comment]
Thanks for opening the issue @kenans Do you mind opening this issue: https://github.com/kubernetes-sigs/secrets-store-csi-driver so we can get more people to vote on this and see if this makes sense as a feature to support in the csi driver.

**Comment by kenans** [comment]
@ritazh Thank you for the quick response. I've opened [a new issue](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/265) under the csi driver repo

**Comment by aramase** [comment]
Thank you for opening the issue @kenans. We can use https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/265 to track this. Closing this issue.
