### ISSUE TITLE
Unable to install HELM Chart in PSP enabled environments

### ISSUE THREAD

**Issue by chakri-nelluri** [Azure/secrets-store-csi-driver-provider-azure#180]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Unable to use CSI driver on PSP enabled clusters, where `hostPath` is disabled in restrictive PSP.

It is failing with error: 

 Warning  FailedCreate  9m39s (x26 over 148m)  daemonset-controller  Error creating: pods "csi-secrets-store-provider-azure-1596210160-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]

**What did you expect to happen:**
Run Keyvault CSI Driver

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Make PSP configurable in values.yaml. Users can specify PSP to use.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
N/A

**Environment:**
AKS

- Secrets Store CSI Driver version: (use the image tag):
NAME                                            NAMESPACE       REVISION        UPDATED                                 STATUS
 CHART                                  APP VERSION
csi-secrets-store-provider-azure-1596210160     default         1               2020-07-31 11:42:41.8503783 -0400 EDT   deployed
 csi-secrets-store-provider-azure-0.0.9 0.0.7

- Azure Key Vault provider version: (use the image tag):

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
NAME                             STATUS   ROLES   AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-worker-11323804-vmss000000   Ready    agent   7d13h   v1.17.7   10.161.116.5    <none>        Ubuntu 16.04.6 LTS   4.15.0-1091-azure   docker://3.0.10+azure
aks-worker-11323804-vmss000001   Ready    agent   7d13h   v1.17.7   10.161.116.30   <none>        Ubuntu 16.04.6 LTS   4.15.0-1091-azure   docker://3.0.10+azure
- Cluster type: (e.g. AKS, aks-engine, etc):
AKS

**Comment by aramase** [comment]
@chakri-nelluri Thank you for opening the issue 👍 

There is no kubernetes primitive for defining the PSP to use. The pods service account needs to be authorized to use a policy that's defined via RBAC. The `secrets-store-csi-driver` and `csi-secrets-store-provider-azure`are bootstrapped with a service account which you can use for authorizing to use with PSP. 

We'll add a sample PSP in our docs that you can refer to. Is the question whether we can include a PSP in helm charts?

**Comment by ekhaydarov** [comment]
So you manually have to add pod security policy and it does not come shipped as a standard option in your helm charts?
