### ISSUE TITLE
New secrets from KeyVault are not immediately available in the `secretObjects`

### ISSUE THREAD

**Issue by connor4312** [Azure/secrets-store-csi-driver-provider-azure#182]
**What steps did you take and what happened:**

I did the following:

1. Updated my SecretProviderClass with new secret `object`s in the `parameters`
1. Referenced those new secrets in the `secretObjects` to sync with k8s secrets, in a secret
1. Among the new `data` in the k8s secret, only secrets I had already pulled from KeyVault were present in the k8s secret within the cluster.

**What did you expect to happen:**

I expected the newly referenced secrets to be available in the object.

**Anything else you would like to add:**

I was able to 'fix' this by deleting the secret and allow it to be recreated. So I think this was probably some timing error where the k8s secret sync happened before the secret was pulled from the keyvault.

**Which access mode did you use to access the Azure Key Vault instance:**

System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1alpha1
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.17.7
- Cluster type: (e.g. AKS, aks-engine, etc): aks

**Comment by aramase** [comment]
@connor4312 Thank you for opening the issue 👍 

The mount and secret creation is only performed during the pod creation. There is no update to the mount/k8s secret when the `SecretProviderClass` is updated. Currently, the pod and secret need to be recycled when the `SecretProviderClass` is updated or the contents in Key Vault are rotated. I've a PR in progress to update the secret contents when the pods are recycled - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/277. With this PR, the secret contents will be updated and this will mean the secret doesn't need to be deleted.

**Comment by connor4312** [comment]
Thanks for the fast response, looks like I had good timing 🙂  Closing as a duplicate
