### ISSUE TITLE
Handling password protected SSL certificates in AKV using CSI

### ISSUE THREAD

**Issue by zicaden** [Azure/secrets-store-csi-driver-provider-azure#185]
Team,

We would like to use this solution to integrate AKS with AKV. Our primary intent is to configure an NGINX service with the SSL certificates stored in AKV.

The SSL cert is stored as a pfx file [public & private key included] which is base64 encoded and is protected by a password. The password is also stored in AKV as a secret. Per company policy - the private key must be protected by a password.

I would like to understand how we can use this solution to configure NGINX with SSL certificate file that is password protected. I looked at the documentation provided but could not find a suitable example. 

Could someone point me to an example of how it is done?

Any help would be greatly appreciated.

Thanks

**Comment by aramase** [comment]
Thank you for opening the issue 👍 

One way I could think of is to configure the `SecretProviderClass` to get the base64 encoded PFX raw data written to the file1.pfx (*This was added recently - [PR](https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/175) and will be in the next release*)  and the password written to a file2. The workload pod can then use the secret to decode the pfx file.  The driver today doesn't take a parameter input for the password, so it decodes to PEM without any password. If the certificate file is password protected, then this decode will error out - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/pkg/azure/provider.go#L594-L598

**Comment by zicaden** [comment]
Hello - Thank you. We also have another org security policy that the private key can never leave the akv. So essentially we cannot "extract" the private key file from the CSI read only mount volume and store it in our pod locally.  An approach like ssl_password_file mentioned here - https://www.nginx.com/blog/secure-distribution-ssl-private-keys-nginx/ would be very beneficial

**Comment by jrudley** [comment]
@aramase Getting the base64 encoded pfx is exactly what I need. Do you have an eta on the next release? Thanks

**Comment by aramase** [comment]
The release `0.0.8` is planned for tomorrow.

**Comment by aramase** [comment]
We are currently unable to get release test signals for windows because of https://github.com/Azure/aks-engine/issues/3700. As a result, the `0.0.8` release has been postponed to Monday tentatively.

**Comment by brianlongmsc** [comment]
Hi all, 

I'm very interested in seeing a working example of retrieving certificates from AKV and having the relevant SecretProviderClass generate the kubernetes.io/tls secret for use in Ingress for TLS.

Tried this earlier but not sure on how to split my AKV cert back into it's 'cert' and 'key' values for the TLS secret i.e.

spec:
  provider: azure
  secretObjects:
    - secretName: dvs-tls-cert
      type: kubernetes.io/tls
      data:
        - objectName: akv-certificate
          key: tls.crt
        - objectName: akv-certificate
          key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "<redacted>"
    objects: |
      array:
        - |
          objectName: akv-certificate
          objectType: cert

Getting Opaque (secret) working is a relatively as there are lots of example from the main README and test folders but can't seem to track a working example of certs with secrets store CSI anywhere?

Regards, Brian.

**Comment by aramase** [comment]
@brianlongmsc We have a sample doc in here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls on how to use the driver for ingress TLS. More info on object type for certificate are documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md

**Comment by aramase** [comment]
> Hello - Thank you. We also have another org security policy that the private key can never leave the akv. So essentially we cannot "extract" the private key file from the CSI read only mount volume and store it in our pod locally. An approach like ssl_password_file mentioned here - https://www.nginx.com/blog/secure-distribution-ssl-private-keys-nginx/ would be very beneficial. We can have the pfx file and the password available in the mount volume from the secret. For every cert / pfx / key we can have a variable to accept the password and point to the mounted password secret against each in the configuration.

@zicaden Based on your last comment this should be possible today by getting the pfx file and secret file, then using `ssl_password_file` directive. Is that right? Is there anything outstanding in this issue?

**Comment by aramase** [comment]
Closing this issue now. Please feel free to re-open if you have any more questions.
