### ISSUE TITLE
Mount Volume setup fail: Failed to execute refresh request / refresh token failure

### ISSUE THREAD

**Issue by zicaden** [Azure/secrets-store-csi-driver-provider-azure#186]
Hello Team,

I followed the steps to setup CSI from this link. https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes

I am using service principal based access. Getting the following error. 

MountVolume.SetUp failed for volume "csi-secrets-store" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret time="2020-08-11T10:54:15Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:tempUser, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://mykv.vault.azure.net/secrets/tempUser/?api-version=2016-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/xxx-xxx-xxx-xx-xxx/oauth2/token?api-version=1.0: dial tcp: i/o timeout'"

**Comment by zicaden** [comment]
Just in case anyone wants to refer to config files - here they are



[mycsi-yaml.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/5057489/mycsi-yaml.txt)
[mysvc-yaml.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/5057490/mysvc-yaml.txt)

**Comment by aramase** [comment]
@zicaden The Azure Keyvault provider for Secrets Store CSI driver runs as a binary on the host. The CSI driver invokes the binary on the host to fetch contents from Keyvault and write the contents to the pod mount. 

> azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://mykv.vault.azure.net/secrets/tempUser/?api-version=2016-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/xxx-xxx-xxx-xx-xxx/oauth2/token?api-version=1.0: dial tcp: i/o timeout'"

This means the connection to `login.microsoftonline.com` is being blocked. Do you have NSG rules that deny outbound traffic from host?

**Comment by zicaden** [comment]
Hello - my bad. NSG rules were the issue. It is resolved now. Thanks for the help
