### ISSUE TITLE
provide official production support within Microsoft

### ISSUE THREAD

**Issue by jrudley** [Azure/secrets-store-csi-driver-provider-azure#188]
The docs state that since this is open source, Microsoft will not provide support. Since Microsoft provides support for other integrations with key vault, such as VM's, Web apps, etc,  AKS should be no different. It is a hard sell to use AKS and Key Vault in an enterprise deployment.

**Comment by ritazh** [comment]
@jrudley Thanks for reaching out! If you need assistance in addition to github issues, you can also join the [#csi-secrets-store](https://kubernetes.slack.com/messages/csi-secrets-store) channel on [Kubernetes Slack](https://kubernetes.slack.com/), where other community members can also help.

**Comment by jrudley** [comment]
Hi @ritazh 
Thanks, but I am a bit more concerned that official Microsoft documents are referencing this driver, but the repo states no official support from Microsoft. Example https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes
If I have a customer who has an issue with the driver and they reach out to CSS, they will deny support. There are no warnings on the documentation page saying that this is not a supported feature within Microsoft. When specific SLA's must be met, running unsupported code could impact that SLA. Why I am curious how this is not integrated into Microsoft's support channel. 

Thanks

**Comment by jrudley** [comment]
MS is updating their docs to state the support issue.
