### ISSUE TITLE
spec.volumes[0]: Required value: must specify a volume type

### ISSUE THREAD

**Issue by snobu** [Azure/secrets-store-csi-driver-provider-azure#19]
```bash
$ kubectl apply -f \
        nginx-pod-secrets-store-inline-volume-secretproviderclass.yaml

The Pod "nginx-keyvault-inline" is invalid:
* spec.volumes[0]: Required value: must specify a volume type
* spec.containers[0].volumeMounts[0].name: Not found: "keyvault"
```

What did i miss? Not sure how to enable feature gates (`--feature-gates=CSIInlineVolume=true`) on the api-server in AKS, how is that handled?

k8s version: `1.15.5` (on AKS)

**Comment by aramase** [comment]
@snobu Currently there is no way to add `--feature-gates` on AKS. This feature gate is enabled by default in 1.16. Would it be possible for you to try out secrets-store-csi-driver with a `1.16` cluster on AKS?

**Comment by aramase** [comment]
@snobu Please try it out on a 1.16 cluster. If you still have issues with 1.16 cluster feel free to reopen the issue.
