### ISSUE TITLE
driver reads secrets from secretproviderclass of wrong namespace

### ISSUE THREAD

**Issue by mo-saeed** [Azure/secrets-store-csi-driver-provider-azure#195]
**What steps did you take and what happened:**
- Create 2 namespaces "development" and "testing"
- Create 2 secret provider classes with the same name (e.g. test-driver) in both namespaces with different list of secrets
- create a deployment in the testing namespace with the secretproviderclass "test-driver", it will read the secretproviderclass from development namespace 

**What did you expect to happen:**
secretproviderclass should be the one where the pod is running even if the secretproviderclass has the same name in different namespace.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
 User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: Latest:
- Azure Key Vault provider version: Latest:
- Kubernetes version: v1.16.10:
- Cluster type: AKS:

**Comment by zicaden** [comment]
Hello - I have a related question. Did you try and install the driver in both the namespaces using helm? 

helm install <prov-name> csi-secrets-store-provider-azure/csi-secrets-store-provider-azure -n development

helm install <prov-name> csi-secrets-store-provider-azure/csi-secrets-store-provider-azure -n testing

What I have observed is that the first one goes through. The second one errors out stating the following: 

Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "secretproviderclasses.secrets-store.csi.x-k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "testing": current value is "development"

How did you achieve this?

**Comment by aramase** [comment]
Issue has been fixed with https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/264. This will be part of driver `v0.0.13` release.

> Hello - I have a related question. Did you try and install the driver in both the namespaces using helm?

@zicaden The driver and providers pods are only one per cluster node. You don't need to deploy it multiple namespaces.
