### ISSUE TITLE
Failed to get key vault token: nmi response failed with status code: 404

### ISSUE THREAD

**Issue by mansing2** [Azure/secrets-store-csi-driver-provider-azure#200]
I'm trying to retrieve secrets and certificates from the Azure key vault, I have been referring to the guide https://github.com/HoussemDellai/aks-keyvault. I have observed that sometimes I see it's working and sometimes doesn't.  The pod status shows creating... and when I do describe pod I see an error 'Failed to get key vault token: nmi response failed with status code: 404'

Provider Class:

`apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{.Values.secretproviderclass}}
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{.Values.keyvault_name}}
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DatabasePassword
          objectAlias: DATABASE_PASSWORD
          objectType: secret
        - |
          objectName: DatabaseLogin
          objectAlias: DATABASE_LOGIN
          objectType: secret
        - |
          objectName: ingresscert
          objectType: secret
    tenantId: {{.Values.tenantid}}`

I'm expecting the application pod can fetch the secrets from the mounted volume.

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity and AKS has been configured with Managed Identity. 

**Environment:**
Kubernetes Version: 1.16.13

- Cluster type: AKS

MIC Log:
``
I0821 12:36:29.547180       1 stats.go:129] *********************
I0821 12:36:29.747628       1 mic.go:1006] processing node aks-agentpool-20474252-vmss, add [1], del [1], update [0]
I0821 12:36:29.782905       1 cloudprovider.go:196] updating user-assigned identities on aks-agentpool-20474252-vmss, assign [1], unassign [0]
E0821 12:36:29.816391       1 mic.go:1077] failed to update user-assigned identities on node aks-agentpool-20474252-vmss (add [1], del [1], update[0]), error: failed to update identities for aks-agentpool-20474252-vmss in MC_aks-cluster_aks-cluster_eastus, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subid>/resourceGroups/MC_aks-cluster_aks-cluster_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-20474252-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
``

Azure Identity and IdentityBinding definition:

```apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{.Values.aks_identity}}
spec:
  type: 0
  resourceID: {{.Values.keyvault_id}}
  clientID: {{.Values.identity_clientid}}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{.Values.aks_identity}}-binding
spec:
  azureIdentity: {{.Values.aks_identity}}
  selector: {{.Values.identity_selector}}```

**Comment by mansing2** [comment]
Latest error from the pod

```
Events:
  Type     Reason       Age    From                                        Message
  ----     ------       ----   ----                                        -------
  Normal   Scheduled    3m18s  default-scheduler                           Successfully assigned default/nginx-secrets-store to aks-agentpool-20474252-vmss000000
  Warning  FailedMount  3m17s  kubelet, aks-agentpool-20474252-vmss000000  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to get secretproviderclass default/secret-provider-kv, error: secretproviderclasses.secrets-store.csi.x-k8s.io "secret-provider-kv" not found
  Warning  FailedMount  97s    kubelet, aks-agentpool-20474252-vmss000000  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret time="2020-08-24T13:58:18Z" level=fatal msg="[error] : failed to get keyvaultClient: failed to get key vault token: nmi response failed with status code: 404"
 for pod: default/nginx-secrets-store
  Warning  FailedMount  75s  kubelet, aks-agentpool-20474252-vmss000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-bg79n]: timed out waiting for the condition
```

**Comment by ritazh** [comment]
> failed to get secretproviderclass default/secret-provider-kv, error: secretproviderclasses.secrets-store.csi.x-k8s.io "secret-provider-kv" not found

How is the `secretproviderclass` resource `default/secret-provider-kv` deployed? Was it deployed in the same namespace as the pod in the `default` namespace?

**Comment by mansing2** [comment]
@ritazh - Sorry for the delay in reply, the issue has been resolved after adding . Answer to your question, secretproviderclass and secrete-provider-kv are created in the default namespaces.

I have a question, as per https://github.com/HoussemDellai/aks-keyvault, _"The Azure Key Vault Provider offers four modes for accessing a Key Vault instance: Service Principal, Pod Identity, VMSS User Assigned Managed Identity and VMSS System Assigned Managed Identity"_ I have AKS cluster with System Assigned Managed Identity, so I was wondering if there is any way to retrieve secrets from the Azure key vault without installing the pod identity. Thank you.

**Comment by aramase** [comment]
@mansing2 PTAL at this section - https://github.com/Azure/secrets-store-csi-driver-provider-azure#provide-identity-to-access-key-vault. We have a doc on how to use system assigned managed identity for accessing Key Vault - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/system-assigned-msi-mode.md. 

The required configuration parameters for each mode is documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure#create-your-own-secretproviderclass-object

**Comment by mansing2** [comment]
@aramase - Sorry for the delay in reply. Many thanks for the information. The issue we were facing has been fixed by adding below. Appreciate your help!

```
linux:
  env:
    - name: KUBERNETES_SERVICE_HOST
      value: <cluster>
```

**Comment by varunjain1995** [comment]
@mansing2 - I am facing similar issue, can you explain where you have added that.


Error Message : failed to mount objects, error: failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 404

**Comment by mansing2** [comment]
@varunjain1995 - Sorry for the delay in response. Answer to your question, you can create another yaml file with the same content above and apply during helm install or update with -f 
```linux:
  env:
    - name: KUBERNETES_SERVICE_HOST
      value: <cluster>
```
Another way is using kubelet 

```kubectl set env deployment<deployment_name> KUBERNETES_SERVICE_HOST=<your AKS host> -n <namespace>```

Let me know if that helps.

**Comment by akshaychopra5207** [comment]
Hi I am facing the same error as below
**SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-secrets-store, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 403, err: <nil>**

DId this last solution works ? if yes then what exactly needs to be done . Can you explain a bit more

**Comment by melkamar** [comment]
@aramase the links in your answer https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/200#issuecomment-683880300 are either 404 or the anchors you reference are no longer there. Could you please update them?

**Comment by aramase** [comment]
@melkamar The documentation for the project is here: https://azure.github.io/secrets-store-csi-driver-provider-azure/
