### ISSUE TITLE
(feat): Sync with kubernetes secrets to multiple namespaces

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/secrets-store-csi-driver-provider-azure#205]
Info:
Would be nice to have option to sync secrets to multiple namespaces.

Use case:
- postgresql password referenced in multiple namespaces

Workarounds:
- https://github.com/emberstack/kubernetes-reflector ( another component that may break.. )
- https://github.com/appscode/kubed ( another component that may break.. )

**Comment by aramase** [comment]
@lukasmrtvy Thank you for opening the issue. Allowing syncing the secret in multiple namespaces could result in privilege escalation. The Secrets Store CSI Driver has RBAC privileges to create/update secrets in any namespace. However it's possible the user only has access to a particular namespace and could request for the sync secrets in namespaces they don't have access to. This is not a desirable behavior. 

Let me know what you think.

**Comment by aramase** [comment]
Closing this issue because supporting this feature could be a privilege escalation. Please feel free to reopen if you have any thoughts.
