### ISSUE TITLE
(feat): provide labels/annotations option to the helm chart

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/secrets-store-csi-driver-provider-azure#206]
Would be nice to provide provide labels/annotations option to the helm chart.

Use case:
- set prometheus annotations ( `prometheus.io/port: "8080"`, `prometheus.io/scrape: "true"` )
- set aad-pod-identity label ( `aadpodidbinding: "select"` )

**Comment by lukasmrtvy** [comment]
oh, nvm, seems that secrets-store-csi-driver-provider-azure does not work like https://github.com/SparebankenVest/azure-key-vault-to-kubernetes ( sync secrets from keyvault to kubernetes secrets ).

Related proposal: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/132#issuecomment-663961316

**Comment by aramase** [comment]
> Related proposal: #132 (comment)

@lukasmrtvy The CSI driver is invoked by kubelet for mounting volume for individual pods.

1. It's not possible to mount the secret for all pods inside `csi-secrets-store-provider-azure`.
2. Mounting all the secrets to a single pod means anyone who has access to the `csi-secrets-store-provider-azure` would be able to view the secrets for every other pod. 
3. The CSI spec is defined for the `volumeMounts` and `volumes` defined for the pod. 
4. With todays approach the users can configure the access method for Key Vault for each individual pod using the `aadpodidbinding` label and `SecretProviderClass` config. This granularity provides the options for users to not rely on a single managed identity/service principal that would require permissions across multiple Key Vault instances. 

Hope this clarifies your question.

> set prometheus annotations ( prometheus.io/port: "8080", prometheus.io/scrape: "true" )

We can add a configuration option for setting annotations. Would you be interested in opening a PR to add this to the helm charts in `manifest_staging/charts/secrets-store-csi-driver`?

**Comment by drwoods** [comment]
Ability to defein our own labels and annotations to add to the pods would be great, as we're using custom labels to track deployer and cost tracking info

Also, being able to override priorityClassName is a must, as using the default of 0 means the pod is getting starved in some of our clusters where we use priorities to ensure some pods (like infrastructure or system critical pods) are not evicted before application/service pods.

**Comment by drwoods** [comment]
PR #263 adds the priorityClassName

**Comment by aramase** [comment]
> Ability to define our own labels and annotations to add to the pods would be great, as we're using custom labels to track deployer and cost tracking info

@drwoods Would you be interested in opening a PR for allowing labels and annotations to be configurable using helm?

**Comment by aramase** [comment]
Closing this with #263 and #392. Feel free to open a new issue for any further enhancement requests.
