### ISSUE TITLE
Question: Does SecretProviderClass belong in an application Helm chart

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#217]
Does the `SecretProviderClass` belong in application Helm Charts or should it be added at the infrastructure side (deployed by Terraform k8s provider)?

I'm thinking it should be treated like a `StorageProviderClass`, applications shouldn't be concerned with this and only mount K8s Secrets.

**Comment by aramase** [comment]
@dkirrane the `SecretProviderClass` is a namespaced resource and needs to exist in the same namespace as the application pod. `StorageClass` on the other hand define the default classes supported on the cluster which can then be referenced in the `PersistentVolumeClaim`. The `SecretProviderClass` is closed to a pvc here.

**Comment by dkirrane** [comment]
ok thanks, so there is no concept of global type Secrets. i.e. if apps in same namespace need the exact same secrets from key vault they should have their own SecretProviderClass in their helm chart.
Apps need to ensure the K8s `secretName` don't clash.

**Comment by aramase** [comment]
> ok thanks, so there is no concept of global type Secrets. i.e. if apps in same namespace need the exact same secrets from key vault they should have their own SecretProviderClass in their helm chart.
Apps need to ensure the secretNames don't clash when they Sync with Kubernetes Secrets

That's correct. It is good to have the level of isolation by having a `SecretProviderClass` per deployment to ensure no conflicts and also scenarios where a particular secret is only required for one of the pods in the same namespace.

**Comment by MrRenx** [comment]
Hi guys, do you know how to implement the **SecretProviderClass** as terraform for AKS provider?
