### ISSUE TITLE
test: add CI job that validates "custom cloud" features

### ISSUE THREAD

**Issue by jadarsie** [Azure/secrets-store-csi-driver-provider-azure#223]
**Describe the solution you'd like**

It is possible to pretend that `AzurePublicCloud` is a custom cloud by using this AKS Engine [cluster definition](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/test/e2e/cluster_configs/linux-custom-cloud.json)

**Anything else you would like to add:**

The CI job will require an AKS Engine release that includes the following feature: https://github.com/Azure/aks-engine/pull/3787

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
We have an e2e test today for custom cloud environment validation: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/test/e2e/custom_cloudenv_test.go. Closing this issue with test.
