### ISSUE TITLE
Kubernetes secret not updated even after pod restart

### ISSUE THREAD

**Issue by kamilzzz** [Azure/secrets-store-csi-driver-provider-azure#224]
**What steps did you take and what happened:**
1. Deployed 2 pods referencing SecretProviderClass
2. Volumes were mounted correctly and kubernetes secret was created
3. Updated a certificate stored in a keyvault
4. Redeployed one of the pods
5. Updated certificate was correctly mounted as a volume but kubernetes secret was not updated

**What did you expect to happen:**
Kubernetes secret to be updated

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Installed via helm, chart - csi-secrets-store-provider-azure-0.0.10
- Azure Key Vault provider version: (use the image tag): Installed via helm, chart - csi-secrets-store-provider-azure-0.0.10 
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.16.13
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@kamilzzz The CSI driver currently doesn't support automatic reload of secrets after it is created. This is planned for the next release of the driver - [issue](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/125). For the current release, you will need to delete the Kubernetes secret and redeploy the pods for the secret to be created with the new certificate.

**Comment by kamilzzz** [comment]
@aramase thanks for the response.

Any estimate when next release will be out?

**Comment by aramase** [comment]
@kamilzzz The release is tentatively planned for sometime in the next 2 weeks. The PRs for adding the feature are currently under review.

**Comment by aramase** [comment]
We have added the latest CSI Driver `v0.0.16` as part of the Azure Key Vault provider helm release. The secret rotation alpha feature can be tried out with the latest helm charts.

Here are some docs on how to enable the secret rotation and configure the poll interval for rotation -
- https://github.com/Azure/secrets-store-csi-driver-provider-azure#optional-enable-auto-rotation-of-secrets
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md
