### ISSUE TITLE
Whether the volume can be mounted with non-root user

### ISSUE THREAD

**Issue by Shuanglu** [Azure/secrets-store-csi-driver-provider-azure#225]
**Describe the solution you'd like**
Whether the volume can be mount with non-root user

**Anything else you would like to add:**
N/A

**Environment:**
AKS
- Secrets Store CSI Driver version: (use the image tag):  mcr.microsoft.com/k8s/csi/secrets-store/driver:v0.0.13
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/k8s/csi/secrets-store/provider-azure:0.0.8
- Kubernetes version: (use `kubectl version`): v1.16.13
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@Shuanglu Could you elaborate more on this issue? What is the current behavior you're seeing and what is the use case?

**Comment by ma185360** [comment]
Hi Team,

Use case is like this. Application container is running with non-root user and secrets are getting mounted with root privileges because of which container application is not able to access those secrets.

**Comment by aramase** [comment]
PR to make file permission configurable is merged: https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/751. This will be available in `v1.1.0` release planned for next week.
