### ISSUE TITLE
New Versions of a Key Vault Secret Are Not Being Retrieved

### ISSUE THREAD

**Issue by kylelee24** [Azure/secrets-store-csi-driver-provider-azure#231]
**What steps did you take and what happened:**
- Deployed `SecretProviderClass` using `secretObjects` to sync secrets.
- Mounted volume and referenced secrets in `Deployment` file and observed the environment variables are available to the pods.
- Created a new version of a Key Vault secret.
- Deleted Kubernetes secret to workaround this bug - https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/224.
- Verify Kubernetes secret was recreated and observed that the content of the secret was with the previous (original) Key Vault secret version.

**What did you expect to happen:**
- The newly created Kubernetes secret would of reflected the latest version of the Azure Key Vault secret.

**Anything else you would like to add:**
- I tried to specify the `objectVersion` which didn't make any difference.

**Which access mode did you use to access the Azure Key Vault instance:**
- Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): csi-secrets-store-provider-azure-0.0.10
- Azure Key Vault provider version: (use the image tag): csi-secrets-store-provider-azure-0.0.10
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): AKS 1.17.9
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@kylelee24 After the secret is deleted, the pod needs to be restarted to fetch the latest content. 

The secret is a reflection of the content in the pod mount. If pod isn't restarted then the secret is created with the existing content from pod mount which is still the old version.
