### ISSUE TITLE
Better guidance for access options

### ISSUE THREAD

**Issue by ritazh** [Azure/secrets-store-csi-driver-provider-azure#235]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Provide pros and cons of each access option listed: https://github.com/Azure/secrets-store-csi-driver-provider-azure#provide-identity-to-access-key-vault

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
Add the details here: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/

**Comment by lpunati** [comment]
Hello @aramase, the above link is not working. It is throwing a 404

**Comment by nilekhc** [comment]
> Hello @aramase, the above link is not working. It is throwing a 404. Can you please take a look. thanks.

Could you try https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/

**Comment by lpunati** [comment]
> > Hello @aramase, the above link is not working. It is throwing a 404. Can you please take a look. thanks.
> 
> Could you try https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/

This link is working, thanks
