### ISSUE TITLE
plugin GA on AKS

### ISSUE THREAD

**Issue by aelmanaa** [Azure/secrets-store-csi-driver-provider-azure#237]
Hello and thanks for the work.

are there any plans to make this plugin GA on AKS? 

for instance, we are using azure-file-csi (https://github.com/kubernetes-sigs/azurefile-csi-driver) since the earlier versions and now we see that it is in preview and will be soon GA on AKS. So I was thinking that you would have similar roadmap.
I'm asking this question as our stakeholders (Infra managers..Etc) will be more relieved to know that we are using a plugin which is planed to be GA (meaning that it will be included in the support contract with Azure).

**Comment by aramase** [comment]
@aelmanaa Thank you for opening the issue 👍 

The integration is in the AKS backlog. You can open an issue here - https://github.com/Azure/AKS/issues to get updates.

**Comment by aelmanaa** [comment]
ok thanks @aramase  will do. 
another question: do you support all AKS GA versions ? For instance 1.18 is GA now and 1.19 will GA soon. Do you ensure that AZure CSI secret store supports new k8s versions before that they become GA?

thanks

**Comment by aramase** [comment]
> another question: do you support all AKS GA versions ? For instance 1.18 is GA now and 1.19 will GA soon. Do you ensure that AZure CSI secret store supports new k8s versions before that they become GA?

@aelmanaa We currently test the driver with the latest versions of AKS as part of our CI pipeline.

**Comment by aelmanaa** [comment]
ok thanks @aramase
