### ISSUE TITLE
kubernetes secret sync does not recreate it  if already exists

### ISSUE THREAD

**Issue by tigran-a** [Azure/secrets-store-csi-driver-provider-azure#240]
**What steps did you take and what happened:**
secretObjects does not honor updates in the KeyVault 

Scenario:
Assuming a SecretProviderClass with secretObjects defined. 
A secret with value Value1 is in KeyVault

1. Create a pod that mounts a csi volume with secrets-store.csi.k8s.io driver referencing the secretProviderClass. 
 _(it will create a k8s secret with value Value1)_
2. Update secret value in the KV to Value2
_(mounted value in the pod and in the k8s secret are still Value1. Ok, can understand)_
3. Create another pod with the same settings
_(mounted value is Value2, the new one. k8s secret is still Value1. Here, in my view, it should be Value2)_
4. Delete the first pod
_(now we have a (second and the only) pod running launched when value in the KeyVault was Value2, but synced secret has still Value1)_)

**What did you expect to happen:**
When the second pod is created, update k8s secret with the new value from the KV.

Why this behaviour would be "better": If we also define an environment variable out of the secret in the newly created pods, it would have the new secret value. 

**Anything else you would like to add:**
In between of a bug report and feature request.

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): installed with helm (today), app version 0.0.8
- Azure Key Vault provider version: (use the image tag): installed with helm, app version 0.0.8
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.16.9
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@tigran-a Thank you for opening the issue 👍 

This is a know limitation in the `secrets-store-csi-driver` - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store.

When the `v0.0.15` for driver will be released, the secrets and mounted contents will be periodically updated to the latest value.

**Comment by tigran-a** [comment]
Thanks @aramase, you are right, I did not spot it. Closing the issue.
