### ISSUE TITLE
Additional example for usage of CSI with Service Principal when deploying resources in different namespaces

### ISSUE THREAD

**Issue by akav** [Azure/secrets-store-csi-driver-provider-azure#241]
Documentation provided for usage of Service Principal:
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/service-principal-mode.md

If one applies the secrets-store-creds and SecretProviderClass in default namespace only, when one deploys resources in namespace other than default containers will generate not found errors. It would be helpful to expand the documentation and mention that if one wishes to use the mounted volume that they would need to apply both secrets-store-creds and SecretProviderClass to each namespace where we wish our resources to have access to KeyVault.

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**
- Kubernetes version: 1.17.11
- Cluster type: AKS

**Comment by pradorodriguez** [comment]
Also, if you try to sync the Secrets in other Namespaces it fails.

**Comment by aramase** [comment]
Closed with https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/468
