### ISSUE TITLE
MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = stat /etc/kubernetes/secrets-store-csi-providers/azure/provider-azure: no such file or directory

### ISSUE THREAD

**Issue by veboddu** [Azure/secrets-store-csi-driver-provider-azure#259]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Using deployment yaml files to deploy CSI secret store with azure provider for Geneva services. The same script worked for deploying geneva services with CSI driver enabled for most of our deployments, but failed with below error in one region.

`
  Warning  FailedMount  69s (x12 over 9m27s)  kubelet, aks-nodepool-24549477-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = stat /etc/kubernetes/secrets-store-csi-providers/azure/provider-azure: no such file or directory
`

And yes, CSI secret store provider pods are healthy and running fine.

NAME                                                     READY   STATUS      RESTARTS   AGE
csi-secrets-store-bvgjc                            3/3     Running             0          20h
csi-secrets-store-provider-azure-cnj5q   1/1     Running             0          12m
csi-secrets-store-provider-azure-g4fhj   1/1     Running             0          12m
csi-secrets-store-provider-azure-j67xq   1/1     Running             0          12m
csi-secrets-store-tbtwb                            3/3     Running             0          20h
csi-secrets-store-w2tbh                            3/3     Running             0          20h

But my geneva services are struck in container create state -

geneva-services-bsl52                    0/4     ContainerCreating   0          10m
geneva-services-kr96d                   0/4     ContainerCreating   0          3m51s

**What did you expect to happen:**
Geneva services running without any error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity

**Environment:**
 PROD 

- Secrets Store CSI Driver version: (use the image tag):
us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.12

- Azure Key Vault provider version: (use the image tag):
mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.9

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

NAME                               STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool-24549477-vmss000000   Ready    agent   14d   v1.18.8   10.240.0.4    <none>        Ubuntu 16.04.7 LTS   4.15.0-1093-azure   docker://19.3.12
aks-nodepool-24549477-vmss000001   Ready    agent   14d   v1.18.8   10.240.0.5    <none>        Ubuntu 16.04.7 LTS   4.15.0-1093-azure   docker://19.3.12
aks-nodepool-24549477-vmss000002   Ready    agent   14d   v1.18.8   10.240.0.6    <none>        Ubuntu 16.04.7 LTS   4.15.0-1093-azure   docker://19.3.12

- Cluster type: (e.g. AKS, aks-engine, etc):
AKS

**Comment by aramase** [comment]
@veboddu The latest version of the Azure Key Vault provider `0.0.9` is not compatible with driver versions < `v0.0.14`. While installing the driver and providers using yamls, there are few additional configuration flags that need to be set as documented here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/install-yamls.md

```
--grpc-supported-providers=azure
```
arg in the `secrets-store` container for the secrets-store-csi-driver.

**Comment by aramase** [comment]
If the Secrets Store CSI Driver and Azure Key Vault provider are installed using helm from this repo, the helm charts automatically configure the required flags documented above.

**Comment by veboddu** [comment]
Thanks @aramase . But the same has been working for other regions. Any reason why this could have been a specifically for few?

**Comment by aramase** [comment]
@veboddu That's probably because the old version of provider binary exists and is being used with the driver. If you want to use the latest version `0.0.9`, then you would need to set the flags to configure the driver.

**Comment by veboddu** [comment]
Ok. As we don't have specific reason for the older binaries, will update driver to the latest and check.

**Comment by jrudley** [comment]
I think I ran into this on, but a windows container. I am not sure if it is related? It was a k8s job and successfully ran, so I am assuming it worked eventually?
` Warning  FailedToCreateSecret  42s (x17 over 6m16s)  csi-secrets-store-controller  failed to get mounted files, err: failed to list all files in target path c:\var\lib\kubelet\pods\35a528b8-57d2-44a6-b219-f78fe5ca91b3\volumes\kubernetes.io~csi\secrets-store-inline\mount, err: open c:\var\lib\kubelet\pods\35a528b8-57d2-44a6-b219-f78fe5ca91b3\volumes\kubernetes.io~csi\secrets-store-inline\mount: The system cannot find the path specified.`

**Comment by aramase** [comment]
@veboddu Were you able to follow the instructions to update to the latest version? Is the issue resolved now?

**Comment by mortenlerudjordet** [comment]
Can confirm on my side that adding --grpc-supported-providers=azure to secrets-store-csi-driver.yaml solved my problem with the same error.
Should look like this after edit:
```
        - name: secrets-store
          image: us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.16
          args:
            - "--debug=true"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--provider-volume=/etc/kubernetes/secrets-store-csi-providers"
            - "--metrics-addr=:8095"
            - "--enable-secret-rotation=false"
            - "--rotation-poll-interval=2m"
            - "--grpc-supported-providers=azure"
```

**Comment by aramase** [comment]
@veboddu Any update on this issue?

**Comment by veboddu** [comment]
Thank you @aramase . With the suggested change, I was able to get it working.

**Comment by ascdi** [comment]
I do not understand where to put the `grpc-supported-providers=azure` in terraform.
Can i put it in the Helm Chart somewhere?
I am using the `helm_release` terraform provider.
