### ISSUE TITLE
"provider-azure" binary expected in "/etc/kubernetes/secrets-store-csi-providers/azure" of every node

### ISSUE THREAD

**Issue by aelmanaa** [Azure/secrets-store-csi-driver-provider-azure#269]
Hello,

we have a lab cluster on which I'm testing new versions of secret store csi & provider-azure before rolling out on our other AKS clusters.

I've remarked that with the last version of azure provider (mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.9) , on every node, a file "azure.sock" is created in "/etc/kubernetes/secrets-store-csi-providers" and there is no more the binary  in "/etc/kubernetes/secrets-store-csi-providers/azure/provider-azure".
This is causing an issue as my pods are unable to fetchs the secrets, I get the following error message

 err: failed to find provider binary azure, err: stat /etc/kubernetes/secrets-store-csi-providers/azure/provider-azure: no such file or directory

**Comment by aramase** [comment]
@aelmanaa If the driver is installed manually using the yamls from the driver repo, you'll need to set the `--grpc-supported-providers=azure` arg in the driver manifest.

Ref doc: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/install-yamls.md#install-the-secrets-store-csi-driver

If using helm, this arg is automatically configured in the driver deployment - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/values.yaml#L75

**Comment by aelmanaa** [comment]
ok @aramase  thanks ,it works fine now.
The note is confusing though:

elease of the Azure Key Vault provider is incompatible with the Secrets Store CSI Driver versions < **v0.0.14** ; I'm using secret store CSI driver v0.0.16 and as we can see, "--grpc-supported-providers=azure" is needed

**Comment by aramase** [comment]
@aelmanaa The release notes also have a ref to the doc which explains setting this flag if you using manifests - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/how-to-upgrade.md

```
**Please read the doc carefully before upgrading.**
```

**Comment by aramase** [comment]
Closing this issue as it's resolved now. Please feel free to reopen if there is any other issue.
