### ISSUE TITLE
aks start/stop 

### ISSUE THREAD

**Issue by jrudley** [Azure/secrets-store-csi-driver-provider-azure#278]
I am testing out the aks start/stop preview feature. What is happening when I start the cluster back up is that the specific node running the provider and driver need to pull the image, so other pods on the same node are throwing mount failures.  I was looking to run an init container to check to make sure the pod is up, but not sure what kind of health check I could use. I could depend on the retrys, but it would be cleaner if I could check to see the status of my driver pod. Any suggestions?

**Comment by ritazh** [comment]
@jrudley Thanks for the feedback! 
We should think about adding readiness probe for the csi driver @aramase

**Comment by aramase** [comment]
Thank you @jrudley!

I've opened https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/353 to track it.

**Comment by deuch** [comment]
Maybe use a PriorityClassName too to system-cluster-critical to be sure that csi pods are scheduled and started before applicative pods ?

**Comment by aramase** [comment]
@jrudley I did some investigation today. The driver has a liveness probe side car container which queries the driver using the unix socket and reports readiness status every `3s`. You can query the driver readiness status by `curl <node ip>:9808/healthz`. This will return response `ok` with `200 OK` status code if the driver is up and running on the node and is responding on the unix socket.

```bash
root@kind-control-plane:/# curl 172.18.0.2:9808/healthz -vvv
*   Trying 172.18.0.2:9808...
* TCP_NODELAY set
* Connected to 172.18.0.2 (172.18.0.2) port 9808 (#0)
> GET /healthz HTTP/1.1
> Host: 172.18.0.2:9808
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 02 Nov 2020 19:38:27 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 172.18.0.2 left intact
ok

root@kind-control-plane:/# curl 172.18.0.2:9808/healthz
ok
```

Here `172.18.0.2` is my node ip and port `9808` is defined [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/deploy/secrets-store-csi-driver.yaml#L105) and exposed [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/deploy/secrets-store-csi-driver.yaml#L72-L75) in the CSI driver deployment manifest.

**Comment by jrudley** [comment]
Ah, great suggestion

**Comment by aramase** [comment]
We'll also add this to the driver docs

**Comment by aramase** [comment]
@jrudley Did you get a chance to try out the liveness probe response to determine readiness status?

**Comment by jrudley** [comment]
Yes, all good. Feel free to close this! Thanks

**Comment by aramase** [comment]
Thank you for the confirmation. Closing this now. Please feel free to re-open if you have any questions.
