### ISSUE TITLE
Possibility to annotate the created secret with secretprovider

### ISSUE THREAD

**Issue by local-master** [Azure/secrets-store-csi-driver-provider-azure#279]
**Describe the solution you'd like**
At the moment the secrets can only be used within the namespace that the pod mounts the disk and secret is created. Using kubed we could share that secret with other namespaces. This will allow us to have single namespace with some alpine pod running all the mounts with secret and spread the secrets across namespaces. 

For this to work the secret has to be annotated. At the moment it is not possible to annotate on creation/before. And every time you update the secret and redeploy mounts the manual annotation is removed. 

I guess possibility of adding annotation to the secret on secreptorvider level would be enough. 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  0.0.16
- Azure Key Vault provider version: (use the image tag): 0.0.9
- Kubernetes version: (use `kubectl version`): v1.17.11
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@local-master Thank you for the feedback. Since this is a driver feature I've opened the issue here - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/356.
