### ISSUE TITLE
Support for reading the azure environment file

### ISSUE THREAD

**Issue by ZeroMagic** [Azure/secrets-store-csi-driver-provider-azure#281]
**Describe the solution you'd like**
Currently, secret-store-csi-driver-provider-azure just sets the azure environment file path. It does not read the content. 
In the MSI scenario, it works as a managed addon in AKS. While in the SP scenario, users still need to create another SP to access their key vaults. 

As a managed addon, it is a better way for SP users to directly access the key vault with the in-cluster azure environment file.

**Anything else you would like to add:**
Since most of the users are leveraging MSI, we are not sure about how many users are using SP and need this change. If anyone needs this feature, please +1 in the comment. 

**Environment:**
- Cluster type: AKS

**Comment by aramase** [comment]
Closing this issue because we have no user requests on this. Please feel free to reopen if you have any questions or suggestions.
