### ISSUE TITLE
Support configuring updateStrategy.rollingUpdate.maxUnavailable in Helm charts

### ISSUE THREAD

**Issue by chrisamert** [Azure/secrets-store-csi-driver-provider-azure#283]
**Describe the solution you'd like**
Right now the Helm Charts configure Daemonsets with the RollingUpdate strategy, but don't provide any option so specify the 'maxUnavailble' property, so the default value of '1' is being used.  On our 60+ node clusters this is causing the deployment to take 40+ minutes to complete.  It would be great if the Helm charts allowed 'maxUnavailable' to be configurable so more than one node can be updated at once.

**Anything else you would like to add:**
This should apply to both Azure/secrets-store-csi-driver-provider-azure and kubernetes-sigs/secrets-store-csi-driver.  Should I open a second issue over there?

Related question, but what is the impact when a single node is being updated?  Would new pods using the Secrets Store CSI Driver be blocked from coming online until the update is complete on that node?

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
@chrisamert Thank you for opening the issue 👍 

> This should apply to both Azure/secrets-store-csi-driver-provider-azure and kubernetes-sigs/secrets-store-csi-driver. Should I open a second issue over there?

Yeah, please open another issue for the driver.

> Related question, but what is the impact when a single node is being updated? Would new pods using the Secrets Store CSI Driver be blocked from coming online until the update is complete on that node?

That is correct. When kubelet invokes the driver for the volume mount it needs to wait until the new pod is up and running for the mount to succeed.

Would you be interested in opening a PR for this?

**Comment by chrisamert** [comment]
@aramase Yes, I can send a PR for this.  And I will open another issue for the driver

**Comment by chrisamert** [comment]
Issue for the driver: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/361
