### ISSUE TITLE
Support using `userAssignedIdentityID` when `usePodIdentity` is true

### ISSUE THREAD

**Issue by jbearor** [Azure/secrets-store-csi-driver-provider-azure#284]
**Describe the solution you'd like**
When `usePodIdentity` is `true`, I would like to be able to use `userAssignedIdentityID` to chose the `AzureIdentity` I want to use in the csi driver (when multiple identities are configured).  Looking through the code, this doesn't seem to be configured, is there another way this functionality is already in place?

**Anything else you would like to add:**
 I currently have two `AzureIdentityBindings` configured, following the [aad-pod-identity docs](https://azure.github.io/aad-pod-identity/docs/best-practices/#a-pod-using-multiple-azureidentities), with one identity containing the keyvault access role assignments.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`): 
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by Tenseiga** [comment]
eagerly waiting :)

**Comment by schwichti** [comment]
@jbearor Is there something new to this? Maybe https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/771 is relevant.

**Comment by aramase** [comment]
AAD Pod Identity is deprecated, so this is not something that'll be supported. Closing this issue.
