### ISSUE TITLE
cluster autoscaler causes failed mount

### ISSUE THREAD

**Issue by jrudley** [Azure/secrets-store-csi-driver-provider-azure#286]
**What steps did you take and what happened:**
Deploying new image, no available nodes, new node provisioned, secret store pods deployed, my container keeps retrying to mount while secret store pods are pulling new image and creating container, my container eventually mounts the volume.

whats happening is when my container try's to mount once csi pods are up is a mount failure
```
Events:
  Type     Reason            Age                    From                     Message
  ----     ------            ----                   ----                     -------
  Warning  FailedScheduling  9m41s (x2 over 9m41s)  default-scheduler        0/12 nodes are available: 2 node(s) didn't match node selector, 4 Insufficient cpu, 6 Insufficient memory.
  Normal   Scheduled         9m37s                  default-scheduler        Successfully assigned nonprod1/cm-587767d79d-8lbc5 to aksnpwin00000c
  Warning  FailedMount       9m36s                  kubelet, aksnpwin00000c  MountVolume.SetUp failed for volume "default-token-fvlt7" : failed to sync secret cache: timed out waiting for the condition  Warning  FailedMount       83s (x12 over 9m37s)   kubelet, aksnpwin00000c  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
  Warning  FailedMount       47s (x4 over 7m34s)    kubelet, aksnpwin00000c  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-fvlt7 secrets-store-inline]: timed out waiting for the condition
```
I tried restarting the deployment after the secret store pods were up, but no luck.

**What did you expect to happen:**
my container to mount the volume once the secret store pods are running

**Anything else you would like to add:**
k logs azure-csi-secrets-store-csi-driver-windows-hdfmm node-driver-registrar

I1023 19:27:29.530398    4520 main.go:110] Version: v1.2.1-alpha.1-0-gb4bdb81f
I1023 19:27:31.167388    4520 main.go:120] Attempting to open a gRPC connection with: "unix://C:\\csi\\csi.sock"
I1023 19:27:31.167388    4520 connection.go:151] Connecting to unix://C:\csi\csi.sock
I1023 19:27:31.676393    4520 main.go:127] Calling CSI driver to discover driver name
I1023 19:27:31.676393    4520 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1023 19:27:31.676393    4520 connection.go:181] GRPC request: {}
I1023 19:27:32.265199    4520 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"0.0.16"}
I1023 19:27:32.266203    4520 connection.go:184] GRPC error: <nil>
I1023 19:27:32.266203    4520 main.go:137] CSI driver name: "secrets-store.csi.k8s.io"
I1023 19:27:32.384202    4520 node_register.go:51] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I1023 19:27:32.856246    4520 node_register.go:60] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock

```
k get csidriver

NAME                       ATTACHREQUIRED   PODINFOONMOUNT   MODES       AGE
secrets-store.csi.k8s.io   false            true             Ephemeral   3d2h
```
It feels like the pod was provisioned without any configuration. I did another deployment and same thing happened when it was thrown on the newly created node.

```
Normal   TriggeredScaleUp  5m49s                  cluster-autoscaler       pod triggered scale-up: [{aksnpwin 4->5 (max: 20)}]
  Warning  FailedScheduling  4m23s (x4 over 5m54s)  default-scheduler        0/12 nodes are available: 3 Insufficient memory, 4 Insufficient cpu, 5 node(s) didn't match node selector.
  Normal   Scheduled         3m24s                  default-scheduler        Successfully assigned nonprod1/id-65dffd697-8x9nx to aksnpwin00000c
  Warning  FailedMount       81s                    kubelet, aksnpwin00000c  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-fvlt7 secrets-store-inline]: timed out waiting for the condition
  Warning  FailedMount       76s (x9 over 3m24s)    kubelet, aksnpwin00000c  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
```

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**
Windows nodes

Secrets Store CSI Driver version: (use the image tag): 0.0.16
Azure Key Vault provider version: (use the image tag): 0.0.9
Kubernetes version: (use kubectl version and kubectl get nodes -o wide): 1.18.8
Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@jrudley From the logs posted above -

```bash
I1023 19:27:31.676393 4520 connection.go:181] GRPC request: {}
I1023 19:27:32.265199 4520 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"0.0.16"}
```

this indicates the driver `secrets-store` container is up and running and is responding on the socket.

On a good node (in my cluster) -
```bash
I1023 20:05:08.298385       1 node_register.go:58] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I1023 20:05:08.298570       1 node_register.go:67] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I1023 20:05:09.190447       1 main.go:77] Received GetInfo call: &InfoRequest{}
I1023 20:05:09.208849       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

the last 2 lines of log usually indicate the plugin being registered and kubelet ACK'in it with `NotifyRegistrationStatus`.

Could you check the kubelet logs for the node to see if there are any errors?

**Comment by jrudley** [comment]
I could not see any errors that stood out. I had to blow away this cluster and reprovisioned. I'll see if I can repo again

**Comment by aramase** [comment]
@jrudley Were you able to repro this? I haven't had a repro so far, but will try again.

**Comment by jrudley** [comment]
I was able to repo it when using insights monitoring. That bug caused all
kinds of issues. They rolled out the fix to the US region Friday. I am
testing my cluster with Microsoft today, but so far so good. I would close
this issue.

**Comment by aramase** [comment]
Thank you for confirming. I'll close this issue now but please feel free to reopen.
