### ISSUE TITLE
Kubernetes Secrets not getting refreshed during pod restart

### ISSUE THREAD

**Issue by barlass** [Azure/secrets-store-csi-driver-provider-azure#289]
**What steps did you take and what happened:**
We have secret-store mounted on pods. 

        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-v

So when the certs in key vault are updated and we restart the pods , the mounted secret-store gets updated version and content from Key Vault , but the kube Secret objects are not synced/refreshed,

**What did you expect to happen:**
Expect the kube secrets to have the same content as mounted secret-store.

**Comment by aramase** [comment]
@barlass  So this is a known limitation - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store. The Kubernetes secret is created the first time a pod referencing it is created. The secret data is mirrored based on the content in mount. 

To enable update of the created Kuberentes secret and the mounted contents, we have introduced secret rotation alpha feature in `v0.0.16`. 

Docs on how to enable secret rotation -
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md

**Comment by barlass** [comment]
So , the only time kubernetes secret is updated is when the first pod referencing it is created for the first time. And after that it is not sync with the mounted secret store during subsequent rolling deployments ?  Is this the correct understanding?

**Comment by aramase** [comment]
@barlass That's correct. The primary functionality for the driver is to mount the objects in the pod. Mirroring as Kubernetes secret is optional and if enabled will be done if the secret doesn't exist. If the secret already exists and needs update then it would need to be deleted. 

But with the new auto rotation alpha feature the secret is periodically updated with the latest mount content. Also, when the certs are updated in key vault it doesn't require a pod restart. The mounted content and Kubernetes secret will be automatically updated based on the configured poll interval. 

- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md

**Comment by aramase** [comment]
@barlass Did you get a chance to try out the auto rotation feature?

**Comment by barlass** [comment]
Yes I did and the secrets are now getting refreshed. If we could restrict this to pod restarts only , it would have been great. thanks for the quick response.

**Comment by aramase** [comment]
> Yes I did and the secrets are now getting refreshed. If we could restrict this to pod restarts only , it would have been great. thanks for the quick response

The idea is to not have to restart the pods manually for updates to the mount. Without the secret auto rotation if you still want to do the restart, you can accomplish it as documented here - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store. Delete the Kubernetes Secret and then restart the pods. The new secret will be created with the latest content.

Thank you for confirming the secrets are refreshed. Closing this issue as it's resolved. Please feel free to open a new issue if you have any questions or requests.
