### ISSUE TITLE
PFX certificate fetched from keyvault is not working/not in correct format

### ISSUE THREAD

**Issue by rahulgkrishna97** [Azure/secrets-store-csi-driver-provider-azure#291]
**What steps did you take and what happened:**

Installed azure-provider using the command 
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name

installed the secretproviderclass.yaml and deployment.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: test-secret
    type: kubernetes.io/tls
    data: 
    - objectName: test-cert-pfx
      key: tls.key
    - objectName: test-cert-pfx
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: "azure-keyvault"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: test-cert-pfx
          objectType: secret
          objectVersion: ""
          objectFormat: "pfx"
    tenantId: "3exxxxxxxxxxxxxxxxxxxxxxxx95" 

current output:
apiVersion: v1
data:
  tls.crt: ""
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret

not getting the expected contents in the certificate retrieved
 
**What did you expect to happen:**
Expect to retrieve the proper certificate in the kubernetes secret and use that certificate in gateway communication
example:
  
  apiVersion: v1
data:
  tls.crt: QmFnIEF0dHJpYnV0ZXMNCiAgICBsb2NhbEtlxxx.........xxxxxxx
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLxxx...........xxxxxx
kind: Secret
**Anything else you would like to add:**
would be great if we could get the pfx file as it is from the keyvault
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**

   Service principal

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: AKS

**Comment by aramase** [comment]
@rahulgkrishna97 If the object type is pfx, then it can't be converted to Kubernetes Secret. 
```
objectFormat: "pfx"
```

If you want to sync the data as Kubernetes secret, then you can set the `objectFormat: pem`. This will write the certificate in pem format in the pod and also sync the pem content (splitting cert and key) as kubernetes secret.

**Comment by deuch** [comment]
Even if you choose Pem, if you secret is not a part of a certificate object in keyvault, it will not work.
If you store your certificate as a pure secret in keyvault (uploading the pfx cert  in keyvault as a secret for eg) the conversion will not occur.
This is a big issue for us because App Service Cerificate store the certificate as secret and not as certificate :( we faced many incident in production because of that with business impact recently 😞

**Comment by rahulgkrishna97** [comment]
@aramase I've tried as said above and it is still not working as expected , FYI we directly store the CA signed cert(pfx format) as a certificate object in keyvault and it also contains bag attributes, when we try to retrieve the cert those bag attributes are missing and the expected data is not retrieved.

**Comment by aramase** [comment]
> @aramase I've tried as said above and it is still not working as expected , FYI we directly store the CA signed cert(pfx format) as a certificate in keyvault and it also contains bag attributes, when we try to retrieve the cert those bag attributes are missing and the expected data is not retrieved.

@rahulgkrishna97 The bag attributes are not set when the certificate is written to the pod. However that should not affect the actual cert. Is this a cert chain? What is the difference in the PEM written to the pods vs the one uploaded? Are you able to validate the cert and key using openssl?
