### ISSUE TITLE
support for keyvault private link

### ISSUE THREAD

**Issue by katomel4** [Azure/secrets-store-csi-driver-provider-azure#296]
for best security please consider ability for integrate azure key vault with private link

**Comment by phillipgibson** [comment]
Thanks for your feedback @katomel4. This would fall under Azure Private Link functionality, which they currently do not support the KeyVault service. I would recommend posting your feedback on the Azure networking forum as well [here](https://feedback.azure.com/forums/217313-networking?category_id=368830)

**Comment by aramase** [comment]
@katomel4 Please take a look at https://docs.microsoft.com/en-us/azure/key-vault/general/private-link-service?tabs=portal. 

Closing this issue now.
