### ISSUE TITLE
no clientID or resourceID in request

### ISSUE THREAD

**Issue by KevinM2k** [Azure/secrets-store-csi-driver-provider-azure#300]
Hi,

We are using 1.6.3 of the RBAC release, and although this is working in general on most of ours pods, i am seeing some errors with a few, in the nmi i'm seeing this kind of behaviour:

```
I1106 14:32:47.654521       1 standard.go:72] no clientID or resourceID in request. test-dev/test-review-api-dev-5c4ddd78c8-gx9kg has been matched with azure identity test-dev/test-dev-review-api
I1106 14:32:47.654859       1 standard.go:178] matched identityType:0 clientid:eb77##### REDACTED #####16c3 resource:https://storage.azure.com
I1106 14:32:47.665450       1 server.go:192] status (200) took 12102272 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.192

```
I'm trying to understand what the above means - it seems to be causing us a few issues when connecting to blob storage accounts in the azure cloud.

Thanks

**Comment by aramase** [comment]
@KevinM2k For pod identity you can open issues here - https://github.com/Azure/aad-pod-identity/issues. 

> no clientID or resourceID in request. test-dev/test-review-api-dev-5c4ddd78c8-gx9kg has been matched with azure identity test-dev/test-dev-review-api

That's not an error. It's an info message. It indicates there was no specific clientID in the token request, so NMI is going to default to using the first clientID (from `AzureIdentity`) for the token request. The `clientID` is read from the token request header originating from the application pod. If you want to use a specific identity, then the `clientID` needs to be set.

**Comment by KevinM2k** [comment]
Thanks for your reply. Absolutely makes sense, and yeah I'll be sure to raise on the other area next time.
