### ISSUE TITLE
[Question] Understanding the road map of the solution

### ISSUE THREAD

**Issue by chirangaalwis** [Azure/secrets-store-csi-driver-provider-azure#302]
**Describe the question**

We have a few road map questions with regards to this solution.

- **Can we consider that this solution ready for a production grade deployment?**

Currently, this solution is at [`0.0.9`](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.9).

Thus, is it recommended to use this solution in production grade deployments?

- **Will this solution be integrated into AKS based clusters in the future, by default?**

- **Will this solution receive Azure technical support in the future?**

The Azure official [documentation](https://docs.microsoft.com/en-us/azure/aks/developer-best-practices-pod-security#use-azure-key-vault-with-secrets-store-csi-driver) recommends the use of this solution as a best practice.

But, as per [this documentation](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes) this solution will **not receive** Azure technical support.

Having Azure technical support will be essential when moving forward with this solution in a production grade deployment.

Appreciate if you can provide us with an understanding of the above.

**Suggested tags**
question

**Comment by aramase** [comment]
@chirangaalwis Thank you for opening the issue. 

We are working on the GA/Stable criteria in the community for the driver and the provider. This is the doc - https://docs.google.com/document/d/1ySjR_Zk93Kk7rel8ZIa4Spum-xArx3jRKPsFWTUKNr0/edit?usp=sharing

We have created `Stable` milestone for both the driver and provider and will be working on those issues for the next few months.

> Will this solution be integrated into AKS based clusters in the future, by default?

There is a GitHub issue opened for AKS integration - https://github.com/Azure/AKS/issues/1876. You can follow the issue for updates.

> Will this solution receive Azure technical support in the future?

After this solution is integrated with AKS, it will be supported by Azure technical support.

The project is currently open source and is only supported via GitHub issues - https://github.com/Azure/secrets-store-csi-driver-provider-azure#support. If you need assistance in addition to GitHub issues, you can also join the [#csi-secrets-store](https://kubernetes.slack.com/messages/csi-secrets-store) channel on [Kubernetes Slack](https://kubernetes.slack.com/), where other community members can also help.

**Comment by aramase** [comment]
Closing this issue now. 

Please follow https://github.com/Azure/AKS/issues/1876 to track progress of AKS integration.
