### ISSUE TITLE
Issue when using csi provider 

### ISSUE THREAD

**Issue by girishgouda** [Azure/secrets-store-csi-driver-provider-azure#303]
C:\Users\Girishgouda.Goudar\source\repos\multicluster\k8sonprem\kustomize\sql\base>kubectl get pods
NAME                                               READY   STATUS              RESTARTS   AGE
csi-secrets-store-provider-azure-f6m7x             1/1     Running             0          5m7s
csi-secrets-store-secrets-store-csi-driver-cnwcv   3/3     Running             0          14m
nginx-secrets-store-inline-user-msi                0/1     ContainerCreating   0          9m16s

Warning  FailedMount  85s (x10 over 5m35s)  kubelet, aks-default-28951543-vmss000000  MountVolume.SetUp failed for volume "secrets-store01-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-secrets-store-inline-user-msi, err: failed to
find provider binary azure, err: stat /etc/kubernetes/secrets-store-csi-providers/azure/provider-azure: no such file or directory
  Warning  FailedMount  79s (x2 over 3m32s)   kubelet, aks-default-28951543-vmss000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store01-inline], unattached volumes=[secrets-store01-inline default-token-l45pb]: timed out waiting for the condition

**Comment by aramase** [comment]
@girishgouda How are you installing the driver and provider? Which version are you installing?

If installing using yamls, please follow the docs here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/install-yamls.md. There is a note in the install docs on setting the required flag in the driver manifest if installing with yamls. Please ensure this flag is added -

```
NOTE: 0.0.9+ release of the Azure Key Vault provider is incompatible with the Secrets Store CSI Driver versions < v0.0.14. While installing the Secrets Store CSI Driver using yamls, add the following flag --grpc-supported-providers=azure to the Linux and Windows daemonset manifests.

The flag needs to be added to the secrets-store container args
```

**Comment by aramase** [comment]
@girishgouda Could you confirm if this issue is resolved now?

**Comment by aramase** [comment]
Closing this for now. Please feel free to re-open if you're still experiencing this issue.
