### ISSUE TITLE
Add support for ClusterIdentity

### ISSUE THREAD

**Issue by ritazh** [Azure/secrets-store-csi-driver-provider-azure#312]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
For Arc enabled clusters, an identity resource can be created via a `ClusterIdentity` CRD. Add support for `ClusterIdentity` to allow access to AKV via this identity.  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
[Azure Key Vault Secrets Provider extension to fetch secrets into Arc clusters](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-akv-secrets-provider) is in preview. It supports getting the secrets from AKV using service principal. The plan is to deprecate user-assigned and system-assigned managed identity for this provider and only support workload identity.

Closing this issue as we will not support cluster identity. We should plan for using workload identity with the arc extension when workload identity support is available in arc.
