### ISSUE TITLE
Unable to mount shared vault secret in eastus2 / voice namespace - csi driver failed

### ISSUE THREAD

**Issue by ashokbanerjee** [Azure/secrets-store-csi-driver-provider-azure#317]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
40417s         Warning   FailedMount
       pod/gsp-jm-0          
                     
      MountVolume.SetUp failed for volume
'gsp-secrets' : kubernetes.io/csi: mounter.SetupAt failed: rpc error:
code = Unknown desc = failed to mount secrets store objects for pod
gsp/gsp-jm-0, err: rpc error: code = Unknown desc = failed to mount objects,
error: failed to get keyvault client: failed to get key vault token: nmi
response failed with status code: 40480s

**What did you expect to happen:**
No failed mount, tests would work was the expectations.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
for eastus2 we, now, have cases where POD mount had worked but resulted in empty folder being mapped to a POD (valid secrets visible through mount), resulting in crashloop in service:
λ kubectl -n voice describe po t3000-0
Name:                 t3000-0
Namespace:            voice
Priority:             10000000
Priority Class Name:  genesysengage-critical-priority
Node:                 aks-general01-16542494-vmss000005/10.206.3.111
Start Time:           Fri, 06 Nov 2020 12:17:27 -0800
Labels:               aadpodidbinding=voice-identity
...
Containers:
  tenant:
    Container ID:   docker://d2c953454fb2dc51a5ff24d75c4a091f14764519aac74496ac0de2c6dafe63e7
    Image:          pureengage-docker-dev.jfrog.io/genesys/katana/tenant_node:latest
    Image ID:       docker-pullable://pureengage-docker-dev.jfrog.io/genesys/katana/tenant_node@sha256:c53ede53079bb0c7ceefc4d210509f3d3800ff93b5edff5510d9fc81a0dcdcd7
    Ports:          15000/TCP, 8888/TCP, 8000/TCP, 5050/TCP, 2060/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 09 Nov 2020 15:34:57 -0800
      Finished:     Mon, 09 Nov 2020 15:34:57 -0800
    Ready:          False
    Restart Count:  875
    ...
    Mounts:
      /opt/genesys/configdb-secret from configdb-secret (ro)
      /opt/genesys/consul-shared-secret from consul-shared-secret (ro)

...
Volumes:
...
  consul-shared-secret:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=keyvault-consul-consul-voice-token

with container exit error:
C:\\Users\\andreyy\\source\\repos\\genesysengag\\tools
λ kubectl -n voice logs t3000-0 tenant
ERROR CONSUL token is invalid. exiting
indicating secret being read is empty. 
container backoff restarts aren't clearing condition as it require POD re-creation to trigger proper mount, deletion of re-ceration of POD resulted in proper mount and no errors resported:
λ kubectl -n voice describe po t3000-0
Name:                 t3000-0
Namespace:            voice
Priority:             10000000
Priority Class Name:  genesysengage-critical-priority
Node:                 aks-general01-16542494-vmss000005/10.206.3.111
Start Time:           Mon, 09 Nov 2020 15:51:16 -0800
Labels:               aadpodidbinding=voice-identity
...
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  92s   default-scheduler  Successfully assigned voice/t3000-0 to aks-general01-16542494-vmss000005
  Normal  Pulling    86s   kubelet            Pulling image 'pureengage-docker-dev.jfrog.io/genesys/katana/tenant_pgdb_init:latest'
  Normal  Pulled     85s   kubelet            Successfully pulled image 'pureengage-docker-dev.jfrog.io/genesys/katana/tenant_pgdb_init:latest'
  Normal  Created    84s   kubelet            Created container tenant-pgdb-init
  Normal  Started    84s   kubelet            Started container tenant-pgdb-init
  Normal  Pulling    78s   kubelet            Pulling image 'pureengage-docker-dev.jfrog.io/genesys/bec/tools/cspostdeplrs:azure'
  Normal  Pulled     77s   kubelet            Successfully pulled image 'pureengage-docker-dev.jfrog.io/genesys/bec/tools/cspostdeplrs:azure'
  Normal  Created    77s   kubelet            Created container tenant-rcsinit
  Normal  Started    77s   kubelet            Started container tenant-rcsinit
  Normal  Pulled     71s   kubelet            Container image 'consul:1.7.2' already present on machine
  Normal  Created    71s   kubelet            Created container consul-connect-inject-init
  Normal  Started    70s   kubelet            Started container consul-connect-inject-init
  Normal  Pulling    70s   kubelet            Pulling image 'pureengage-docker-dev.jfrog.io/genesys/katana/tenant_node:latest'
  Normal  Pulling    68s   kubelet            Pulling image 'fluent/fluent-bit:1.3.5'
  Normal  Created    68s   kubelet            Created container tenant
  Normal  Started    68s   kubelet            Started container tenant
  Normal  Pulled     68s   kubelet            Successfully pulled image 'pureengage-docker-dev.jfrog.io/genesys/katana/tenant_node:latest'
  Normal  Pulled     67s   kubelet            Successfully pulled image 'fluent/fluent-bit:1.3.5'
  Normal  Created    67s   kubelet            Created container json-sidecar
  Normal  Started    67s   kubelet            Started container json-sidecar
  Normal  Pulled     67s   kubelet            Container image 'envoyproxy/envoy-alpine:v1.13.0' already present on machine
  Normal  Created    67s   kubelet            Created container consul-connect-envoy-sidecar
  Normal  Started    66s   kubelet            Started container consul-connect-envoy-sidecar
  Normal  Pulled     66s   kubelet            Container image 'hashicorp/consul-k8s:0.14.0' already present on machine
  Normal  Created    66s   kubelet            Created container consul-connect-lifecycle-sidecar
  Normal  Started    66s   kubelet            Started container consul-connect-lifecycle-sidecar

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
@ashokbanerjee Could you provide more info that'll help us debug?

1. Which version of the Secrets Store CSI Driver and Key Vault provider are you using?
2. What is the kubernetes version? `kubectl version` and `kubectl get nodes -o wide` output
3. Could you share the `SecretProviderClass` yaml being used?
4. Could you share the `Pod` yaml being used?
5. `failed to get keyvault client: failed to get key vault token: nmi` indicates there is an error with identity assignment. Did you get a chance to check the MIC logs for error? If there are no errors in MIC for the pod, could you confirm if the `AzureIdentity`, `AzureIdentityBinding` are setup correctly and the `selector` defined in the binding matches the `aadpodidbinding` label in the pod.

**Comment by ashokbanerjee** [comment]
Which version of the Secrets Store CSI Driver and Key Vault provider are you using?
Seems Donald and Derek are actively working on it.  My permission level won’t let me access configs.
What is the kubernetes version? kubectl version and kubectl get nodes -o wide output
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
 
Table

Description automatically generated
Could you share the SecretProviderClass yaml being used?
Don’t have direct access to this.  Need permission class admin
Could you share the Pod yaml being used?
This a number of pods.  Primary config listed below
failed to get keyvault client: failed to get key vault token: nmi indicates there is an error with identity assignment. Did you get a chance to check the MIC logs for error? If there are no errors in MIC for the pod, could you confirm if the AzureIdentity, AzureIdentityBinding are setup correctly and the selector defined in the binding matches the aadpodidbinding label in the pod.

**Comment by StephFitz-gene** [comment]
So the current issue has been happen across multiple Kubernetes services.  here's a screen grab of the above requested commands.  I am working on getting more permission to access the rest of the info as I am hitting a permission issue.
<img width="1535" alt="Screen Shot 2020-11-16 at 1 49 59 PM" src="https://user-images.githubusercontent.com/73569556/99306814-ec112100-2812-11eb-8437-258052fc21b1.png">

**Comment by StephFitz-gene** [comment]
kubectl describe
[gcxi-raa-0112-westus2-dev-statefulset-0.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/5549706/gcxi-raa-0112-westus2-dev-statefulset-0.txt)

**Comment by StephFitz-gene** [comment]
Example pod yaml
[gcxi-raa-0112-westus2-dev-statefulset-0.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/5549788/gcxi-raa-0112-westus2-dev-statefulset-0.txt)

**Comment by StephFitz-gene** [comment]
Example pod with issue yaml
gcxi-raa-0112-west yaml.txt

**Comment by aramase** [comment]
@StephFitz-gene In the describe output you posted, there is an error log - 

```
  Warning  FailedMount  3m7s (x33 over 54m)  kubelet            MountVolume.SetUp failed for volume "gcxi-raa-0112-westus2-dev-gim-secret-volume" : rpc error: code = Unknown desc = failed to get secretproviderclass gcxi/keyvault-gim-db-t0112, error: secretproviderclasses.secrets-store.csi.x-k8s.io "keyvault-gim-db-t0112" not found
```

The `SecretProviderClass` doesn't exist in the same namespace the pod is running.

**Comment by StephFitz-gene** [comment]
This was reported to be a deployment issue and has been resolved.

**Comment by aramase** [comment]
@StephFitz-gene Just to confirm the deployment issue has been fixed and is now resolved? Can we close this GitHub issue now?

**Comment by StephFitz-gene** [comment]
From what is being reported to me, yes.  Thank you.

**Comment by aramase** [comment]
Thank you for the confirmation. Closing this issue. Please feel free to re-open if they're any other issues.
