### ISSUE TITLE
Job and Deployment using same SecretProviderClass undesirably

### ISSUE THREAD

**Issue by kgriffiths** [Azure/secrets-store-csi-driver-provider-azure#321]
**What steps did you take and what happened:**
Using Helm, I use a job to run a db migration (as a pre-upgrade hook), and then on success, update the deployment. Both the job and deployment make use of the same `SecretProviderClass`. 

I add new secrets to Azure Key Vault, then delete the existing `Secret` created by the `SecretProviderClass`. Using Helm, I update the job, which creates a new pod, which requests the new secrets from Key Vault. The older version of the deployment is still running, asking for an older list of secret names. The recreated `Secret` undesirably creates itself using the old list of secret names from the deployment, and the db migration job's pod fails to find the new env var in the secret.

**What did you expect to happen:**
I expect the `SecretProviderClass` to merge the list of secrets from pods asking for different secret names, when creating a new secret.  

**Anything else you would like to add:**
When dealing with pods which may ask for different lists of secrets from time to time, is the best practice to use a different `SecretProviderClass` for each type? (I.e. a `SecretProviderClass` for the db migration job, and one for the deployment)

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.11
- Azure Key Vault provider version: (use the image tag): v0.0.7
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.16.10
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
> When dealing with pods which may ask for different lists of secrets from time to time, is the best practice to use a different SecretProviderClass for each type? (I.e. a SecretProviderClass for the db migration job, and one for the deployment)

@kgriffiths For multiple pods using different versions of secrets, the recommendation would be to use different `SecretProviderClass`. The Kubernetes secret created by the CSI driver is a mirror of the mounted values inside the pod. The Kubernetes secret is created if not found during pod volume mount and isn't updated unless it's manually deleted/auto rotation is enabled. If the job and deployment are using different versions, it's better to have different `SecretProviderClass` for each and sync to different Kubernetes secret to ensure no overlap or inconsistency in the values.

**Comment by kgriffiths** [comment]
@aramase Thanks for the clarification, this sounds like a good approach. I've set up my job with its own corresponding `SecretProviderClass`. It seems like after a pod created by the job completes successfully and is scaled to 0, the corresponding `Secret` is deleted. Is this because there are no mounted values to mirror, once the pod is deleted?

**Comment by aramase** [comment]
@kgriffiths That's right. The lifetime of the secret is tied to the pods consuming the secret. When all pods using the Kubernetes secret/`SecretProviderClass` are deleted, the secret is garbage collected.

**Comment by kgriffiths** [comment]
@aramase I appreciate the explanation, this makes sense. Would you review a PR with an update to the documentation which explains this behavior? I think it might be useful for others - some of the `Secret` behavior was surprising, to me at least.

**Comment by aramase** [comment]
@kgriffiths For sure! PRs are always welcome 😄  Thank you for taking the time to help improve our documentation.
