### ISSUE TITLE
Change secret store provider from DaemonSet to Deployment

### ISSUE THREAD

**Issue by armondressler** [Azure/secrets-store-csi-driver-provider-azure#323]
Is it possible to use the csi-secrets-store-provider as a simple deployment instead of a daemonset?

We use a service mesh which injects an additional container into every pod, making a daemonset resource wise an even costlier affair in clusters with a high nodecount. Is there a necessity to deploy this application as a daemonset or could a simple deployment provide the same services?

**Comment by aramase** [comment]
@armondressler The provider needs to be run as a daemonset because the CSI driver communicates using gRPC with the provider on the same node.

**Comment by armondressler** [comment]
Thanks for the quick response.
