### ISSUE TITLE
How to Trigger Sync On Demand

### ISSUE THREAD

**Issue by dilip-panwar-by** [Azure/secrets-store-csi-driver-provider-azure#325]
**Describe the solution you'd like**
[We have enabled the Auto Rotation in our AKS cluster and mounted secrets are also getting updated. However, environment variables inside the pod are still stale. Now, when I do another deployment with change in secret values, They are not getting picked up in the environment variables and I have to bounce the pods to get the changes in effect.  To avoid this situation, I am looking to have a pre-install hook through which, I could trigger the sync manually before deployment. or do let me know if there could be a better way of handling it.]

**Anything else you would like to add:**
[]

**Environment:*All*

- Secrets Store CSI Driver version: (use the image tag):latest
- Azure Key Vault provider version: (use the image tag):latest
- Kubernetes version: (use `kubectl version`): latest
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@dilip-panwar-by Thank you for opening the issue. 

The only way to get the latest env variable is by restarting the pod. Have you taken a look at [Reloader](https://github.com/stakater/Reloader). This will trigger pod restart when the secret it's consuming is updated. 

We have listed some of the use cases and how to handle each here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/325#issuecomment-754311586. Please feel free to reopen if you have any questions.
