### ISSUE TITLE
Customizing logVerbosity crashes secret store provider

### ISSUE THREAD

**Issue by doug-papenthien-by** [Azure/secrets-store-csi-driver-provider-azure#330]
**What steps did you take and what happened:**
We upgraded to the latest version of the csi-secrets-store-provider-azure helm chart (v0.0.14) and customized the logVerbosity to 2.  However, deploying the chart with this configuration results in the secret store provider being unable to start due to an unknown flag that's added when logVerbosity != 0:

```
❯ k logs csi-secrets-store-provider-azure-1606860391-8s4jg
unknown shorthand flag: 'v' in -v=2
Usage of /bin/secrets-store-csi-driver-provider-azure:
      --endpoint string   CSI gRPC endpoint (default "unix:///tmp/azure.sock")
      --log-format-json   set log formatter to json
      --version           prints the version information
```

Snippet from the pod description showing the updated argument coming from the logVerbosity configuration:
```
Containers:
  provider-azure-installer:
    Container ID:  docker://8c3df0b98a0d8bf85fc90fce291c633937fac05a8940b88085a66d25f446df81
    Image:         mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.10
    Image ID:      docker-pullable://mcr.microsoft.com/oss/azure/secrets-store/provider-azure@sha256:f23d699ac74e4a7eae1f7f8f4db010701e6438b4c643056aa6d3df6336f4eab2
    Port:          <none>
    Host Port:     <none>
    Args:
      --endpoint=unix:///provider/azure.sock
      -v=2
    State:          Waiting
      Reason:       CrashLoopBackOff
```

**What did you expect to happen:**
Helm chart deploys successfully with a log level configured according to the supplied value.

**Anything else you would like to add:**

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.0.17
- Azure Key Vault provider version: (use the image tag): 0.0.10
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.17.11
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@doug-papenthien-by Thank you for reporting the issue. I'll take a look and add the fix to the next release.
