### ISSUE TITLE
storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+

### ISSUE THREAD

**Issue by veccsolutions** [Azure/secrets-store-csi-driver-provider-azure#333]
**What steps did you take and what happened:**
Installed the helm chart using the following commands:
```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm repo update
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure -n $n azurekeyvault-csi
```

**What did you expect to happen:**
No warnings about things being deprecated

**Anything else you would like to add:**
I get the following messages:
```
W1204 17:00:52.505001     226 warnings.go:67] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
W1204 17:00:53.973286     226 warnings.go:67] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
```

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: 0.0.17
- Azure Key Vault provider version: 0.0.10
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Client: 1.19.2
Server: 1.19.4
- Cluster type: (e.g. AKS, aks-engine, etc):
On-prem

**Comment by aramase** [comment]
This change is already being tracked in https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/319. The deprecation warning is part of the kube-apiserver response and isn't an error. We'll be updating the versions in the driver soon.

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/402
