### ISSUE TITLE
Install to support windows containers..

### ISSUE THREAD

**Issue by nreddipalle** [Azure/secrets-store-csi-driver-provider-azure#336]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --set windows.enabled=true --set secrets-store-csi-driver.windows.enabled=true

Currently noticed two daemon sets
**Name                                                                Namespace  pods  Node Selector**
csi-secrets-store-secrets-store-csi-driver                 default    1     kubernetes.io/os=linux
csi-secrets-store-secrets-store-csi-driver-windows default     0     kubernetes.io/os=windows

Is this expected?? 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@nreddipalle The helm charts in https://github.com/kubernetes-sigs/secrets-store-csi-driver only install the driver. You'll need to install the provider as well. Please follow the instructions here: https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider to install the driver and the provider.

**Comment by nreddipalle** [comment]
Hello @aramase 
I followed as stated here: https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver-and-the-azure-keyvault-provider and followed the helm based installation https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md and as I am planning to use this for windows containers I ran the helm install by overriding two values to enable for windows containers windows.enabled=true and secrets-store-csi-driver.windows.enabled=true. Can you please confirm about the provider install you stated above??  Thanks.

**Comment by aramase** [comment]
@nreddipalle From the output you posted above, the helm charts you're adding are for the driver and not the one provider here: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md.

```
$ helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
$ helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name
```

You can set the windows enabled flags to the above command.

**Comment by nreddipalle** [comment]
Thanks @aramase . I am able to successfully deploy them now to default namespace (which is a linux pool VM) .. Is this the expected output??
csi-secrets-store-provider-azure-1607621080                                                   default    1   kubernetes.io/os=linux    53m
csi-secrets-store-provider-azure-1607621080-secrets-store-csi-d                   default     1   kubernetes.io/os=linux    53m
csi-secrets-store-provider-azure-1607621080-secrets-store-csi-d-windows    default     0   kubernetes.io/os=windows 53m
csi-secrets-store-provider-azure-1607621080-windows                                    default     0   kubernetes.io/os=windows  53m
As the default namespace is a linux node, it deployed and running a single daemonset pod.. and nothing for windows.. but I am expecting it will work automatically once I try to use for windows containers.. Am I missing any additional config/setup to make it work for windows containers?? I already added a SecretProviderClass kind object and relevant volume mount object to my helm deploy..

**Comment by aramase** [comment]
@nreddipalle Yeah, that's the expected output. The driver and AKV provider are daemonsets and run on all nodes. As you can see in the output posted, there is a daemonset of each for Linux and Windows.

**Comment by nreddipalle** [comment]
Thank you so much for quick response.
Closing the issue.

**Comment by nreddipalle** [comment]
@aramase sorry one final question. currently I do have one windows node running, was it suppose to run a windows pod on it??

**Comment by nreddipalle** [comment]
@aramase I am seeing this error while my windows pod trying to mount the volume..
![image](https://user-images.githubusercontent.com/28302399/102047269-f5a68e00-3daa-11eb-8e35-e48fc4153d2e.png)

**Comment by aramase** [comment]
@nreddipalle Can you confirm if there is a driver pod running on the windows node? The number of pods show as 0 in the output you posted.

**Comment by nreddipalle** [comment]
Hello @aramase that is correct.. no pods are running on windows node.. as I ran the install setup against default namespace (default namespace being in linux node), I do not see any pod running on windows node as part of install.. do I need to configure something different during install other than running as below: 
`helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set windows.enabled=true --set secrets-store-csi-driver.windows.enabled=true --generate-name`

**Comment by aramase** [comment]
@nreddipalle Try describing the daemonset for windows nodes. This could be because there are taints configured on the windows nodes? If you've configured taints, then you would need to add tolerations for those taints in the daemonsets so Kubernetes can schedule and run the driver and provider pods on those nodes. The tolerations can be configured using helm: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration for both driver and provider.

**Comment by nreddipalle** [comment]
@aramase My windows node is a spot node.. which has a taint called 
`Taints: kubernetes.azure.com/scalesetpriority=spot:NoSchedule`

So re-ran the helm install command with the below values 

`helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set windows.enabled=true,secrets-store-csi-driver.windows.enabled=true,windows.tolerations[0].key="kubernetes.io/os",windows.tolerations[0].value="windows", windows.tolerations[0].effect="NoSchedule",windows.tolerations[0].operator="equal",windows.tolerations[1].key="kubernetes.azure.com/scalesetpriority",windows.tolerations[1].value="spot", windows.tolerations[1].effect="NoSchedule",windows.tolerations[1].operator="equal" --generate-name` but still no pods on windows nodes 

![image](https://user-images.githubusercontent.com/28302399/102138999-3e059080-3e2b-11eb-9e18-99d4184be7d6.png)

Am i still missing something?

**Comment by aramase** [comment]
I just tried the same thing by tainting my linux node and can confirm it works:

```
➜ helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set secrets-store-csi-driver.enableSecretRotation=true --set secrets-store-csi-driver.rotationPollInterval=10s --set windows.enabled=true --set secrets-store-csi-driver.windows.enabled=true --set logVerbosity=2 --set secrets-store-csi-driver.logVerbosity=2 --set linux.tolerations\[0\].key="kubernetes.azure.com/scalesetpriority",linux.tolerations\[0\].value="spot",linux.tolerations\[0\].effect="NoSchedule",linux.tolerations\[0\].operator="Equal"
```

Please check if there are more taints on the windows nodes and if the taints have been added correctly to the *Daemonset* manifest for the driver and the provider.

**Comment by nreddipalle** [comment]
This is the output for my windows node (describe command)
```
Name:               aksdvsp0100003c
Roles:              agent
Labels:             agentpool=dvsp01
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2ds_v4
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=eastus2
                    failure-domain.beta.kubernetes.io/zone=eastus2-1
                    kubernetes.azure.com/cluster=MC_azure-devops_senseiazuredevopsaks0_eastus2
                    kubernetes.azure.com/node-image-version=AKSWindows-2019-17763.1554.201021
                    kubernetes.azure.com/role=agent
                    kubernetes.azure.com/scalesetpriority=spot
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=aksdvsp0100003c
                    kubernetes.io/os=windows
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    node.kubernetes.io/instance-type=Standard_D2ds_v4
                    node.kubernetes.io/windows-build=10.0.17763
                    storageprofile=managed
                    storagetier=Premium_LRS
                    topology.kubernetes.io/region=eastus2
                    topology.kubernetes.io/zone=eastus2-1
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 13 Dec 2020 06:04:05 -0500
Taints:             kubernetes.azure.com/scalesetpriority=spot:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 14 Dec 2020 18:53:03 -0500   Sun, 13 Dec 2020 06:04:05 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 14 Dec 2020 18:53:03 -0500   Sun, 13 Dec 2020 06:04:05 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 14 Dec 2020 18:53:03 -0500   Sun, 13 Dec 2020 06:04:05 -0500   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready
```

**Comment by nreddipalle** [comment]
@aramase I think it is working now but still not seeing one windows daemon set getting deployed onto nodes..

![image](https://user-images.githubusercontent.com/28302399/102169956-4f698f80-3e61-11eb-99f4-3ba2be305113.png)

**Comment by nreddipalle** [comment]
@aramase Ok. I think i figured it out now.. 
`helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set 'windows.enabled=true,secrets-store-csi-driver.windows.enabled=true,windows.tolerations[0].key=kubernetes.io/os,windows.tolerations[0].value=windows, windows.tolerations[0].effect=NoSchedule,windows.tolerations[0].operator=Equal,windows.tolerations[1].key=kubernetes.azure.com/scalesetpriority,windows.tolerations[1].value=spot, windows.tolerations[1].effect=NoSchedule,windows.tolerations[1].operator=Equal,secrets-store-csi-driver.windows.tolerations[0].key=kubernetes.io/os,secrets-store-csi-driver.windows.tolerations[0].value=windows, secrets-store-csi-driver.windows.tolerations[0].effect=NoSchedule,secrets-store-csi-driver.windows.tolerations[0].operator=Equal,secrets-store-csi-driver.windows.tolerations[1].key=kubernetes.azure.com/scalesetpriority,secrets-store-csi-driver.windows.tolerations[1].value=spot, secrets-store-csi-driver.windows.tolerations[1].effect=NoSchedule,secrets-store-csi-driver.windows.tolerations[1].operator=Equal' --generate-name --namespace csi-driver`
