### ISSUE TITLE
logFormatJSON only works for some containers

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#337]
**What steps did you take and what happened:**
I have `csi-secrets-store-provider-azure` chart version `0.0.14` with `logFormatJSON: true`.

I can only see the `key-vault-csi-csi-secrets-store-provider-azure` Pod using json logging.

All containers in `key-vault-csi-secrets-store-csi-driver` still using standard logging.

**What did you expect to happen:**
JSON logging used by all containers

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `helm.sh/chart: secrets-store-csi-driver-0.0.17`
- Azure Key Vault provider version: (use the image tag): `helm.sh/chart: csi-secrets-store-provider-azure-0.0.14`
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): `v1.19.3`  all nodes
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@dkirrane You can set the `logFormatJSON` for the provider pods, and `secrets-store` container in the driver using `secrets-store-csi-driver.logFormatJSON`. The other 2 containers in the driver pods are provided by the Kubernetes CSI community and is not something we own.

**Comment by dkirrane** [comment]
@aramase okay thanks I'll give that a go
