### ISSUE TITLE
Support logFormatJSON for node-driver-registrar & liveness-probe

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#338]
**Describe the solution you'd like**
Currently `secret-store` & `provider-aure-installer` containers support JSON logging format.

This is a feature request to add the same for the other containers in the `key-vault-csi-secrets-store-csi-driver` Pod.
- `node-driver-registrar`
- `liveness-probe`

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `helm.sh/chart: secrets-store-csi-driver-0.0.17`
- Azure Key Vault provider version: (use the image tag): `helm.sh/chart: csi-secrets-store-provider-azure-0.0.14`
- Kubernetes version: (use `kubectl version`): `v1.19.3`
- Cluster type: (e.g. AKS, aks-engine, etc): `AKS`

**Comment by aramase** [comment]
@dkirrane Thank you for opening the issue. These 2 components are owned by the kubernetes-csi community. I've opened PR to add support for it in both the components:

- https://github.com/kubernetes-csi/node-driver-registrar/pull/129
- https://github.com/kubernetes-csi/livenessprobe/pull/98

**Comment by aramase** [comment]
I'm closing this issue because it's not owned by us. You can follow the issues: https://github.com/kubernetes-csi/livenessprobe/issues/97 and https://github.com/kubernetes-csi/node-driver-registrar/issues/128 in addition to the PRs to track progress of this support.
