### ISSUE TITLE
Error creating Volume Mount using Azure AD Pod Identity

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/secrets-store-csi-driver-provider-azure#34]
After following the setup instructions for Azure AD pod identity I was able to confirm the pod is running with the correct identity by inspecting the mic logs.

After setting up the Azure provider, I was unable to attach a volume mount and am receiving the following error:

> MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret time="2020-03-23T23:33:37Z" level=fatal msg="[error] : failed to get vault: failed to get management token: nmi response failed with status code: 403"

I have also confirmed that the User Assigned Managed Identity has Read Access to the secret I'm trying to mount.

**Comment by aramase** [comment]
@KSchlobohm Can you please provide the following information -

1. What version of pod-identity are you using?
2. Output for `kubectl get azureassignedidentities --all-namespaces -o yaml`. Please make sure to REDACT all sensitive information.
3. Can you check the logs for NMI pod running on the same node as the application pod? The error logs in NMI should provide more detail as to why NMI is unable to fetch a token.

**Comment by KSchlobohm** [comment]
I used the [AAD Pod setup instructions](https://github.com/Azure/aad-pod-identity) for [v1](https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml)

Found an error in the NMI logs:
> msg="failed to get service principal token for pod:default/azure-vote-front-9b67ff6b-2dspv, adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" req.method=GET req.path=/host/token/ req.remote=127.0.0.1

[azureassignedidentities.zip](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/4375809/azureassignedidentities.zip)

**Comment by aramase** [comment]
@KSchlobohm From the files you provided, looks like MIC was successfully able to assign the identity to the underlying vmss (there is an AzureAssignedIdentity in `Assigned` state for pod `azure-vote-front-9b67ff6b-2dspv`). Can you confirm if the identity does in fact exist on the underlying node? 

```
az vmss identity show -g <resource group> --name <vmss name>
```

The above command will provide a list of identities currently on the node. If the identity does exist and you still see the identity not found error, then I can request the appropriate team internally to check why we are getting an `identity not found` error when NMI tries to fetch the token on behalf of the application.

**Comment by KSchlobohm** [comment]
Here's the result:
{
  "principalId": null,
  "tenantId": null,
  "type": "UserAssigned",
  "userAssignedIdentities": {
    "/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourcegroups/demo-k8s-keyvault-podidentity/providers/Microsoft.ManagedIdentity/userAssignedIdentities/voting-app": {
      "clientId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
      "principalId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
    }
  }
}

**Comment by aramase** [comment]
@KSchlobohm Can you share the NMI and MIC logs? From the output you posted above looks like the identity does exist on the node. Once you share the logs, I can go over it to ensure no pod-identity errors and then request assistance from the internal team for IMDS that's currently returning the `identity not found` error. Also, few other questions -

1. When was this identity created?
2. Does the User Managed Identity object (`/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourcegroups/demo-k8s-keyvault-podidentity/providers/Microsoft.ManagedIdentity/userAssignedIdentities/voting-app`) still exist in Azure?
3. Other applications using the identity see the same error?

**Comment by KSchlobohm** [comment]
1. The identity was created yesterday.
2. The identity still exists
3. There are no other apps in the cluster.

**Comment by aramase** [comment]
@KSchlobohm I think the cluster with the issue has been deleted. Please feel free to reopen if you still have any issues getting started.
