### ISSUE TITLE
Write certificate content as true pfx file instead of base64 encoded string

### ISSUE THREAD

**Issue by djj0809** [Azure/secrets-store-csi-driver-provider-azure#349]
**Describe the solution you'd like**

Currently when we choose to write content of a certificate as pfx format to a file, it is base64 encoded. This is not convenient as many programs expect a pfx file format instead of a base64 encoded string.

**Comment by aramase** [comment]
@djj0809 You can use the `objectEncoding: base64` to have the certificate content written in base64 decoded pfx format: https://github.com/Azure/secrets-store-csi-driver-provider-azure#create-your-own-secretproviderclass-object.

**Comment by djj0809** [comment]
@aramase Thanks, it works. I saw that configuration but not sure what it is used for.
