### ISSUE TITLE
How do I delete an installed provider?

### ISSUE THREAD

**Issue by Riddle4045** [Azure/secrets-store-csi-driver-provider-azure#353]
**What steps did you take and what happened:**
I installed the csi azure provider and now I want to uninstall/delete it, how do I go about doing it?
```
helm delete <release-name>
kubectl delete pods 
```
did not work

**What did you expect to happen:**
I expect the csi-provider to stop running on my aks cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: secrets-store.csi.x-k8s.io/v1alpha1
- Azure Key Vault provider version: (use the image tag):csi-secrets-store-provider-azure
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cluster type: (e.g. AKS, aks-engine, etc): aks

**Comment by Riddle4045** [comment]
it runs a DaemonSet and can be delete using `kubectl delete daemonset <name>`

**Comment by dermoritz** [comment]
just with ` kubectl.exe get secretproviderclasses.secrets-store.csi.x-k8s.io` you get the name
and then 
`kubectl.exe delete secretproviderclasses.secrets-store.csi.x-k8s.io <name>`
