### ISSUE TITLE
azure-csi-secrets-csi-secrets-store-provider and secrets-store containers does not apply logVerbosity levels

### ISSUE THREAD

**Issue by jose-antony-by** [Azure/secrets-store-csi-driver-provider-azure#358]
**What steps did you take and what happened:**
When installing  Secrets Store CSI driver and the Azure Key Vault provider using Helm and `logVerbosity` and `secrets-store-csi-driver.logVerbosity` set to 2 for `ERROR`, the logs produced by the containers does not reflect the correct verbosity levels. ( looks like the -v argument gets passed down to the containers correctly)

```
Image
mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.11
Arguments
--endpoint=unix:///provider/azure.sock
-v=2
```

Example log from the container:
```
I0106 15:13:51.221481       1 provider.go:283] "successfully wrote file" file="vault-secret" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.221523       1 provider.go:250] "fetching object from key vault" objectName="vault-secret" objectType="secret" keyvault="vault-name" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.221536       1 provider.go:146] vaultName: vault-name
I0106 15:13:51.221699       1 auth.go:148] "using service principal to retrieve access token" clientID="##### REDACTED #####" secret="##### REDACTED #####" pod="default/defualt-pod-59bd77bc97-bf2jn"
I0106 15:13:51.309916       1 provider.go:283] "successfully wrote file" file="vault-secret" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.310180       1 grpc.go:31] GRPC response: {"object_version":[{"id":"secret
```

Same issue also happens in secrets-store container.

**What did you expect to happen:**
Only error level logs are logged when `logVerbosity` is set to 2.

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: 0.0.11
- Azure Key Vault provider version: 0.0.18
- Kubernetes version: 1.17.11
- Cluster type: AKS

**Comment by aramase** [comment]
@jose-antony-by `logVerbosity=2` doesn't indicate error logs. The driver and provider use klog logging framework. Certain debug logs are marked with higher log levels. In case of debugging, if you bump the log verbosity, then logs marked at the level will be included in the logs. 

For instance:
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/99ffa929be397384d33237a393e6484305eb35c0/pkg/provider/provider.go#L151

This log will only be printed when the logVerbosity >= 2. This flag is for v style logging.

**Comment by jose-antony-by** [comment]
@aramase  thanks for the quick response. 
Is there any other to control the verbosity of these 2 containers? We are polling every 2 minutes and since we ship all our container logs to log workspace it does seem to add up to a lot of entries over time.

**Comment by aramase** [comment]
@jose-antony-by Which containers are you referring to? The default log verbosity is 0 which means only essential logs are logged by the containers. The logVerbosity is set to a higher level only for debug. 

The logVerbosity can be configured for `secrets-store` container in the driver and `provider-azure-installer` container in the provider pods. The other 2 containers in the driver pod are owned by Kubernetes CSI community. I've a PR to configure to log verbosity in those components as well. Hope this answers your question.

**Comment by jose-antony-by** [comment]
@aramase  The biggest concern for me was "mcr.microsoft.com/oss/azure/secrets-store/provider-azure". This one does seem to produce a lot of logs on every polling interval per secret.

```
I0106 15:13:51.221481       1 provider.go:283] "successfully wrote file" file="vault-secret" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.221523       1 provider.go:250] "fetching object from key vault" objectName="vault-secret" objectType="secret" keyvault="vault-name" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.221536       1 provider.go:146] vaultName: vault-name
I0106 15:13:51.221699       1 auth.go:148] "using service principal to retrieve access token" clientID="##### REDACTED #####" secret="##### REDACTED #####" pod="default/defualt-pod-59bd77bc97-bf2jn"
I0106 15:13:51.309916       1 provider.go:283] "successfully wrote file" file="vault-secret" pod="default/example-pod-59bd77bc97-bf2jn"
I0106 15:13:51.310180       1 grpc.go:31] GRPC response: {"object_version":[{"id":"secret
```

What that be covered by the PR to the CSI community?

**Comment by aramase** [comment]
@jose-antony-by Those are default logs we log to show current state of the world when mount requests come in. Looks like you have the log verbosity set to 2. You can set it to 0 to just get the bare minimum logs. At level 0, the provider only logs the requests coming in, auth method used and errors if any. The same logs apply for rotation requests as well. 

The PR for CSI community is for `node-driver-registrar` and `liveness-probe` containers in the driver pods/

**Comment by dilip-panwar-by** [comment]
@aramase  We just want to enable error logs. When we set polling to 2 mins, it is considered as a **request** and we get logs in bulk(as shared by @jose-antony-by) in every 2 mins. Can we disable/suppress these logs?

**Comment by aramase** [comment]
@dilip-panwar-by klog has `stderrthreshold` flag which can be used to configure the log threshold, but `ERROR` is after `INFO` which means it'll include both the logs. The poll at 2min is in fact a regular grpc request because it checks if new contents exist in key vault and updates that in the mount if required.

**Comment by dilip-panwar-by** [comment]
@aramase Thanks for sharing more details. It sounds to me like there is no way of suppressing regular grpc request logs right?

**Comment by aramase** [comment]
@dilip-panwar-by The default log level is 0 which doesn't print grpc request or response in the logs. This is the 3 lines of logs that can get printed for each object:

```log
I0120 19:34:25.112668       1 provider.go:255] "fetching object from key vault" objectName="ecccert1" objectType="secret" keyvault="kindkv" pod="default/nginx-69b6cb6668-xgl5g"
I0120 19:34:25.113976       1 auth.go:148] "using service principal to retrieve access token" clientID="4648##### REDACTED #####abcd" secret="kMzY##### REDACTED #####L44J" pod="default/nginx-69b6cb6668-xgl5g"
I0120 19:34:25.670055       1 provider.go:288] "successfully wrote file" file="ecccert1" pod="default/nginx-69b6cb6668-xgl5g"
```

So keeping the verbosity will provide the bare minimum. Increasing the log verbosity to a higher level will add additional debug logging as well.

**Comment by aramase** [comment]
Closing this issue now. Please feel free to reopen if you've any questions.
