### ISSUE TITLE
Provide a discoverable link to the docs

### ISSUE THREAD

**Issue by dhirschfeld** [Azure/secrets-store-csi-driver-provider-azure#361]
I only found the doc url by luck/chance!
* https://azure.github.io/secrets-store-csi-driver-provider-azure/

Did I miss some obvious link to the docs?!? If not, it might be useful to provide a prominent link in the README.md or to provide a *website* entry in the about config:

----

![image](https://user-images.githubusercontent.com/881019/103847729-a541f800-50ec-11eb-8ff2-f7f0a5b0f64a.png)

----

![image](https://user-images.githubusercontent.com/881019/103847817-bf7bd600-50ec-11eb-966e-6a8f92a26769.png)

**Comment by aramase** [comment]
@dhirschfeld Thank you for opening the issue. The docs website still requires few changes which are currently in progress. Once that's complete, we'll be updating the main README to stub out the content and point to the new docs URL. I'll be adding the website to the repo details once that's complete.
