### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AkshayaAnil** [Azure/secrets-store-csi-driver-provider-azure#366]
Hey Aramase, I am exploring this project for a use case to mount azure kv secrets to pods, I got a question though, when the secrets are mounted as volume using the csi driver, is it going to live on the disk(of the node where pod is running) until pod is terminated ? This is an important question for my implementation. kindly let me your comment.

**Comment by aramase** [comment]
@AkshayaAnil That is right. The content is written to a target path on the node and then mounted into the pod as `tmpfs`. When the pod is deleted, the corresponding target path is cleaned up and deleted.

**Comment by aramase** [comment]
Just to clarify:

The secrets aren't persisted to the disk. The mount is done via tmpfs as you can see here:
```
root@kind-control-plane:~# mount | grep secrets-store-inlinetmpfs on /var/lib/kubelet/pods/f826640c-b1d5-473b-b157-14936a330925/volumes/kubernetes.io~csi/secrets-store-inline/mount type tmpfs (rw,relatime)
```

**Comment by aramase** [comment]
Closing this with the docs update in the driver. Please feel free to reopen if you've any questions.
