### ISSUE TITLE
Can the Secrets Store CSI driver be used to access the Azure Key Vault REST API?

### ISSUE THREAD

**Issue by joelnotified** [Azure/secrets-store-csi-driver-provider-azure#371]
Hi, 
I have a legacy application that pulls secrets from an Azure Key Vault by making HTTP requests to its API (using the URL `https://<keyvaultname>.vault.azure.net`). The application is deployed in Azure and uses managed identities to do this. We're moving the application into Kubernetes, and as a first step I would like to change the current implementation as little as possible. 

So my question is this: Can the Secrets Store CSI driver be used to access the Azure Key Vault REST API  via its url? Or is it only used to mount secrets into pods in different ways?

**Comment by aramase** [comment]
@joelnotified Thank you for reaching out.

The Secrets Store CSI Driver makes the HTTP requests to Keyvault, fetches the contents and writes to the pod mount. This means the application can just read the secret from the filesystem or if it relies on env variables, then also do so by leveraging the Sync as Kubernetes secrets and then using that as env variable. 

However if the application is already making API requests to Keyvault, then the Secrets Store CSI Driver will not be required.

**Comment by joelnotified** [comment]
@aramase Thanks for the reply! 

Ok, I think I'm starting to understand how it works. I see now that Secrets Store CSI Driver uses AAD Pod Identity. And it looks like having AAD Pod Identity setup is what's required to access the keyvault from within the cluster.

Thanks for clarifying! 👍
