### ISSUE TITLE
Unable to mount secret from Keyvault on pod using managed identity

### ISSUE THREAD

**Issue by ShubhasisMathur** [Azure/secrets-store-csi-driver-provider-azure#382]
FOllowed the doc: 
https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                   # [REQUIRED] Set to "true" if using managed identities
    useVMManagedIdentity: "false"             # [OPTIONAL] if not provided, will default to "false"
    # userAssignedIdentityID: "xxx"       # [REQUIRED]  If you're using a user-assigned identity as the VM's managed identity, specify theidentity's client id. If the value is empty, it defaults to use the system-assigned identity on the VM

    keyvaultName: "Contoso-Vaultmintoo"          # [REQUIRED] the name of the key vault
                                              #     az keyvault show --name contosoKeyVault5
                                              #     the preceding command will display the key vault metadata, which includes the subscription ID, resource group name, keyvault
    cloudName: ""                                # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExamplePassword                 # [REQUIRED] object name
                                              #     az keyvault secret list --vault-name "contosoKeyVault5"
                                              #     the above command will display a list of secret names from your key vault
          objectType: secret                  # [REQUIRED] object types: secret, key, or cert
          objectVersion: ""                   # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: "myrg"     # [REQUIRED] the resource group name of the key vault
    subscriptionId: "xxxx "         # [REQUIRED] the subscription ID of the key vault
    tenantId: "xxxx"                      # [REQUIRED] the tenant ID of the key vault
    
Here is the binding yaml:

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: "myidentityshubh"               # The name of your Azure identity
spec:
    type: 0                                 # Set type: 0 for managed service identity
    resourceID: /subscriptions/xx/resourcegroups/myrg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myidentityshubh
    clientID: "xx"     # The clientId of the Azure AD identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "myidentityshubh"      # The name of your Azure identity
    selector: azure-pod-identity-binding-selector

POd.yaml:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store-inline
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector
spec:
        #nodeSelector:
        #agentpool: npwin
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname

Pod is not coming to running state:, tried creating for both windows and linux nodes . FOllowed the steps mentioned in https://github.com/MicrosoftDocs/azure-docs/issues/67311

Error:
Warning  FailedMount  3s (x5 over 16s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp [::1]:2579: connectex: No connection could be made because the target machine actively refused it.

**Comment by ShubhasisMathur** [comment]
Label: general/subsvc
key-vault/svc
product-question
triaged

**Comment by ShubhasisMathur** [comment]
@aramase please have a look

**Comment by aramase** [comment]
@ShubhasisMathur 

1. Pod identity isn't supported for windows. Please refer to [docs](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/) for supported access modes.
2. What is the error with the Linux pod? If it's the same error, then it means the pod identity component hasn't been deployed to the cluster. 

This is our [troubleshooting guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/).

**Comment by aramase** [comment]
@ShubhasisMathur Any updates on this?

**Comment by ShubhasisMathur** [comment]
Hello @aramase  I am not sure where is the problem. I have re created the key vault and re created the managed identities and tried to refer the sceret from a linux node but I am getting this error:

Warning  FailedMount  2s (x6 over 18s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to create auth config, error:failed to get credentials, nodePublishSecretRef secret is not set

Although I need to set up on a windows node but right now even the linux node has the mount issue

**Comment by aramase** [comment]
@ShubhasisMathur As the error suggest, you're missing `nodePublishSecretRef` in the pod yaml.

If you're using service principal, then you need to set `nodePublishSecretRef` with the aad client id and client secret. You can find the required steps and example yamls for using service principal access mode: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/service-principal-mode/

**Comment by ShubhasisMathur** [comment]
Thanks Anish and that solved it. I am able to create pod on both windows and Linux Node after creating the secret.

Feedback: https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes, we need to update the doc with the right steps. Cx's face lots of issue following the doc. We need to refine the doc with steps.

**Comment by ShubhasisMathur** [comment]
Please mark the case as closed. Thanks for your help!

**Comment by aramase** [comment]
Thank you for the feedback @ShubhasisMathur. I've a PR to update the docs. I'll also work with the docs team to get the guide updated.
