### ISSUE TITLE
Quertion: Secrets update

### ISSUE THREAD

**Issue by tasb** [Azure/secrets-store-csi-driver-provider-azure#386]
Hi!

If the secret is updated on AKV the pods needs to be restarted t have that update or there is any automatic way to do it?

Thanks!

**Comment by aramase** [comment]
@tasb Thank you for opening an issue.

To enable update of the created Kubernetes secret and the mounted contents, we have introduced secret rotation alpha feature in Secrets Store CSI Driver v0.0.16.

Docs on how to enable secret rotation -
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/enable-auto-rotation-secrets/

**Comment by aramase** [comment]
@tasb Did you get a chance to look at the docs and try out the feature?

**Comment by tasb** [comment]
Hi @aramase, thanks for your reply. Didn't got the chance yet. 
I'll try during this week and give you some feedback.

Thanks!

**Comment by aramase** [comment]
@tasb Did you get a chance to try it out? Can we close this issue now?

**Comment by aramase** [comment]
Closing this issue now. Please feel free to open a new issue when you get a chance to try out and run into any issues.
