### ISSUE TITLE
Standard Walkthrough

### ISSUE THREAD

**Issue by snobu** [Azure/secrets-store-csi-driver-provider-azure#389]
This page -
https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/#5-deploy-secretproviderclass

references `userAssignedIdentityID: ""` which isn't clear what it is. It's not the resource id (which would be my first choice just by reading the key name) but the Client ID.

You should add a comment above it to clearly state that's the CLIENT ID of the user identity, so just the GUID value.

**Comment by aramase** [comment]
@snobu Thank you for opening the issue.

The standard walkthrough uses the service principal auth method. For more details on the configuration parameters and values, you can see https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/#create-your-own-secretproviderclass-object which defines the expected value for each field.

Also, if you refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/user-assigned-msi-mode/, we have an example for the SecretProviderClass to use with user-assigned managed identity.
