### ISSUE TITLE
liveness-probe is logging to stderr

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#398]
**What steps did you take and what happened:**

We ship logs to DataDog. All the the liveness-probe logs appear as errors.
On closer inspection I found the csi-secrets-store-provider-azure-0.0.15 `liveness-probe` container is always logging to `stderr`

I ssh to AKS node and viewed logs on disk.
They all looks like info logs but have `"stream":"stderr"`
```
cd /var/log/pods/key-vault-csi_key-vault-csi-secrets-store-csi-driver-xxxx/liveness-probe
sudo head -10
{"log":"I0211 13:05:39.065849       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:05:39.066030737Z"}
{"log":"I0211 13:05:39.066315       1 main.go:125] calling CSI driver to discover driver name\n","stream":"stderr","time":"2021-02-11T13:05:39.066428237Z"}
{"log":"I0211 13:05:39.067196       1 main.go:131] CSI driver name: \"secrets-store.csi.k8s.io\"\n","stream":"stderr","time":"2021-02-11T13:05:39.067369137Z"}
{"log":"W0211 13:05:39.067220       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.\n","stream":"stderr","time":"2021-02-11T13:05:39.067383237Z"}{"log":"I0211 13:05:39.067229       1 main.go:142] Serving requests to /healthz on: 0.0.0.0:9808\n","stream":"stderr","time":"2021-02-11T13:05:39.067387437Z"}
{"log":"I0211 13:06:16.696788       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:06:16.696974137Z"}
{"log":"I0211 13:06:31.696259       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:06:31.696397737Z"}
{"log":"I0211 13:06:46.696679       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:06:46.696858937Z"}
{"log":"I0211 13:07:01.696538       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:07:01.696665037Z"}
{"log":"I0211 13:07:16.696668       1 connection.go:153] Connecting to unix:///csi/csi.sock\n","stream":"stderr","time":"2021-02-11T13:07:16.696831937Z"}
```

**What did you expect to happen:**
Logs at INFO level sent to stdout

**Anything else you would like to add:**
From chart:
```
    livenessProbeImage:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.1.0
```

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `"image":"mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.18`
- Azure Key Vault provider version: (use the image tag): `0.0.15`
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
```
NAME                             STATUS   ROLES   AGE     VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-kvtest-91575272-vmss000000   Ready    agent   3h17m   v1.18.10   10.240.1.4    <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS cluster on version `1.18.10`

**Comment by aramase** [comment]
@dkirrane The `liveness-probe` component is owned by the Kubernetes CSI community: https://github.com/kubernetes-csi/livenessprobe

They use the `klog` log framework which is used in all Kubernetes components. All the logs by default are written to `stderr`.

**Comment by dkirrane** [comment]
Thanks I've raised it there https://github.com/kubernetes-csi/livenessprobe/issues/105

**Comment by aramase** [comment]
Thanks @dkirrane. I'll close this issue so we can track this in one location. We can follow up with any changes that are recommended on the issue.
