### ISSUE TITLE
Unable to read secrets from "/mnt/secrets-store" in spring boot app running on AKS

### ISSUE THREAD

**Issue by vijaythotadappa** [Azure/secrets-store-csi-driver-provider-azure#413]
**Describe the solution you'd like**
We used the steps on below link to configure SecretProviderClass with CSI, and we were able to mount secrets ("/mnt/secrets-store") from Key vault into application container. 

https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes

Now we are stuck while trying to read secrets from "/mnt/secrets-store", we are using below dependency.

runtimeOnly group: 'com.microsoft.azure', name: 'azure-keyvault-secrets-spring-boot-starter', version: '2.3.5'

Could you please suggest any solution to our problem, thanks.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.2.0
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.13
- Kubernetes version: (use `kubectl version`):  v1.19.7
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@vijaythotadappa Could you elaborate more on the issue? 

The file mount is read only and should be generally consumable by the application. What is the issue with reading the secrets?

**Comment by vijaythotadappa** [comment]
We are unable to read this secret from java spring boot app. I have added the variables in application.properties as below, and added dependency for azure keyvault spring boot starter. 
Application is failing to start with error  “ Could not resolve placeholder ' KAFKA-URL' in value "${KAFKA-URL}"”

application.properties file:

spring.kafka.connectionString= "${KAFKA-URL}"
spring.kafka.username= "${USER-NAME}"
spring.kafka.password= "${PASSWORD }"

Dependency added:
runtimeOnly group: 'com.microsoft.azure', name: 'azure-keyvault-secrets-spring-boot-starter', version: '2.3.5'

Not sure what I am missing, please let me know if you are available for a call, thanks.

**Comment by aramase** [comment]
The CSI driver writes the individual objects to the files in the mount. So if you're reading each individual file in your application and consuming it then that would work. The file you posted above is just assuming static values which will not be replaced/needs to be set by your app.

There is an issue open for custom file formats: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/142

**Comment by aramase** [comment]
Closing this issue as the CSI driver and AKV provider is writing the file to the mount as expected. Feel free to open a new if you have any questions.
