### ISSUE TITLE
Add possibility to use cluster managed identity without explicitly specifying it

### ISSUE THREAD

**Issue by ilya-git** [Azure/secrets-store-csi-driver-provider-azure#414]
**Describe the solution you'd like**
It is not possible to use system assigned managed identities of VM without extra configuration, it would be nice to have a flag, e.g.:

   `useClusterKubeletManagedIdentity: "true"`

that will allow usage of kubelet identity from AKS (`identityProfile.kubeletidentity.clientId`). It is possible now already, but one has to specify the id in each yaml manifest (`userAssignedIdentityID`).

**Anything else you would like to add:**

As far as I know AKS uses a built-in `SystemAssigned` principal (`identity.principalId`) as well with the same name as the AKS itself in addition to the kubelet managed identity. It's perhaps a good idea to allow that one as an additional flag, e.g.:

   `useClusterSystemAssignedIdentity: "true"`

P.S. It's a bit confusing now that the `System-assigned Managed Identity` model is actually using the vms system assigned managed identity and not the one from the cluster.

**Comment by aramase** [comment]
@ilya-git The AKS kubelet identity is a user-assigned managed identity. There are multiple user-assigned managed identities in the cluster and the clientID for the kubelet identity needs to be specified so the AKV provider can use the correct one.

You can confirm there is no system assigned identity on the vm/vmss in aks by running:
```
➜ az vmss identity show -g MC_csiloadtest_c00_centralus -n aks-nodepool1-13437782-vmss
{
  "principalId": null,
  "tenantId": null,
  "type": "UserAssigned",
  "userAssignedIdentities": {
    "/subscriptions/d4f20976-17ab-4f88-a99b-a64552938228/resourceGroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/c00-agentpool": {
      "clientId": "<client id>",
      "principalId": "<principal id>"
    }
  }
}
```

As you can see above, the type is only `UserAssigned`. If you want to create a system assigned identity and use it on AKS, then you can follow the docs: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/system-assigned-msi-mode/.

**Comment by ilya-git** [comment]
Yes, I thought you would not be able to find the identity among all the assigned ones. There is though a very strange confusion in the name "user-assigned managed identity" as the kubelet identity being user assigned is actually not assigned by the user (not by default anyway). It's Azure that creates this identity and assigns it, though it technically is user assigned :)

What about the service principal of the cluster, that one is SystemAssigned and is only one, but perhaps it's not available on the node?

**Comment by aramase** [comment]
> Yes, I thought you would not be able to find the identity among all the assigned ones. There is though a very strange confusion in the name "user-assigned managed identity" as the kubelet identity being user assigned is actually not assigned by the user (not by default anyway). It's Azure that creates this identity and assigns it, though it technically is user assigned :)

User-assigned managed identity gives the flexibility of having individual identity per component. System-assigned managed identity is one per node and it could have permissions for higher scope. Although, for system-assigned managed identity that you manually create, the permissions can be scoped only to keyvault. 

> What about the service principal of the cluster, that one is SystemAssigned and is only one, but perhaps it's not available on the node?

That's right. The `SystemAssigned` is not available on the node. If you still want to use a system-assgined managed identity, you can manually assign it to the VMSS and then use that with the CSI driver.

**Comment by ilya-git** [comment]
Thanks for the details :)

**Comment by aramase** [comment]
Sure thing! Anything else I can help answer in this issue?

**Comment by ilya-git** [comment]
The answer was very detailed thank you :) I am not sure if this is related to the issue, but I was wondering what gives the provider access to assume any identity? I suppose any random pod cannot do the same and impersonate the identity? It's probably some setting in the manifest that allows access to the node resources?

**Comment by aramase** [comment]
The providers uses only the user assigned identity specified in `userAssignedIdentityID`. If not provided, then the provider requests for a token using the system-assigned managed identity. 

User-assigned and system-assigned managed identities are assigned to the underlying VMSS. This means any pod scheduled on the node can access the identity. To make this more fine grained and configure which pods can access which identities, we have the [AAD Pod Identity](https://github.com/Azure/aad-pod-identity) project. The docs are here: https://azure.github.io/aad-pod-identity/

The AKV provider for CSI driver can work with pod identity. Here is the doc for pod identity mode with the provider: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/

**Comment by ilya-git** [comment]
Thanks a lot for your explanation, I'll close the ticket as it seems not feasible to add the feature that I was asking for
