### ISSUE TITLE
Custom annotation to pods 

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/secrets-store-csi-driver-provider-azure#427]
**Describe the solution you'd like**

I wish I could add annotations to the provider `daemoset` metadata.
The chart provides the possibility only to add labels and not annotations.

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml#L15-L19

**Anything else you would like to add:**

Please? 🙏🏻

**Comment by pierluigilenoci** [comment]
And nothing ... I'm blind. I found how to do it. Sorry.

**Comment by pierluigilenoci** [comment]
And I was still wrong. It can only be done on the driver. 
@aramase can you also do it for the provider? 
It should be a trivial change.

**Comment by aramase** [comment]
@pierluigilenoci We can add it to the next helm chart release. Would you be interested in opening a PR?

**Comment by pierluigilenoci** [comment]
@aramase done https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/442
