### ISSUE TITLE
Failed to reconcile spc on secret rotation, secret not rotated

### ISSUE THREAD

**Issue by fraserdarwent** [Azure/secrets-store-csi-driver-provider-azure#434]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Create a secret in KeyVault. Mount it into a pod volume using CSI Driver Provider Azure. Rotate the secret in KeyVault.
Secret is not rotated in the pod. 

CSI Driver logs:
```
time="2021-03-11T12:38:16Z" level=debug msg="rotation reconciler started for istio-egressgateway-5f9854ddf9-85bdf-istio-system-certificates"
time="2021-03-11T12:38:16Z" level=error msg="[rotation] failed to reconcile spc istio-system/certificates for pod istio-system/istio-egressgateway-5f9854ddf9-85bdf, err: failed to rotate objects for pod istio-system/istio-egressgateway-5f9854ddf9-85bdf, err: rpc error: code = Unknown desc = failed to unmarshal secrets, error: unexpected end of JSON input"
time="2021-03-11T12:38:16Z" level=debug msg="rotation reconciler completed for istio-egressgateway-5f9854ddf9-85bdf-istio-system-certificates"
```
Azure Provider logs:
```
E0311 12:47:46.836105       1 server.go:38] failed to unmarshal secrets, error: unexpected end of JSON input
E0311 12:47:46.836131       1 grpc.go:29] GRPC error: failed to unmarshal secrets, error: unexpected end of JSON input
```

**What did you expect to happen:**
The secret to be rotated on the pod volume.

**Anything else you would like to add:**
Helm chart version `0.12`

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): `v0.0.15`
- Azure Key Vault provider version: (use the image tag): `0.0.9`
- Kubernetes version: `v1.18.10`
- Cluster type: AKS

**Comment by fraserdarwent** [comment]
This appears to be because the `0.12` Helm chart sets the version of the Secrets Store CSI Driver to `0.0.15` which is not compatible with rotation? (Have noticed `0.0.16` being referenced as the minimum required version for rotation), despite rotation being listed as an option in the Helm values (which lead me to believe it should work).

Setting the version of the Secrets Store CSI Driver to `0.0.16` makes it work as expected.

**Comment by aramase** [comment]
@fraserdarwent Rotation was supported since `v0.0.15` but there were bug fixes that were added later. It's always recommended to use the latest release as it contains bug fixes and improvements. For more details on the changes that go into each release, you can check the changelog: https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases
