### ISSUE TITLE
Allow own release name definition to support Terraform deployment

### ISSUE THREAD

**Issue by cberge908** [Azure/secrets-store-csi-driver-provider-azure#436]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Hi all,

it seems that installing the helm chart via Terraform is not possible. The Terraform resource "[helm_release](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#name)" does not support the option to supply the "--generate-name" option for the deployment.

I've tried to manually install the name with a fixed release name, but this also does not work. This ends in an error:

```
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure csi-provider
Error: failed to download "csi-provider" (hint: running `helm repo update` may help)
```
I have already downloaded and updated the repo, using "helm repo update". So this does not change the behavior.

When using the option "--generate-name", everything works fine:

```
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name                 
NAME: csi-secrets-store-provider-azure-1615480240
LAST DEPLOYED: Thu Mar 11 17:30:43 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**What did you expect to happen:**

I would expect that the helm chart allows to enter an own release name. Otherwise the deployment will never work with Terraform.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I think everything has already been stated above.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

None of them yet.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): n/a - not installed yet
- Azure Key Vault provider version: (use the image tag): n/a - not installed yet
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.18.14 (server and client)
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@cberge908 Helm uses positional arguments and the name is the 1st expected value. Please see `helm install -h` output:

```
Usage:
  helm install [NAME] [CHART] [flags]
```

`helm install csi-provider csi-secrets-store-provider-azure/csi-secrets-store-provider-azure` instead of `helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure csi-provider`

**Comment by cberge908** [comment]
@aramase Thanks for the hint. Sorry for this silly mistake from my end.
