### ISSUE TITLE
Secret Store Driver constantly logs reconcile error

### ISSUE THREAD

**Issue by LP0101** [Azure/secrets-store-csi-driver-provider-azure#464]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Deployed the secret provider/driver to namespace `security`, running an app that uses it in the `luca-test` namespace. The respective secret-store-driver is constantly logging reconcile errors, as shown in this gist: https://gist.github.com/LP0101/19c1bb0943ca0754d310f31e6a35ba58

Every 5 minutes exactly, the reconcile succeeds, and there's no error.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.2.1
- Azure Key Vault provider version: (use the image tag): 0.0.14
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.18.14
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@LP0101 That error message is from the rotation reconciler. The success is for the secret sync reconciler.

Questions:
1. Do you have `--filtered-watch-secret=true`?
2. Is this pod using `nodePublishSecretRef`?
  - If yes, have you labelled the secret used in node publish secret ref with `secrets-store.csi.k8s.io/used=true`?

Reference docs: 
https://secrets-store-csi-driver.sigs.k8s.io/load-tests.html
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/service-principal-mode/

**Comment by LP0101** [comment]
Yup, that was it. Thank you, must have missed that during the update :)
