### ISSUE TITLE
The demo setup doesn't work

### ISSUE THREAD

**Issue by marceloes** [Azure/secrets-store-csi-driver-provider-azure#465]
Performed all the steps and secret never gets created and the application doesn't run because of that.

**Comment by aramase** [comment]
Could you provide more details on what is the error you're seeing while trying the demo?

The troubleshooting docs are here: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/.

**Comment by marceloes** [comment]
The issue seems to be that, after following all the steps, the ingress controller is not using the certificate created. Instead, it uses this one:

`* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Apr 14 18:20:24 2021 GMT
*  expire date: Apr 14 18:20:24 2022 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.`

**Comment by andyw248** [comment]
Same problem here. Ingress finds the correct issuer when the secret has been created manually, but for secrets imported by CSI Secret Store Driver it thinks the cert has been issued by Acme. Another issue is that ingress can also not find the CN in the cert that was imported by the CSI driver, even though the original cert in Key Vault contains the correct CN.

When looking at the secrets in kubernetes or through a busybox, the differences are:

**Create secret manually:**
Cert has this header:
Bag Attributes
    localKeyID: 01 00 00 00 
subject=C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = centralus.ads.guestconfig-test.azure.com

issuer=C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 02

-----BEGIN CERTIFICATE-----

And then the Base64 of one certificate.

Same for the key:
Bag Attributes
    localKeyID: 01 00 00 00 
    friendlyName: 20a3f645-13ba-4623-becd-12e9ee5befd3
    Microsoft CSP Name: Microsoft Enhanced RSA and AES Cryptographic Provider
Key Attributes
    X509v3 Key Usage: 10 
-----BEGIN PRIVATE KEY-----

And then the private key of the cert.

**Import secret with CSI driver:**
Cert starts right away with:
-----BEGIN CERTIFICATE-----
and then the Base64 of the cert.
There is no header. But there are three certificates. Could it be that CSI driver imports the entire chain as cert contents?

The key starts right away too, with no header.

So it seems that the issuer information and CN is missing from the certs that were imported by the CSI driver.

**Comment by aramase** [comment]
> There is no header. But there are three certificates. Could it be that CSI driver imports the entire chain as cert contents?

@andyw248 The CSI driver does import and write the entire certificate chain. The order of the certificate matches the order in which the certificates where uploaded in keyvault. We have an optional feature to reconstruct the certificate chain in the order (server, intermediate, root) in the CSI driver: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/feature-flags/#construct-pem-chain-feature-flag. Try it out when you get a chance.

**Comment by marceloes** [comment]
I was able to get it to work. One of the issues was namespaces: it seemed that the secret provider class, the created secret, the ingress controller, the ingress and apps all had to be on the same namespace (or namespace be explicitly declared on each reference).

**Comment by andyw248** [comment]
@aramase Thank you for pointing out the construct-pem-chain option! This completely solved the issue for me.

**Comment by aramase** [comment]
Thank you for confirming. 

The `SecretProviderClass` needs to be in the same namespace as the application and synced Kubernetes secret will be created in the same namespace following RBAC best practices with namespace being the security boundary.

The kubernetes secret being in the same namespace as Ingress is an ingress requirement and best practice. 

Closing this issue as it's now resolved.
