### ISSUE TITLE
Cert permission too open for postgres ssl requirement 

### ISSUE THREAD

**Issue by dcint** [Azure/secrets-store-csi-driver-provider-azure#490]
**What steps did you take and what happened:**
When mounting key vault cert permission of file is 0644. Meaning anyone can read cert file. My specifc issue is postgres requires permission for cert files to be 0640 in order to use ssl connection . 

**What did you expect to happen:**
I expected permission for cert to be more restrictive and not read everyone. 

**Anything else you would like to add:**
If there is a way to change permission during mount it would resolve my issue. 

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: latest helm deployment
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: 1.19.3
- Cluster type: AKS

**Comment by aramase** [comment]
File permissions are currently not configurable. The default permission is `0644` which is set and passed from the driver. Please feel free to comment on this issue: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/346 and for tracking.

**Comment by aramase** [comment]
Closing this issue as the feature request is being tracked in the driver. The issue will contain a reference to this issue.
