### ISSUE TITLE
Error installing helm chart

### ISSUE THREAD

**Issue by seb0006** [Azure/secrets-store-csi-driver-provider-azure#505]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I received the below error following the helm installation instructions from [this link](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html)

$ helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
"secrets-store-csi-driver" has been added to your repositories

$ helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "secrets-store-csi-driver" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-secrets-store"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

**What did you expect to happen:**

Successful installation of secrets-store-csi-driver

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
N/A

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Azure Key Vault provider version: (use the image tag): 
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"d2ea02d7bcf37724adabbdb9d37ede0cf2c0d627", GitTreeState:"clean", BuildDate:"2020-04-24T22:59:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1

NAME                     STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-41725384-0   Ready    agent    19m   v1.16.9   10.240.0.5       <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
aks-default-41725384-1   Ready    agent    19m   v1.16.9   10.240.0.6       <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
aks-default-41725384-2   Ready    agent    19m   v1.16.9   10.240.0.4       <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
k8s-master-41725384-0    Ready    master   19m   v1.16.9   10.240.255.233   <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
k8s-master-41725384-1    Ready    master   19m   v1.16.9   10.240.255.234   <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
k8s-master-41725384-2    Ready    master   19m   v1.16.9   10.240.255.235   <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.11+azure
- Cluster type: (e.g. AKS, aks-engine, etc): AKS Private Preview for Azure Stack Hub

**Comment by aramase** [comment]
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "secrets-store-csi-driver" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-secrets-store"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

@seb0006 This error indicates you already have the driver installed in the cluster with different helm release name.

The helm charts hosted [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure) have the driver charts as a dependency. Using the chart from this repo will install the driver and also the azure provider.

**Comment by seb0006** [comment]
@aramase - It turns out that the AKS Private Preview product on Azure Stack Hub has the driver and azure provider installed when a new cluster is created with Kubernetes version 1.16.9.  This was a surprise since this isn't documented anywhere that I have found, but was able to confirm the installation by creating a new cluster.
