### ISSUE TITLE
Cluster level authentication when not using AKS

### ISSUE THREAD

**Issue by Shaked** [Azure/secrets-store-csi-driver-provider-azure#514]
**Describe the solution you'd like**
Currently, when not using AKS, I have to authenticate using [service principal](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/service-principal-mode/). 

This means that if I have several deployments/resources and several namespaces, I have to set a k8s secret per namespace as stated in the docs: 

> The Kubernetes Secret containing the credentials need to be created in the same namespace as the application pod. If pods in multiple namespaces need to use the same SP to access Keyvault, this Kubernetes Secret needs to be created in each namespace.

That also means that when using GitOps in CI/CD, I have to create N*M [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) per N namespace and M clusters (dev, stage, prod etc).

As I'm using different k8s cloud providers (AKS, EKS, GKE), I'd like to have a more global way to authenticate against Azure KeyVault (AKV) instead of duplicating this k8s secret and having to encrypt it whenever a new namespace/cluster are added. 

With AKS this is relatively simple, considering the other [identity access modes](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/). However, for other provider it would be easier to have a solution on a cluster level. One idea that came in mind is creating a similar solution to what cert-manager is doing with [ClusterIssuer](https://docs.cert-manager.io/en/release-0.11/reference/clusterissuers.html) so in that case it will reduce the amount of setup to M secrets i.e secret per cluster, instead of NM secrets as stated above. 

**Environment:**

- Secrets Store CSI Driver version: latest
- Azure Key Vault provider version: latest
- Kubernetes version: 1.18
- Cluster type: (e.g. AKS, aks-engine, etc): GKE, AKS, EKS

**Comment by nilekhc** [comment]
Hi @Shaked Thanks for opening the issue. Could you try other methods of accessing Keyvault? It might help in your use case.
[provide-identity-to-access-key-vault](https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/#provide-identity-to-access-key-vault)

**Comment by Shaked** [comment]
> Hi @Shaked Thanks for opening the issue. Could you try other methods of accessing Keyvault? It might help in your use case.

Which ones? AFAIU the last two require an AKS cluster, aren't they?

**Comment by nilekhc** [comment]
Service Principal is currently the only way to connect with Key Vault from non Azure environment. But we can certainly look into other options.

**Comment by Shaked** [comment]
@nilekhc 

I might have an idea but first I need to understand something about the controller. Is there a reason why it requires a secret per namespace instead of having one secret on the same namespace of the controller itself? 

i.e if the csi-secrets-store-provider-azure is installed in a namespace called `devops` then why not having the SP creds only available within this namespace and then pods will communicate only with the driver

**Comment by DaveSlinn** [comment]
> 
> 
> Service Principal is currently the only way to connect with Key Vault from non Azure environment. But we can certainly look into other options.

@nilekhc We've been trying to use a User Managed Identity from an on-premises Kubernetes cluster to access Key Vault but have been thwarted by a weird error we didn't understand:
```
MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod mo-communication-platform/nginx-deployment-7b685d6dd5-pkdt7, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:aws-pinpoint-access-key-id, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://gmsca.vault.azure.net/secrets/aws-pinpoint-access-key-id/?api-version=2016-10-01: StatusCode=0 -- Original Error: the MSI endpoint is not available. Failed HTTP request to MSI endpoint: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01": dial tcp 169.254.169.254:80: i/o timeout
```
Based on your comment, should we be modifying our approach to use a Service Principal for auth to Azure KV instead of a managed identity?

**Comment by nilekhc** [comment]
@DaveSlinn yes. try with Service Principal.

**Comment by nilekhc** [comment]
> @nilekhc
> 
> I might have an idea but first I need to understand something about the controller. Is there a reason why it requires a secret per namespace instead of having one secret on the same namespace of the controller itself?
> 
> i.e if the csi-secrets-store-provider-azure is installed in a namespace called `devops` then why not having the SP creds only available within this namespace and then pods will communicate only with the driver

@Shaked The secrets needs to be present in the namespace where the pod is trying to use it. This is due to restriction imposed by k8s.
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/127#issuecomment-644874658

**Comment by Shaked** [comment]
@nilekhc I find it a bit strange. Maybe it is possible to use a different object? 

Currently I'm solving this issue by using https://github.com/mittwald/kubernetes-replicator which replicates the secret to the relevant namespaces.

**Comment by aramase** [comment]
Closing this issue with #534
