### ISSUE TITLE
Can update KV by using Azure Key Vault Provider for Secrets Store CSI Driver?

### ISSUE THREAD

**Issue by ttmonica** [Azure/secrets-store-csi-driver-provider-azure#518]
Except read from KV, my pod is also want to update/add a new item to KV.  Does it support?

**Comment by nilekhc** [comment]
Hello @ttmonica , thanks for opening an issue. Secret Store CSI driver today do not support this. It mounts secrets/keys/certs to pod.  AKV Provider acts as plugin to fetch those objects. Could you elaborate on your use case?
