### ISSUE TITLE
Secret failed to write to file on Microk8s

### ISSUE THREAD

**Issue by nbeal** [Azure/secrets-store-csi-driver-provider-azure#521]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We follow your tutorial: https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/
down through connecting our existing keyvault and service principal. We created a kubernetes secret and followed using the example secretproviderclass given with busybox. When the pod tries to start, it fails to write the secret to file.

Describe Pod
```
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    9m7s                 default-scheduler  Successfully assigned default/busybox-secrets-store-inline to nathan-xps
  Warning  FailedMount  43s (x12 over 9m7s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/busybox-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to write file BackendDatabaseUserPassword at /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount: open /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount/BackendDatabaseUserPassword: no such file or directory
  Warning  FailedMount  16s (x4 over 7m5s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-w2h45]: timed out waiting for the condition

```
Logs:
`E0528 19:20:50.702213       1 grpc.go:29] "GRPC error" err="failed to mount objects, error: failed to write file BackendDatabaseUserPassword at /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount: open /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount/BackendDatabaseUserPassword: no such file or directory"`

test.yaml we were using:
```
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
spec:
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    command:
      - "/bin/sleep"
      - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
        nodePublishSecretRef:                       # Only required when using service principal mode
          name: secrets-store-creds   
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kvname"
    objects: |
      array:
        - | #Backend ----------------------------------------------------------
          objectName: BackendDatabaseUserPassword
          objectType: secret
          objectVersion: "" 
    tenantId: "1234
```

**What did you expect to happen:**
It to work and start.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Started from scratch, so should be working with your examples.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Azure Key Vault provider version: (use the image tag): latest
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.17.17
- Cluster type: (e.g. AKS, aks-engine, etc): Microk8s

**Comment by dmcconnell-m** [comment]
We are also experiencing this issue on microk8s. We followed the steps #101 (related to rancher however this was also affecting microk8s) and setting `secrets-store-csi-driver.linux.kubeletRootDir="/var/snap/microk8s/common/var/lib/kubelet"` enabled us to move past the issues in #101, however now we are experiencing the same issue that @nbeal is reporting. To add, microk8s appears to use `--root-dir=${SNAP_COMMON}/var/lib/kubelet` which translates to the path above.

**Comment by dmcconnell-m** [comment]
@aramase I have found the cause of this issue. The `mountpoint-dir` fields are hardcoded to be `/var/lib/kubelet/pods` whereas they should actually be using the helm variable `kubeletRootDir`. So these lines should be updated to the helm variable `secrets-store-csi-driver.linux.kubeletRootDir` or a new variable `linux.kubeletRootDir` should be used:

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/5a7176d78c2af91e081d2d63f2122871d1510352/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml#L73

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/5a7176d78c2af91e081d2d63f2122871d1510352/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml#L89

Also the windows template equivalents I assume also have this problem?
@nbeal if you manually modify the azure secret store provider DaemonSet's 2 mountpoint-dir variables from `/var/lib/kubelet/pods` to `/var/snap/microk8s/common/var/lib/kubelet/pods` it should work as a workaround until the helm templates are updated

**Comment by nilekhc** [comment]
@dmcconnell-m Thanks for looking into issue. Will you be interested in opening a PR for this? We can leverage `secrets-store-csi-driver.linux.kubeletRootDir` var in template.

**Comment by aramase** [comment]
> So these lines should be updated to the helm variable secrets-store-csi-driver.linux.kubeletRootDir or a new variable linux.kubeletRootDir should be used

Thanks @dmcconnell-m. Agree, we would need to use a new `linux.kubeletRootDir` unless there is a way to reuse the value from the driver. Also, in the future releases we're going to move the file writing logic to the driver. So the provider will only return the secret content to the provider and will no longer require this mount path.

**Comment by djarvis** [comment]
@aramase @dmcconnell-m I am seeing this exact same issue:

_Warning  FailedMount  4s (x6 over 20s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod myapp1/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = error making mount request: secrets-store csi driver failed to write password at /var/snap/microk8s/common/var/lib/kubelet/pods/c5bfecd0-e2f4-45ca-9503-c2a37e8ae233/volumes/kubernetes.io~csi/secrets-store-inline/mount: open /var/snap/microk8s/common/var/lib/kubelet/pods/c5bfecd0-e2f4-45ca-9503-c2a37e8ae233/volumes/kubernetes.io~csi/secrets-store-inline/mount/password: **no such file or directory**_

  Are we saying that I should be able to:

**helm3 upgrade csi secrets-store-csi-driver/secrets-store-csi-driver --namespace=vault --set "secrets-store-csi-driver.linux.kubeletRootDir=/var/snap/microk8s/common/var/lib/kubelet"**

and it should work?  Do I need to set some other variable here?

Using microk8s and helm3, following the tutorial on https://www.hashicorp.com/blog/retrieve-hashicorp-vault-secrets-with-kubernetes-csi

Thanks!
