### ISSUE TITLE
Using the Azure Key Vault Provider

### ISSUE THREAD

**Issue by lilinvictorms** [Azure/secrets-store-csi-driver-provider-azure#523]
This link is 404: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys.md

**Comment by nilekhc** [comment]
@lilinvictorms Try without `.md` at the end.
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/

Aslo, could you tell where did you get above link from? We can fix if there is a broken link.
