### ISSUE TITLE
It is not able to install the of the secret provider class into another namespace of the same cluster

### ISSUE THREAD

**Issue by mkk1985** [Azure/secrets-store-csi-driver-provider-azure#524]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)
I would like to know how to leverage this feature across namespaces of the same AKS cluster. As we are maintaining lower environments in the cluster separated by namespaces. please advice!

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
@mkk1985 Could you add more information to the issue? 

> I would like to know how to leverage this feature across namespaces of the same AKS cluster. As we are maintaining lower environments in the cluster separated by namespaces. please advice!

The `SecretProviderClass` is namespaced scope and you can create the `SecretProviderClass` in the required namespace.

> It is not able to install the of the secret provider class into another namespace of the same cluster #524

Are you trying to create the `SecretProviderClass` custom  resource in the namespace or trying the deploy CSI Driver in multiple namespaces? Only 1 CSI driver install is required per cluster.

**Comment by mkk1985** [comment]
we are getting the below error while trying to install the same in another namespace:

 

**_rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "secretproviderclasses.secrets-store.csi.x-k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "namespace1": current value is "namespace2"_**

**Comment by mkk1985** [comment]
ok then, when you that.. we should create the driver in the kube-system namespace and how can we create the provider classes in the other namespaces ? could you please provide me some examples to this scenario?

**Comment by aramase** [comment]
> we are getting the below error while trying to install the same in another namespace:

The driver runs as a daemonset and only single instance of the daemonset is required per cluster. The driver running in `kube-system` will be invoked by the kubelet on the node for volume mount operations.

> ok then, when you that.. we should create the driver in the kube-system namespace and how can we create the provider classes in the other namespaces ? could you please provide me some examples to this scenario?

You can create the `SecretProviderClass` in the respective namespace: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/#create-your-own-secretproviderclass-object. For the `SecretProviderClass` set the namespace to be same as the application pod referencing it. When a pod references a `SecretProviderClass`, the driver will lookup the `SecretProviderClass` only in the same namespace as the pod conforming to RBAC best practices.

**Comment by aramase** [comment]
Closing this issue now with https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/524#issuecomment-852302031. Please feel free to reopen if you've any questions.
