### ISSUE TITLE
SecretObject not found; volume gets mounted

### ISSUE THREAD

**Issue by rucheeg** [Azure/secrets-store-csi-driver-provider-azure#542]
**Have you**

- [y] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [y ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

![image](https://user-images.githubusercontent.com/2429649/122079613-323b5c80-cdc3-11eb-99c0-9adfe3e230f2.png)

**SecretProvider.yaml**
![image](https://user-images.githubusercontent.com/2429649/122079868-6f9fea00-cdc3-11eb-9548-9ecfa819b689.png)

**Deployment.yaml**
![image](https://user-images.githubusercontent.com/2429649/122080045-91996c80-cdc3-11eb-89f7-8cbc20ea8263.png)

**kubectl describe pd <pod name>**
![image](https://user-images.githubusercontent.com/2429649/122080152-aa098700-cdc3-11eb-8fd1-60075c3a483a.png)

**Comment by aramase** [comment]
@rucheeg Thank you for reporting the issue.

The logs from `secrets-store` container in the driver pod should have more information on why the sync secret failed. Here is our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

Did you set `secrets-store-csi-driver.syncSecret.enabled=true` as part of helm install while setting up the driver and provider? As of the last release, the RBAC roles and rolebindings required for sync secret are not installed by default. They need to be explicitly set as part of helm install command.

Here is a list of helm configurable values: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration
Release notes: https://azure.github.io/secrets-store-csi-driver-provider-azure/upgrading/#upgrading-to-helm-chart-version-0020

**Comment by rucheeg** [comment]
Thanks for your quick response @aramase. The only error I see is following in driver logs. There are no errors in provider logs.

_E0615 16:39:48.653579       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:cluster-addons:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope_

I've asked the team that installed the driver/provider if they enabled the syncSecret.

**Comment by aramase** [comment]
@rucheeg Yeah, that looks like the issue with the `syncSecret` not enabled.

I'm adding this step to few other docs and our troubleshooting guide:  https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/543.

**Comment by rucheeg** [comment]
Thanks @aramase! you were spot on. That fixed the error. Appreciate the quick turnaround!
