### ISSUE TITLE
Use default User-assigned Managed Identity if userAssignedIdentityID is not provided

### ISSUE THREAD

**Issue by fdebuire** [Azure/secrets-store-csi-driver-provider-azure#546]
When an AKS cluster is created with a managed identity (https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#create-an-aks-cluster-with-managed-identities), a user managed identity with the name `yourClusterName-agentpool` is created.

This identity is automatically assigned as the default user managed identity for the VM/VMSS.

The clientId of this identity can be found in the AzureCloud credentials present in the file `/etc/kubernetes/azure.json` on any VMs:
```
{
    "cloud": "AzurePublicCloud",
    ...
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "xxxx-xxxx-xxxx-xxxx-xxxx",
    ...
}
```

RIght now if the field `userAssignedIdentityID` is not provided in the `SecretProviderClass` (and we don't have any System managed identity assigned to the VM/VMSS) the following error happen:
```
Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```

It would be nice if this identity could be used by default, so we could avoid having to provide the userAssignedIdentityID field.
We are using a GitOps approach and ideally we want to avoid having hardcoded ID that could change in case of cluster recreation.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.22
- Azure Key Vault provider version: (use the image tag): 0.0.15
- Kubernetes version: (use `kubectl version`): 1.19.9
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by justinokay** [comment]
@aramase Any plans to introduce this in the near future? AKS should be smart enough to dynamically fetch resource URIs/IDs based on default naming conventions instead of relying on hard coded values that are subject to change.  The best approach I've found is inline replace and commit to master as part of my CI/CD which is not an ideal in 2023.

@fdebuire did you ever find a solution/workaround?
