### ISSUE TITLE
SecretProviderClass doesn't create k8s secret

### ISSUE THREAD

**Issue by HighWatersDev** [Azure/secrets-store-csi-driver-provider-azure#550]
Hi,

I'm following this guide - https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html - to inject secrets from KV to K8s pod. If I understand correctly using "secretObjects" allows the SecretProvider to create k8s secret and sync it with existing secret in KV. However, when running a pod referencing the secret, it fails with "secret not found".
All I'm trying to do is use KV secret as env var inside a Pod. 

SecretProviderClass.yaml
`spec:
  provider: azure
  secretObjects:
  - secretName: azdo-pat
    type: Opaque
    data:
    - objectName: azdevops-pat
      key: pat
  parameters:
    usePodIdentity: "false"
    keyvaultName: "###"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: azdevops-pat
          objectType: secret
  tenantId: "###"
`

Pod.yaml

`piVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    env:
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: azdo-pat
            key: pat
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/secrets-store"
      readOnly: true
  volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "###"
          nodePublishSecretRef:
            name: secrets-store-creds`

**Comment by aramase** [comment]
@HighWatersDev Thank you for reporting the issue.

The logs from `secrets-store` container in the driver pod should have more information on why the sync secret failed. Here is our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

Did you set `secrets-store-csi-driver.syncSecret.enabled=true` as part of helm install while setting up the driver and provider? In the latest release the RBAC roles and rolebindings required for sync secret are not installed by default. They need to be explicitly set as part of helm install command.

Here is a list of helm configurable values: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration
Release notes: https://azure.github.io/secrets-store-csi-driver-provider-azure/upgrading/#upgrading-to-helm-chart-version-0020

**Comment by HighWatersDev** [comment]
@aramase you are right. I overlooked that setting. I didn't pay attention that it changed from last time I used it. I updated the setting and it's working now. Now I feel embarrassed for not reading the docs properly.
Thanks a lot!
