### ISSUE TITLE
Helm chart deployment - ClusterRole missing permissions for k8s secret sync to work

### ISSUE THREAD

**Issue by jcobb48** [Azure/secrets-store-csi-driver-provider-azure#553]
**What steps did you take and what happened:**

Deployed using helm chart:

```
NAME: csi-secrets-store-provider-azure 
NAMESPACE: kube-system
CHART: csi-secrets-store-provider-azure-0.0.20 
APP VERSION: 0.0.16
```

**Provided values > syncSecret.enabled=true**

Deployed SecretProviderClass with some keyvault secrets, deployed a pod with volume mount referencing the SecretProviderClass and it works as expected, pod has all the corresponding files with the secrets content inside.

When trying to sync AKV secrets as k8s secrets and add them as env , pod provisioning fails with status 'CreateContainerConfigError' because the Secret reference is missing.

Checked  secrets-store-csi-driver / secrets-store container logs and got this error when syncing the secrets to k8s>

`E0623 12:44:03.792528       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope`

Cluster Role assigned to the Service Account:

---------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: csi-secrets-store-provider-azure
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-06-23T12:35:36Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2021-06-23T12:35:36Z"
  name: secretproviderclasses-role
  resourceVersion: "30350802"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/secretproviderclasses-role
  uid: 6b9ae290-8175-4711-80a4-4bbc682d3fec
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasspodstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasspodstatuses/status
  verbs:
  - get
  - patch
  - update
---------------------------------------------------

After checking that the SA did not have permits on Secrets, added this rule to the ClusterRole:

---------------------------------------------------
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---------------------------------------------------

Retried the pod deployment and it worked as expected.

**What did you expect to happen:**

Expected the helm chart to configure the correct permissions for secret sync to work.

**Anything else you would like to add:**

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**
- Secrets Store CSI Driver version:  
mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.23
mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.2.0
- Azure Key Vault provider version: 
mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.16 
- Kubernetes version: v1.18.10
- Cluster type: AKS

**Comment by aramase** [comment]
@jcobb48 The `syncSecret.enabled=true` is required for the driver which is a helm dependency. For dependencies you would need to set the value with `secrets-store-csi-driver.syncSecret.enabled=true`.

**Comment by jcobb48** [comment]
@aramase haha thanks! I worked, missed to check that piece of info.

Configuration Doc only said "syncSecret.enabled", maybe "secrets-store-csi-driver." can be added.
 
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/

`If the driver and provider have been installed using helm, ensure the syncSecret.enabled=true helm value is set as part of install/upgrade. This is required to install the RBAC clusterrole and clusterrolebinding required by the CSI driver to sync mounted content as Kubernetes secret. For a list of customizable values that can be injected when invoking helm install, please see the Helm chart configurations.`
