### ISSUE TITLE
Get Current + Older versions of a certificate

### ISSUE THREAD

**Issue by kchilka-msft** [Azure/secrets-store-csi-driver-provider-azure#557]
**Describe the solution you'd like**
Currently there **isn't** an option to pull all the available versions of a certificate from Azure keyvault. There is an option to pull a certificate by providing **_objectVersion_** but we have a scenario where we want all the versions of a certificate (including the older versions). Currently this involves manually looking up the **_objectVersion_** and updating the manifest

**Comment by kchilka-msft** [comment]
thanks for adding it to the backlog! appreciate it! and would it possible to provide a timeline as to when can we expect it? or is it too soon for that? just wanted to gauge as to how long would be the wait. thanks!

**Comment by aramase** [comment]
@kchilka-msft I've added it to the backlog for now. If we do have more requests for this feature, we'll move it todo and prioritize it.

**Comment by aramase** [comment]
Consolidating the feature requests in a single issue: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/571.
