### ISSUE TITLE
CSI Driver does not create Secrets in Helm Chart version 0.0.20

### ISSUE THREAD

**Issue by iamNoah1** [Azure/secrets-store-csi-driver-provider-azure#568]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

CSI Driver Secret Store is not able to create Secrets in Kubernetes using the newest helm version (0.0.20)

**What did you expect to happen:**

That secrets are created inside of Kubernetes. 

**Anything else you would like to add:**
Using version 0.0.17 works fine. Using the newest version I can see the following error message in the secrets-store container of the csi-secrets-store-provider-azure-xxxxxx-xxxx pod: 

reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:default:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Don't know how to find that out. 
- Azure Key Vault provider version: (use the image tag): Helm Chart version 0.0.20
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:51:17Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4a4913e790a033f1101af2f0fb7be189b106e3ae", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:03Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

aks-systempool-11691003-vmss000000     Ready    agent   32d   v1.20.7   10.1.0.66     <none>        Ubuntu 18.04.5 LTS   5.4.0-1047-azure   containerd://1.4.4+azure
aks-workloadpool-11691003-vmss000000   Ready    agent   32d   v1.20.7   10.1.0.4      <none>        Ubuntu 18.04.5 LTS   5.4.0-1047-azure   containerd://1.4.4+azure

- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@iamNoah1 Here is the exact same issue: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/556.

This comment has the details on the changes: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/556#issuecomment-868683075. Please let us know if you need more information.

**Comment by iamNoah1** [comment]
@aramase thanks for the quick feedback. Apparently, I did not search carefully enough. Just as a proposal, would you consider setting the value default to true? People that upgrade assume that secrets are injected by default because the older versions did. In every case I think it should not result in the stated error messages if the value is set to false.

**Comment by aramase** [comment]
> @aramase thanks for the quick feedback. Apparently, I did not search carefully enough. Just as a proposal, would you consider setting the value default to true? People that upgrade assume that secrets are injected by default because the older versions did. In every case, I think it should not result in the stated error messages if the value is set to false.

@iamNoah1 We want to disable by default because sync as Kubernetes secret is an optional feature that not all users of secrets-store-csi-driver consume. So we want to use the minimal permissions required OOTB with the helm install. This is a breaking change and is part of upgrade notes as well.

**Comment by iamNoah1** [comment]
Fair enough. Will close this one.
