### ISSUE TITLE
CSI driver is not able to pull the newly added keys from the keyvault

### ISSUE THREAD

**Issue by akashsg** [Azure/secrets-store-csi-driver-provider-azure#570]
We are facing issues with CSI driver where it can’t get the value from keyvault. We defined the keyvault name and referenced that in secretproviderclass. The old keys which are already present as nonprodsecret are getting deployed fine, only the newly added keyvault keys are failing. Then I deleted the old CSI driver and it’s components and re-installed the new one, but still we are facing the same issue. Can you please help us with this issue? Please let me know if you need any further information.

**Comment by aramase** [comment]
@akashsg Could you please provide more info:

1. What version of the driver and provider you using?
2. `SecretProviderClass` yaml
3. `Pod` yaml
4. Do you have secret auto rotation enabled? 
5. Do you have sync secret enabled?
6. What are the steps you took for adding new secret?
7. Did you try restarting the pod?

Here are some useful docs for troubleshooting:
1. https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/
2. https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html
3. https://secrets-store-csi-driver.sigs.k8s.io/troubleshooting.html

**Comment by akashsg** [comment]
1. apiVersion: storage.k8s.io/v1
kind: CSIDriver
2. apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname1
  namespace: meijer
spec:
  provider: azure
  parameters:
    keyvaultName: "kv-np-ea2-retail-ASE" # the name of the KeyVault
    objects: |
      array:
      - |
        objectName: BarcodeNormalize-int # This will get replaced through pipeline per environment
        objectAlias: fa-np-ea2-BarcodeNormalize
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: retail-NextGenPOS-Transaction-Completion-int # This will get replaced through pipeline per environment
        objectAlias: retail-NextGenPOS-Transaction-Completion
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: fa-np-ea2-TaxCalc-int # This will get replaced through pipeline per environment
        objectAlias: fa-np-ea2-TaxCalc
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: retail-transaction-coupon-validation-int # This will get replaced through pipeline per environment
        objectAlias: fa-np-ea2-retail-transaction-coupon-validation
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: ADS-SQLMI-Username # This will get replaced through pipeline per environment
        objectAlias:  ADS-SQLMI-Username
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: ADS-SQLMI-Username-Password # This will get replaced through pipeline per environment
        objectAlias: ADS-SQLMI-Username-Password
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: retail-Transaction-Number-Service-int # This will get replaced through pipeline per environment
        objectAlias: retail-Transaction-Number-Service
        objectType: secret        # object types: secret, key or cer
      #- |
      #  objectName: transaction-number-service-connectionURI # This will get replaced through pipeline per environment
      #  objectAlias: transaction-number-service-connectionURI
      #  objectType: secret        # object types: secret, key or cert
      - |
        objectName: ADS-SQLMI-Username # This will get replaced through pipeline per environment
        objectAlias: SQLMI-DBUsername
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: ADS-SQLMI-Username-Password # This will get replaced through pipeline per environment
        objectAlias: SQLMI-DBPassword
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: LoyalityCoordinationService-int # This will get replaced through pipeline per environment
        objectAlias: api-np-ea2-LoyaltyCoordinationService
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: APIManagerSubscriptionKey # This will get replaced through pipeline per environment
        objectAlias: MperksPIN
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: DigitalApiManagerKey # This will get replaced through pipeline per environment
        objectAlias: DigitalKey
        objectType: secret        # object types: secret, key or cert
      - |
        objectName: APIManagerSubscriptionKey # This will get replaced through pipeline per environment
        objectAlias: APIManagerSubscriptionKey
        objectType: secret        # object types: secret, key or cert      
      - |
        objectName: NextGenPOSTeamMemberAuth-int # This will get replaced through pipeline per environment
        objectAlias: fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int
        objectType: secret        # object types: secret, key or cert  
      - |
        objectName: Confluent-Kafka-Table-Names # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_TOPICS
        objectType: secret        # object types: secret, key or cert  
      - |
        objectName: Confluent-Kafka-URL # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_URL
        objectType: secret        # object types: secret, key or cert       
      - |
        objectName: Confluent-Kafka-Key # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_KEY
        objectType: secret        # object types: secret, key or cert        
      - |
        objectName: Confluent-Kafka-Secret # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_SECRET
        objectType: secret        # object types: secret, key or cert       
      - |
        objectName: Confluent-Schema-Registry-URL # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_SCHEMA_REGISTRY_URL
        objectType: secret        # object types: secret, key or cert         
      - |
        objectName: Confluent-Schema-Registry-Key # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_SCHEMA_REGISTRY_KEY
        objectType: secret        # object types: secret, key or cert     
      - |
        objectName: Confluent-Schema-Registry-Secret # This will get replaced through pipeline per environment
        objectAlias: CONFLUENT_KAFKA_SCHEMA_REGISTRY_SECRET
        objectType: secret        # object types: secret, key or cert         

      
    resourceGroup: "rg-np-retail-ASE-Shared" # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "adc75fb7-63fc-41c2-ab98-50a514fa15ba" # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "9b415222-16dc-4250-bd60-8a375591609a"  # the tenant ID of the KeyVault
  secretObjects:
    - data:
      - key: barcode-secret
        objectName: fa-np-ea2-BarcodeNormalize
      - key: worker-service-secret
        objectName: retail-NextGenPOS-Transaction-Completion
      - key: taxcalc-secret
        objectName: fa-np-ea2-TaxCalc
      - key: couponval-secret
        objectName: fa-np-ea2-retail-transaction-coupon-validation
      - key: couponval-apimgrkey-secert
        objectName: APIManagerSubscriptionKey    
      - key: ADS-SQLMI-Username-secret
        objectName: ADS-SQLMI-Username
      - key: ADS-SQLMI-Username-Password-secret
        objectName: ADS-SQLMI-Username-Password
      - key: transaction-number-service-secret
        objectName: retail-Transaction-Number-Service    
      #- key: transaction-number-service-connectionURI-secret
      #  objectName: transaction-number-service-connectionURI    
      - key: SQLMI-DBUsername-secret
        objectName: SQLMI-DBUsername
      - key: SQLMI-DBPassword-secret
        objectName: SQLMI-DBPassword    
      - key: LoyalityCoordination-AppKey-secret
        objectName: api-np-ea2-LoyaltyCoordinationService
      - key: LoyalityCoordination-MperksPIN-secret
        objectName: MperksPIN
      - key: LoyalityCoordination-DigitalKey-secret
        objectName: DigitalKey
      - key: APIManagerSubscriptionKey
        objectName: APIManagerSubscriptionKey     
      - key: teammemberauth-appKey-secret
        objectName: fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int
      - key: Confluent-Kafka-Table-Name-secret
        objectName: CONFLUENT_KAFKA_TOPICS
      - key: Confluent-Kafka-URL-secret
        objectName: CONFLUENT_KAFKA_URL
      - key: Confluent-Kafka-Key-secret
        objectName: CONFLUENT_KAFKA_KEY
      - key: Confluent-Kafka-Secret-secret
        objectName: CONFLUENT_KAFKA_SECRET
      - key: Confluent-Kafka-Schema-Registry-Url-secret
        objectName: CONFLUENT_SCHEMA_REGISTRY_URL
      - key: Confluent-Kafka-Schema-Registry-Key-secret
        objectName: CONFLUENT_KAFKA_SCHEMA_REGISTRY_KEY
      - key: Confluent-Kafka-Schema-Registry-Secret-secret
        objectName: CONFLUENT_KAFKA_SCHEMA_REGISTRY_SECRET
      secretName: nonprodsecret
      type: Opaque

3. apiVersion: apps/v1
kind: Deployment
metadata:
  name: posstoreteammemberauthorization
  namespace: meijer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posstoreteammemberauth
  template:
    metadata:
      labels:
        app: posstoreteammemberauth
    spec:
      containers:
        - name: posstoreteammemberauth
          image: crea2retailcontainers.azurecr.io/rng-nextgenposteammemberauthfunction:bn234746
          env:
          - name: AppName
            value: "fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int"          
          - name: fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int
            valueFrom:
              secretKeyRef:
                name: nonprodsecret
                key: teammemberauth-appKey-secret
          - name: sql-server-name
            valueFrom:
              configMapKeyRef:
                name: sql-server-details
                key: sql-server-name
          - name: DBName-Transaction
            valueFrom:
              configMapKeyRef:
                name: sql-server-details
                key: db-name-posteammember
          - name: ADS-SQLMI-Username
            valueFrom:
              secretKeyRef:
                name: nonprodsecret
                key: ADS-SQLMI-Username-secret
          - name: ADS-SQLMI-Username-Password
            valueFrom:
              secretKeyRef:
                name: nonprodsecret
                key: ADS-SQLMI-Username-Password-secret
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: "d1c0af6a-047c-40a3-9324-dfd2b54f94a4"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname1"
            nodePublishSecretRef:
              name: secrets-store-creds1
      imagePullSecrets:
        - name: dockersecret
        
---
apiVersion: v1
kind: Service
metadata:
  name: posstoreteammemberauth-svc
  namespace: meijer
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: posstoreteammemberauth
  type: NodePort

4.  I just installed CSI driver, I didn't setup anything explicitly
5. I just installed CSI driver, I didn't setup anything explicitly
6. After adding a new secret to keyvault, we are referring the keyvault name in secretproviderclass and in Pod Yaml.
For example: In the above secretproviderclass.yaml, "NextGenPOSTeamMemberAuth-int" this is the keyvault secret name and alias is what app is expecting objectAlias: fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int
Then referred the key name in the pod yaml "teammemberauth-appKey-secret"
      - key: teammemberauth-appKey-secret
        objectName: fa-np-ea2-retail-NextGenPOSTeamMemberAuth-int
7. The pod is not even in running state, it is failing in fetching the key from key vault itself. ERROR: Couldn't find the key teammemberauth-appKey-secret in Secret meijer/nonprodsecret

**Comment by aramase** [comment]
@akashsg What version of the helm charts did you install? Also, could you check the logs in the driver and provider pod running on the same node as the application with issue. Here is troubleshooting guide on how to get the logs: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

You're using sync secret feature. Did you enable the feature flag required: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/ (`secrets-store-csi-driver.syncSecret.enabled=true`) when you installed with helm.

Without autorotation new added keys to secret provider class will not be automatically updated. Here is more info on what auto rotation is and how to enable it: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/enable-auto-rotation-secrets/

If you don't want to use auto rotation, these are the steps to get the new added secrets in the secretproviderclass for the pod: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated

**Comment by akashsg** [comment]
1. @aramase we are using helm v3 version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}

below are the logs of driver and provider which are running on the same node as the application with issue
> kubectl get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
csi-secrets-csi-secrets-store-provider-azure-zkw5z                1/1     Running   2          25d
csi-secrets-secrets-store-csi-driver-fhd7t                        3/3     Running   3          25d
csi-secrets-store-provider-azure-1608059928-cwpfr                 1/1     Running   0          9d
csi-secrets-store-provider-azure-1608059928-secrets-store-5ghrp   3/3     Running   1          9d
kafka-7d746c8b5d-ppx4d                                            1/1     Running   15         152d
zookeeper-5c9446b4cb-9vcq4                                        1/1     Running   7          152d
> kubectl get pods -l app=secrets-store-csi-driver -o wide
NAME                                                              READY   STATUS    RESTARTS   AGE   IP              NODE             NOMINATED NODE   READINESS GATES
csi-secrets-secrets-store-csi-driver-fhd7t                        3/3     Running   3          25d             XXXXX                   XXXXXX<none>           <none>
csi-secrets-store-provider-azure-1608059928-secrets-store-5ghrp   3/3     Running   1          9d    XXXXX           XXXXX<none>           <none>
> kubectl logs csi-secrets-secrets-store-csi-driver-fhd7t secrets-store --since=1h | grep ^E
> kubectl logs csi-secrets-secrets-store-csi-driver-fhd7t secrets-store --since=1h | grep ^E
> kubectl logs csi-secrets-secrets-store-csi-driver-fhd7t secrets-store --since=1800h | grep ^E
E0708 15:32:37.400225       1 secretproviderclasspodstatus_controller.go:101] "failed to patch secret owner ref" err="failed to fetch pod during patching, err: Pod \"transactionnumberservice-57cd7899c7-k6dpf\" not found"
E0714 18:47:52.400142       1 secretproviderclasspodstatus_controller.go:101] "failed to patch secret owner ref" err="failed to fetch pod during patching, err: Pod \"everseenconsumerfunction-6bcb4468b6-r7cs6\" not found"
> kubectl get pods -l app=csi-secrets-store-provider-azure -o wide
NAME                                                 READY   STATUS    RESTARTS   AGE   IP              NODE             NOMINATED NODE   READINESS GATES
csi-secrets-csi-secrets-store-provider-azure-zkw5z   1/1     Running   2          25d     Xxxxxx                  XXXXXXXXX   <none>           <none>
csi-secrets-store-provider-azure-1608059928-cwpfr    1/1     Running   0          9d    xxxxxxx                XXXXXXXXXX  <none>           <none>
> kubectl logs csi-secrets-csi-secrets-store-provider-azure-zkw5z --since=1h | grep ^E
> kubectl logs csi-secrets-csi-secrets-store-provider-azure-zkw5z --since=1800h | grep ^E
> kubectl logs csi-secrets-csi-secrets-store-provider-azure-zkw5z --since=1800000h | grep ^E

2. Do i need to delete the existing CSI driver and re-install the new one with secrets-store-csi-driver.syncSecret.enabled=true and secrets-store-csi-driver.enableSecretRotation=true ?
I tried without deleting the existing CSI driver and tried to enable the sync and rotation =true as below but getting error

> helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
"csi-secrets-store-provider-azure" has been added to your repositories
> helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure secrets-store-csi-driver.syncSecret.enabled=true
Error: failed to download "secrets-store-csi-driver.syncSecret.enabled=true" (hint: running `helm repo update` may help)
> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "csi-secrets-store-provider-azure" chart repository
Update Complete. ⎈Happy Helming!⎈
> helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure secrets-store-csi-driver.syncSecret.enabled=true
Error: failed to download "secrets-store-csi-driver.syncSecret.enabled=true" (hint: running `helm repo update` may help)

**Comment by aramase** [comment]
@akashsg I don't see any errors in the logs you posted. The owner reference one should be fine but other than that there are no error messages in the output. 

For setting helm values you need to use `--set` as part of helm install/upgrade. You can upgrade the existing helm deployment or delete/reinstall. All the supported helm configuration values are here: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration.
