### ISSUE TITLE
Get all versions of a keyvault object

### ISSUE THREAD

**Issue by aramase** [Azure/secrets-store-csi-driver-provider-azure#571]
Issue: #557 

Currently there isn't an option to pull all the available versions of a certificate from Azure keyvault. There is an option to pull a certificate by providing objectVersion but we have a scenario where we want all the versions of a certificate (including the older versions). Currently this involves manually looking up the objectVersion and updating the manifest

 #482

It would be useful to specify objectVersion: "*" and have all versions of that secret retrieved. They could be mounted on the volume either as secret-name/version or secret-name-version.

The driver for this is the .Net Data Protection API. This allows use of certificates to protect the key. In order to provide backwards compatibility when the certificate updates you can pass in previous certs. At present this would have to be done by manually looking up the versions and putting them in the manifest.

**Comment by ivanalfonso-msft** [comment]
Hello, does anyone knows if this request has been evaluated/considered for implementation?

We have a need that should be satisfied by this feature, we need to keep the latest _**n**_ versions mounted with **autorotation**.

```
objectAlias: name-v0
objectVersion: "latest"
...
objectAlias: name-v1
objectVersion: "latest-1"
...
objectAlias: name-v2
objectVersion: "latest-2"
...
```

**Comment by lnr0626** [comment]
Howdy! We also need this functionality and so I'm considering implementing it. If I put up a PR, would y'all accept this as a contribution?

**Comment by mrjamiebowman** [comment]
This would be very useful for Key Rotation in Identity Server with Azure Key Vault. We need the current and older version of the certificate for that process.
