### ISSUE TITLE
No mention of volumeHandle in https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/

### ISSUE THREAD

**Issue by shicholas** [Azure/secrets-store-csi-driver-provider-azure#577]
The volumeHandle attribute looks like it's now required as part of the CSI - https://kubernetes.io/docs/concepts/storage/volumes/#csi. This caused our TF module to fail trying to replicate the same instructions as here. I think this can be any string? But I'm not too sure.

**Comment by aramase** [comment]
@shicholas What was the error in TF module for the secrets-store-csi-driver?

The secrets-store-csi-driver supports ephemeral volumes. So only the `NodePublishVolume` and `NodeUnpublishVolume` grpc calls are required. Those 2 calls don't required the `volumeHandle`.

**Comment by shicholas** [comment]
it said 'volume_handle' is required. I can try creating an ephemeral volume to get around this.

**Comment by shicholas** [comment]
it looks like this is a known issue, closing this. thanks for the explanation 

https://github.com/hashicorp/terraform-provider-kubernetes/issues/1086
