### ISSUE TITLE
Enable NGINX Ingress Controller with TLS

### ISSUE THREAD

**Issue by DavidMarquezF** [Azure/secrets-store-csi-driver-provider-azure#583]
I believe that the [setup](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/ingress-tls/#deploy-secrets-store-csi-driver-and-the-azure-key-vault-provider) of the csi is not correct for the tutorial since it uses secrets but doesn't enable the secret syncing feature.

The correct install with helm would be the following:
```
helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set secrets-store-csi-driver.syncSecret.enabled=true
```

I can create a pull request if this is correct

**Comment by nilekhc** [comment]
Hi @DavidMarquezF Thanks for reporting this. Your observation is right. We recently disabled synching secrets by default.

PR is always welcome 👍🏻
