### ISSUE TITLE
Unable to get access to Keyvault secrets using RBAC.

### ISSUE THREAD

**Issue by saif-cl0ud** [Azure/secrets-store-csi-driver-provider-azure#585]
**Have you**

- [ YES] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [YES ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[error_kv_cg.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/6880336/error_kv_cg.txt)

We are trying to integrate Azure Keyvault with RBAC to AKS using secret store csi driver and using pod identity to authenticate.
So we have mutiple secrets within the same keyvault. And these secrets are being accessed through specific manage identity.
So some deployment are working with the integration but couple of them are not able to read the secret and throwing RBAC error even the required access has been provided.
When i am running describe commands i can see it's accessing the secrets with different object id of different Identity. And its been changing. These object ids are not correct for given manage identity.

**What did you expect to happen:**
It should access the keyvault correctly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Earlier we had multiple Keyvaults with different set of secrets and these secrets accessed through pod identity. We have separate identity for each keyvault. The keyvaults were using access policy to read the value of secret. Everything is working with this setup. 
Later we wanted to move all these secrets in single keyvault (with RBAC). The respective management identity will have read access to selective secrets in the KV. But this setup is not stable its working for some secrets but not others.

**Which access mode did you use to access the Azure Key Vault instance:**
 
Pod Identity,

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): provider-azure:0.0.7
- Azure Key Vault provider version: (use the image tag): provider-azure:0.0.7
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68e3e47dad98b808ba41087c0c62e80cd4fcec36", GitTreeState:"clean", BuildDate:"2021-05-25T02:41:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@saif-cl0ud Thank you for reporting the issue. Could you share the following details?

1. `SecretProviderClass` yaml with sensitive info redacted
2. `Pod` yaml
3. Are you using provider version `0.0.7` or helm chart version `0.0.7`?
4. Logs from the driver and provider pods running on the same node as your app.

The error you shared seem to indicate the auth method isn't pod identity.

**Comment by saif-cl0ud** [comment]
**SecretProviderClass YAML:**

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  annotations:
    meta.helm.sh/release-name: comm-gateway-api
    meta.helm.sh/release-namespace: internal-api
  creationTimestamp: "2021-03-24T19:48:08Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.16.0
    application: comm-gateway-api
    environment: dev
    helm.sh/chart: comm-gateway-api-0.1.0
    owner: internal-api-team
    product: communicationgateway
    region: east-us2
    tier-level: "4"
  name: comm-gateway-api
  namespace: internal-api
  resourceVersion: "114323260"
  selfLink: /apis/secrets-store.csi.x-k8s.io/v1alpha1/namespaces/internal-api/secretproviderclasses/comm-gateway-api
  uid: 594473axxx54fd4
spec:
  parameters:
    keyvaultName: AzDevIntApiCommGwKV
    objects: "array:\n  - | \n     objectName: twilioAccountSid \n     objectType:
      secret\n     objectVersion: \n     objectAlias: \n  - | \n     objectName: twilioAuthToken
      \n     objectType: secret\n     objectVersion: \n     objectAlias: \n  - | \n
      \    objectName: twiliomessageserviceid \n     objectType: secret\n     objectVersion:
      \n     objectAlias: \n  - | \n     objectName: authenticationClientId \n     objectType:
      secret\n     objectVersion: \n     objectAlias: \n  - | \n     objectName: authenticationClientSecret
      \n     objectType: secret\n     objectVersion: \n     objectAlias: \n  - | \n
      \    objectName: clientid \n     objectType: secret\n     objectVersion: \n
      \    objectAlias: \n  - | \n     objectName: clientsecret \n     objectType:
      secret\n     objectVersion: \n     objectAlias: \n  - | \n     objectName: testtwilioaccountsid
      \n     objectType: secret\n     objectVersion: \n     objectAlias: \n  - | \n
      \    objectName: testtwilioauthtoken \n     objectType: secret\n     objectVersion:
      \n     objectAlias: \n  - | \n     objectName: sendgridkey \n     objectType:
      secret\n     objectVersion: \n     objectAlias: \n  - | \n     objectName: twiliopathservicesid
      \n     objectType: secret\n     objectVersion: \n     objectAlias: \n  - | \n
      \    objectName: testtwiliopathservicesid \n     objectType: secret\n     objectVersion:
      \n     objectAlias: \n"
    resourceGroup: AzKeyVaultsIntApiRG
    subscriptionId: xxx
    tenantId: xxx
    usePodIdentity: "true"
  provider: azure
  
**Pod YAML:**

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-29T15:48:40Z"
  generateName: comm-gateway-api-dev-6bb4c96849-
  labels:
    aadpodidbinding: AzDevIntApiCommGwKVidentity
    app.kubernetes.io/instance: comm-gateway-api
    app.kubernetes.io/name: comm-gateway-api
    pod-template-hash: 6bb4c96849
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:aadpodidbinding: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"32f46341-497f-44d5-9103-1ea37d57dee8"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"comm-gateway-api"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"ASPNETCORE_BASEPATH"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"ASPNETCORE_ENVIRONMENT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"NLOG_CONFIG_FILE_LOCATION"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"SECRETS_MOUNT_PATH"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":80,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/mnt/nlog"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/mnt/secrets-store"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:imagePullSecrets:
          .: {}
          k:{"name":"sharedacr"}:
            .: {}
            f:name: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"nlog-config-volume"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"secrets-store-inline"}:
            .: {}
            f:csi:
              .: {}
              f:driver: {}
              f:readOnly: {}
              f:volumeAttributes:
                .: {}
                f:secretProviderClass: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-07-29T15:48:40Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.100.52.118"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-07-29T15:50:12Z"
  name: comm-gateway-api-dev-6bb4c96849-vtwrj
  namespace: internal-api
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: comm-gateway-api-dev-6bb4c96849
    uid: 32f46341-497f-44d5-9103-1ea37d57dee8
  resourceVersion: "120387283"
  selfLink: /api/v1/namespaces/internal-api/pods/comm-gateway-api-dev-6bb4c96849-vtwrj
  uid: 59e63126-0512-414e-87f2-e2af6ef1593a
spec:
  containers:
  - env:
    - name: ASPNETCORE_ENVIRONMENT
      value: staging
    - name: SECRETS_MOUNT_PATH
      value: /mnt/secrets-store
    - name: ASPNETCORE_BASEPATH
      value: /communicationgateway
    - name: NLOG_CONFIG_FILE_LOCATION
      value: /mnt/nlog
    image: registry6be1369c817b722a.azurecr.io/int-api-comm-gateway:5566f2c8011bf4f21ea6de1a747f2eab76d5a2b4
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /communicationgateway/api/health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    name: comm-gateway-api
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /communicationgateway/api/health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 700m
        memory: 500Mi
      requests:
        cpu: 700m
        memory: 500Mi
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/nlog
      name: nlog-config-volume
    - mountPath: /mnt/secrets-store
      name: secrets-store-inline
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4nk78
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: sharedacr
  nodeName: aks-nodepool2-17585647-vmss000010
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: comm-gateway-api
    name: nlog-config-volume
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: comm-gateway-api
    name: secrets-store-inline
  - name: default-token-4nk78
    secret:
      defaultMode: 420
      secretName: default-token-4nk78
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T15:48:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T15:50:12Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T15:50:12Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T15:48:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://64ced410c1d9d275e5296d695c894005983bbc7170ef336996f5eee44e16f474
    image: registry6be1369c817b722a.azurecr.io/int-api-comm-gateway:5566f2c8011bf4f21ea6de1a747f2eab76d5a2b4
    imageID: docker-pullable://registry6be1369c817b722a.azurecr.io/int-api-comm-gateway@sha256:d2787327fcf0a21805db53c76c37055c496b62623885c8d371081283a4960d37
    lastState: {}
    name: comm-gateway-api
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-29T15:48:46Z"
  hostIP: 10.100.52.64
  phase: Running
  podIP: 10.100.52.118
  podIPs:
  - ip: 10.100.52.118
  qosClass: Guaranteed
  startTime: "2021-07-29T15:48:40Z"
  

**Versions:**

saif@SAIFRAHM-M-V0EV ~ % helm -n secrets-store-csi-driver  ls
NAME                                       	NAMESPACE               	REVISION	UPDATED                             	STATUS  	CHART                                 	APP VERSION
csi-secrets-store-provider-azure-1597163285	secrets-store-csi-driver	1       	2020-08-11 09:28:09.476303 -0700 PDT	deployed	csi-secrets-store-provider-azure-0.0.9	0.0.7      

Auth Method is pod identity.

**Comment by aramase** [comment]
@saif-cl0ud Please provide the logs
