### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by ritazh** [Azure/secrets-store-csi-driver-provider-azure#59]
- [ ] table of content
- [ ] demo to show how the solution works
- [ ] diagram to show how diff components work together

**Comment by ankitbko** [comment]
CSI driver works perfectly in [KIND](https://kind.sigs.k8s.io/) using Service Principle. Let me know if you need a  doc or sample around it.

**Comment by ritazh** [comment]
@ankitbko yes that would be great! 👏
