### ISSUE TITLE
Job.batch invalid value - must be no more than 63 characters

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/secrets-store-csi-driver-provider-azure#592]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

During the `helm upgrade` the update failed due to this error: 
```shell
Upgrade "csi-secrets-store-provider-azure" failed: pre-upgrade hooks failed: warning: Hook pre-upgrade csi-secrets-store-provider-azure/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml failed: Job.batch "csi-secrets-store-provider-azure-secrets-store-csi-driver-upgrade-crds" is invalid: spec.template.labels: Invalid value: "csi-secrets-store-provider-azure-secrets-store-csi-driver-upgrade-crds": must be no more than 63 characters
```

**What did you expect to happen:**

The `Job.batch` name string truncation if it exceeds 63 characters. 

**Anything else you would like to add:**

Not relevant

**Which access mode did you use to access the Azure Key Vault instance:**

Not relevant

**Environment:**

Secrets Store CSI Driver version: 0.1.0
The chart is installed with the name `csi-secrets-store-provider-azure`
Other informations are not relevant.

**Comment by pierluigilenoci** [comment]
@aramase could you please take a look, I think it's pretty critical stuff.

**Comment by nilekhc** [comment]
@pierluigilenoci Thanks for reporting this. We append certain string to release name. In this case `-secrets-store-csi-driver-upgrade-crds`

Could you try with shorter release name instead of `csi-secrets-store-provider-azure`?

**Comment by pierluigilenoci** [comment]
@nilekhc I wish I could have the freedom to choose the release name based on the specifications of `helm`.
I will wait for the [fix](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/665) from @aramase.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/608 which sets `fullnameOverride` for the driver charts to `secrets-store-csi-driver`. Please feel free to open a new issue if you have any questions.
