### ISSUE TITLE
Difference between this driver and sig

### ISSUE THREAD

**Issue by jabbera** [Azure/secrets-store-csi-driver-provider-azure#604]
Can someone explain the difference between this driver and the sig driver located here: https://github.com/kubernetes-sigs/secrets-store-csi-driver

I'm very confused.

Thanks!

**Comment by aramase** [comment]
@jabbera Thank you for opening the issue!

This repo is the implementation of Azure Keyvault for the Secrets Store CSI Driver. It's not a different project. The Secrets Store CSI Driver supports multiple secrets store providers and has a pluggable interface.

Check out https://secrets-store-csi-driver.sigs.k8s.io/concepts.html

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/604#issuecomment-895353564. Please feel free to reopen if you have any questions.
