### ISSUE TITLE
Question: Minimum supported secret rotation interval

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#606]
**Question**
The default secrets `--rotation-poll-interval` is 2 minutes.

Is it possible to have a second or millisecond interval? 
I'd like faster or even immediate refresh of mounted secrets to latest Key Vault version.

Does the KV CSI cpu/memory footprint drastically increase if I do this?

**Comment by aramase** [comment]
Thank you for opening the issue! 

How often are you updating the secret/keys in keyvault? 

`second` or `millisecond` is too aggressive. Every rotation call is translated to the keyvault `GET` call for the secrets/keys defined per pod + `SecretProviderClass`. This will exhaust the API limits pretty quickly: https://docs.microsoft.com/en-us/azure/key-vault/general/service-limits.

**Comment by dkirrane** [comment]
Ya, my use case is storing database credentials in Key Vault. 
If we change the credentials then the application have an db connection outage for 2 minutes.

**Comment by aramase** [comment]
As part of rotation, don't the old and new version of database credentials exist for a brief period of time for the clients to pick up the new creds? 

Setting it to a `second` or `millisecond` is aggressive and will exhaust the API limits. If the rate limit is hit, that can prevent further mount requests to succeed until we're past the throttling window.

cc @jlichwa

**Comment by jlichwa** [comment]
Key vault recommends caching for several hours to avoid service outages - so for Key Vault default should be 8 hours.
The recommendation is to always have primary and secondary credentials and alternate rotation between them to prevent any outages.
You can read more about pattern here:
https://docs.microsoft.com/en-us/azure/key-vault/secrets/tutorial-rotation-dual?tabs=azure-cli
