### ISSUE TITLE
"mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io   not found in the list of registered CSI drivers" on AKS windows pods

### ISSUE THREAD

**Issue by Dolevco** [Azure/secrets-store-csi-driver-provider-azure#620]
We have issues with some of our windows pods - we are getting the following error: 
"MountVolume.SetUp failed for volume "kv-volume" : kubernetes.io/csi:
  mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io
  not found in the list of registered CSI drivers"

some of the pods are working (on different nodes) and some are not. I verified the nodes having the same pods installed, including the csi driver for windows:
![image](https://user-images.githubusercontent.com/13572203/130799279-a4a0a264-ede6-4307-bbf8-e79ae7eaba02.png)

And the pod hangs in ContainerCreating state with the these evnets:
![image](https://user-images.githubusercontent.com/13572203/130800327-51e6f771-6356-4191-9689-f102419a9320.png)

**What did you expect to happen:**
Pod should be initialized successfully using the key vault provider 

**Which access mode did you use to access the Azure Key Vault instance:**
 System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.2.0
- Azure Key Vault provider version: (use the image tag): 0.2.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.21.2
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by trhumphries** [comment]
We've seen this issue as well, sometimes restarting the node resolves it

**Comment by Dolevco** [comment]
issue still active

**Comment by aramase** [comment]
Create #639 to summarize this issue and marked it a known-issue. Closing this issue in favor of that.
