### ISSUE TITLE
Unable to retrieve the current version certificate from CSI drivers, its still pointing to older version

### ISSUE THREAD

**Issue by KunalAdu** [Azure/secrets-store-csi-driver-provider-azure#622]
**Have you**

- [-] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [-] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Installed CSI drivers and able to fetch the certificate from the Key vault , Uploaded a new version of certificate as older version is going to expire now in key vault there are two version i.e. current version and Older version if i delete the kubernetes secret it is creating new secret in approx. 5 mints but it is pointing to older version , how to refresh that and point it to new version automatically ?

**What did you expect to happen:**
It should retrieve the current version as secret provider is pointing to keyvault 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by pdonovan** [comment]
@KunalAdu Did you manage to resolve this?

I'm seeing the same behaviour, after deleting the secret it pulled a new one after a few minutes but it didn't get the "Latest" version. It pulled the Certificate version that was previously being used. It's still valid, but it's not the newly-renewed cert (not the one shown as CURRENT VERSION in the Key Vault admin portal).

I'm also using the same Key Vault and same Certificate for a both Front Door instance and for a Front Door (preview) instance. The FAQ for Front Door says that it can take 24 hours for Front Door to see the 'Latest' certificate. And the FD (preview) instance which has a better portal UI that shows the details of the cert it's using does not have the latest "Latest" either. So perhaps it just takes time for Key Vault to report the correct "Latest" version?

**Comment by KunalAdu** [comment]
@pdonovan : Yes , I did a mistake

**Comment by KunalAdu** [comment]
@pdonovan  : Yes its resolved , I missed to add below step while installing CSI drivers 

--set secrets-store-csi-driver.enableSecretRotation=true


Check below issues , this worked for me like a charm  . Now as soon as we updated the certificate in the key vault . It got reflected for our APIs swagger URL If its a router certificate please restart it once 

https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/548
https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/390


Thanks , 
Kunal

**Comment by KunalAdu** [comment]
@pdonovan : Yes its resolved , I missed to add below step while installing CSI drivers 

--set secrets-store-csi-driver.enableSecretRotation=true


Check below issues , this worked for me like a charm  . Now as soon as we updated the certificate in the key vault . It got reflected for our APIs swagger URL If its a router certificate please restart it once 

https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/548
https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/390


Thanks , 
Kunal

**Comment by pdonovan** [comment]
Thanks, I'd missed that switch too.

**Comment by KunalAdu** [comment]
@pdonovan : After adding Is it working ?

**Comment by raghu-manne** [comment]
In my case rotation is working only if i add both the `--set enableSecretRotation=true` and  `--set secrets-store-csi-driver.enableSecretRotation=true` flags to true.
Commenting if in case anyone faces the same issue.
