### ISSUE TITLE
Application pod is container creating state in AKS 1.20.7 with mount failure errors in secret-store logs

### ISSUE THREAD

**Issue by jakond1** [Azure/secrets-store-csi-driver-provider-azure#628]
we has upgraded the AKS to 1.20.7 and application pods stucked in container creating state. The pod is using secret-store and keyvault-secret-store-csi-driver pod has below errors. Where as we added new nodepool with 1.19 in same cluster which is working fine. 

E0830 07:05:54.376166       1 nodeserver.go:190] "failed to mount" err="mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/42ab3156-a955-48c9-9ba6-ecc584c5c2bf/volumes/kubernetes.io~csi/secrets-store-inline/mount\nOutput: mount: /var/lib/kubelet/pods/42ab3156-a955-48c9-9ba6-ecc584c5c2bf/volumes/kubernetes.io~csi/secrets-store-inline/mount: mount point does not exist.\n" pod="default/c
E0830 07:05:54.376186       1 utils.go:103] GRPC error: mount failed: exit status 32.

Namespace:      default
Priority:       0
Node:           aks-XXXXXXXX-xxxxxxxxxx-vmss000000/
Start Time:     Mon, 30 Aug 2021 12:05:16 +0530
Labels:         aadpodidbinding=keyvault-csi-arm
                app=xxx
                pod-template-hash=
Annotations:    release: 62
Status:         Pending
IP:
Controlled By:  ReplicaSet/
Containers:
  xxx:
    Container ID:
    Image:          xxxxxxxxxxx.azurecr.io/
    Image ID:
    Port:           8443/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  6G
    Requests:
      cpu:      125m
      memory:   4G
    Liveness:   http-get https://:8443/xxx/version.txt delay=300s timeout=30s period=10s #success=10 #failure=30
    Readiness:  http-get https://:8443/xxx/version.txt delay=60s timeout=10s period=10s #success=30 #failure=30
    Environment:
      MEM_TOTAL_MB:           6000000000 (limits.memory)
      env:                    dev
      context:                xxx
      datacenter:             xxxxxxx
      splunk_url:             https://splunk.
    
    Mounts:
      /mnt/secrets-store from secrets-store-inline (ro)

Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  xxx-pv:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cxx-xxx
    ReadOnly:   false
  secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=cs-secret-provider-kv
  default-token-xxxxx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xxxxx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  agentpool=xxxxxxx
                 agentpoolType=xxxx
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s

**Comment by jakond1** [comment]
@aramase To check this issue please

**Comment by vivekjilla** [comment]
@jakond1 How did this issue get resolved for you. We're also hitting into this exact issue. Can you please help.

**Comment by jakond1** [comment]
@vivekjilla  We have updated chart version to 0.20 and pods came to running state

**Comment by xieskysky** [comment]
@jakond1 , we see the same thing when trying to upgrade from K8S 1.19 to K8S 1.20. Did you upgrade yaml including the CSI driver container images? What was your previous CSI driver version? What did you upgrade to? Can you share some details how you fixed the issue?
