### ISSUE TITLE
Connection refuse to Azure Key Vault

### ISSUE THREAD

**Issue by tasb** [Azure/secrets-store-csi-driver-provider-azure#632]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Installed Secret Store using AKS addon, created and granted access to a Managed Identity and make all configuration stated on walkthrough I got a "Connection Refused" message like this:

Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  35m (x276 over 9h)    kubelet  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod cluster-settings/busybox-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
  Warning  FailedMount  9m22s (x62 over 9h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-jljg9 secrets-store-inline]: timed out waiting for the condition
  Warning  FailedMount  5m16s (x218 over 9h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-jljg9]: timed out waiting for the condition

**What did you expect to happen:**
Manifest for SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-ingress-tls-secret-csi-akv
  namespace: cluster-settings
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "akv-aks"
    objects:  |
      array:
        - |
          objectName: traefik-ingress-internal-aks-ingress-tls
          objectAlias: tls.crt
          objectType: cert
    tenantId: "XXXXXXXXXXXXX"

**Which access mode did you use to access the Azure Key Vault instance:**
PodIdentity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.21
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.14
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.22
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@tasb Did you deploy aad-pod-identity? "Connection refused" seems to indicate that the pod identity is not running in the cluster. This is the doc for using pod identity to access keyvault: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/.

Note: the standard walkthrough is using [Service Principal](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/service-principal-mode/) to access keyvault. If you're using pod identity please make sure you've followed the pod identity mode for setting up access.
