### ISSUE TITLE
Secrets-Store CSI Driver running AKS-Engine (Stack Hub) unable to connect to Stack Hub Key Vault

### ISSUE THREAD

**Issue by pengjz89** [Azure/secrets-store-csi-driver-provider-azure#633]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The following is the error log
server.go:55] "failed to process mount request" err="failed to get objectType:secret, objectName:<secret_name>, objectVersion: keyVault.Base#GetSecret: Failure sending request: Status=0 --Original Error: context cancelled"

The following is the configuration that I have made for the custom environment to point to Azure Stack Hub KeyVault

- Custom Environment File Json
{“name”:”AzureStackCloud”,”activeDirectoryEndpoint”:”https://login.microsoftonline.com/”,”keyVaultEndpoint”,”https://vault.$domain.onmicrosoft.com/$unique_variables”,”keyVaultDNSSuffix”:”vault.$region.$domain”}     

This json is mounted based on the following configuration in the helm values.yaml

  volumes:
    - name: cloudenvfile-vol
      hostPath:
        path: "/etc/kubernetes"
  volumeMounts:
    - name: cloudenvfile-vol
      mountPath: "/custom-azurestackcloud.json"
      subPath: "custom-azurestackcloud.json"

**What did you expect to happen:**
- We verified the connectivity to the AAD Authentication to retrieve the OAuth Token has no issue as we are able to see the request traffic in the authentication logs
- However we suspected that the CSI Driver didn't manage to reach the Azure Stack Hub KeyVault as we received a statuscode=0.

With reference to the autorest package, the reason we gotten the statuscode=0 is because the resp is nil.
https://github.com/Azure/go-autorest/tree/master/autorest/azure

![image](https://user-images.githubusercontent.com/24364463/132657044-7cbf8034-99ba-47ab-a34f-a0cc5c842863.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): CSI-Node-Driver-Registrar-v2.2.0, Driver:v0.1.0, LivenessProbe:v2.3.0
- Azure Key Vault provider version: (use the image tag): v0.1.0 
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.18.15
- Cluster type: (e.g. AKS, aks-engine, etc): AKS-engine

**Comment by aramase** [comment]
> server.go:55] "failed to process mount request" err="failed to get objectType:secret, objectName:<secret_name>, objectVersion: keyVault.Base#GetSecret: Failure sending request: Status=0 --Original Error: context cancelled"

This error usually indicates the request to keyvault didn't complete and the context deadlined. The default context timeout is 2m3s for the volume mount is expected to be complete by then. It's possible the endpoint and the dns suffix for keyvault is correct? I tried this on my cluster to validate csi driver is getting the custom endpoint for keyvault for `AzureStackCloud` and can confirm it works as expected. In my scenario the request timed out because the endpoint I configured for custom cloud is invalid:

```console
E0909 23:06:03.671735       1 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:secret1, objectVersion:: keyvault.BaseClient#GetSecret: Failure sending request: StatusCode=0 -- Original Error: context canceled"
```

But the correct vault url is being used:
```console
I0909 23:04:03.808519       1 provider.go:267] "vault url" vaultName="kindkv" vaultURL="https://kindkv.vault.mydomain.net/" pod="default/csi-linux-pod"
```

**Comment by pengjz89** [comment]
Thanks @aramase for your help.

We managed to resolve the issue by setting the following two files for csi secret-store-provider via worker node volumeMount 
- AzureStackCloud Configuration: /etc/kubernetes/azurestackcloud.json
- SSL Certificates : /etc/ssl/cert/ca-certificates.crt

AKS-Engine is configured with a specific domain and specific root certificate.
AzureStackCloud is used to provide CSI-Secret-Store-Provider with the domain prefix required
SSL CA Certificates is used to connect to the Azure Stack Hub Key Vault HTTPS Endpoint.
