### ISSUE TITLE
`mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers` on windows nodes

### ISSUE THREAD

**Issue by aramase** [Azure/secrets-store-csi-driver-provider-azure#639]
**Steps To Reproduce**

1. Deploy the Secrets Store CSI Driver and Azure Key Vault Provider on windows nodes.
2. Deploy a pod on windows node with a volume spec referencing the Secrets Store CSI Driver.
3. The pod will be stuck in `ContainerCreating` state. On inspecting the pod with `kubectl describe pod`, the following error message is seen:
```log
mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
```

**Expected behavior**
As the driver is running on the windows node, volume mount should succeed and pod start running.

**Root cause**
The driver is registered with kubelet when it's initially deployed to the node. This is done by the `node-driver-registrar` sidecar container in the the driver pod. This behavior is not working as expected because of an issue in kubelet that is being investigated in https://github.com/kubernetes/kubernetes/issues/104584.

**Mitigation**
1. Restarting the driver pod on the windows node to force the registration fixes the issue. In some scenarios this requires multiple restarts before the kubelet recognizes the socket and successfully registers the driver.
2. The Kubernetes CSI community has added a livenessprobe check in the `node-driver-registrar` container to check if the registration is complete. If not, it'll fail the livenessprobe check and restart the `node-driver-registrar` until it succeeds. This was introduced in node-driver-registrar release [v2.3.0](https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.3.0). The latest helm charts in this repo use that image and have livenessprobe configured for the `node-driver-registrar` container.

The long term fix in kubelet is being investigated in https://github.com/kubernetes/kubernetes/issues/104584. This issue most commonly occurs in Kubernetes v1.21+ and can affect the AKS managed add-on for Secrets Store CSI Driver too.

**Comment by Uvindu96** [comment]
@aramase I faced the same issue after upgrading the CSI driver from version 0.0.14 to v0.2.0. I'm running the CSI driver in linux node. So I think this not only happening in windows instances.To upgrade the CSI driver I used the following command,
`helm upgrade csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --namespace kube-system`

**Comment by aramase** [comment]
The fix in k/k is merged: https://github.com/kubernetes/kubernetes/pull/110075 and will be in next release.
