### ISSUE TITLE
Not able to create a secretproviderclasses resource

### ISSUE THREAD

**Issue by chintanr97** [Azure/secrets-store-csi-driver-provider-azure#64]
If I am not wrong, we must use the following command to create the secretproviderclasses resource, right?

`kubectl apply -f <resource-filename>.yaml`

But when I use sample given in the README to create a new secretproviderclasses resource, I get the following error:

error: unable to recognize "resource-filename.yaml": no matches for kind "SecretProviderClass" in version "secrets-store.csi.x-k8s.io/v1alpha1"

**Comment by ritazh** [comment]
Hi @chintanr97 can you please check if you have the `SecretProviderClass` crd installed in the cluster? 
```bash
kubectl get crd      
                                                               
NAME                                          
secretproviderclasses.secrets-store.csi.x-k8s.io   
```
If not, please checkout https://github.com/Azure/secrets-store-csi-driver-provider-azure#install-the-secrets-store-csi-driver

**Comment by chintanr97** [comment]
Hi @ritazh I installed the driver. When I start to deploy the sample yaml file to validate if the driver is working correctly, I get the following error:

```
* spec.volumes[0]: Required value: must specify a volume type
* spec.containers[0].volumeMounts[0].name: Not found: "secrets-store-inline"
```

I am using the same yaml file as specified in 
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/nginx-pod-secrets-store-inline-volume-secretproviderclass.yaml

**Comment by chintanr97** [comment]
Hi @ritazh I solved that using the suggested steps. Thanks.

But now when I try to deploy my app, I wish to mount an "Elliptic Curve" Key in the application pod. But I am getting this error for that:

```
Events:
  Type     Reason       Age   From                                        Message
  ----     ------       ----  ----                                        -------
  Normal   Scheduled    40s   default-scheduler                           Successfully assigned default/certs-store to aks-agentpool-19909641-vmss000001
  Warning  FailedMount  38s   kubelet, aks-agentpool-19909641-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e4b08]

goroutine 1 [running]:
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure.(*Provider).GetKeyVaultObjectContent(0xc0003b7eb8, 0x831620, 0xc00001a018, 0xc00001ab88, 0x3, 0xc00001ab50, 0xc, 0x0, 0x0, 0xc0003eec00, ...)
  /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure/provider.go:431 +0x13f8
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure.(*Provider).MountSecretsStoreObjectContent(0xc0003b7eb8, 0x831620, 0xc00001a018, 0xc00005f260, 0xc00005f290, 0x7ffc950fdd55, 0x6f, 0xc0000001a4, 0x7b21b9, 0x7)
  /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure/provider.go:387 +0xa6d
main.main()
           /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/cmd/main.go:67 +0x42b
  Warning  FailedMount  36s  kubelet, aks-agentpool-19909641-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e4b08]
```

I was getting this error with the Flex Volume too. I switched my testing to "secrets-store-csi-driver" for that. But again facing the same issue.

**Comment by chintanr97** [comment]
Thanks @ritazh that solved the issue.
