### ISSUE TITLE
Client does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action'

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/secrets-store-csi-driver-provider-azure#66]
I followed the steps for using Pod Identity and went into this error:
**$ kubectl logs mic-76dd75ddf9-8g8k8**
E0429 15:46:14.771807       1 vmss.go:73] Failed to update VM with error compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '00000000-28c9-4944-acc4-a08277f0044b' with object id '00000000-28c9-4944-acc4-a08277f0044b' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/00000000-7ca3-4e76-8d0f-31a2c0bee7a3/resourceGroups/MC_demo-rg_aks-demo_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-51725664-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/00000000-7ca3-4e76-8d0f-31a2c0bee7a3/resourcegroups/demo-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-aks-kv' or the linked scope(s) are invalid."

And when running **$ az aks show**, I get it tells me there's no identity! When I created this cluster I selected "Service Principal" from the portal.
  "identity": null,
  "identityProfile": null,

Any help, please ?

**Comment by aramase** [comment]
@HoussemDellai Did your cluster service principal have the correct role assignments, specifically `Managed Identity Operator` on the identity?

```
az role assignment create --role "Managed Identity Operator" --assignee <service principal id>  --scope /subscriptions/<subscription id>/resourcegroups/<resource group name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity name>
```

**Comment by aramase** [comment]
```
however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/00000000-7ca3-4e76-8d0f-31a2c0bee7a3/resourcegroups/demo-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-aks-kv' or the linked scope(s) are invalid."
```

It looks like the cluster service principal does not have permission to assign the identity to the VMSS. 

Could you try running the following commands to grant your service principal Managed Identity Operator role under your resource group scope.

```
az aks show -g <resource group> -n <ask cluster name> --query servicePrincipalProfile.clientId -o tsv
az role assignment create --role "Managed Identity Operator" --assignee <client id from above command>  --scope /subscriptions/<sub id>/resourcegroups/<resource group name>
```

**Comment by HoussemDellai** [comment]
Hi @aramase 
<service principal id> should be the SPN for my AKS cluster ? i.e the one from here?
  "servicePrincipalProfile": {
    "clientId": "**00000000-d4ae-4efe-8ffa-457eb0313668**"
  },

**Comment by aramase** [comment]
@HoussemDellai that's right!

**Comment by HoussemDellai** [comment]
And that works :) Thank you so much @aramase

**Comment by aramase** [comment]
That's great! Closing this issue for now but feel free to re-open it if you have any other issues.
