### ISSUE TITLE
mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers on Linux node

### ISSUE THREAD

**Issue by Uvindu96** [Azure/secrets-store-csi-driver-provider-azure#699]
**What steps did you take and what happened:**

1. Upgrading CSI driver chart version 0.0.14 to latest version.
2. After upgrading to the latest version when I deploy a sample pod my pod status is blocked in "ContainerCreating" status.

**What did you expect to happen:**
volume mount should succeed and pod start running.

**Anything else you would like to add:**
Command I used to upgrade the driver is `helm upgrade csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set secrets-store-csi-driver.syncSecret.enabled=true --namespace kube-system`

I tried to upgrade to the both 0.2.0 and 1.0.0 version, and in both scenarios I go the same error.

all the AKS nodes has a CSI driver pod running and when I restart the CSI driver pod, test pods which are stuck in "ContainerCreating" stage will start to run. If I restart the CSI driver pods test pod will start running, But this will not a acceptable answer in some cases such as production environments, can I have a better soultion for this?

![podstatus](https://user-images.githubusercontent.com/31029812/134816317-9763817b-6282-4ae9-b52f-d75227878b66.png)

**Environment:**
- identity: user-assigned managed identity
- Secrets Store CSI Driver version: (1.0.0):
- Azure Key Vault provider version: (1.0.0):
- Kubernetes version: (1.19.1):
- Cluster type: (AKS):
- Node type : (Linux)

**Comment by nilekhc** [comment]
Hey @Uvindu96 Continuing our disucssion from https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/655, were you able to try it out in another test env? We recommend to install table `v1.0.0` for both driver and provider.

**Comment by iamworldsky** [comment]
I encountered the same problem from v0.0.19 to v0.2.0,  I have tried many times to reproduce it. must need to restart CSI pods to fix it.

but I tried to upgrade from v0.0.19 to v1.0.0, it works

Environment:

- identity: user-assigned managed identity
- Secrets Store CSI Driver version: (0.0.19):
- Azure Key Vault provider version: (0.0.19):
- namespace: secrets-store-provider
- Kubernetes version: (1.20.7):
- Cluster type: (AKS):
- Node type : (Linux)
