### ISSUE TITLE
AKS Vulnerability issue -Running containers as root user should be avoided 

### ISSUE THREAD

**Issue by KGAJUL** [Azure/secrets-store-csi-driver-provider-azure#700]
Issue:

We have AKS cluster deployed in multiple environments and we deployed CSI secret store in AKS cluster but Azure Security center reported one of the vulnerability "Running containers as root user should be avoided" 

What we have done to resolve:

We have followed the Microsoft documentation "https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/deployment/provider-azure-installer.yaml" and tried to run as NonRootUser but it is failing with error message( attached screenshot) 
![Error](https://user-images.githubusercontent.com/93394647/139474016-cb429b2a-99c2-4688-bbd2-8321341287c5.PNG)

We would like to see if there are any other options or solutions to run this as NonRootUser to resolve this vulnerability.

**Comment by KGAJUL** [comment]
@aramase , Thank you for the quick response and recommendation. We have deployed in "kube-system" and this issue is fixed for now but my question is if we deploy this provider in kube-system then it would suppress the vulnerabilities in Security center but Is this recommended approach from Microsoft? Can you please help me understand?

**Comment by aramase** [comment]
@KGAJUL For the provider, it needs to run as root to be able to perform the operations. As it runs as root, it's high privilege and we recommend deploying in `kube-system`. This is the recommendation for this project.
