### ISSUE TITLE
The provider isn't compatible with RHCOS

### ISSUE THREAD

**Issue by Makdaam** [Azure/secrets-store-csi-driver-provider-azure#704]
**What steps did you take and what happened:**
Secrets Store CSI driver is incompatible with Red Hat CoreOS (RHCOS) based nodes used for example in OpenShift products like Azure Red Hat OpenShift.

It places a socket (azure.sock) in /etc/kubernetes/secrets-store-csi-providers which is not expected in RHCOS, as /etc is expected to be managed by the Machine Config Operator in a transactional way. See:
https://docs.openshift.com/container-platform/4.7/architecture/architecture-rhcos.html#rhcos-key-features_architecture-rhcos

This causes the Machine Config Operator to fail validation of the ostree since the socket in /etc can't be verified. https://bugzilla.redhat.com/show_bug.cgi?id=1945274 describes a similar case.

**What did you expect to happen:**
That the socket and other files not managed by Machine Config Operator would be placed in /run.

**Which access mode did you use to access the Azure Key Vault instance:**
N/A

**Environment:**

- Secrets Store CSI Driver version: v0.0.18
- Azure Key Vault provider version: 0.0.11
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.20.0
- Cluster type: (e.g. AKS, aks-engine, etc): ARO

**Comment by aramase** [comment]
@Makdaam How are you deploying the driver and provider? The provider volume path is configurable and you can change it to a different path if `/etc` is not accepted in RHCOS.

For the driver:
1. Use this flag to configure custom path for provider sock: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/deploy/secrets-store-csi-driver.yaml#L57
2. Update the volume mount path here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/deploy/secrets-store-csi-driver.yaml#L96-L97
3. Update the volume here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/deploy/secrets-store-csi-driver.yaml#L136-L139

For the provider:
1. Update the volume here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/deploy/secrets-store-csi-driver.yaml#L136-L139

If you're using helm charts, this is customizable in the driver. For the provider we can make it customizable. Let us know if you try out the above changes and it works.

Also, `v0.0.18` for driver and ` 0.0.11` for provider is old release and is not supported. I would recommend using the latest stable release.
