### ISSUE TITLE
Azure Key Vault and private link using pod identity

### ISSUE THREAD

**Issue by franzoir** [Azure/secrets-store-csi-driver-provider-azure#711]
I'm doing some testing now accessing AKV with private link using Pod Identity and have problems with fetching secrets successfully. 

My current lab config: 
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: operations-lab-azureidentity
  namespace: operations-lab
spec:
 type: 0 # (0=Azure Id, 1=Service Principal)
 resourceID: *redacted*
 clientID: *redacted*

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: operations-lab-azureidentitybinding
  namespace: operations-lab
spec:
  azureIdentity: operations-lab-azureidentity # must match the value in AzureIdentity
  selector: operations-lab-identity # label value to match for the pods
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvaultName-grafana-lab-spc
  namespace: operations-lab
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: grafanasecret
    type: Opaque
    data: 
    - objectName: adminpassword                    # name of the mounted content to sync. this could be the object name or object alias 
      key: adminpwd
  parameters:
    usePodIdentity: "true"
    keyvaultName: *redacted*
    objects: |
      array:
        - |
          objectName: grafana-oauth-creds-lab
          objectType: secret
          objectAlias: oauthsecret
          objectVersion: ""
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectAlias: adminpassword
          objectVersion: ""
    tenantId: *redacted*

``` 

And some logs from the CSI store: 
```
I1103 20:31:54.713723       1 auth.go:77] "using pod identity to retrieve token" pod="operations-lab/grafana-7746f8494c-4fr54"
I1103 20:31:54.731171       1 auth.go:111] "successfully acquired access token" accessToken="eyJ0##### REDACTED #####D0sw" clientID="f105##### REDACT####8e4a" pod="operations-lab/grafana-7746f8494c-4fr54"
I1103 20:31:54.731202       1 provider.go:278] "fetching object from key vault" objectName="grafana-oauth-creds-lab" objectType="secret" keyvault="kbperationskv" pod="operations-lab/grafana-7746f8494c-4fr54"
E1103 20:33:54.703672       1 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:grafana-oauth-creds-labjectVersion:: keyvault.BaseClient#GetSecret: Failure sending request: StatusCode=0 -- Original Error: context canceled"
I1103 20:33:55.755378       1 provider.go:257] "unmarshaled key vault objects" keyVaultObjects=[{ObjectName:grafana-oauth-creds-lab ObjectAlias:oauthet ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:} {ObjectName:grafana-admin-password ObjectAlias:adminpassword ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:}] cou pod="operations-lab/grafana-7746f8494c-4fr54"
E1103 20:33:54.703672       1 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:grafana-oauth-creds-lab, objectVersion:: keyvault.BaseClient#GetSecret: Failure sending request: StatusCode=0 -- Original Error: context canceled"
I1103 20:33:55.755378       1 provider.go:257] "unmarshaled key vault objects" keyVaultObjects=[{ObjectName:grafana-oauth-creds-lab ObjectAlias:oauthsecret ObjectVersion: ObjectType:secret ObjectFormat
```

Based on the troubleshooting docs this points to firewall configuration, but the source network is allowed in AKV. 
nslookup returns the expected private link FQDN. 
Pod identity resource has necessary permissions to get secrets from AKV. 
 
@aramase Am I missing something here?

_Originally posted by @franzoir in https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/670#discussioncomment-1604216_

**Comment by aramase** [comment]
@franzoir To confirm if this is working have you tried any other identity access mode to retrieve the secrets from keyvault (service principal/ managed identity without pod identity)?

You can also try setting `AZURE_GO_SDK_LOG_LEVEL: debug` environment variable in the provider pods. That'll log the actual API calls from the SDK and log the response. It'll provide more info on which call is failing: the token request or keyvault access. 

Looks like @irperez got it working: https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/670#discussioncomment-1606479 but I think he is using service principal based on the `SecretProviderClass`.

**Comment by franzoir** [comment]
I've validated the setup using pod identity and same `SecretProviderClass` against another key vault which isn't configured with private link, but firewall only and it works fine there. 
But for testing purposes I'll do some more debugging and test with managed identity/service principal. 

I will update with outcome.

**Comment by franzoir** [comment]
@aramase (update) I have noticed that all methods of authentication fails/times out. However I cannot see any logs in key vault for failed/forbidden attempts from my source. So it doesn't seem like it even reaches the key vault. I'll will continue with debugging network/routing. 

CSI is deployed into kube-system and I've verified that there isn't any network policies that block egress in-cluster.

**Comment by franzoir** [comment]
Late update: 
We found that the problem was caused by routing issues in our network. So when that was sorted out it worked just fine.

**Comment by aramase** [comment]
Thanks for confirming @franzoir. Based on your investigation anything that you think would be a good addition to our docs? Or the troubleshooting guide?

**Comment by franzoir** [comment]
It would be a good idea to mention the `AZURE_GO_SDK_LOG_LEVEL: debug` environment variable in the troubleshooting guide. 
Add `destination network unreachable/timeout` as a possible reason for the error ref: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/#keyvaultbaseclientgetsecret-failure-sending-request-statuscode0----original-error-context-canceled 

The command: 
` curl --trace-ascii - 'https://<vaultName>.vault.azure.net/secrets/<secretName>?api-version=7.2' -H "Authorization: Bearer <bearerToken>" `
gave some insights when debugging network as well.

**Comment by aramase** [comment]
Thanks for the feedback! We'll get those added to our troubleshooting guide.
