### ISSUE TITLE
Mount fails after upgrading AKS from 1.19.3 to 1.20.9

### ISSUE THREAD

**Issue by kamilzzz** [Azure/secrets-store-csi-driver-provider-azure#713]
**What steps did you take and what happened:**
Started upgrading AKS cluster & node pools from 1.19.3 to 1.20.9.

Secret Store CSI Driver and Secret Store Provider Azure pods started correctly on new nodes with 1.20.9 AKS version.
However, my application pods cannot start due to mount errors, they're stuck in ContainerCreating status.

Events from application pod:
```
Warning  FailedMount  3m46s (x44 over 88m)  kubelet, aks-default-20768531-vmss000000  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/7e006dea-5abb-4cb0-be62-9da3e7a07d1b/volumes/kubernetes.io~csi/secrets-store-inline/mount
Output: mount: /var/lib/kubelet/pods/7e006dea-5abb-4cb0-be62-9da3e7a07d1b/volumes/kubernetes.io~csi/secrets-store-inline/mount: mount point does not exist.
```

**What did you expect to happen:**
Everything work as before update.
Yesterday I was deploying a new application version and everything was working fine.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

Secrets Store Provider was installed using helm charts a while ago:
`helm install secret-store-azure -f config.yaml csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --version 0.0.14 -n keyvault-secret-store --create-namespace`

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.17
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.10
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.20.9
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@kamilzzz `v0.0.17` is an old version of the driver that's no longer supported. Also, there was a change in `v0.0.18` of driver to support kubernetes version v1.20+. Please review the release notes: https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.18 and update to the latest supported versions: 

https://secrets-store-csi-driver.sigs.k8s.io/#project-status
https://azure.github.io/secrets-store-csi-driver-provider-azure/#project-status

**Comment by kamilzzz** [comment]
@aramase thanks.
I was looking at the changelog before because I indeed thought maybe an update is required but somehow I missed it 😊

**Comment by kamilzzz** [comment]
Working fine after upgrading to latest version.
