### ISSUE TITLE
The client does not have permission to perform action 'Microsoft.OperationalInsights/workspaces/sharedkeys/read'

### ISSUE THREAD

**Issue by Nitesh002** [Azure/secrets-store-csi-driver-provider-azure#727]
I have created a Azure Kubernetes Cluster but after that I am getting below error when I am running any commands.

Code: LinkedAuthorizationFailed
Message: The client 'xxxx with object id 'xxxx' has permission to perform action 'Microsoft.ContainerService/managedClusters/write' on scope '/subscriptions/2xxxx/resourceGroups/xxxx/providers/Microsoft.ContainerService/managedClusters/demoAKS_ITE'; however, it does not have permission to perform action 'Microsoft.OperationalInsights/workspaces/sharedkeys/read' on the linked scope(s) '/subscriptions/xxxx/resourcegroups/defaultresourcegroup-ejp/providers/microsoft.operationalinsights/workspaces/defaultworkspace-xxxx' or the linked scope(s) are invalid.

Please suggest.

**Comment by nilekhc** [comment]
Hello @Nitesh002, Is this related to Secrets Store CSI AKV provider project? If you are planning to use Secrets Store CSI driver, it's available as managed add-on on AKS.
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
