### ISSUE TITLE
Azure CSI driver causes OpenShift to be un-upgradable

### ISSUE THREAD

**Issue by paulczar** [Azure/secrets-store-csi-driver-provider-azure#735]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

The CSI driver uses `/etc/kubernetes/...` for the shared csi socket, this causes issues with Red Hat Container Linux's immutable nature, and the OpenShift upgrader cannot upgrade a cluster with it installed. 

Moving the CSI driver to `/var/run/...` fixes the issue, and is a more canonical place to run sockets.

**Comment by aramase** [comment]
Duplicate of https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/704. The providers dir is made is already made configurable in helm charts and is pending chart release.
