### ISSUE TITLE
Synced Kubernetes Secrets were not updated when the value changed in KeyVault

### ISSUE THREAD

**Issue by chrisamert** [Azure/secrets-store-csi-driver-provider-azure#740]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
We have a cluster running v1.0.0 of the Helm chart, and this particular cluster does NOT have the auto-rotation feature enabled.

We needed to change a certificate in KeyVault and update all pods to use the new cert.  We generated the new version, then used `kubectl rollout restart` to restart all the deployments using this certificate. When I checked the `SecretProviderClassPodStatuses` for these pods, they all reported they were using the new certificate version after restart, which is what I expected.  However, this certificate was also synced to a Kubernetes Secret using the built-in feature, and the synced Kubernees Secret was NOT updated after the pods were restarted, it was still using the old certificate.

The only way I was able to get the synced Kubernetes Secret to update with the new version was to delete it, and let the provider re-create it.  When it was re-created a bit later, it was correctly using the new certificate version.

**What did you expect to happen:**
I expected that the synced Kubernetes secret would update with the new version when the pods were restarted with the new version.  I did not expect that I would have to manually delete the synced secret for it to pickup the new version.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Helm Chart v1.0.0
- Azure Key Vault provider version: (use the image tag): Helm Chart v1.0.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.19
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
This is a known limitation that's documented: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html. The Kubernetes secret is only updated with the rotation feature enabled. Without rotation, the steps are to delete the kubernetes secret before triggering rollout of the deployment. The reason for this is the Kubernetes secret is created based on the secret stored in mount. If the secret is updated for every pod restart the data can be inconsistent, so to avoid that we initially create and then not update it. However with rotation it's periodically updated to match the mounted content.

**Comment by chrisamert** [comment]
Ahh got it, I missed that known limitations page.  I would suggest linking the known limitations page from the 'Sync as Kubernetes Secret' page, as this behavior wasn't clear.  I'll close this since it sounds like expected behavior.

**Comment by aramase** [comment]
Thanks for the feedback! I'll link it to the doc.
