### ISSUE TITLE
MountVolume.NewMounter initialization failed for volume "secrets-store-inline" : volume mode "Ephemeral" not supported by driver secrets-store.csi.k8s.io (no CSIDriver object)

### ISSUE THREAD

**Issue by steephan-s1** [Azure/secrets-store-csi-driver-provider-azure#742]
E1214 22:27:31.518630       1 mic.go:1111] failed to update user-assigned identities on node aks-agentpool-33013998-vmss (add [1], del [0], update[0]), error: failed to update identities for aks-agentpool-33013998-vmss in MC_rg-demo5678_aks-demo5678_eastus, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'c8dc49d9-3825-4590-898b-d8fc990790fa' with object id 'c8dc49d9-3825-4590-898b-d8fc990790fa' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/12ca88bc-83a0-4a0e-afc2-58453a285523/resourceGroups/MC_rg-demo5678_aks-demo5678_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-33013998-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/12ca88bc-83a0-4a0e-afc2-58453a285523/resourcegroups/rg-demo5678/providers/microsoft.managedidentity/userassignedidentities/identity-aks-kv' or the linked scope(s) are invalid."
E1214 22:27:31.625347       1 mic.go:1129] failed to apply binding default/identity-aks-kv-binding node aks-agentpool-33013998-vmss000000 for pod default/nginx-secrets-store-5bcf78868f-kjbds, error: failed to update identities for aks-agentpool-33013998-vmss in MC_rg-demo5678_aks-demo5678_eastus, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'c8dc49d9-3825-4590-898b-d8fc990790fa' with object id 'c8dc49d9-3825-4590-898b-d8fc990790fa' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/12ca88bc-83a0-4a0e-afc2-58453a285523/resourceGroups/MC_rg-demo5678_aks-demo5678_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-33013998-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/12ca88bc-83a0-4a0e-afc2-58453a285523/resourcegroups/rg-demo5678/providers/microsoft.managedidentity/userassignedidentities/identity-aks-kv' or the linked scope(s) are invalid."

**Comment by aramase** [comment]
Hello 👋🏻  From the error message you posted this looks like insufficient permissions when using aad-pod-identity. Please refer to https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/ for required role assignments. Also, checkout the aad-pod-identity troubleshooting which has the topic: https://azure.github.io/aad-pod-identity/docs/troubleshooting/#linkedauthorizationfailed

**Comment by steephan-s1** [comment]
Thanks so much now it's working properly.

**Comment by aramase** [comment]
Thanks for confirming! Closing this issue now. Feel free to reopen if you've any questions.

**Comment by steephan-s1** [comment]
Hi Aramase,

This is SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass 
metadata:
  name: secret-provider-kv
  namespace: default
spec:
  provider: azure
  secretObjects:
    - data:
        - key: RABBITMQPASSWORD
          objectName: RABBITMQPASSWORD
      secretName: akvsecrets
      type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: $keyVaultName
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: RABBITMQPASSWORD
          objectType: secret
          objectVersion: ""
          objectAlias: RABBITMQPASSWORD
    resourceGroup: $resourceGroupName
    subscriptionId: $subscriptionId
    tenantId: $tenantId


---------------

This is deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-blog
  template:
    metadata:
      labels:
        app: wordpress-blog
        aadpodidbinding: azure-kv
    spec:
      containers:
      - name: wordpress-blog
        image: wordpress:4.8-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "demoaks.mysql.database.azure.com" #Update here
        - name: WORDPRESS_DB_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: akvsecrets
              key: RABBITMQPASSWORD
        - name: WORDPRESS_DB_NAME
          value: "demo"
        - name: WORDPRESS_DB_USER
          value: "azuredatabase@demoanalytics123"  #Update here
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-provider-kv
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - wordpress-blog
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress-blog



When i deploy this this deployment.yaml file its showing 
this error :  WORDPRESS_DB_PASSWORD:  <set to the key 'DatabasePassword' in secret 'akvsecrets'>  Optional: false
 Error: secret "akvsecrets" not found 

But CSI Volume mounted successfully :  Mounts:
      /mnt/secrets-store from secrets-store-inline (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mnm4r (ro)

Can you please let me know how to declare a variable using ENV
