### ISSUE TITLE
KV CSI will not work for China region AKS

### ISSUE THREAD

**Issue by vinshetty** [Azure/secrets-store-csi-driver-provider-azure#743]
**Have you**

**What steps did you take and what happened:**
I tried using CSI in China region but it's not  working as expected its throwing an error getting below  error

 Warning  FailedMount  1s    kubelet            MountVolume.SetUp failed for volume "emoryalgogpu" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-deployment-665469d894-zcw4g, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:devops, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://kv-mdp-test-ea2cn.vault.azure.net/secrets/devops/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://vault.azure.net was not found in the tenant named Carl Zeiss Shanghai. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 2ec45d47-7fd0-480b-9b50-88f362991300\r\nCorrelation ID: f193072b-77be-4852-bd08-4793479e3636\r\nTimestamp: 2021-12-15 08:50:42Z","error_codes":[500011],"timestamp":"2021-12-15 08:50:42Z","trace_id":"2ec45d47-7fd0-480b-9b50-88f362991300","correlation_id":"f193072b-77be-4852-bd08-4793479e3636","error_uri":"https://login.chinacloudapi.cn/error?code=500011"}

**What did you expect to happen:**
KV values should mount in Pod 

**Anything else you would like to add:**
Looks like CSI trying to reach https://vault.azure.net endpoint but China region different endpoint for KV (https://vault.azure.cn)

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity, System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  0.0.13
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
-  kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"d062c7ef8a88e89e5f28f1c1146bd707d00d4881", GitTreeState:"clean", BuildDate:"2021-11-01T16:41:06Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE   VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-nodepool1-62051732-vmss000000   Ready    agent   86m   v1.19.11   10.240.0.4     <none>        Ubuntu 18.04.6 LTS   5.4.0-1062-azure   containerd://1.4.9+azure
aks-nodepool1-62051732-vmss000001   Ready    agent   86m   v1.19.11   10.240.0.35    <none>        Ubuntu 18.04.6 LTS   5.4.0-1062-azure   containerd://1.4.9+azure
aks-nodepool1-62051732-vmss000002   Ready    agent   86m   v1.19.11   10.240.0.66    <none>        Ubuntu 18.04.6 LTS   5.4.0-1062-azure   containerd://1.4.9+azure
aks-nodepool1-62051732-vmss000003   Ready    agent   86m   v1.19.11   10.240.0.97    <none>        Ubuntu 18.04.6 LTS   5.4.0-1062-azure   containerd://1.4.9+azure
aks-nodepool1-62051732-vmss000004   Ready    agent   86m   v1.19.11   10.240.0.128   <none>        Ubuntu 18.04.6 LTS   5.4.0-1062-azure   containerd://1.4.9+azure
- Cluster type: (e.g. AKS, aks-engine, etc):  AKS

**Comment by wagenrace** [comment]
I am struggling with it but this should be the answer:
https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/custom-environments/

Using these endpoints:
https://docs.azure.cn/en-us/articles/guidance/developerdifferences

But I am missing a step somewhere

**Comment by wei-z-git** [comment]
You could set cloudName in parameters
```
  parameters:
    cloudName: "azurechinacloud"
```
https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/usage/
