### ISSUE TITLE
How to Pass Key vault secrets in Env 

### ISSUE THREAD

**Issue by steephan-s1** [Azure/secrets-store-csi-driver-provider-azure#745]
Hi Aramase,

This is SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
name: secret-provider-kv
namespace: default
spec:
provider: azure
secretObjects:
- data:
- key: RABBITMQPASSWORD
objectName: RABBITMQPASSWORD
secretName: akvsecrets
type: Opaque
parameters:
usePodIdentity: "true"
useVMManagedIdentity: "false"
userAssignedIdentityID: ""
keyvaultName: $keyVaultName
cloudName: AzurePublicCloud
objects: |
array:
- |
objectName: RABBITMQPASSWORD
objectType: secret
objectVersion: ""
objectAlias: RABBITMQPASSWORD
resourceGroup: $resourceGroupName
subscriptionId: $subscriptionId
tenantId: $tenantId

This is deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
name: wordpress-blog
spec:
replicas: 1
selector:
matchLabels:
app: wordpress-blog
template:
metadata:
labels:
app: wordpress-blog
aadpodidbinding: azure-kv
spec:
containers:
- name: wordpress-blog
image: wordpress:4.8-apache
ports:
- containerPort: 80
env:
- name: WORDPRESS_DB_HOST
value: "demoaks.mysql.database.azure.com" #Update here
- name: WORDPRESS_DB_PASSWORD
valueFrom:
secretKeyRef:
name: akvsecrets
key: RABBITMQPASSWORD
- name: WORDPRESS_DB_NAME
value: "demo"
- name: WORDPRESS_DB_USER
value: "azuredatabase@demoanalytics123" #Update here
volumeMounts:
- name: secrets-store-inline
mountPath: "/mnt/secrets-store"
readOnly: true
volumes:
- name: secrets-store-inline
csi:
driver: secrets-store.csi.k8s.io
readOnly: true
volumeAttributes:
secretProviderClass: secret-provider-kv
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: "app"
operator: In
values:
- wordpress-blog
topologyKey: "kubernetes.io/hostname"
apiVersion: v1
kind: Service
metadata:
name: php-svc
spec:
type: LoadBalancer
ports:
- port: 80
selector:
app: wordpress-blog

When i deploy this this deployment.yaml file its showing
this error : WORDPRESS_DB_PASSWORD: <set to the key 'DatabasePassword' in secret 'akvsecrets'> Optional: false
Error: secret "akvsecrets" not found

But CSI Volume mounted successfully : Mounts:
/mnt/secrets-store from secrets-store-inline (ro)
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mnm4r (ro)

Can you please let me know how to declare a variable using ENV

**Comment by MouniR-123** [comment]
Hi @steephan-s1 could you please share the steps you have followed for csidrivervolume integration. I am trying to implement this but seeing 404 error in nmi pods.  our keyvault is RBAC enabled, and I have Reader and "Key Vault Secret Reader" roleassginments created.
Thankyou!

**Comment by steephan-s1** [comment]
This is the link  which i followed to implement Keyvault ( https://github.com/HoussemDellai/aks-keyvault )

> Hi @steephan-s1 could you please share the steps you have followed for csidrivervolume integration. I am trying to implement this but seeing 404 error in nmi pods. our keyvault is RBAC enabled, and I have Reader and "Key Vault Secret Reader" roleassginments created. Thankyou!

**Comment by aramase** [comment]
Using pod identity to access keyvault is documented here: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/. If you receive a 404 from NMI it means the token operation failed in pod identity. You can troubleshoot pod identity failures from the MIC and NMI logs: https://azure.github.io/aad-pod-identity/docs/troubleshooting/.

Here is the troubleshooting guide for the driver and provider: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/
