### ISSUE TITLE
Unable to install with Egress Firewall, depricated objects

### ISSUE THREAD

**Issue by Borrelworst** [Azure/secrets-store-csi-driver-provider-azure#748]
**What steps did you take and what happened:**
When installing the latest version of the provider in Kubernetes 1.22.4 I ran into the following issues:

- Our cluster has an egress route on network level, so I a manually have to set the KUBERNETES_SERVICE_HOST environment var to the pods for API communication. This works fine for the pods, however when deploying, the CRDs are installed with a batch job and the batch job does not have the environment vars I've set for the pods (hence, the batch job fails as it cannot communicate with the API).
- Pod Security Policy is depricated in version 1.21+, so the deployment will fail as there is 1 PodSecurityPolicy not within the pspEnabled if/else in file keep-crds-upgrade-hook.yaml.

**What did you expect to happen:**
That the deployment will work fine with version > 1.22.*

These are not very big changes, but it would be good to see that this project works with the AKS versions supported by Microsoft.

**Comment by aramase** [comment]
> Our cluster has an egress route on network level, so I a manually have to set the KUBERNETES_SERVICE_HOST environment var to the pods for API communication. This works fine for the pods, however when deploying, the CRDs are installed with a batch job and the batch job does not have the environment vars I've set for the pods (hence, the batch job fails as it cannot communicate with the API).

If the driver and provider are deployed in `kube-system` namespace, `KUBERNETES_SERVICE_HOST` is already set for the pods. This is validated and the [AKS add-on for Secrets Store CSI Driver](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver) deploys it in `kube-system`. We have the recommendation to deploy in `kube-system` in our docs: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/ under section "Why kube-system".

> Pod Security Policy is depricated in version 1.21+, so the deployment will fail as there is 1 PodSecurityPolicy not within the pspEnabled if/else in file keep-crds-upgrade-hook.yaml.

This is a fix in the driver helm chart that's already been merged and will be included in the release this month.

> These are not very big changes, but it would be good to see that this project works with the AKS versions supported by Microsoft.

Thanks for the feedback. We have e2e validation with 3 minor kubernetes version as part of PRs and nightly tests. This is also now part of AKS as a managed add-on.

**Comment by aramase** [comment]
https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.0.1 is now released and the chart has the fix for `pspEnabled`. 

Closing this issue now. Feel free to reopen if you've any questions.
