### ISSUE TITLE
Remove `aks-engine` tests and template from PR and nightly runs

### ISSUE THREAD

**Issue by aramase** [Azure/secrets-store-csi-driver-provider-azure#754]
- We have tests running with:
  - kind
  - aks-engine
  - AKS

clusters as part of our PR gate and nightly runs. As `aks-engine` will eventually be replaced with CAPZ, we should remove the aks-engine tests and templates.

**Comment by sozercan** [comment]
.

**Comment by nilekhc** [comment]
We should also add e2e tests with CAPZ

**Comment by aramase** [comment]
> We should also add e2e tests with CAPZ cluster.

I don't think we need tests with CAPZ. We already have tests with kind and the initial motivation for `aks-engine` was to setup the feature gate required for inline volumes. For Azure specific scenarios, just AKS cluster should be enough.
