### ISSUE TITLE
Will this project replaced by Azure AD Workload Identity ?

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/secrets-store-csi-driver-provider-azure#758]
I see a new project: [https://azure.github.io/azure-workload-identity/docs/introduction.html](https://azure.github.io/azure-workload-identity/docs/introduction.html)
It enables to connect to Azure Key Vault using AAD on any Kubernetes cluster.
Will it replace this project ?

**Comment by nilekhc** [comment]
Hello @HoussemDellai, Thanks for opening the issue.

Azure Workload Identity will serve as yet another [identity access method](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/) for secrets store CSI AKV provider.

We are working on adding support for same in this project. This will be our recommended method to connect with AKV when using this project and it will not replace CSI AKV provider.

**Comment by HoussemDellai** [comment]
Thanks very much @nilekhc 💯

**Comment by nilekhc** [comment]
Closing this. Please open new one if you face any problems.
