### ISSUE TITLE
Example for certificates would be nice

### ISSUE THREAD

**Issue by erick-thompson** [Azure/secrets-store-csi-driver-provider-azure#76]
I would like to use this provider so that my ingresses can use certificates stored in KV for TLS. All the examples currently show mounting secrets as volumes, which doesn't help me. 

Is k8s secrets of type TLS supported? If so, is there an example?

**Comment by aramase** [comment]
@erick-thompson The PR to support creating k8s secret has been merged in the driver - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/186

This is doc PR with example on how to use the feature with nginx ingress controller - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/192

This feature will be available with the next release of driver v0.0.10 which is scheduled for next week. I'll update here when the release is cut and ready for use.

**Comment by erick-thompson** [comment]
Excellent, thank you!
