### ISSUE TITLE
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by stan-sz** [Azure/secrets-store-csi-driver-provider-azure#787]
Based on https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125 `PodSecurityPolicy` is deprecated. Opening an issue to track replacement for it.

**Comment by pierluigilenoci** [comment]
PSP are replaced with https://github.com/kubernetes/enhancements/issues/2579

**Comment by pierluigilenoci** [comment]
@aramase this is a workaround to get the software to work on K8s v1.25 as well but this way it doesn't run with the necessary restricted permissions.

All these "[permissions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/templates/podsecuritypolicy.yaml#L8-L23)" need to be moved into the `securityContexts` at the pod and container level.

Ref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/templates/podsecuritypolicy.yaml#L8-L23
