### ISSUE TITLE
azure-csi-driver pkcs12 certificate

### ISSUE THREAD

**Issue by ibattat** [Azure/secrets-store-csi-driver-provider-azure#79]
**What steps did you take and what happened:**
I have configured a persistent volume based on azure-csi-driver.
When fetching a certificate from Azure KeyVault I receive the wrong format.

**What did you expect to happen:**
receive format suitable for Nginx HTTPS configuration

**Anything else you would like to add:**
PEM cert type working fine, but still don't know how to convert the cert file after the 51 PR.

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity

**Comment by ritazh** [comment]
This is probably a duplication of https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/76. Please see response: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/76#issuecomment-622536782

**Comment by ibattat** [comment]
It is not related.
When I am getting a certificate from azure key vault in PKCS#12 format it's not working

**Comment by ritazh** [comment]
@ibattat can you pls share the following:
- How the cert was generated, script used
- How the cert was imported into Azure Key Vault
- Your `SecretProviderClass` resource yaml

**Comment by ibattat** [comment]
@ritazh  the certificate was generated through azure portal and not a script.
Didn't upload anything, and the certificate type is PKCS#12 and not PEM.

I took the secret provider class from the Readme documentation
