### ISSUE TITLE
AuthN to Key Vault from an AKS using "Managed Identity" instead of SPN

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/secrets-store-csi-driver-provider-azure#80]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I create an AKS that uses Managed Identity instead of SPN, the value for .servicePrincipalProfile.clientId is "msi"
```
  "servicePrincipalProfile": {
    "clientId": "msi"
  },
```
Thus, assigning the role doesn't work:
```
$ az role assignment create --role "Managed Identity Operator" --assignee $aks.servicePrincipalProfile.clientId --scope $identity.id
Cannot find user or service principal in graph database for 'msi'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id msi'.
```
But there is another section in AKS that have "principalId":
```
  "identity": {
    "principalId": "00000000-e567-49e7-a579-16e8f4179568",
    "tenantId": "000000-00000-0000000-000000-000000000",
    "type": "SystemAssigned"
  },
  "identityProfile": {
    "kubeletidentity": {
      "clientId": "000000000-ab59-4151-80e4-000000000",
      "objectId": "00000000-40fd-48ac-9ce4-000000000",
      "resourceId": "/subscriptions/000000-0000000000/resourcegroups/MC_rg-demo01_aks-demo01_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-demo01-agentpool"
    }
  },
```
Should I use $aks.identity.principalId instead of $aks.servicePrincipalProfile.clientId ?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc): AKS 1.17.3

**Comment by anandchugh** [comment]
For AKS with managed identity we can use to get the principal id
`az aks show -g <AKSResourceGroup> -n <AKSClusterName> --query identityProfile.kubeletidentity.clientId -otsv`

and the perform below two role assignments

`az role assignment create --role "Managed Identity Operator" --assignee <PrincipalID> --scope /subscriptions/<SubscriptionID>/resourcegroups/<ClusterResourceGroup>
az role assignment create --role "Virtual Machine Contributor" --assignee <PrincipalID> --scope /subscriptions/<SubscriptionID>/resourcegroups/<ClusterResourceGroup>`

More info is [here](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md)

**Comment by HoussemDellai** [comment]
That worked for me.
Million thanks :)
