### ISSUE TITLE
Provide the helm chart through mcr.microsoft.com

### ISSUE THREAD

**Issue by stan-sz** [Azure/secrets-store-csi-driver-provider-azure#802]
**Describe the solution you'd like**
mcr.microsoft.com is capable of storing helm charts. Since all images referenced in the helm chart are from mcr.microsoft.com, it would be coherent to have the chart be pullable from the same source.

**Comment by stan-sz** [comment]
@aramase - what's your take on that? It's is related to #784

**Comment by aramase** [comment]
> @aramase - what's your take on that? It's is related to https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/784

@stan-sz There is currently no plan to move the helm charts to mcr. The common pattern we have been following across all OSS projects (including CNCF ones) have been to host the helm charts in the `main` branch or `gh-pages` (the latter being more commonly used now). 

The images are hosted in mcr but in case of helm charts AFAIK there are certain limitations on helm version for hosting in mcr. Do you have any specific requirement for pulling charts from `mcr.microsoft.com` and not ones hosted in github?

**Comment by stan-sz** [comment]
Indeed, helm 3.7+ is capable of pulling a chart from a container registry. Can you push the chart to both the gh-pages and mcr.microsoft.com?

**Comment by sozercan** [comment]
@stan-sz can you elaborate more on your requirements for chart to be in MCR please?

**Comment by stan-sz** [comment]
It's not a strong requirement yet, it is a simplification to host the chart with images in the same ACR.
A non-functional requirement is that we have seen rate limiting when pulling binaries from github in our build pipelines. Hosting the chart in ACR raises the limit.

**Comment by aramase** [comment]
Closing this issue as it's currently not planned. Feel free to open a new issue if you have any questions.
