### ISSUE TITLE
Mounted secrets do not get updated when secret is changed in Key Vault

### ISSUE THREAD

**Issue by michaelelleby** [Azure/secrets-store-csi-driver-provider-azure#815]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Key Vault secret is accessible from the container at `/mnt/secrets-store/secret-sauce` but when I update the value of the secret in the Key Vault, the contents of  `/mnt/secrets-store/secret-sauce` are not updated. If I delete the pod and recreate the pod, then the new value appears inside  `/mnt/secrets-store/secret-sauce`

CSI driver
`helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set enableSecretRotation=true --set rotationPollInterval=2`

Secret provider class:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: <removed>
    keyvaultName: <removed>
    objects:  |
      array:
        - |
          objectName: secret-sauce
          objectType: secret
    resourceGroup: "<removed>"
    subscriptionId: "<removed>"
    tenantId: "<removed>"
```

Pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
  labels:
    aadpodidbinding: azure-identity
spec:
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    command:
      - "/bin/sleep"
      - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
```

**What did you expect to happen:**
Contents of  `/mnt/secrets-store/secret-sauce` would be updated after ~2 minutes as [documentation states](https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html#enable-auto-rotation).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.0.1
- Azure Key Vault provider version: (use the image tag): v1.0.1
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"37f338aa38e0427e127162afe462e2f4150f0ba3", GitTreeState:"clean", BuildDate:"2022-02-07T20:49:26Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

> kubectl get nodes -o wide
NAME                              STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-default-25023348-vmss000000   Ready    agent   19h   v1.21.9   10.1.0.4      <none>        Ubuntu 18.04.6 LTS   5.4.0-1069-azure   containerd://1.4.12+azure-2
aks-default-25023348-vmss000003   Ready    agent   19h   v1.21.9   10.1.0.97     <none>        Ubuntu 18.04.6 LTS   5.4.0-1069-azure   containerd://1.4.12+azure-2
aks-default-25023348-vmss000009   Ready    agent   13h   v1.21.9   10.1.0.66     <none>        Ubuntu 18.04.6 LTS   5.4.0-1069-azure   containerd://1.4.12+azure-2
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hi @michaelelleby Thanks for opening issue.

Could you try helm install with:
`helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set secrets-store-csi-driver.enableSecretRotation=true --set secrets-store-csi-driver.rotationPollInterval=2`

Also are you using Secrets Store CSI azure provider on AKS? If so we recommend using managed add-on for the same:
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**Comment by michaelelleby** [comment]
Hi @nilekhc I can confirm that setting `secrets-store-csi-driver.enableSecretRotation=true` does fix the problem.

**Comment by nilekhc** [comment]
@michaelelleby I see the confusion now. Thanks for bringing this up. I have created a PR (https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/819) to add a note about this in docs. Feel free to add review comments.
