### ISSUE TITLE
Kubelet plugin registration hasn't succeeded yet

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/secrets-store-csi-driver-provider-azure#829]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

I upgraded the chart from version 1.0.1 to 1.1.0 without any configuration changes.

The `secrets-store-csi-driver` pods started going into `CrashLoopBackOff` with this error:

From K8s events
```shell
[REDACTED]   4m28s       Warning   Unhealthy           pod/secrets-store-csi-driver-hh2vr                                 Liveness probe failed: F0310 13:06:58.107353      11 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/var/lib/kubelet/plugins/csi-secrets-store/registration doesn't exist....
```

Pod logs:
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1632c4e]
goroutine 1 [running]:
go.uber.org/zap/zapcore.(*writerWrapper).Write(0xc0002b0090, {0xc0000da800, 0x526f97c, 0x2abcee0})
<autogenerated>:1 +0x2e
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0003cd110, {0x0, {0xc0829c7a674c990e, 0x526f97c, 0x2abcee0}, {0x0, 0x0}, {0x1a87aa3, 0x1c}, {0x1, ...}, ...}, ...)
/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/core.go:90 +0xb5
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00004c9c0, {0xc0003fc700, 0x2, 0x2})
/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:220 +0x1d9
github.com/go-logr/zapr.(*zapLogger).Info(0xc0003cd170, 0x0, {0x1a87aa3, 0x7af3f3}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/github.com/go-logr/zapr@v1.2.0/zapr.go:198 +0xa5
github.com/go-logr/logr.Logger.Info({{0x1cee840, 0xc0003cd170}, 0x0}, {0x1a87aa3, 0x1c}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:249 +0xd0
k8s.io/klog/v2.(*loggingT).infoS(0x7b4546, 0x1, {0x0, 0x0}, 0x0, {0x1a87aa3, 0x1b39388}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:795 +0x113
k8s.io/klog/v2.InfoS(...)
/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1438
sigs.k8s.io/secrets-store-csi-driver/pkg/metrics.InitMetricsExporter()
/go/src/sigs.k8s.io/secrets-store-csi-driver/pkg/metrics/exporter.go:35 +0xcc
main.main()
/go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:104 +0x19e
```

Helm Chart values used to deploy:
```
linux:
  priorityClassName: system-node-critical
logFormatJSON: true
logVerbosity: "1"
rbac:
  pspEnabled: true
secrets-store-csi-driver:
  enableSecretRotation: true
  filteredWatchSecret: true
  image:
    tag: v1.0.1
  linux:
    priorityClassName: system-node-critical
    registrar:
      logVerbosity: "1"
  livenessProbe:
    logLevel: "1"
  logFormatJSON: true
  logLevel:
    debug: false
  logVerbosity: "1"
  rbac:
    pspEnabled: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true
```

If I roll back everything is fine.

**What did you expect to happen:**

I expected the installation to work without problems.

**Anything else you would like to add:**

Nope

**Which access mode did you use to access the Azure Key Vault instance:**

AAD Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.1.0
- Azure Key Vault provider version: (use the image tag): 1.1.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```shell
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
```shell
aks-[REDACTED]   Ready    agent   197d   v1.21.2   [REDACTED]   <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-azure   containerd://1.4.8+azure
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hey @pierluigilenoci  Coul you run `helm dependency update` then try to install again?

**Comment by pierluigilenoci** [comment]
@nilekhc we don't install the chart manually, we use a GitOps approach, Flux (v1) in particular.

The dependency update is performed by default by `helm-operator`.
Ref: https://fluxcd.io/legacy/helm-operator/helmrelease-guide/automation/#helm-repository-chart-updates

**Comment by nilekhc** [comment]
Could you provide chart versions for both driver and provider?

Also, could you provide the logs of `secrets-store` container from driver?

**Comment by pierluigilenoci** [comment]
@nilekhc all this information is already in the issue text.

In any case, upgrade the chart from version 1.0.1 to version 1.1.0 (the subchart is the one defined by the chart version).
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1632c4e]
goroutine 1 [running]:
go.uber.org/zap/zapcore.(*writerWrapper).Write(0xc0002b0090, {0xc0000da800, 0x526f97c, 0x2abcee0})
<autogenerated>:1 +0x2e
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0003cd110, {0x0, {0xc0829c7a674c990e, 0x526f97c, 0x2abcee0}, {0x0, 0x0}, {0x1a87aa3, 0x1c}, {0x1, ...}, ...}, ...)
/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/core.go:90 +0xb5
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00004c9c0, {0xc0003fc700, 0x2, 0x2})
/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:220 +0x1d9
github.com/go-logr/zapr.(*zapLogger).Info(0xc0003cd170, 0x0, {0x1a87aa3, 0x7af3f3}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/github.com/go-logr/zapr@v1.2.0/zapr.go:198 +0xa5
github.com/go-logr/logr.Logger.Info({{0x1cee840, 0xc0003cd170}, 0x0}, {0x1a87aa3, 0x1c}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:249 +0xd0
k8s.io/klog/v2.(*loggingT).infoS(0x7b4546, 0x1, {0x0, 0x0}, 0x0, {0x1a87aa3, 0x1b39388}, {0xc000092fe0, 0x2, 0x2})
/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:795 +0x113
k8s.io/klog/v2.InfoS(...)
/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1438
sigs.k8s.io/secrets-store-csi-driver/pkg/metrics.InitMetricsExporter()
/go/src/sigs.k8s.io/secrets-store-csi-driver/pkg/metrics/exporter.go:35 +0xcc
main.main()
/go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:104 +0x19e
```

**Comment by aramase** [comment]
There was a bug in driver with json logging format which was fixed in `v1.1.1`: https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.1.1. The helm charts in this repo still use the driver `v1.1.0`.

You can use the driver charts from driver repo for `v1.1.1` release until https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/830 is merged to use new driver release.

**Comment by pierluigilenoci** [comment]
@aramase do you have an ETA for the release of the fix? Without rushing.
Changing the subchart becomes more complex.
I will wait for the release anyway.

**Comment by aramase** [comment]
Chart release `1.1.1` that has driver `v.1.1.1` as dep is published!

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/830
