### ISSUE TITLE
Support Workload Identity

### ISSUE THREAD

**Issue by simongottschlag** [Azure/secrets-store-csi-driver-provider-azure#832]
Hi!

Workload Identity is the next iteration of AAD Pod Identity: https://github.com/Azure/azure-workload-identity

What are the plans for this provider to support it in the future?

Thanks!

**Comment by aramase** [comment]
Hello 👋🏻  Workload identity support is available in [v1.1.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.1.0) release of the driver and provider. Here is the documentation: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/

The webhook is not required for the CSI driver as kubelet plumbs the service account token as part of the volume mount request.

**Comment by simongottschlag** [comment]
Wow! Sorry for creating an issue for something that's already supported - should have looked closer.

@aramase is it possible to separate and isolate namespaces like we were able to with aad-pod-identity?

Thanks!

**Comment by aramase** [comment]
> @aramase is it possible to separate and isolate namespaces like we were able to with aad-pod-identity?

Workload identity federation is based on service account token used by the workload. So everything is bound to a namespace and to the individual service account that's configured with the workload.

**Comment by simongottschlag** [comment]
@aramase epic work! Sorry again and thank you 🙏⭐️

**Comment by aramase** [comment]
No worries at all! 

Let us know your feedback after you get a chance to try it out.
