### ISSUE TITLE
Release v1.1.0 anounced but helm chart is missing [suggestion noted]

### ISSUE THREAD

**Issue by amarkevich** [Azure/secrets-store-csi-driver-provider-azure#838]
**What steps did you take and what happened:**
Install helm chart v1.1.0
`Error: chart "csi-secrets-store-provider-azure" version "v1.1.0" not found in https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts repository`

**Comment by aramase** [comment]
Helm charts have been moved to gh-pages. Please see [Installation steps](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#installation) for the details.
