### ISSUE TITLE
Get secret without mount

### ISSUE THREAD

**Issue by armondressler** [Azure/secrets-store-csi-driver-provider-azure#839]
According to the documentation a secret can only be created once it gets mounted in a pod.
Some deployments dont mount a secret to access it (-> k8s API, see https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings  setting "credentialName" for an example) which then requires a user of this CSI driver to create a pod with the required mount just so the secret becomes available. This is obviously not a desired solution.

Any chance for this feature to be added or am i missing something about the currently available options.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Azure Key Vault provider version: (use the image tag): latest
- Kubernetes version: (use `kubectl version`): 1.21
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hi @armondressler 
There is a similar ask from other users (https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/298) and we are assessing this feature request with community. We are also reviewing proposal (https://docs.google.com/document/d/1Ylwpg-YXNw6kC9-kdHNYD3ZKskj9TTIopwIxz5VUOW4/edit#heading=h.n3xa8h2b1inm) with `SIG-Auth`. Keep an eye on this.

**Comment by armondressler** [comment]
thanks, looking forward to it.
