### ISSUE TITLE
Ho to load secrets in to environment variable on Linux POD

### ISSUE THREAD

**Issue by iamsoorya** [Azure/secrets-store-csi-driver-provider-azure#84]
I am using the below things. However, I need to be able to load these secrets onto env variable. It is not working at all. Could you please help us how to achieve that?

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv    
  name: nginx-flex-kv
  namespace: ns-gdprhub-kc
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["export KEYCLOAK_USER=$(cat /kvmnt-kc/gdpr-key-cloak-admin-user)",
      "export KEYCLOAK_PASSWORD=$(cat /kvmnt-kc/gdpr-key-cloak-admin-user-pwd)"]        
    volumeMounts:
    - name: secrets-store-inline-gdprhub-kc
      mountPath: /kvmnt-kc
      readOnly: true
  volumes:
  - name: secrets-store-inline-gdprhub-kc
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-scp-gdprhub-kc"

**Comment by iamsoorya** [comment]
---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-scp-gdprhub-kc
  namespace: ns-gdprhub-kc
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "false"         
    useVMManagedIdentity: "true"   
    userAssignedIdentityID: "{{kubeletid_clientId}}"  
    keyvaultName: "{{key_vault}}"          
    #cloudName: "AzurePublic"          
    objects:  |
      array:
        - |
          objectName: gdpr-key-cloak-admin-user
          objectAlias: gdpr-key-cloak-admin-user     
          objectType: secret        
          objectVersion: "{{kc-admin-user-ver}}"         
        - |
          objectName: gdpr-key-cloak-admin-user-pwd
          objectAlias: gdpr-key-cloak-admin-user-pwd
          objectType: secret
          objectVersion: "{{kc-admin-user-pwd-ver}}"   
        - |
          objectName: gdpr-sql-kc-db-user-name
          objectAlias: gdpr-sql-kc-db-user-name
          objectType: secret
          objectVersion: "{{kc-db-user-name-ver}}" 
        - |
          objectName: gdpr-sql-kc-db-user-pwd
          objectAlias: gdpr-sql-kc-db-user-pwd
          objectType: secret
          objectVersion: "{{kc-db-user-pwd-ver}}"          
    resourceGroup: "{{key_vault_rg}}"            
    subscriptionId: "{{subscription_id}}"         
    tenantId: "{{tenant_id}}"

**Comment by iamsoorya** [comment]
Can you please help asap we need to do pre prod deploymnet..

**Comment by ritazh** [comment]
Can you PTAL at: https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets looks like you are missing the `secretObjects` fields

**Comment by jrudley** [comment]
I wrote an example:
`---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mssql-config-map"
  namespace: default
  labels:
    app: mssql
data:
  MSSQL_PID: "Developer"
  ACCEPT_EULA: "Y"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mssql" #$(service name).$(namespace).svc.cluster.local
  labels:
    app: mssql
spec:
  clusterIP: "None"
  ports:
  - port: 1433
    name: "mssql"
  selector:
    app: "mssql"
    release: "mssql"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-lb
  labels:
    app: mssql  
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql 
  labels:
    app: mssql
    release: mssql
spec:
  serviceName: "mssql"
  selector:
    matchLabels:
      app: "mssql"
      release: "mssql"
  replicas: 1
  updateStrategy:
        type: OnDelete
  template:
    metadata:
      labels:
        app: "mssql"
        release: "mssql"
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux  
      terminationGracePeriodSeconds: 180
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync" 
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest          
          resources:
            {}
          ports:
          - containerPort: 1433
            name: mssql
          envFrom:
            - configMapRef:
                name: mssql-config-map
          env:
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: mssql-config-map
                  key: MSSQL_PID
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: mssql-config-map
                  key: ACCEPT_EULA
            - name: SA_PASSWORD #env variable to create
              valueFrom:
                secretKeyRef:
                  name: mssql #k8s secret name. (kubectl get secret). this is auto synced during creation and deletion of the POD
                  key: mssql #this must match the kv configuration in the yaml under secretObjects
          volumeMounts:
            - name: mssql-pvc
              mountPath: /var/opt/mssql
            - name: secrets-store-inline 
              mountPath: "/mnt/secrets-store"
              readOnly: true
  volumeClaimTemplates: #default is standard storage. managed-premium is ssd
    - metadata:
        name: mssql-pvc      
      spec:
        storageClassName: default
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
`

snippet of provider configuration
`provider: azure
  secretObjects:                          # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: mssql                     # name of the Kubernetes Secret object
    type: Opaque
    data: 
    - objectName: "mssql-secret"           # name of the mounted content to sync. This could be the object name or object alias 
      key: mssql                           # data field to populate. This must match in deployment yaml for key
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "34d6ef86-9846-4e8e-aa6d-f2ac23908abc"
    keyvaultName: "jrkeyvaultdemo"               # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: mssql-secret
          objectType: secret       # object types: secret, key or cert`

**Comment by iamsoorya** [comment]
Thank you. I shall try this.

**Comment by aramase** [comment]
@iamsoorya Were you able to successfully load the secrets as env variables based on the examples @jrudley provided?

**Comment by iamsoorya** [comment]
Yes, the code has worked. However,  last friday, I tried to use the latest version 11 and version 6,it failed. However, I am happy to continue with older version.

Thanks for solving our issue. It has helped to use to application to user acceptance testing.

**Comment by aramase** [comment]
@iamsoorya Do you have the logs for the failure when you tried with the latest version?

**Comment by aramase** [comment]
@iamsoorya Closing this issue. Please feel to free reopen with logs if you hit any issue while trying out with the latest releases.

**Comment by aelmanaa** [comment]
@aramase  is syncing vault with k8s secrets the only way to load  secrets as env variables? To lower the attack surface, it would be preferable to store minimum of secrets in etcd

**Comment by ritazh** [comment]
@aelmanaa if you do not want to sync with k8s secrets, another option is to set the environment variable before the main process starts in your container. For example:

```yaml
spec:
  containers:
  - name: nginx-kv
    image: nginx
    command: ["/bin/sh", "-c", "export SECRET=$(cat /mnt/secrets-store/mysecret); echo $SECRET; nginx -g 'daemon off;'"]
    volumeMounts:
    - name: test
      mountPath: /mnt/secrets-store
      readOnly: true
```

**Comment by aramase** [comment]
@ritazh This example will be a good addition to our docs for users who don't want to sync as Kubernetes secret.

**Comment by dmradford** [comment]
@ritazh @aramase 
I'm having trouble getting this command to execute correctly. I can get the secrets to mount correctly into the volume, but when I export them via command, the environment variable remains empty once I shell into the container. I've tried the base level command option, as well as the lifecycle poststart hook. Same results. If I run the command via shell on the pod, the environment variable gets set correctly.

Does this method no longer work, or is there a better way to get the secrets from the volume into environment variables?

**Comment by sagark23** [comment]
I'm facing the same problem as @dmradford, secrets mount correctly and `kubectl exec integration-ws-5b6868fcb8-57fg2 -- ls /mnt/secrets-store/ ` gives me the right secrets but unable to create env vars from those secrets.

**Comment by aramase** [comment]
@dmradford @sagark23 The supported way for setting the env var with the CSI driver is to sync the mounted content as Kubernetes secrets and reference those as environment variables in the pod spec: 

https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/set-env-var/

We'll try out the above command and add it as an alternative option after validation.

**Comment by shubhammicrosoft1** [comment]
Hi @aramase : Will it be also possible to mount nginx tls certificate as env for nginx ingress pods

**Comment by mkemmerz** [comment]
Any update on how to set the env var without using Kubernetes secrets?

I also can confirm that the command @ritazh posted does not work, sadly.

**Comment by nilekhc** [comment]
> Hi @aramase : Will it be also possible to mount nginx tls certificate as env for nginx ingress pods

Hey @shubhammicrosoft1, Could you try [this](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/ingress-tls/)?
