### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[config-volume secrets-efulfill-inline appd-agent-repo-java kube-api-access-gbht9 log-volume], unattached volumes=[config-volume secrets-efulfill-inline appd-agent-repo-java kube-api-access-gbht9 log-volume]: timed out waiting for the condition

### ISSUE THREAD

**Issue by Madhu052** [Azure/secrets-store-csi-driver-provider-azure#851]
“HPA is not working since 18th of February.

ASK:  Why is the volume mounted correctly when using manual scale pods but using HPA it has an issue?

Describe for HPA has no error / events:

************* HPA *******************
Name:                    excess-cartons-cpu-hpa
Namespace:               ns-store
Labels:                  app.kubernetes.io/managed-by=Helm
Annotations:             meta.helm.sh/release-name: excess-cartons-ppd
                         meta.helm.sh/release-namespace: ns-store
CreationTimestamp:       Thu, 17 Feb 2022 04:49:25 +0000
Reference:               Deployment/excess-cartons
Metrics:                 ( current / target )
  resource cpu on pods:  0 / 213m
Min replicas:            2
Max replicas:            4
Deployment pods:         2 current / 2 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from cpu resource
  ScalingLimited  True    TooFewReplicas       the desired replica count is less than the minimum replica count
Events:           <none>

 
Name:                       excess-cartons-memory-hpa
Namespace:                  ns-store
Labels:                     app.kubernetes.io/managed-by=Helm
Annotations:                meta.helm.sh/release-name: excess-cartons-ppd
                            meta.helm.sh/release-namespace: ns-store
CreationTimestamp:          Thu, 17 Feb 2022 04:49:25 +0000
Reference:                  Deployment/excess-cartons
Metrics:                    ( current / target )
  resource memory on pods:  45800106666m / 255Mi
Min replicas:               2
Max replicas:               4
Deployment pods:            2 current / 2 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from memory resource
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:           <none>

Current version of the CSI driver and AKV provider being used:
madhu@Azure:~$ helm ls -n ns-csi
NAME                                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
csi-secrets-store-provider-azure-1620916355     ns-csi          4               2021-05-16 13:04:57.654586501 +0000 UTC deployed        csi-secrets-store-provider-azure-0.0.18 0.0.14   
 
Kubernetes version: kubectl get nodes -o wide and kubectl version output:
NAME                                 STATUS   ROLES   AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-nodepool02-37501463-vmss000002   Ready    agent   101d   v1.21.2   10.160.97.158   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss000003   Ready    agent   101d   v1.21.2   10.160.97.204   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00001n   Ready    agent   101d   v1.21.2   10.160.96.9     <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00001o   Ready    agent   101d   v1.21.2   10.160.96.55    <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00001p   Ready    agent   101d   v1.21.2   10.160.96.154   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00001x   Ready    agent   101d   v1.21.2   10.160.96.247   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss000023   Ready    agent   19d    v1.21.2   10.160.97.130   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00002h   Ready    agent   10d    v1.21.2   10.160.96.107   <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
aks-nodepool02-37501463-vmss00002k   Ready    agent   7d9h   v1.21.2   10.160.97.38    <none>        Ubuntu 18.04.6 LTS   5.4.0-1063-azure   containerd://1.4.9+azure
 
madhu@Azure:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

**Comment by Madhu052** [comment]
Hi All

Whenever we are trying to scale up pods through HPA we are getting mount failures and pods are getting terminated.
But if we try to scale manually pods are coming up and need your support to resolve the same

**Comment by aramase** [comment]
Thanks for opening the issue! 

The driver and provider version you're currently running is not supported. `0.0.14` release is a year old and there have been multiple releases since then. The project is now GA and here is the list of supported releases: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/#project-status.

**Please upgrade to the latest supported release.** 

If you still run into any issues with any of the latest releases, provide the following details in this issue:
1. `SecretProviderClass` yaml
2. `Deployment` yaml
3. Logs from driver and provider pods running on the same node as your app. Refer to our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/
