### ISSUE TITLE
SecurityContext configurable

### ISSUE THREAD

**Issue by arevell89** [Azure/secrets-store-csi-driver-provider-azure#858]
Running root pods in Azure causes a high security alert in Azure monitors. Is it possible to configure the securityContext so we can run unprivileged pods?

https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml#L73

**Comment by aramase** [comment]
Closing this as `privileged` is required for the provider pods. Feel free to reopen if there is a feature request or if you have any further questions.
