### ISSUE TITLE
Create azure key vault secrets using helm chart ( with any CRD object )

### ISSUE THREAD

**Issue by rajeevpnair** [Azure/secrets-store-csi-driver-provider-azure#861]
Is there a way to create azure key vault secrets using helm charts, or any CRD object which can create azure key vault secrets... ?
We do have a lot of application charts and i am unable to figure out a way to move the secrets to azure key vault.

**Comment by aramase** [comment]
Hello 👋🏻  

Azure Key Vault Provider for Secrets Store CSI Driver is to get secrets stored in AKV and make them accessible to pods during runtime. It does not support creating secrets in AKV from the cluster and that is not under the scope of this project.

**Comment by rajeevpnair** [comment]
@aramase... thanks for the response.. 
Since SecretProviderClass object is created with secrets-store.csi.x-k8s.io/v1, was just looking for an object which can also create a azure key vault secret...
Is there kuberentes object  available to create a azure key vault secrets using helm or definition file?
since the secrets defined in our helm charts has a lot of dependency ( based on conditions ) in values.yml file, Its bit difficult to create these with azure cli as the data in the secrets will be based on values.yml file.
looks like secret store csi cant help with storing secrets in azure key vault in places where a large number of applications managed with helm charts...

**Comment by aramase** [comment]
> Is there any kubernetes object available to create a azure key vault secrets using helm or definition file?

@rajeevpnair I'm not aware of any project that syncs secrets in Azure Key Vault based on definition in Kubernetes. 

> looks like secret store csi cant help with storing secrets in azure key vault in places where a large number of applications managed with helm charts...

Right, the scope of this project is to pull and make secrets available during runtime. No push.

**Comment by aramase** [comment]
Closing this issue now. Please feel free to open a new issue if you have any questions about the driver.
