### ISSUE TITLE
[AKS add-on] Failed to get service account token attrs -- failed to fetch token (forbidden)

### ISSUE THREAD

**Issue by PPACI** [Azure/secrets-store-csi-driver-provider-azure#871]
Hello.

I allowed myself to skip the template since this is an issue that is created elsewhere.

**What happened**
It appears that the addon deployment on AKS is not deploying all the required components.
Indeed it lacks a ClusterRole/ClusterRoleBinding.

Right now, we are manually adding the required files to AKS.

Would it be possible to add it in the future?

reference: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/939

**Comment by nilekhc** [comment]
@PPACI As mentioned by [Ji'an Liu](https://github.com/ZeroMagic) This should be available in next release.

Ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/939#issuecomment-1105103273

**Comment by aramase** [comment]
cc @zeromagic

**Comment by aramase** [comment]
@ZeroMagic confirmed the fix has been rolled out to all regions.

I was able to validate in `southcentralus` by enabling the add-on in a new cluster and I see all the required cluster roles
```bash
➜ k get clusterrole | grep aks
aks-secretproviderclasses-admin-role 2022-05-25T00:08:19Z
aks-secretproviderclasses-role 2022-05-25T00:08:19Z
aks-secretproviderclasses-viewer-role 2022-05-25T00:08:19Z
aks-secretprovidersyncing-role 2022-05-25T00:08:19Z
aks-secretprovidertokenrequest-role 2022-05-25T00:08:19Z
```

Closing this issue now. Please feel free to reopen/open a new issue in [AKS](https://github.com/Azure/AKS/issues) for issues related to the AKS add-on.
