### ISSUE TITLE
Is service endpoint supported for AKS - Azure Keyvault?

### ISSUE THREAD

**Issue by lissff** [Azure/secrets-store-csi-driver-provider-azure#873]
**Describe the solution you'd like**
I've configured the AKS subnet into key vault's allowed Vnet access range follow https://docs.microsoft.com/en-gb/azure/key-vault/general/network-security?WT.mc_id=Portal-Microsoft_Azure_KeyVault
;
 but still failed with
**Service returned an error. Status=403 Code="Forbidden" Message="Public network access is disabled and request is not from a trusted service nor via an approved private link.**

if I'm adding AKS outbound public IP or using private link then it is working.

Did i miss any step here or AKS is not trusted service from keyvault?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by aramase** [comment]
@jlichwa could you help with this?

cc @miwithro

**Comment by jlichwa** [comment]
It is correct, AKS outbound public IP has to be set. Trusted service is mostly designed for multi-tenant PAS services running in Microsoft tenant. I don't think you would like that any AKS cluster for any customer can access your Key Vault.

**Comment by lissff** [comment]
@jlichwa which means that even if AKS is not a trusted service. 
We can still access Keyvault from the service endpoint, by allowing the **AKS subnet**(**instead of AKS outbound IP**) in AKV's  "allow public access from specific virtual networks"?

**Comment by jlichwa** [comment]
Not sure what could be an issue with subnet, if there are any limitations or not. You will need to create support request on Key Vault to find the root cause of the issue.

**Comment by aramase** [comment]
@lissff Is this issue resolved now?
