### ISSUE TITLE
TLS Version

### ISSUE THREAD

**Issue by chaitanyakmr1** [Azure/secrets-store-csi-driver-provider-azure#880]
Hello,

Currently I use csi-secrets-store-provider-azure-0.2.1 with version 0.2.0. I am having a question. Does the operator uses TLS to communicate with Microsoft Azure Key Vault? If yes, which version.

I am asking the above question because I had seen that the TLS Versions below 1.2 will be deprecated and I want to be sure, if this might affect my application.

Thanks for the answers in advance.

Regards,
Chaitanya

**Comment by nilekhc** [comment]
Hello @chaitanyakmr1 Thanks for opening the issue. We use go-autorest. It has TLS 1.2 set as default. https://github.com/Azure/go-autorest/issues/363

Having said that, your provider version is very old. We have stable release now and recommend to upgrade to `v1.0.0` or later version.
