### ISSUE TITLE
Getting "Access Denied" for AKV when it is in a different subscription and region

### ISSUE THREAD

**Issue by MrBasset** [Azure/secrets-store-csi-driver-provider-azure#881]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/) <- __note: template URL is wrong__
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

Admittedly the terms are common though, so I may have missed a previous issue/discussion.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am trying to access a Secret stored within an Azure key vault that is both in a different region and a different subscription to my AKS cluster. However I am getting "Access Denied" error, despite the permissions being correctly set. Accessing Key vaults within the same subscription (but different region) work, so it seems to be something to do with the subscription.

```
E0505 18:19:41.251729       1 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:my-secret, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Forbidden\" Message=\"The user, group or application 'appid=[APP-ID-OMMITTED];oid=[OBJECT_ID_OMMITTED];iss=https://sts.windows.net/[OMMITTED]/' does not have secrets get permission on key vault '[KEY VAULT NAME];location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287\" InnerError={\"code\":\"AccessDenied\"}"
```

I am sure that the configuration for the cluster and the key vault are correct; executing the same terraform scripts but moving the keyvault to the same subscription works (key vault is question is a shared resource hence different sub).

**What did you expect to happen:**
The keyvault to authenticate and connect

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The issue seems to be subscription related - the same subscription in different regions works; it is only when pared with different regions and different subscriptions that this error occurs.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

The AKV cluster consists of multiple node pools using a System Assigned Managed Identity. The ID for the key_vault_secrets_provider is being extracted by terraform when the cluster is created and is used to assign the access policy for the vault.

The same configuration works when the key vault is in the same subscription 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.1.0
- Azure Key Vault provider version: (use the image tag): v2.6.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.23.3
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
@MrBasset Are you using manages AKS add-on for Secrets Store CSI driver?

**Comment by MrBasset** [comment]
Hi,

I'm closing this issue as I have found what the problem was. When I tested key vaults in the same/other regions I set the permissions using ```az keyvault set-policy``` rather than running terraform scripts. What happens behind the scenes is that the policy permission is set using the MSI's Object_Id whilst the SecretProviderClass uses the MSI's Principal_ID.

As I'd been using the principal ID to set the permission Azure was correctly returning a permission denied error. If it helps anyone, the terraform to assign the permission correctly for a System Managed Identity is:
'''
resource "azurerm_key_vault_access_policy" "aks-access" {
  key_vault_id            = data.azurerm_key_vault.kv.id
  tenant_id               = data.azurerm_client_config.current.tenant_id
  object_id               = azurerm_kubernetes_cluster.k8s.key_vault_secrets_provider[0].secret_identity[0].object_id

  certificate_permissions = [
    "Get",
    "List"
  ]

  key_permissions         = [
    "Get",
    "List"
  ]

  secret_permissions      = [
    "Get",
    "List"
  ]
}
'''
