### ISSUE TITLE
Support for file encoding

### ISSUE THREAD

**Issue by alsastre** [Azure/secrets-store-csi-driver-provider-azure#89]
**Describe the solution you'd like**
Right now when you specify a secret it is always downloaded using `utf-8` encoding. Something like `objectencoding` could be added in order to be able to download correctly other file encodings.

This would be useful to upload/download  binary files or jks files which cannot be converted to utf-8 [More info](https://stackoverflow.com/a/22500357)

**Comment by aramase** [comment]
cc @chrisamert who is going to work on this
