### ISSUE TITLE
Sync with Kubernetes Secrets not working

### ISSUE THREAD

**Issue by bq1756** [Azure/secrets-store-csi-driver-provider-azure#90]
**What steps did you take and what happened:**
1. Install csi-secrets-store-provider-azure
`helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name --namespace kube-system`

2. Deploy secretproviderclass
`kc apply -f secretproviderclasses-sync-k8s-secrets.yaml`
Sample yaml:
---
apiVersion:` secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: test-k8s-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: kvcreds
    type: Opaque 
    data:
    - objectName: kvClientId
      key: kvclientid
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "***********"
    keyvaultName: "test-kv"
    objects:  |
      array:
        - |
          objectName: kvClientId
          objectType: secret
    resourceGroup: "test-rg"
    subscriptionId: "************"
    tenantId: "**************"
---
3. Deploy k8s secret
`kc apply -f secret-kvcreds.yaml`
Sample yaml:
apiVersion: v1
kind: Secret
metadata:
  name: kvcreds
type: Opaque
data:
  kvclientid: ZnJvbV9rZXlfdmF1bHQNCg==

**What works as expected?**
Deploy a pod containing.....
 volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "test-k8s-secrets"

`kubectl exec -it test-pod -- cat /mnt/secrets-store/kvClientId `
  - matches the value I set in Key Vault

**What does not work as expected?**
`kc get secret kvcreds -o yaml` shows 
data:
  kvclientid: ZnJvbV9rZXlfdmF1bHQNCg==
  - ZnJvbV9rZXlfdmF1bHQNCg== (decoded) does not match the value I set in Key Vault

**What did you expect to happen:**
I expected the key kvclientid in the k8s secret to be updated with the sync'd value of kvclientid from Key Vault.

**Anything else you would like to add:**
I tried a few variations of the above repro steps:
I created the k8s secret first, then the secretproviderclass second.
I created the secretproviderclass first, then the k8s secret second.
I did not create a K8s secret in hopes that the secretproviderclass would create the secret for me.
I created the k8s secret with a bogus key in hopes that secretproviderclass would create the key for me.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.2.0
- Azure Key Vault provider version: (use the image tag): 0.0.5
- Kubernetes version: (use `kubectl version`): v1.16.7
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by ritazh** [comment]
Hi @bq1756 thanks for reporting this issue. Can you please try the followingt:
1. Can you please verify that you are using the latest release of secrets store CSI driver? The image tag should be `docker.io/deislabs/secrets-store-csi:v0.0.10`
2. Is the base64 decoded value `from_key_vault` different from what you stored in key vault?
> I expected the key kvclientid in the k8s secret to be updated with the sync'd value of kvclientid from Key Vault.
```bash
echo ZnJvbV9rZXlfdmF1bHQNCg== | base64 -d
from_key_vault
```
3. Here is the sequence the driver creates the k8s secret:
pod deployment request -> pod yaml references a volume that uses `driver: secrets-store.csi.k8s.io` -> secrets store csi driver is called -> driver looks for the `secretProviderClass` object referenced in the pod yaml: `secretProviderClass: "test-k8s-secrets"` -> the csi driver uses the `provider` property to call the provider (e.g. Azure key vault) to retrieve the secret content then mounts the secret to the file system -> if the `secretObjects` properties are provided, then it is used by the csi driver to create the k8s secret object -> k8s secret object is created -> pod is created

**Comment by jrudley** [comment]
I cannot get this to work either. Documentation example would be great. I am referencing https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/vault_synck8s_v1alpha1_secretproviderclass.yaml

**Comment by ritazh** [comment]
@jrudley PTAL https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets

Here is the azure provider sample used in the e2e:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml
and
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/nginx-deployment-synck8s-azure.yaml

We also have this ingress controller tls sample: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/sample/ingress-controller-tls

**Comment by jrudley** [comment]
@ritazh I am using image 0.0.5. I am assuming you need 0.0.10 for these examples?

**Comment by bq1756** [comment]
@ritazh I have it working!  2 issues.
1. I was creating the secret via kubectl manifest.  There is no need to perform this step.  The secret is automatically created when a pod is deployed that calls the secretproviderclass.
2. Also, I mis-typed the secretProviderClass: value in the pod deployment yaml.

**Comment by jrudley** [comment]
@ritazh It works with 0.0.10. Thanks!
