### ISSUE TITLE
Feature request: Sync Kubernetes Secrets to AKV 

### ISSUE THREAD

**Issue by iusergii** [Azure/secrets-store-csi-driver-provider-azure#919]
**Describe the solution you'd like**
I'd like to have an option to sync Kubernetes Secrets to Azure KeyVault. 

**Anything else you would like to add:**
We use cert-manager for managing certificates and I'd like to sync it to AKV to use with Azure Application Gateway listeners.

**Comment by nilekhc** [comment]
Hello @iusergii, Thanks for opening the issue. The primary goal of Secrets Store CSI driver and provider project is to fetch the Secrets from external Key Vaults.

At the moment we are not considering synching/Creating secrets in AKV
