### ISSUE TITLE
Cannot turn  SecretProvideClass created secrets into environment variables

### ISSUE THREAD

**Issue by gyorgysimon** [Azure/secrets-store-csi-driver-provider-azure#925]
In our Azure Redhat Openshift environment we would use the Azure KeyVault secrets as environment variables. The Pod deployment events says that the secret is missing. The mode to access to the Azure Key Vault is based on the Service Principal.
When I just did not put the environment variables into the Pod manifest file the secrets are mounted in the given path. But when the environment variables is included into the Pod manifest I got the error mentioned above.

Environment:
- Secrets Store CSI Driver version: csi-secrets-store-provider-azure-1.1.3	1.1.0  
- Cluster type: ARO (version: 4.9.35)
- Installation method: helm

**Comment by aramase** [comment]
@gyorgysimon Thanks for reporting the issue. 

Here is our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/. The logs in the driver would have more information on why the secret sync failed. Please share the driver logs and `SecretProviderClass` being used.

**Comment by gyorgysimon** [comment]
I went through the troubleshooting guide without success. But a bit confused on the logs, because I can see 2 different pods for the driver. 
The first is created by my (by helm especially), the name of those: secrets-store-csi-driver-XXXXX
Logs for that:
I0630 13:50:53.408331       1 main.go:166] Version: v2.5.0-0-ge68322fe
I0630 13:50:53.408559       1 main.go:167] Running node-driver-registrar in mode=registration
I0630 13:50:53.409247       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0630 13:50:53.410848       1 connection.go:154] Connecting to unix:///csi/csi.sock
W0630 13:51:03.411525       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0630 13:51:13.411952       1 connection.go:173] Still connecting to unix:///csi/csi.sock
W0630 13:51:23.411559       1 connection.go:173] Still connecting to unix:///csi/csi.sock
I0630 13:51:26.834860       1 main.go:198] Calling CSI driver to discover driver name
I0630 13:51:26.834954       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0630 13:51:26.834986       1 connection.go:184] GRPC request: {}
I0630 13:51:26.848396       1 connection.go:186] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v1.1.2"}
I0630 13:51:26.849052       1 connection.go:187] GRPC error: <nil>
I0630 13:51:26.849311       1 main.go:208] CSI driver name: "secrets-store.csi.k8s.io"
I0630 13:51:26.849388       1 node_register.go:53] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0630 13:51:26.935265       1 node_register.go:62] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0630 13:51:26.937616       1 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0630 13:51:27.931241       1 main.go:102] Received GetInfo call: &InfoRequest{}
I0630 13:51:27.931705       1 main.go:109] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/csi-secrets-store/registration"
I0630 13:51:28.096001       1 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}

the second one, which is new to me here named: csi-csi-secrets-store-provider-azure-XXXXX
Logs for these: 
I0630 13:50:55.034948       1 main.go:66] "Starting Azure Key Vault Provider" version="v1.1.0"
I0630 13:50:55.035025       1 exporter.go:14] "intializing metrics backend" backend="prometheus"
I0630 13:50:55.035069       1 main.go:83] construct pem chain feature enabled
I0630 13:50:55.035345       1 main.go:122] "Listening for connections" address="//provider/azure.sock"

**Comment by aramase** [comment]
The helm charts install a driver and provider. You need the `secrets-store` container logs from the driver pod running on the same node as your application that's trying to mount the volume: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/#for-csi-driver-logs

**Comment by gyorgysimon** [comment]
I just wanted to have the logs for you, but:
```
> for pod in $(oc get pods -l app=secrets-store-csi-driver --no-headers=true|awk '{print $1}'); do echo ${pod}:; oc logs $pod secrets-store --since=1h | grep ^E; done
csi-secrets-store-secrets-store-csi-driver-nqjrk:
csi-secrets-store-secrets-store-csi-driver-pflrg:
csi-secrets-store-secrets-store-csi-driver-thdxv:
>
```

however I got an error in events now: 
` MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod gsimon-test-project/test-multiple-secrets-store-inline, err: error connecting to provider "azure": provider not found: provider "azure"`

This is because I modified the deployment (maybe not the best idea but) now the driver installed with:
`helm install -n kube-system csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --version v1.0.1 --set "linux.providersDir=/var/run/secrets-store-csi-providers" --set "syncSecret.enabled=true" --set secrets-store-csi-driver.rotationPollInterval=2m`

The SecretClassProvider manifest file:
`
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret-to-env-variables
  namespace: gsimon-test-project
spec:
  provider: azure
  secretObjects:
  - secretName: kvsecret
    type: Opaque
    data:
    - objectName: secret1
      key: secret1
    - objectName: test-secret-2
      key: test-secret-2
    - objectName: test-secret-3
      key: test-secret-3
  parameters:
    keyvaultName: ${KEYVAULT_NAME}
    objects: |
      array:
      - |
        objectName: secret1
        objectType: secret
      - |
        objectName: test-secret-2
        objectType: secret
      - |
        objectName: test-secret-3
        objectType: secret
    tenantId: ${TENANT_ID}
`

Finally the pod manifest:
`
kind: Pod
apiVersion: v1
metadata:
  name: test-multiple-secrets-store-inline
  namespace: gsimon-test-project
spec:
  containers:
   - name: ubi-test-container
     image: registry.access.redhat.com/ubi8/ubi:latest
     command:
     - "/bin/sleep"
     - "10000"
     volumeMounts:
     - name: secrets-store-inline
       mountPath: "/mnt/secrets-store"
       readOnly: true
     env:
       - name: VAR1
         valueFrom:
           secretKeyRef:
             name: kvsecret
             key: secret1
       - name: VAR2
         valueFrom:
           secretKeyRef:
             name: kvsecret
             key: test-secret-2
       - name: VAR3
         valueFrom:
           secretKeyRef:
             name: kvsecret
             key: test-secret-3
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-secret-to-env-variables"
        nodePublishSecretRef:
          name: secrets-store
`

**Comment by aramase** [comment]
@gyorgysimon Looks like you're installing the driver with the helm charts from the driver repo and not the provider. There are 2 ways to install:
1. Install driver and provider separately: https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html and then azure provider.
2. Install driver and provider together with the helm charts from this repo: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#installation. More details are available in the installation docs https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/.
