### ISSUE TITLE
Possibility to disable secret caching?

### ISSUE THREAD

**Issue by NillsF** [Azure/secrets-store-csi-driver-provider-azure#93]
Hi,

With typical Kubernetes secrets, [mounted Secrets are updated automatically](https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically). 

I noticed that with the CSI-driver, updating the secret in Key Vault, doesn't make the secret change in the filepath. In my (limited) testing, I was able to get the new version of a secret loaded after recreating the pod (deleting pod and having deployment create a new pod).

This lead to two questions from my side:
1. Is there the ability to disable secret caching?
2. By default, how long are secrets cached before getting re-fetched from Key Vault?

**Comment by aramase** [comment]
@NillsF `secrets-store-csi-driver` currently doesn't automatically reload when secrets/keys/certs are updated in Key Vault. We have an issue open for this enhancement - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/125.  Feel free to chime in on the issue.

**Comment by tomkerkhove** [comment]
What if we could use a sidecar to notify the Azure Key Vault provider for Secret Store CSI driver by using Event Grid? https://docs.microsoft.com/en-us/azure/event-grid/event-schema-key-vault

We use a similar approach for non-Kubernetes workloads but should be an opt-in; if that's feasible ofcourse - I'm not a secret store expert.

https://background-jobs.arcus-azure.net/features/security/auto-invalidate-secrets

**Comment by deuch** [comment]
Maybe a another option is to watch the secrets in KV and update the K8S secrets accordingly.
For example, with the certificate during renew (app service certificate). The  certs are renew 60 days before the expiration date. So if a check is done every 24h, it can be OK. Of course the frequency to check the secret in KV can be configured. It’s a pull solution, but can help a lot of project to handle TLS secret for ingress :)

**Comment by aramase** [comment]
This is being tracked in kubernetes-sigs/secrets-store-csi-driver#125. @tomkerkhove @deuch @NillsF Please feel free to chime in on the issue.
