### ISSUE TITLE
Unable to continue with install: CSIDriver "secrets-store.csi.k8s.io" 

### ISSUE THREAD

**Issue by donjetam** [Azure/secrets-store-csi-driver-provider-azure#930]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Try to install csi via terraform:
```
resource "helm_release" "azure_csi" {
  name       = "csi"
  repository = "https://azure.github.io/secrets-store-csi-driver-provider-azure/charts"
  chart      = "csi-secrets-store-provider-azure"
  version    = "1.0.1"
  namespace  = "kube-system"

  values = [
    "${file("../../../../deploy/csi/values.dev.yaml")}"
  ]
}
```
Error message:
```
╷
│ Error: rendered manifests contain a resource that already exists. Unable to continue with install: CSIDriver "secrets-store.csi.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
│ 
│   with helm_release.azure_csi,
│   on main.tf line 122, in resource "helm_release" "azure_csi":
│  122: resource "helm_release" "azure_csi" {
│ 
```

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag): 1.0.1
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): kubernetes_version: 1.22.4, 3 nodes
- Cluster type: (e.g. AKS, aks-engine, etc): AKS Azure
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):

**Comment by aramase** [comment]
@donjetam The error message from terraform indicates there is already another deployment of the CSI driver and its components. You would need to cleanup the old deployment and reinstall with helm.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/930#issuecomment-1175269018. Please feel free to reopen if you have any questions.
