### ISSUE TITLE
The driver doesn't work on windows2022

### ISSUE THREAD

**Issue by ZeroMagic** [Azure/secrets-store-csi-driver-provider-azure#931]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
![image](https://user-images.githubusercontent.com/12582312/178436606-199ff81d-9e91-4909-a32d-5198f8cb8d7b.png)
I tried to run a demo with secrets-store-csi-driver. But the demo didn't work.
` secrets-store-csi-driver` and `secrets-store-csi-driver-windows` were running well. 
The sample demo pod was blocked. Following is the result with `kubectl describe`.
```
Events:
  Type     Reason       Age               From                     Message
  ----     ------       ----              ----                     -------
  Normal   Scheduled    <unknown>                                  Successfully assigned default/sample-5dc79b6b55-kj7fc to akswin22000000
  Warning  FailedMount  3s (x5 over 11s)  kubelet, akswin22000000  MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/sample-5dc79b6b55-kj7fc, err: error connecting to provider "azure": provider not found: provider "azure"
```

After debugging, I located the problem at this line https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/v1.2.0/pkg/secrets-store/provider_client.go#L133

Logon the vm. Found that the socket file was created successfully. The socket file was also mounted. But it cannot be read.

**What did you expect to happen:**
The demo can work well.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.2.0
- Azure Key Vault provider version: (use the image tag): 1.2.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):  v1.23.8
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): Helm

**Comment by andyzhangx** [comment]
use `os.Lstat` would fix the issue?

**Comment by aramase** [comment]
> use os.Lstat would fix the issue?

@andyzhangx Good call! I looked at the k/k code and see similar issues in windows were resolved with `os.Lstat`.  Opened https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/998 to resolve this and I've tested this in the cluster @ZeroMagic provided.

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/998
