### ISSUE TITLE
MountVolume.SetUp failed for volume "volume" kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by Uvindu96** [Azure/secrets-store-csi-driver-provider-azure#937]
**What steps did you take and what happened:**
We needed to upgrade our AKS cluster to version `1.22.11`, before that we have upgraded our CSI driver version from `0.0.15` to `1.0.0`, We have successfully upgraded the CSI driver version and then we upgraded the AKS cluster to the version `1.22.11`, but after that when AKS cluster restarting we observed the following error in our application pods.
```
Warning  FailedMount  12m (x296 over 9h)   kubelet  MountVolume.SetUp failed for volume "query-service-secrets-volume" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
  Warning  FailedMount  2m47s (x45 over 9h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[query-service-secrets-volume], unattached volumes=[query-service-secrets-volume query-service-secret query-service-log4j2-properties query-service-application-properties]: timed out waiting for the condition
```
And then, I checked the CSI driver pods status, And I observed that several pods are not started correctly and I checked the logs in those pods. And I observed following error logs.
```
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Warning  FailedScheduling   162m                   default-scheduler   0/2 nodes are available: 1 Too many pods, 1 node(s) didn't match Pod's node affinity/selector.
  Normal   NotTriggerScaleUp  4m14s (x3527 over 9h)  cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector
``` 
When I manually scaled up the AKS cluster to 3 nodes, both CSI driver and application pods scheduled successfully. I checked the newly scheduled CSI driver pods and each pod is correctly deployed into 3 nodes, so seems like there is no issue with pod's node affinity
```
NAME                                                              READY   STATUS    RESTARTS   AGE   IP            NODE                                   NOMINATED NODE   READINESS GATES
csi-secrets-store-provider-csi-secrets-store-provider-azur5qstw   1/1     Running   0          60m   172.***   aks-aksnpdefault-25590835-vmss0000qy   <none>           <none>
csi-secrets-store-provider-csi-secrets-store-provider-azurh74n5   1/1     Running   0          11h   172.****    aks-aksnpdefault-25590835-vmss0000qw   <none>           <none>
csi-secrets-store-provider-csi-secrets-store-provider-azurrkt49   1/1     Running   0          52m   172.****   aks-aksnpdefault-25590835-vmss0000qx   <none>           <none>
secrets-store-csi-driver-cq24h                                    3/3     Running   0          11h   172****   aks-aksnpdefault-25590835-vmss0000qx   <none>           <none>
secrets-store-csi-driver-lzjpb                                    3/3     Running   0          11h   172***   aks-aksnpdefault-25590835-vmss0000qw   <none>           <none>
secrets-store-csi-driver-tng6j                                    3/3     Running   0          60m   17*****   aks-aksnpdefault-25590835-vmss0000qy   <none>           <none>
```
**What did you expect to happen:**
When AKS cluster is restarting CSI driver pods should start correctly. and pods should schedule in each node correctly.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.0.0
- Azure Key Vault provider version: (use the image tag): v1.0.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.22.11
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm)

**Comment by Uvindu96** [comment]
Hi @nilekhc `Do you know what was the state of driver pods when cluster autoscaler hit?` --> pods were in pending state. Is this is a intermittent failure ? Is there a fix for this ?

**Comment by nilekhc** [comment]
> pods were in pending state.

It may take some time for kubelet to register driver. It keeps on retrying.

> isn't this related something with resource limitation

Yes, but this does not affect driver registration.


Do you have steps to reproduce this? I can try at my end and debug.

**Comment by Uvindu96** [comment]
@nilekhc These are the steps I followed,

1. install the CSI driver chart version 0.0.15
2. Upgrade the CSI driver version 0.0.15 to version 1.0.0.
3. Upgrade AKS cluster version 1.21.9 to 1.22.11

You can use the same steps, if possible please let us know a quick fix for this ?

**Comment by Uvindu96** [comment]
@nilekhc were you able to check on this ?

**Comment by nilekhc** [comment]
> @nilekhc were you able to check on this ?

Bit swamped this week. I'll get to this in next week. Hope you are not blocked on this.

**Comment by nilekhc** [comment]
@Uvindu96 I followed your steps above but did not get any error. Both charts and aks upgrade worked perfectly with workload pod running as expected.
Here is workload pod's transition output while cluster upgrade.
```bash
NAME                                 READY   STATUS              RESTARTS   AGE     IP           NODE                                NOMINATED NODE   READINESS GATES
busybox-deployment-7658f6df5-ldzrq   1/1     Running             0          5m57s   10.244.1.2   aks-agentpool-32016312-vmss000001   <none>           <none>
busybox-deployment-7658f6df5-ldzrq   1/1     Terminating         0          9m14s   10.244.1.2   aks-agentpool-32016312-vmss000001   <none>           <none>
busybox-deployment-7658f6df5-ldzrq   1/1     Terminating         0          9m14s   10.244.1.2   aks-agentpool-32016312-vmss000001   <none>           <none>
busybox-deployment-7658f6df5-d5lwz   0/1     Pending             0          0s      <none>       <none>                              <none>           <none>
busybox-deployment-7658f6df5-d5lwz   0/1     Pending             0          0s      <none>       aks-agentpool-32016312-vmss000003   <none>           <none>
busybox-deployment-7658f6df5-d5lwz   0/1     ContainerCreating   0          0s      <none>       aks-agentpool-32016312-vmss000003   <none>           <none>
busybox-deployment-7658f6df5-d5lwz   1/1     Running             0          7s      10.244.3.7   aks-agentpool-32016312-vmss000003   <none>           <none>
```

Also fyi, you can find supported version of secrets store csi azure provider [here](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/#project-status).

**Comment by Happycoil** [comment]
> Also, on (unrelated) side note, we do recommend using Secrets Store CSI [managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver) with AKS.

@nilekhc is there a migration path from a helm deployment to a plugin deployment?

**Comment by nilekhc** [comment]
> > Also, on (unrelated) side note, we do recommend using Secrets Store CSI [managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver) with AKS.
> 
> @nilekhc is there a migration path from a helm deployment to a plugin deployment?

No. Recommended approach is to uninstall manual installation and then [enabling plugin on existing cluster](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#upgrade-an-existing-aks-cluster-with-azure-key-vault-provider-for-secrets-store-csi-driver-support). 

But this should be seamless as we do not remove CRDs (SecertProviderClass) while uninstalling. So when you enable plug-in you can still use your old CRDs. Already running pods should also work just fine unless they are restarted. Rotation might impact as driver/provider pods are required for it.
