### ISSUE TITLE
Error in documentation (pod identity) ?

### ISSUE THREAD

**Issue by lgmorand** [Azure/secrets-store-csi-driver-provider-azure#94]
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md

On step 7, we add "usepodidentity" to secretProvider class, which seems logical.
but on step 6 **b**. it says to had "usepodidentity: true", while we are talking about the deployment. Do we really need to had it to the deployment? If yes, at which level. my different tries make k8s grumpy

**Comment by aramase** [comment]
@lgmorand It's only required in the `secretProviderClass` - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/v1alpha1_secretproviderclass_podid.yaml#L8. It's not required to be in the deployment. Will remove that step 6b to avoid confusion.
