### ISSUE TITLE
Clarification on the Ingress scenario with Nginx

### ISSUE THREAD

**Issue by ferronsw** [Azure/secrets-store-csi-driver-provider-azure#944]
I want to use this provider to supply certificates to the Nginx Ingress.
I've deployed the driver within the AKS cluster and mounted the volume within the Ingress controller.
Like the [instructions](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-nginx-tls) described. 

The Ingress Controller is created in a separate namespace called "Ingress-nginx".
The secrets are correctly created when I create the SecretProviderClass within the "ingress-nginx" namespace.
But I don't want them there, because my applications (so also the ingresses) life in another namespace.
When I create the SecretProviderClass in the namespace where my apps life the secrets aren't created.

So my understanding is that the SecretProviderClass has to be created in the namespace where the Nginx Ingress Controller is located. But that would mean I need a Ingress Controller per namespace right?

**Comment by aramase** [comment]
> So my understanding is that the SecretProviderClass has to be created in the namespace where the Nginx Ingress Controller is located. But that would mean I need a Ingress Controller per namespace right?

Hello 👋🏻  Thanks for opening the issue. Secrets Store CSI Driver requires the `SecretProviderClass` to be in the same namespace as the pod referencing it, so it needs to be in `ingress-nginx` namespace if it needs to be used by the ingress controller. If you need the secret in different namespace, you can create the `SecretProviderClass` in the diff namespace and mount the certs to the app pods that's consuming it.

**Comment by ferronsw** [comment]
Thank for the clarification! It's a bit disappointing, but at least it's clear now.

**Comment by OriHoch** [comment]
if you use a wildcard SSL certificate you can set it as a default certificate for the ingress, then you don't have to set tls on the individual ingress objects
https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/tls.md#default-ssl-certificate
