### ISSUE TITLE
Consider not requiring AAD Client ID in SPC template for workload identity

### ISSUE THREAD

**Issue by jroggeman** [Azure/secrets-store-csi-driver-provider-azure#952]
I'm onboarding my team's apps to use CSI Driver, and while planning for a future move to use workload ID for auth, I noticed that the secret provider class still requires the `clientId` field.

Is this field strictly necessary? To my understanding, workload identity will inject an environment variable into all containers of pods that are running as a K8S Service Account that contains the client ID of the AAD app associated with the K8S service account. Could CSI Driver utilize that to retrieve the client ID dynamically?

It's not a huge problem for us, but it does present some additional deployment code we need to write to dynamically retrieve and populate the client ID when it doesn't seem like it'd be required.

Thanks!

**Comment by aramase** [comment]
> Is this field strictly necessary? To my understanding, workload identity will inject an environment variable into all containers of pods that are running as a K8S Service Account that contains the client ID of the AAD app associated with the K8S service account. Could CSI Driver utilize that to retrieve the client ID dynamically?

@jroggeman The `clientID` is required because this project doesn't rely on the mutating webhook or projected service account token volume from https://github.com/Azure/azure-workload-identity. For CSI drivers, the service account token is provided by kubelet as part of the mount request and we don't need an additional volume to use workload identity.

**Comment by aramase** [comment]
Closing this issue as `clientID` field is required. 

Feel free to reopen if you have any other questions/suggestions.
