### ISSUE TITLE
Is this supported in Azure Stack Hub with AD FS identity?

### ISSUE THREAD

**Issue by sieg2010** [Azure/secrets-store-csi-driver-provider-azure#980]
Hi,

I would like to know if this is supported in Azure Stack Hub with AD FS identity?
I can't find it in the document.
While this CSI driver can be used normally in Azure Stack Hub with Azure AD identity,  I can not get it to work in Azure Stack Hub with AD FS identity.
The tests in my lab only get the following error message.
```
E0921 13:33:09.015501       1 server.go:58] 'failed to process mount request' err='failed to get objectType:secret, objectName:[SECRET_NAME], objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://[KEY_VAULT_NAME].vault.[REGION].[AZURE_STACK_HUB_FQDN]/secrets/[SECRET_NAME]/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\\'error\\':\\'invalid_resource\\',\\'error_description\\':\\'MSIS9602: The received \\\\u0027resource\\\\u0027 parameter is invalid. The authorization server can not find a registered resource with the specified identifier.\\'} Endpoint https://adfs.[REGION].[AZURE_STACK_HUB_FQDN]/adfs/oauth2/token?api-version=1.0';
```
I'm not sure if I set something wrong, but I want to make sure this CSI driver supported AD FS identity first.

**Comment by aramase** [comment]
> While this CSI driver can be used normally in Azure Stack Hub with Azure AD identity, I can not get it to work in Azure Stack Hub with AD FS identity.

It is not supported with AD FS identity.

**Comment by sieg2010** [comment]
Thanks for your reply
