### ISSUE TITLE
CSI Driver Installation failed | job failed: BackoffLimitExceeded

### ISSUE THREAD

**Issue by pnl0ep7f** [Azure/secrets-store-csi-driver-provider-azure#988]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/) - Yes
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions] (https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions) - Yes

**What steps did you take and what happened:**
We  are trying to install the CSI driver on our AKS cluster version 1.24. 
We are currently deploying the driver to the helm charts and not using the add-on feature

Ran the command helm upgrade --namespace kube-system --install --wait --set secrets-store-csi-driver.syncSecret.enabled=true csi-secrets-store csi-secrets-store-provider-azure/csi-secrets-store-provider-azure 

The step failed with error 

2022-10-05T14:53:30.7486813Z client.go:568: [debug] Add/Modify event for secrets-store-csi-driver-upgrade-crds: MODIFIED
2022-10-05T14:53:30.7487845Z upgrade.go:434: [debug] warning: Upgrade "csi-secrets-store" failed: pre-upgrade hooks failed: job failed: BackoffLimitExceeded
2022-10-05T14:53:30.7488803Z Error: UPGRADE FAILED: pre-upgrade hooks failed: job failed: BackoffLimitExceeded
2022-10-05T14:53:30.7489687Z helm.go:84: [debug] pre-upgrade hooks failed: job failed: BackoffLimitExceeded
2022-10-05T14:53:30.7490215Z UPGRADE FAILED

The pod secrets-store-csi-driver-upgrade-crds which gets created had the following error log
![image](https://user-images.githubusercontent.com/66358388/194097858-b0e2dead-b51c-485f-a823-de4723e152f9.png)

**What did you expect to happen:**
Expected the installation to happen correctly 

**Anything else you would like to add:**
We did the same activity on another AKS cluster with version 1.21 and the installation did not fail.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.3.0
- Azure Key Vault provider version: (use the image tag): 1.2.3
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.24.3
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): deployment using helm

**Comment by nilekhc** [comment]
Hi @pnl0ep7f, Thanks for opening an issue. Helm install/upgrade uses hooks to create/update CRDs. It creates a Job to do so. Do clusters have sufficient resources? Could you grab the output of `kubectl describe` for the job (job name contains _upgrade-crds_)


Also, may I know the reason/usecase for not using an add-on? For AKS clusters it is highly recommended to use add-on.

**Comment by pnl0ep7f** [comment]
HI @nilekhc,
The cluster does have sufficient resources. The CRDS are getting created, but the pods for csi driver are not spinning up.
here the output of the kubectl describe command 
![image](https://user-images.githubusercontent.com/66358388/194219964-172fdf5b-f3b4-4f4a-8c59-64c5abbdb209.png)

We are eventually going to move to the add-on feature, but the cluster that we are working right now with had to be redeployed and the csi driver was deployed through helm initially because the ad-on feature was still in preview at that time.

**Comment by nilekhc** [comment]
> HI @nilekhc, The cluster does have sufficient resources. The CRDS are getting created, but the pods for csi driver are not spinning up. here the output of the kubectl describe command ![image](https://user-images.githubusercontent.com/66358388/194219964-172fdf5b-f3b4-4f4a-8c59-64c5abbdb209.png)
> 
> We are eventually going to move to the add-on feature, but the cluster that we are working right now with had to be redeployed and the csi driver was deployed through helm initially because the ad-on feature was still in preview at that time.

Could you validate if Cluster Role and Rolebinding with the name `secrets-store-csi-driver-upgrade-crds` exists?

**Comment by nilekhc** [comment]
@pnl0ep7f Is this resolved? Were you able to successfully update it?
