### ISSUE TITLE
Kubernetes Secret Sync without volume mount

### ISSUE THREAD

**Issue by swgriffith** [Azure/secrets-store-csi-driver-provider-azure#99]
**Describe the solution you'd like**
It appears that for the secret sync to work, you first need to have a pod that mounts the kv volume to trigger the secret creation. It would be great if the secret creation could be triggered off of the creation of the SecretProviderClass instead. I assume this is just a requirement of the CSI driver itself, so maybe this is outside of the intent of the implementation.

**Comment by lgmorand** [comment]
Do you get also the "secret not found" when you try to do it ? I get it, but not constantly

**Comment by tanzencoder** [comment]
It would be nice to not have to use a volume mount to get the sync to work. In my case I am trying to use virtual nodes in AKS and I can't schedule a pod on a virtual node when I am using the secrets provider.

**Comment by aramase** [comment]
Closing this issue as it's a driver feature request - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/298
