### ISSUE TITLE
Identity not found when using Workload Identity with secret store driver

### ISSUE THREAD

**Issue by insertusername20** [Azure/secrets-store-csi-driver-provider-azure#991]
Hi,

So we are trying to use workload-identity to bind certificate hosted on keyvault to our ingress app deployment.
But we are facing some issues during deployment.

We get the error message "Identity not found" 

Now, we do have workload-identity working with service accounts and able to fetch secrets from keyvault. For use within our app.
Also able to use user assigned identity to get the SSL certificate. But we would like to use workload-identity.

**Comment by aramase** [comment]
> We get the error message "Identity not found"

`Identity not found` error is if you're using [user-assigned managed identity](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/user-assigned-msi-mode/) to access keyvault.

> Now, we do have workload-identity working with service accounts and able to fetch secrets from keyvault. For use within our app.

Are you using [workload identity](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/workload-identity-mode/) or user-assigned managed identity? If you're using workload identity, then ensure you set the `clientID` as mentioned in the docs to use the correct mode. Also, share the `SecretProviderClass` yaml.

**Comment by insertusername20** [comment]
This was it. Thanks for answering.
